svn del doc/examples/avio_list_dir.c
svn del ffmpeg_vda.c
svn del libavcodec/aacpsdsp.c
svn del libavcodec/api-flac-test.c
svn del libavcodec/qsvdec_h264.c
svn del libavcodec/s3tc.c
svn del libavcodec/s3tc.h
svn del libavcodec/vda_internal.h
svn del libavformat/asfdec.c
svn del tests/ref/fate/filter-histogram-waveform
svn del tests/ref/vsynth/vsynth1-ffv1.0
svn del tests/ref/vsynth/vsynth2-ffv1.0
svn del tests/ref/vsynth/vsynth3-ffv1.0
svn del tests/ref/vsynth/vsynth_lena-ffv1.0
