/*
 * Copyright (c) 2022-2023, Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef __EDMA_DEBUGFS_H__
#define __EDMA_DEBUGFS_H__

#define EDMA_STATS_BANNER_MAX_LEN	80
#define EDMA_RX_RING_STATS_NODE_NAME	"EDMA_RX"
#define EDMA_TX_RING_STATS_NODE_NAME	"EDMA_TX"
#define EDMA_MISC_STATS_NODE_NAME	"EDMA_MISC"
#define EDMA_RX_RING_PPEDS_STATS_NODE_NAME	"EDMA_RX_PPEDS"
#define EDMA_TX_RING_PPEDS_STATS_NODE_NAME	"EDMA_TX_PPEDS"

int edma_debugfs_init(void);
void edma_debugfs_exit(void);

#endif	// __EDMA_DEBUGFS_H__
