# Version.tcl --
#
#	This file is automatically generated by the Tix version control tool
#
#
# Copyright (c) 1996, Expert Interface Technologies
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#

proc tixScriptVersion {} {
    return 4.1
}
proc tixScriptPatchLevel {} {
    return 4.1.0
}
