#!/bin/sh
#
# Little shell script to grab current version number from configure.in
#
# $Id: version,v 1.1.1.1 2004/04/02 18:55:11 jj Exp $

VER=`grep AC_INIT configure.in | awk -F'[(),]' '{print $3}'`
if [ "$1" == "-VERSION" ]
then
  echo $VER | awk -F'.' '{print $1}'
  exit
fi
if [ "$1" == "-PATCHLEVEL" ]
then
  echo $VER | awk -F'.' '{print $2}'
  exit
fi
if [ "$1" == "-SUBLEVEL" ]
then
  echo $VER | awk -F'.' '{print $3}'
  exit
fi
echo $VER
exit
