#!/usr/bin/env bash

. ./test.common

test_start "memory locking"

extra_chronyd_options="-m"

start_chronyd || test_fail
wait_for_sync || test_fail
stop_chronyd || test_fail
check_chronyd_messages || test_fail
check_chronyd_files || test_fail

test_pass
