#!/usr/bin/env bash

. ./test.common

[ "$(uname -s)" = "Linux" ] || test_skip "non-Linux system"

test_start "binddevice directives"

extra_chronyd_directives="
binddevice lo
bindacqdevice lo
bindcmddevice lo"

start_chronyd || test_fail
wait_for_sync || test_fail

run_chronyc "ntpdata $server" || test_fail
check_chronyc_output "^Remote address" || test_fail

stop_chronyd || test_fail
check_chronyd_messages || test_fail
check_chronyd_files || test_fail

test_pass
