obj-y := pmu.o prom.o dma.o timer.o reset.o clk-xway.o
obj-y += gpio.o gpio_ebu.o gpio_leds.o devices.o mach-wmbr.o
obj-$(CONFIG_LANTIQ_MACH_EASY50812) += mach-easy50812.o
obj-$(CONFIG_LANTIQ_MACH_EASY50712) += mach-easy50712.o
obj-$(CONFIG_LANTIQ_MACH_EASY4010) += mach-easy4010.o
obj-$(CONFIG_LANTIQ_MACH_ARV45XX) += mach-arv45xx.o
obj-y += dev-dwc_otg.o
