#ifndef RZB_SAAC_H
#define RZB_SAAC_H

#define SAAC_HTTP 6880

#define URLLEN 1000
#define HOSTNAMELEN 256
#define NUMSTREAMSTOTRACK 5000

#define NRTSID                  0xa5a5a5a5
#define INVALIDSTREAMIDX        0xFFFFFFFF
#define OUTOFSTREAMINFOSTORAGE  0xFFFFFFFF

#endif // RZB_SAAC_H

