#!/bin/sh
#./build_broadcom.sh
#./build_ggew.sh
./build_ca8.sh
./build_ca8_pro.sh
#./build_ca8_pro_maksat.sh
./build_fonera.sh
./build_fonera_special.sh
./build_wrt54g2.sh
./build_gw54g2.sh
./build_mr3202a.sh
#./build_mr3202a_trimax.sh
#./build_mr3202a_maksat.sh
#./build_mr3202a-4mb_maksat.sh
#./build_mr3202a_maksat-retail.sh
#./build_aw6660_maksat.sh
./build_bwrg1000.sh
./build_wgt624v4.sh
./build_dir300.sh
./build_dir300_special.sh
./build_dir400.sh
./build_aw6660.sh
./build_meraki.sh
./build_whrag108.sh
./build_ls2.sh
#./build_ls2_telcom.sh
./build_ns2.sh
./build_ns3.sh
./build_bs2.sh
./build_bs2hp.sh
./build_pico2.sh
./build_pico2hp.sh
./build_pico5.sh
./build_lc2.sh
#./build_ns5_ggew.sh
#./build_ls2_sputnik.sh
#./build_ps2_sputnik.sh
#./build_ns2_sputnik.sh
#./build_ns2_maksat.sh
#./build_ns2_ggew.sh
./build_ls5.sh
./build_ns5.sh
./build_bs5.sh
./build_lc5.sh
#./build_ns2_mediaconstruct.sh
#./build_ns5_mediaconstruct.sh
./build_ps5.sh
./build_ps2.sh
./build_lsx.sh
./build_rs.sh
#./build_ls5_sputnik.sh
#./build_ps5_sputnik.sh
#./build_ns5_sputnik.sh
#./build_ns5_ggew.sh
./build_wbd500.sh
#./build_wbd500_sputnik.sh
./build_eap3660.sh
./build_ecb3500.sh
./build_eoc1650.sh
./build_eoc2610.sh
./build_eoc5610.sh
#./build_eoc2610_trimax.sh
./build_wrk54g.sh
./build_wrt54gv7.sh
./build_usr5453.sh
./build_rdat81.sh
./build_wla-9000ap.sh
#./build_alpha_maksat.sh
#./build_cambria_kmt.sh
#./build_cambria.sh
#./build_cambria_wavesat.sh
#./build_cambria_free.sh
#./build_xscale.sh
#./build_xscale_ggew.sh
#./build_xscale_tonze.sh
#./build_xscale_wavesat.sh
#./build_xscale_free.sh
#./build_xscale_maksat.sh
#./build_xscale_maksat.sh -wimax
#./build_xscale_sputnik.sh
./build_wbd111.sh
#./build_wbd111_maksat.sh
#./build_tonze_ap120.sh
./build_compex_wp54.sh
./build_compex_np28g.sh
./build_x86.sh
#./build_x86_gw700.sh
./build_magicbox.sh
./build_mikrotik.sh
./build_whrg300n.sh
#./build_whrg300n_buffalo.sh
#./build_ecb9750.sh
