#!/bin/sh
./build_lsx.sh
./build_rs.sh
#./build_ls5_sputnik.sh
#./build_ps5_sputnik.sh
#./build_ns5_sputnik.sh
#./build_ns5_ggew.sh
./build_wbd500.sh
#./build_wbd500_sputnik.sh
./build_eap3660.sh
./build_ecb3500.sh
./build_eoc1650.sh
./build_eoc2610.sh
./build_eoc5610.sh
#./build_eoc2610_trimax.sh
./build_wrk54g.sh
./build_wrt54gv7.sh
./build_usr5453.sh
./build_rdat81.sh
./build_wla-9000ap.sh
#./build_alpha_maksat.sh
./build_cambria.sh
#./build_cambria_wavesat.sh
#./build_cambria_free.sh
./build_xscale.sh
#./build_xscale_ggew.sh
./build_xscale_tonze.sh
#./build_xscale_wavesat.sh
#./build_xscale_free.sh
#./build_xscale_maksat.sh
#./build_xscale_maksat.sh -wimax
#./build_xscale_sputnik.sh
./build_wbd111.sh
#./build_wbd111_maksat.sh
./build_tonze_ap120.sh
./build_compex_wp54.sh
./build_compex_np28g.sh
./build_x86.sh
#./build_x86_gw700.sh
./build_magicbox.sh
./build_mikrotik.sh
./build_whrg300n.sh
#./build_whrg300n_buffalo.sh
./build_ecb9750.sh
