#!/bin/sh
if test x$1 = x
then
        echo "Usage $0 interfacenumber [frequency]"
fi
mode=`nvram get ath${1}_net_mode`
/usr/sbin/wlanconfig mon${1} destroy
#restore mode
/sbin/ifconfig ath${1} down
if test mode = "mixed"
then
        /usr/sbin/iwpriv ath${1} mode 0
fi
if test mode = "b-only"
then
        /usr/sbin/iwpriv ath${1} mode 2
fi
if test mode = "g-only"
then
        /usr/sbin/iwpriv ath${1} mode 3
        /usr/sbin/iwpriv ath${1} protmode 0
fi
if test mode = "bg-mixed"
then
        /usr/sbin/iwpriv ath${1} mode 3
        /usr/sbin/iwpriv ath${1} protmode 1
fi
if test mode = "a-only"
then
        /usr/sbin/iwpriv ath${1} mode 1
fi
/sbin/ifconfig ath${1} up
echo "mon interface removed"
echo
echo "have a nice day"
