mtk-mdp-y += mtk_mdp_core.o
mtk-mdp-y += mtk_mdp_comp.o
mtk-mdp-y += mtk_mdp_m2m.o
mtk-mdp-y += mtk_mdp_regs.o
mtk-mdp-y += mtk_mdp_vpu.o

obj-$(CPTCFG_VIDEO_MEDIATEK_MDP) += mtk-mdp.o

ccflags-y += -I$(backport_srctree)/drivers/media/platform/mtk-vpu
