#!/bin/sh

# tests that the makeann utility can produce output in the prescribed payloads
# from a single source .sln file.

. $(dirname $0)/functions

MAKEANN_RFILES="ringback.0 ringback.3 ringback.8 ringback.18 ringback.9"
rm -f ${MAKEANN_RFILES}
${MAKEANN} ${BASEDIR}/ringback.sln ${BASEDIR}/ringback
report "makeann ringback.sln"
for rfile in ${MAKEANN_RFILES}
do
  test -s ${rfile}
  report "${rfile}"
done
sha256_compute ${MAKEANN_RFILES} | \
  ${DIFF} ${BASEDIR}/makeann.output -
report "G.711[ua], GSM, G.729a, G.722 data"
