.TH projid 5
.SH NAME
projid \- the project name mapping file
.SH DESCRIPTION
The
.I /etc/projid
file provides a mapping between numeric project identifiers and a
simple human readable name (similar relationship to the one that
exists between usernames and uids).
Its format is simply:
.nf
.sp
.in +5
# comments are hash-prefixed
# ...
cage:10
logfiles:42

.in -5
.fi
.PP

This file is optional, if a project identifier cannot be mapped to
a name, it will be parsed and displayed as a numeric value.

.SH SEE ALSO
.BR xfs_quota (8),
.BR xfsctl (3),
.BR projects (5).
