/*
 * Copyright (c) 2015-2016, The Linux Foundation. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */
#ifndef _DT_BINDINGS_CLK_IPQ_ADCC_4019_H
#define _DT_BINDINGS_CLK_IPQ_ADCC_4019_H

#define ADSS_PLL_SRC				1
#define RXM_CLK_SRC				2
#define ADCC_RXM_CLK_SRC			3
#define TXM_CLK_SRC				4
#define ADCC_TXM_CLK_SRC			5
#define TXB_CLK_SRC				6
#define ADCC_TXB_CLK_SRC			7
#define RXB_CLK_SRC				8
#define ADCC_RXB_CLK_SRC			9
#define PCM_CLK_SRC				10
#define ADCC_PCM_CLK_SRC			11
#define AUDIO_SPDIFINFAST_SRC			12
#define ADCC_AUDIO_SPDIFINFAST_SRC		13
#define ADCC_AUDIO_AHB_SRC			14
#define ADCC_AHB_I2S0				15
#define ADCC_AHB_I2S3				16
#define ADCC_AHB_MBOX0_SRC			17
#define ADCC_AHB_MBOX3_SRC			18
#define SPDIF_SRC				19
#define ADCC_SPDIF_SRC				20
#define SPDIFDIV2_SRC				21
#define ADCC_SPDIFDIV2_SRC			22
#define ADCC_SAMPLE_SRC				23
#define ADCC_XO_SRC				24

#endif
