'\" t
.\"     Title: glib-compile-schemas
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/05/2011
.\"    Manual: User Commands
.\"    Source: User Commands
.\"  Language: English
.\"
.TH "GLIB\-COMPILE\-SCHEM" "1" "06/05/2011" "User Commands" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
glib-compile-schemas \- GSettings schema compiler
.SH "SYNOPSIS"
.HP \w'\fBglib\-compile\-schemas\fR\ 'u
\fBglib\-compile\-schemas\fR [option...] {directory}
.SH "DESCRIPTION"
.PP
\fBglib\-compile\-schemas\fR
compiles all the GSettings XML schema files in
\fIdirectory\fR
into a binary file with the name
gschemas\&.compiled
that can be used by
\fBGSettings\fR\&. The XML schema files must have the filename extension
\&.gschema\&.xml\&. For a detailed description of the XML file format, see the
\fBGSettings\fR
documentation\&.
.PP
At runtime, GSettings looks for schemas in the
glib\-2\&.0/schemas
subdirectories of all directories specified in the
\fBXDG_DATA_DIRS\fR
environment variable\&. The usual location to install schema files is
/usr/share/glib\-2\&.0/schemas\&.
.PP
In addition to schema files, glib\-compile\-schemas reads \*(Aqvendor override\*(Aq files, which are key files that can override default values for keys in the schemas\&. The group names in the key files are the schema id, and the values are written in serialized GVariant form\&. Vendor ovrride files must have the filename extension
\&.gschema\&.override\&.
.SS "Options"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print help and exit
.RE
.PP
\fB\-\-targetdir=\fR\fB\fITARGETDIR\fR\fR
.RS 4
Store
gschemas\&.compiled
in
\fITARGETDIR\fR
instead of
\fIdirectory\fR\&.
.RE
.PP
\fB\-\-dry\-run\fR
.RS 4
Don\*(Aqt write
gschemas\&.compiled\&. This option can be used to check
\&.gschema\&.xml
sources for errors\&.
.RE
.PP
\fB\-\-allow\-any\-name\fR
.RS 4
Do not enforce restrictions on key names\&. Note that this option is purely to facility the transition from GConf, and will be removed at some time in the future\&.
.RE
.SH "SEE ALSO"
