
#include <support.h>
struct support_list supports[] = {
  {"MULTICAST", "", "", "MULTICAST_SUPPORT", "1", "0"},
  {"PPPOE", "pppd", "PPPoE", "PPPOE_SUPPORT", "1", "0"},
  {"WRITE_MAC", "", "", "WRITE_MAC_SUPPORT", "1", "0"},
  {"DDNS", "ez-ipupdate", "Dynamic DNS", "DDNS_SUPPORT", "1", "0"},
  {"PPPD", "pppd", "PPPD", "PPPD_SUPPORT", "1", "0"},
  {"L2TP", "l2tp", "PPTP", "L2TP_SUPPORT", "1", "0"},
  {"WL_STA", "", "", "WL_STA_SUPPORT", "1", "0"},
  {"UDHCPD", "udhcpd", "dhcp server", "UDHCPD_SUPPORT", "1", "0"},
  {"XBOX", "", "", "XBOX_SUPPORT", "1", "0"},
  {"HEARTBEAT", "bpalogin", "heartbeat", "HEARTBEAT_SUPPORT", "1", "0"},
  {"BACKUP_RESTORE", "", "", "BACKUP_RESTORE_SUPPORT", "1", "0"},
  {"PORT_TRIGGER", "", "", "PORT_TRIGGER_SUPPORT", "1", "0"},
  {"SETUP_WIZARD", "", "", "SETUP_WIZARD_SUPPORT", "1", "0"},
  {"GET_POST", "", "", "GET_POST_SUPPORT", "1", "0"},
  {"SETUP_WIZARD", "", "", "SETUP_WIZARD_SUPPORT", "1", "0"},
  {"GET_POST", "", "", "GET_POST_SUPPORT", "1", "0"},
  {"TFTPD", "tftpd", "tftp server", "TFTPD_SUPPORT", "1", "0"},
  {"HTTPD", "httpd", "http server", "HTTPD_SUPPORT", "1", "0"},
  {"DIAG", "", "", "DIAG_SUPPORT", "1", "0"},
  {"DNSMASQ", "dnsmasq", "DNS relay", "DNSMASQ_SUPPORT", "1", "0"},
  {"PPTP", "pptp", "PPTP", "PPTP_SUPPORT", "1", "0"},
  {"CRON", "crond", "CRON", "CRON_SUPPORT", "1", "0"},
  {"UDHCPC", "udhcpc", "dhcp client", "UDHCPC_SUPPORT", "1", "0"},
  {"EOU", "", "", "EOU_SUPPORT", "1", "0"},
  {"ZEBRA", "zebra", "Dynamic route", "ZEBRA_SUPPORT", "1", "0"},
//      {"HTTPS",               "",                     "",                     "HAVE_HTTPS",                   "1", "0"},
  {"HSIAB", "hotspot", "hotspot support", "HSIAB_SUPPORT", "0", "0"},
};
