#!/bin/ksh
#
# NSDistrib -- make NeXTSTEP distribution of lsof 4.x
#
# Usage: NSDistrib [<suffix>]
#
#	 <suffix>	optional suffix for identification

if test $# -gt 1
then
  echo "Usage: [<suffix>]"
  exit 1
fi
$HOME/src/lsof4/support/GenericDistrib ns $1
