obj-$(CPTCFG_VIDEO_TI_VPE) += ti-vpe.o
obj-$(CPTCFG_VIDEO_TI_VPDMA) += ti-vpdma.o
obj-$(CPTCFG_VIDEO_TI_SC) += ti-sc.o
obj-$(CPTCFG_VIDEO_TI_CSC) += ti-csc.o

ti-vpe-y := vpe.o
ti-vpdma-y := vpdma.o
ti-sc-y := sc.o
ti-csc-y := csc.o

ccflags-$(CPTCFG_VIDEO_TI_VPE_DEBUG) += -DDEBUG

obj-$(CPTCFG_VIDEO_TI_CAL) += ti-cal.o

ti-cal-y := cal.o
