svn add compat/windows/mslink
svn add doc/examples/avio_dir_cmd.c
svn add doc/examples/avio_list_dir.c
svn add doc/examples/http_multiclient.c
svn add ffmpeg_vda.c
svn add ffmpeg_videotoolbox.c
svn add libavcodec/aac_defines.h
svn add libavcodec/aacdec_fixed.c
svn add libavcodec/aacdec_template.c
svn add libavcodec/aacenc_is.c
svn add libavcodec/aacenc_is.h
svn add libavcodec/aacenc_pred.c
svn add libavcodec/aacenc_pred.h
svn add libavcodec/aacenc_quantization.h
svn add libavcodec/aacenc_tns.c
svn add libavcodec/aacenc_tns.h
svn add libavcodec/aacenc_utils.h
svn add libavcodec/aacenctab.c
svn add libavcodec/aacenctab.h
svn add libavcodec/aacps_fixed.c
svn add libavcodec/aacps_fixed_tablegen.c
svn add libavcodec/aacps_fixed_tablegen.h
svn add libavcodec/aacps_float.c
svn add libavcodec/aacps_tablegen_template.c
svn add libavcodec/aacpsdsp.c
svn add libavcodec/aacpsdsp_fixed.c
svn add libavcodec/aacpsdsp_float.c
svn add libavcodec/aacpsdsp_template.c
svn add libavcodec/aacsbr_fixed.c
svn add libavcodec/aacsbr_fixed_tablegen.c
svn add libavcodec/aacsbr_fixed_tablegen.h
svn add libavcodec/aacsbr_tablegen_common.h
svn add libavcodec/aacsbr_template.c
svn add libavcodec/aarch64/h264pred_init.c
svn add libavcodec/aarch64/h264pred_neon.S
svn add libavcodec/api-flac-test.c
svn add libavcodec/cbrt_fixed_tablegen.c
svn add libavcodec/cbrt_tablegen_template.c
svn add libavcodec/dds.c
svn add libavcodec/elsdec.c
svn add libavcodec/elsdec.h
svn add libavcodec/g729_parser.c
svn add libavcodec/h263data.c
svn add libavcodec/hap.c
svn add libavcodec/hap.h
svn add libavcodec/hapdec.c
svn add libavcodec/hapenc.c
svn add libavcodec/hevc_data.c
svn add libavcodec/hevc_mp4toannexb_bsf.c
svn add libavcodec/hevc_parse.c
svn add libavcodec/hevc_ps_enc.c
svn add libavcodec/libkvazaar.c
svn add libavcodec/mips/blockdsp_init_mips.c
svn add libavcodec/mips/blockdsp_mips.h
svn add libavcodec/mips/blockdsp_mmi.c
svn add libavcodec/mips/blockdsp_msa.c
svn add libavcodec/mips/constants.c
svn add libavcodec/mips/constants.h
svn add libavcodec/mips/h263dsp_init_mips.c
svn add libavcodec/mips/h263dsp_mips.h
svn add libavcodec/mips/h263dsp_msa.c
svn add libavcodec/mips/h264chroma_msa.c
svn add libavcodec/mips/h264idct_msa.c
svn add libavcodec/mips/h264pred_init_mips.c
svn add libavcodec/mips/h264pred_mips.h
svn add libavcodec/mips/h264pred_mmi.c
svn add libavcodec/mips/h264pred_msa.c
svn add libavcodec/mips/h264qpel_init_mips.c
svn add libavcodec/mips/h264qpel_mmi.c
svn add libavcodec/mips/h264qpel_msa.c
svn add libavcodec/mips/hevc_lpf_sao_msa.c
svn add libavcodec/mips/hevcpred_init_mips.c
svn add libavcodec/mips/hevcpred_mips.h
svn add libavcodec/mips/hevcpred_msa.c
svn add libavcodec/mips/hpeldsp_init_mips.c
svn add libavcodec/mips/hpeldsp_mips.h
svn add libavcodec/mips/hpeldsp_msa.c
svn add libavcodec/mips/idctdsp_init_mips.c
svn add libavcodec/mips/idctdsp_mips.h
svn add libavcodec/mips/idctdsp_mmi.c
svn add libavcodec/mips/idctdsp_msa.c
svn add libavcodec/mips/me_cmp_init_mips.c
svn add libavcodec/mips/me_cmp_mips.h
svn add libavcodec/mips/me_cmp_msa.c
svn add libavcodec/mips/mpegvideo_init_mips.c
svn add libavcodec/mips/mpegvideo_mips.h
svn add libavcodec/mips/mpegvideo_mmi.c
svn add libavcodec/mips/mpegvideo_msa.c
svn add libavcodec/mips/mpegvideoencdsp_init_mips.c
svn add libavcodec/mips/mpegvideoencdsp_msa.c
svn add libavcodec/mips/pixblockdsp_init_mips.c
svn add libavcodec/mips/pixblockdsp_mips.h
svn add libavcodec/mips/pixblockdsp_mmi.c
svn add libavcodec/mips/pixblockdsp_msa.c
svn add libavcodec/mips/qpeldsp_init_mips.c
svn add libavcodec/mips/qpeldsp_mips.h
svn add libavcodec/mips/qpeldsp_msa.c
svn add libavcodec/mips/simple_idct_mmi.c
svn add libavcodec/mips/simple_idct_msa.c
svn add libavcodec/mips/vp8_idct_msa.c
svn add libavcodec/mips/vp8_lpf_msa.c
svn add libavcodec/mips/vp8_mc_msa.c
svn add libavcodec/mips/vp8dsp_init_mips.c
svn add libavcodec/mips/vp8dsp_mips.h
svn add libavcodec/mips/vp9_idct_msa.c
svn add libavcodec/mips/vp9_intra_msa.c
svn add libavcodec/mips/vp9_lpf_msa.c
svn add libavcodec/mips/vp9_mc_msa.c
svn add libavcodec/mips/vp9dsp_init_mips.c
svn add libavcodec/mips/vp9dsp_mips.h
svn add libavcodec/mips/xvid_idct_mmi.c
svn add libavcodec/mips/xvididct_init_mips.c
svn add libavcodec/mips/xvididct_mips.h
svn add libavcodec/mpeg12vlc.h
svn add libavcodec/mpegpicture.c
svn add libavcodec/mpegpicture.h
svn add libavcodec/qsvdec_h264.c
svn add libavcodec/qsvdec_h2645.c
svn add libavcodec/qsvdec_mpeg2.c
svn add libavcodec/qsvdec_vc1.c
svn add libavcodec/qsvenc_hevc.c
svn add libavcodec/qsvenc_mpeg2.c
svn add libavcodec/reverse.c
svn add libavcodec/rv10.h
svn add libavcodec/s3tc.c
svn add libavcodec/s3tc.h
svn add libavcodec/sbrdsp_fixed.c
svn add libavcodec/sbrdsp_template.c
svn add libavcodec/sinewin_fixed.c
svn add libavcodec/sinewin_fixed_tablegen.c
svn add libavcodec/sinewin_tablegen_template.c
svn add libavcodec/snappy.c
svn add libavcodec/snappy.h
svn add libavcodec/texturedsp.c
svn add libavcodec/texturedsp.h
svn add libavcodec/texturedspenc.c
svn add libavcodec/vaapi_hevc.c
svn add libavcodec/vda_internal.h
svn add libavcodec/vda_vt_internal.h
svn add libavcodec/vdpau_hevc.c
svn add libavcodec/videotoolbox.c
svn add libavcodec/videotoolbox.h
svn add libavcodec/x86/aacpsdsp.asm
svn add libavcodec/x86/aacpsdsp_init.c
svn add libavcodec/x86/jpeg2000dsp.asm
svn add libavcodec/x86/jpeg2000dsp_init.c
svn add libavfilter/af_dynaudnorm.c
svn add libavfilter/af_sidechaincompress.c
svn add libavfilter/avf_aphasemeter.c
svn add libavfilter/avf_showfreqs.c
svn add libavfilter/avf_showvolume.c
svn add libavfilter/f_drawgraph.c
svn add libavfilter/f_reverse.c
svn add libavfilter/psnr.h
svn add libavfilter/removegrain.h
svn add libavfilter/ssim.h
svn add libavfilter/vf_atadenoise.c
svn add libavfilter/vf_colorkey.c
svn add libavfilter/vf_deband.c
svn add libavfilter/vf_framerate.c
svn add libavfilter/vf_neighbor.c
svn add libavfilter/vf_random.c
svn add libavfilter/vf_removegrain.c
svn add libavfilter/vf_ssim.c
svn add libavfilter/vf_stack.c
svn add libavfilter/vf_vectorscope.c
svn add libavfilter/vf_waveform.c
svn add libavfilter/x86/vf_psnr.asm
svn add libavfilter/x86/vf_psnr_init.c
svn add libavfilter/x86/vf_removegrain.asm
svn add libavfilter/x86/vf_removegrain_init.c
svn add libavfilter/x86/vf_ssim.asm
svn add libavfilter/x86/vf_ssim_init.c
svn add libavformat/aadec.c
svn add libavformat/asfdec.c
svn add libavformat/asfdec_f.c
svn add libavformat/asfdec_o.c
svn add libavformat/async.c
svn add libavutil/mem_internal.h
svn add libavutil/reverse.c
svn add libavutil/tea.c
svn add libavutil/tea.h
svn add libswscale/alphablend.c
svn add libswscale/gamma.c
svn add libswscale/hscale.c
svn add libswscale/slice.c
svn add libswscale/vscale.c
svn add tests/api
svn add tests/checkasm
svn add tests/fate/api.mak
svn add tests/fate/checkasm.mak
svn add tests/filtergraphs/mergeplanes
svn add tests/ref/fate/api-h264
svn add tests/ref/fate/asf-repldata
svn add tests/ref/fate/async
svn add tests/ref/fate/bcstm
svn add tests/ref/fate/bfstm
svn add tests/ref/fate/d-eavp6-demux
svn add tests/ref/fate/dds-argb
svn add tests/ref/fate/dds-argb-aexp
svn add tests/ref/fate/dds-dx10-bc1
svn add tests/ref/fate/dds-dx10-bc1a
svn add tests/ref/fate/dds-dx10-bc2
svn add tests/ref/fate/dds-dx10-bc3
svn add tests/ref/fate/dds-dx10-bc4
svn add tests/ref/fate/dds-dx10-bc5
svn add tests/ref/fate/dds-dxt1
svn add tests/ref/fate/dds-dxt1-normalmap
svn add tests/ref/fate/dds-dxt1a
svn add tests/ref/fate/dds-dxt2
svn add tests/ref/fate/dds-dxt3
svn add tests/ref/fate/dds-dxt4
svn add tests/ref/fate/dds-dxt5
svn add tests/ref/fate/dds-dxt5-aexp
svn add tests/ref/fate/dds-dxt5-normalmap
svn add tests/ref/fate/dds-dxt5-normalmap-ati
svn add tests/ref/fate/dds-dxt5-rbxg
svn add tests/ref/fate/dds-dxt5-rgxb
svn add tests/ref/fate/dds-dxt5-rxbg
svn add tests/ref/fate/dds-dxt5-rxgb
svn add tests/ref/fate/dds-dxt5-xgbr
svn add tests/ref/fate/dds-dxt5-xgxr
svn add tests/ref/fate/dds-dxt5-xrbg
svn add tests/ref/fate/dds-dxt5-ycocg
svn add tests/ref/fate/dds-dxt5-ycocg-scaled
svn add tests/ref/fate/dds-pal
svn add tests/ref/fate/dds-pal-ati
svn add tests/ref/fate/dds-rgb16
svn add tests/ref/fate/dds-rgb24
svn add tests/ref/fate/dds-rgba
svn add tests/ref/fate/dds-rgtc1s
svn add tests/ref/fate/dds-rgtc1u
svn add tests/ref/fate/dds-rgtc2s
svn add tests/ref/fate/dds-rgtc2u
svn add tests/ref/fate/dds-rgtc2u-xy
svn add tests/ref/fate/dds-uyvy
svn add tests/ref/fate/dds-xbgr
svn add tests/ref/fate/dds-xrgb
svn add tests/ref/fate/dds-y
svn add tests/ref/fate/dds-ya
svn add tests/ref/fate/dds-ycocg
svn add tests/ref/fate/dds-yuyv
svn add tests/ref/fate/filter-formats
svn add tests/ref/fate/filter-histogram-waveform
svn add tests/ref/fate/filter-mergeplanes
svn add tests/ref/fate/filter-pixdesc-ayuv64le
svn add tests/ref/fate/filter-pixdesc-ya8
svn add tests/ref/fate/filter-removegrain-mode-00
svn add tests/ref/fate/filter-removegrain-mode-01
svn add tests/ref/fate/filter-removegrain-mode-02
svn add tests/ref/fate/filter-removegrain-mode-03
svn add tests/ref/fate/filter-removegrain-mode-04
svn add tests/ref/fate/filter-removegrain-mode-05
svn add tests/ref/fate/filter-removegrain-mode-06
svn add tests/ref/fate/filter-removegrain-mode-07
svn add tests/ref/fate/filter-removegrain-mode-08
svn add tests/ref/fate/filter-removegrain-mode-09
svn add tests/ref/fate/filter-removegrain-mode-10
svn add tests/ref/fate/filter-removegrain-mode-11
svn add tests/ref/fate/filter-removegrain-mode-12
svn add tests/ref/fate/filter-removegrain-mode-13
svn add tests/ref/fate/filter-removegrain-mode-14
svn add tests/ref/fate/filter-removegrain-mode-15
svn add tests/ref/fate/filter-removegrain-mode-16
svn add tests/ref/fate/filter-removegrain-mode-17
svn add tests/ref/fate/filter-removegrain-mode-18
svn add tests/ref/fate/filter-removegrain-mode-19
svn add tests/ref/fate/filter-removegrain-mode-20
svn add tests/ref/fate/filter-removegrain-mode-21
svn add tests/ref/fate/filter-removegrain-mode-22
svn add tests/ref/fate/filter-removegrain-mode-23
svn add tests/ref/fate/filter-removegrain-mode-24
svn add tests/ref/fate/filter-stereo3d-sbsl-agmc
svn add tests/ref/fate/filter-stereo3d-sbsl-agmd
svn add tests/ref/fate/filter-stereo3d-sbsl-agmg
svn add tests/ref/fate/filter-stereo3d-sbsl-agmh
svn add tests/ref/fate/filter-stereo3d-sbsl-arbg
svn add tests/ref/fate/filter-stereo3d-sbsl-arcc
svn add tests/ref/fate/filter-stereo3d-sbsl-arcd
svn add tests/ref/fate/filter-stereo3d-sbsl-arcg
svn add tests/ref/fate/filter-stereo3d-sbsl-arch
svn add tests/ref/fate/filter-stereo3d-sbsl-argg
svn add tests/ref/fate/filter-stereo3d-sbsl-aybc
svn add tests/ref/fate/filter-stereo3d-sbsl-aybd
svn add tests/ref/fate/filter-stereo3d-sbsl-aybg
svn add tests/ref/fate/filter-stereo3d-sbsl-aybh
svn add tests/ref/fate/filter-tblend
svn add tests/ref/fate/filter-vectorscope_color
svn add tests/ref/fate/filter-vectorscope_color2
svn add tests/ref/fate/filter-vectorscope_color3
svn add tests/ref/fate/filter-vectorscope_color4
svn add tests/ref/fate/filter-vectorscope_gray
svn add tests/ref/fate/filter-vectorscope_xy
svn add tests/ref/fate/filter-w3fdif-complex
svn add tests/ref/fate/filter-w3fdif-simple
svn add tests/ref/fate/filter-waveform_column
svn add tests/ref/fate/filter-waveform_envelope
svn add tests/ref/fate/filter-waveform_row
svn add tests/ref/fate/filter-waveform_uv
svn add tests/ref/fate/g2m2
svn add tests/ref/fate/g2m3
svn add tests/ref/fate/g2m4
svn add tests/ref/fate/hap-chunk
svn add tests/ref/fate/hap1
svn add tests/ref/fate/hap5
svn add tests/ref/fate/hapy
svn add tests/ref/fate/j2k-dwt
svn add tests/ref/fate/tea
svn add tests/ref/fate/txd-odd
svn add tests/ref/vsynth/vsynth1-ffv1-v0
svn add tests/ref/vsynth/vsynth1-ffv1-v3-bgr0
svn add tests/ref/vsynth/vsynth1-ffv1-v3-yuv420p
svn add tests/ref/vsynth/vsynth1-ffv1-v3-yuv422p10
svn add tests/ref/vsynth/vsynth1-ffv1-v3-yuv444p16
svn add tests/ref/vsynth/vsynth1-ffv1.0
svn add tests/ref/vsynth/vsynth2-ffv1-v0
svn add tests/ref/vsynth/vsynth2-ffv1-v3-bgr0
svn add tests/ref/vsynth/vsynth2-ffv1-v3-yuv420p
svn add tests/ref/vsynth/vsynth2-ffv1-v3-yuv422p10
svn add tests/ref/vsynth/vsynth2-ffv1-v3-yuv444p16
svn add tests/ref/vsynth/vsynth2-ffv1.0
svn add tests/ref/vsynth/vsynth3-ffv1-v0
svn add tests/ref/vsynth/vsynth3-ffv1-v3-bgr0
svn add tests/ref/vsynth/vsynth3-ffv1-v3-yuv420p
svn add tests/ref/vsynth/vsynth3-ffv1-v3-yuv422p10
svn add tests/ref/vsynth/vsynth3-ffv1-v3-yuv444p16
svn add tests/ref/vsynth/vsynth3-ffv1.0
svn add tests/ref/vsynth/vsynth_lena-ffv1-v0
svn add tests/ref/vsynth/vsynth_lena-ffv1-v3-bgr0
svn add tests/ref/vsynth/vsynth_lena-ffv1-v3-yuv420
svn add tests/ref/vsynth/vsynth_lena-ffv1-v3-yuv420p
svn add tests/ref/vsynth/vsynth_lena-ffv1-v3-yuv422p10
svn add tests/ref/vsynth/vsynth_lena-ffv1-v3-yuv444p16
svn add tests/ref/vsynth/vsynth_lena-ffv1.0
