svn del .gitattributes
svn del 271.diff
svn del add.sh
svn del compat/avisynth/avisynth_c_25.h
svn del compat/avisynth/avs
svn del compat/avisynth/avs/capi.h
svn del compat/avisynth/avs/config.h
svn del compat/avisynth/avs/types.h
svn del configure.orig
svn del doc/examples/avio_list_dir.c
svn del doc/examples/qsvdec.c
svn del ffserver_config.c
svn del ffserver_config.h
svn del libavcodec/aarch64/imdct15_init.c
svn del libavcodec/aarch64/imdct15_neon.S
svn del libavcodec/aarch64/opus_imdct_init.c
svn del libavcodec/aarch64/opus_imdct_neon.S
svn del libavcodec/api-flac-test.c
svn del libavcodec/apng.h
svn del libavcodec/arm/fmtconvert_vfp_armv6.S
svn del libavcodec/arm/g722dsp_init_arm.c
svn del libavcodec/arm/g722dsp_neon.S
svn del libavcodec/arm/hevcdsp_arm.h
svn del libavcodec/arm/hevcdsp_deblock_neon.S
svn del libavcodec/arm/hevcdsp_idct_neon.S
svn del libavcodec/arm/hevcdsp_init_arm.c
svn del libavcodec/arm/hevcdsp_init_neon.c
svn del libavcodec/arm/hevcdsp_qpel_neon.S
svn del libavcodec/canopus.c
svn del libavcodec/canopus.h
svn del libavcodec/ccaption_dec.c
svn del libavcodec/d3d11va.h
svn del libavcodec/dca_exss.c
svn del libavcodec/dca_syncwords.h
svn del libavcodec/dca_xll.c
svn del libavcodec/dcadata.c
svn del libavcodec/dsputil.h
svn del libavcodec/dsputil_compat.c
svn del libavcodec/dss_sp.c
svn del libavcodec/dxva2_hevc.c
svn del libavcodec/g722dsp.c
svn del libavcodec/g722dsp.h
svn del libavcodec/hq_hqa.c
svn del libavcodec/hq_hqa.h
svn del libavcodec/hq_hqadata.c
svn del libavcodec/hq_hqadsp.c
svn del libavcodec/hq_hqadsp.h
svn del libavcodec/hqx.c
svn del libavcodec/hqx.h
svn del libavcodec/hqxdsp.c
svn del libavcodec/hqxdsp.h
svn del libavcodec/hqxvlc.c
svn del libavcodec/imdct15.c
svn del libavcodec/imdct15.h
svn del libavcodec/ivi.c
svn del libavcodec/ivi.h
svn del libavcodec/ivi_common.c
svn del libavcodec/ivi_common.h
svn del libavcodec/jpeg2000dsp.c
svn del libavcodec/jpeg2000dsp.h
svn del libavcodec/jpegtables.c
svn del libavcodec/jpegtables.h
svn del libavcodec/libdcadec.c
svn del libavcodec/libopenh264enc.c
svn del libavcodec/libwebpenc_animencoder.c
svn del libavcodec/libwebpenc_common.c
svn del libavcodec/libwebpenc_common.h
svn del libavcodec/mathops.c
svn del libavcodec/mips/h264chroma_init_mips.c
svn del libavcodec/mips/h264chroma_mips.h
svn del libavcodec/mips/h264chroma_mmi.c
svn del libavcodec/mips/h264dsp_init_mips.c
svn del libavcodec/mips/h264dsp_mips.h
svn del libavcodec/mips/h264dsp_mmi.c
svn del libavcodec/mips/h264dsp_msa.c
svn del libavcodec/mips/hevc_idct_msa.c
svn del libavcodec/mips/hevc_macros_msa.h
svn del libavcodec/mips/hevc_mc_bi_msa.c
svn del libavcodec/mips/hevc_mc_biw_msa.c
svn del libavcodec/mips/hevc_mc_uni_msa.c
svn del libavcodec/mips/hevc_mc_uniw_msa.c
svn del libavcodec/mips/hevcdsp_init_mips.c
svn del libavcodec/mips/hevcdsp_mips.h
svn del libavcodec/mips/hevcdsp_msa.c
svn del libavcodec/mjpeg.c
svn del libavcodec/mmaldec.c
svn del libavcodec/motion_est.h
svn del libavcodec/mpeg4_unpack_bframes_bsf.c
svn del libavcodec/mpegvideodata.c
svn del libavcodec/mpegvideodata.h
svn del libavcodec/nvenc.c
svn del libavcodec/opus_imdct.c
svn del libavcodec/opus_imdct.h
svn del libavcodec/qsv.c
svn del libavcodec/qsv.h
svn del libavcodec/qsv_api.c
svn del libavcodec/qsv_internal.h
svn del libavcodec/qsvdec.c
svn del libavcodec/qsvdec.h
svn del libavcodec/qsvdec_h264.c
svn del libavcodec/qsvenc.c
svn del libavcodec/qsvenc.h
svn del libavcodec/qsvenc_h264.c
svn del libavcodec/rl.c
svn del libavcodec/tableprint_vlc.h
svn del libavcodec/tdsc.c
svn del libavcodec/v210enc.h
svn del libavcodec/vaapi_mpeg.c
svn del libavcodec/vc1_block.c
svn del libavcodec/vc1_loopfilter.c
svn del libavcodec/vc1_mc.c
svn del libavcodec/vc1_pred.c
svn del libavcodec/vc1_pred.h
svn del libavcodec/vdpau_compat.h
svn del libavcodec/vorbis_parser_internal.h
svn del libavcodec/vp9_mc_template.c
svn del libavcodec/vp9dsp_10bpp.c
svn del libavcodec/vp9dsp_12bpp.c
svn del libavcodec/vp9dsp_8bpp.c
svn del libavcodec/vp9dsp_template.c
svn del libavcodec/x86/g722dsp.asm
svn del libavcodec/x86/g722dsp_init.c
svn del libavcodec/x86/hevc_sao.asm
svn del libavcodec/x86/idctdsp_mmx.c
svn del libavcodec/x86/mlpdsp.asm
svn del libavcodec/x86/mlpdsp.c
svn del libavcodec/x86/mlpdsp_init.c
svn del libavcodec/x86/v210enc.asm
svn del libavcodec/x86/v210enc_init.c
svn del libavcodec/x86/xvididct.asm
svn del libavcodec/x86/xvididct_mmx.c
svn del libavcodec/x86/xvididct_sse2.c
svn del libavdevice/alsa-audio-common.c
svn del libavdevice/alsa-audio-dec.c
svn del libavdevice/alsa-audio-enc.c
svn del libavdevice/alsa-audio.h
svn del libavdevice/alsa.c
svn del libavdevice/alsa.h
svn del libavdevice/alsa_dec.c
svn del libavdevice/alsa_enc.c
svn del libavdevice/decklink_common.cpp
svn del libavdevice/decklink_common.h
svn del libavdevice/decklink_common_c.h
svn del libavdevice/decklink_dec.cpp
svn del libavdevice/decklink_dec.h
svn del libavdevice/decklink_dec_c.c
svn del libavdevice/dshow_crossbar.c
svn del libavdevice/internal.h
svn del libavdevice/jack.c
svn del libavdevice/jack_audio.c
svn del libavdevice/oss.c
svn del libavdevice/oss.h
svn del libavdevice/oss_audio.c
svn del libavdevice/oss_audio.h
svn del libavdevice/oss_audio_dec.c
svn del libavdevice/oss_audio_enc.c
svn del libavdevice/oss_dec.c
svn del libavdevice/oss_enc.c
svn del libavdevice/sndio.c
svn del libavdevice/sndio.h
svn del libavdevice/sndio_common.c
svn del libavdevice/sndio_common.h
svn del libavdevice/utils.c
svn del libavdevice/xcbgrab.c
svn del libavfilter/af_aconvert.c
svn del libavfilter/af_chorus.c
svn del libavfilter/af_dcshift.c
svn del libavfilter/interlace.h
svn del libavfilter/libmpcodecs
svn del libavfilter/libmpcodecs/av_helpers.h
svn del libavfilter/libmpcodecs/cpudetect.h
svn del libavfilter/libmpcodecs/img_format.c
svn del libavfilter/libmpcodecs/img_format.h
svn del libavfilter/libmpcodecs/libvo
svn del libavfilter/libmpcodecs/libvo/fastmemcpy.h
svn del libavfilter/libmpcodecs/libvo/video_out.h
svn del libavfilter/libmpcodecs/mp_image.c
svn del libavfilter/libmpcodecs/mp_image.h
svn del libavfilter/libmpcodecs/mp_msg.h
svn del libavfilter/libmpcodecs/mpc_info.h
svn del libavfilter/libmpcodecs/vf.h
svn del libavfilter/libmpcodecs/vf_eq.c
svn del libavfilter/libmpcodecs/vf_eq2.c
svn del libavfilter/libmpcodecs/vf_fspp.c
svn del libavfilter/libmpcodecs/vf_ilpack.c
svn del libavfilter/libmpcodecs/vf_pp7.c
svn del libavfilter/libmpcodecs/vf_softpulldown.c
svn del libavfilter/libmpcodecs/vf_uspp.c
svn del libavfilter/libmpcodecs/vfcap.h
svn del libavfilter/tinterlace.h
svn del libavfilter/vf_colorlevels.c
svn del libavfilter/vf_cover_rect.c
svn del libavfilter/vf_detelecine.c
svn del libavfilter/vf_eq.c
svn del libavfilter/vf_eq.h
svn del libavfilter/vf_fftfilt.c
svn del libavfilter/vf_find_rect.c
svn del libavfilter/vf_fspp.c
svn del libavfilter/vf_fspp.h
svn del libavfilter/vf_mp.c
svn del libavfilter/vf_noise.h
svn del libavfilter/vf_palettegen.c
svn del libavfilter/vf_paletteuse.c
svn del libavfilter/vf_pp7.c
svn del libavfilter/vf_pp7.h
svn del libavfilter/vf_qp.c
svn del libavfilter/vf_repeatfields.c
svn del libavfilter/vf_showpalette.c
svn del libavfilter/vf_uspp.c
svn del libavfilter/vf_xbr.c
svn del libavfilter/x86/vf_eq.c
svn del libavfilter/x86/vf_fspp.asm
svn del libavfilter/x86/vf_fspp_init.c
svn del libavfilter/x86/vf_interlace.asm
svn del libavfilter/x86/vf_interlace_init.c
svn del libavfilter/x86/vf_noise.c
svn del libavfilter/x86/vf_pp7.asm
svn del libavfilter/x86/vf_pp7_init.c
svn del libavfilter/x86/vf_tinterlace_init.c
svn del libavformat/apngdec.c
svn del libavformat/apngenc.c
svn del libavformat/dashenc.c
svn del libavformat/dss.c
svn del libavformat/dvbsub.c
svn del libavformat/mpjpegdec.c
svn del libavformat/rtpdec_ac3.c
svn del libavformat/rtpdec_dv.c
svn del libavformat/rtpdec_mpa_robust.c
svn del libavformat/rtpdec_vp9.c
svn del libavformat/rtpenc_h264.c
svn del libavformat/rtpenc_h264_hevc.c
svn del libavformat/rtpenc_mpegts.c
svn del libavformat/seek.c
svn del libavformat/seek.h
svn del libavformat/stldec.c
svn del libavformat/supdec.c
svn del libavformat/tls.h
svn del libavformat/tls_gnutls.c
svn del libavformat/tls_openssl.c
svn del libavformat/tls_securetransport.c
svn del libavformat/webm_chunk.c
svn del libavformat/webpenc.c
svn del libavresample/arm/asm-offsets.h
svn del libavresample/arm/resample_init.c
svn del libavresample/arm/resample_neon.S
svn del libavutil/camellia.c
svn del libavutil/camellia.h
svn del libavutil/cast5.c
svn del libavutil/cast5.h
svn del libavutil/color_utils.c
svn del libavutil/color_utils.h
svn del libavutil/error.c.orig
svn del libavutil/intfloat_readwrite.c
svn del libavutil/intfloat_readwrite.h
svn del libavutil/mips/asmdefs.h
svn del libavutil/mips/generic_macros_msa.h
svn del libavutil/ppc/float_dsp_vsx.c
svn del libavutil/ppc/float_dsp_vsx.h
svn del libavutil/softfloat_tables.h
svn del libavutil/thread.h
svn del libavutil/time_internal.h
svn del libavutil/twofish.c
svn del libavutil/twofish.h
svn del libavutil/wchar_filename.h
svn del libavutil/x86/intmath.h
svn del tests/fate/gapless.mak
svn del tests/fate/mpeg4.mak
svn del tests/fate/mxf.mak
svn del tests/ref/acodec/flac-exact-rice
svn del tests/ref/acodec/s302m
svn del tests/ref/acodec/tta
svn del tests/ref/acodec/wavpack
svn del tests/ref/fate/aic-oddsize
svn del tests/ref/fate/binsub-mksenc
svn del tests/ref/fate/binsub-movtextenc
svn del tests/ref/fate/canopus-cllc-argb
svn del tests/ref/fate/canopus-cllc-rgb
svn del tests/ref/fate/canopus-cllc-yuy2-noblock
svn del tests/ref/fate/canopus-hq_hqa-hq
svn del tests/ref/fate/canopus-hq_hqa-hqa
svn del tests/ref/fate/canopus-hq_hqa-inter
svn del tests/ref/fate/canopus-hqx422
svn del tests/ref/fate/canopus-hqx422a
svn del tests/ref/fate/cllc-argb
svn del tests/ref/fate/cllc-rgb
svn del tests/ref/fate/cllc-yuy2-noblock
svn del tests/ref/fate/dict
svn del tests/ref/fate/dpxparser
svn del tests/ref/fate/dss-lp
svn del tests/ref/fate/dss-sp
svn del tests/ref/fate/filter-2xbr
svn del tests/ref/fate/filter-3xbr
svn del tests/ref/fate/filter-4xbr
svn del tests/ref/fate/filter-palettegen-1
svn del tests/ref/fate/filter-palettegen-2
svn del tests/ref/fate/filter-paletteuse-bayer
svn del tests/ref/fate/filter-paletteuse-nodither
svn del tests/ref/fate/filter-paletteuse-sierra2_4a
svn del tests/ref/fate/filter-pixdesc-yuv440p10be
svn del tests/ref/fate/filter-pixdesc-yuv440p10le
svn del tests/ref/fate/filter-pixdesc-yuv440p12be
svn del tests/ref/fate/filter-pixdesc-yuv440p12le
svn del tests/ref/fate/filter-pp1
svn del tests/ref/fate/filter-qp
svn del tests/ref/fate/filter-showpalette
svn del tests/ref/fate/gapless-mp3
svn del tests/ref/fate/hevc-paramchange-yuv420p-yuv420p10
svn del tests/ref/fate/libavcodec-options
svn del tests/ref/fate/lossless-truehd-5.1
svn del tests/ref/fate/lossless-truehd-5.1-downmix-2.0
svn del tests/ref/fate/mpeg4-bsf-unpack-bframes
svn del tests/ref/fate/mpeg4-resolution-change-down-down
svn del tests/ref/fate/mpeg4-resolution-change-down-up
svn del tests/ref/fate/mpeg4-resolution-change-up-down
svn del tests/ref/fate/mpeg4-resolution-change-up-up
svn del tests/ref/fate/mxf-essencegroup-demux
svn del tests/ref/fate/mxf-missing-index-demux
svn del tests/ref/fate/opt
svn del tests/ref/fate/pict
svn del tests/ref/fate/ra3-144
svn del tests/ref/fate/rtmpdh
svn del tests/ref/fate/sub-ass-to-ass-transcode
svn del tests/ref/fate/sub-cc
svn del tests/ref/fate/sub-movtextenc
svn del tests/ref/fate/sub-ssa-to-ass-remux
svn del tests/ref/fate/sub-stl
svn del tests/ref/fate/svq1-headerswap
svn del tests/ref/fate/tdsc
svn del tests/ref/fate/theora-offset
svn del tests/ref/fate/tscc2
svn del tests/ref/fate/tscc2-avi
svn del tests/ref/fate/tscc2-mov
svn del tests/ref/fate/vc1_ilaced_twomv
svn del tests/ref/fate/vp9-05-resize
svn del tests/ref/fate/vp9-06-bilinear
svn del tests/ref/fate/vp9-09-lf_deltas
svn del tests/ref/fate/vp9-10-show-existing-frame
svn del tests/ref/fate/vp9-10-show-existing-frame2
svn del tests/ref/fate/vp9-15-segkey_adpq
svn del tests/ref/fate/vp9-16-intra-only
svn del tests/ref/fate/vp9-trac3849
svn del tests/ref/fate/vp9-trac4359
svn del tests/ref/fate/vp9p1-04-yuv422
svn del tests/ref/fate/vp9p1-04-yuv440
svn del tests/ref/fate/vp9p1-04-yuv444
svn del tests/ref/fate/vp9p2-20-10bit-yuv420
svn del tests/ref/fate/vp9p2-20-12bit-yuv420
svn del tests/ref/fate/vp9p3-20-10bit-yuv422
svn del tests/ref/fate/vp9p3-20-10bit-yuv440
svn del tests/ref/fate/vp9p3-20-10bit-yuv444
svn del tests/ref/fate/vp9p3-20-12bit-yuv422
svn del tests/ref/fate/vp9p3-20-12bit-yuv440
svn del tests/ref/fate/vp9p3-20-12bit-yuv444
svn del tests/ref/fate/webm-dash-manifest-live
svn del tests/ref/fate/webm-dash-manifest-representations
svn del tests/ref/lavf/mxf_opatom
svn del tests/ref/lavf/mxf_opatom_audio
svn del tests/ref/seek/extra-mp3
svn del tests/ref/seek/lavf-mxf_opatom
svn del tests/ref/seek/lavf-mxf_opatom_audio
svn del tests/ref/seek/vsynth2-asv1
svn del tests/ref/seek/vsynth2-asv2
svn del tests/ref/seek/vsynth2-dnxhd-1080i
svn del tests/ref/seek/vsynth2-dnxhd-720p
svn del tests/ref/seek/vsynth2-dnxhd-720p-rd
svn del tests/ref/seek/vsynth2-dv
svn del tests/ref/seek/vsynth2-dv-411
svn del tests/ref/seek/vsynth2-dv-50
svn del tests/ref/seek/vsynth2-ffv1
svn del tests/ref/seek/vsynth2-flashsv
svn del tests/ref/seek/vsynth2-flv
svn del tests/ref/seek/vsynth2-h261
svn del tests/ref/seek/vsynth2-h263
svn del tests/ref/seek/vsynth2-h263p
svn del tests/ref/seek/vsynth2-huffyuv
svn del tests/ref/seek/vsynth2-jpegls
svn del tests/ref/seek/vsynth2-ljpeg
svn del tests/ref/seek/vsynth2-mjpeg
svn del tests/ref/seek/vsynth2-mpeg1
svn del tests/ref/seek/vsynth2-mpeg1b
svn del tests/ref/seek/vsynth2-mpeg2-422
svn del tests/ref/seek/vsynth2-mpeg2-idct-int
svn del tests/ref/seek/vsynth2-mpeg2-ilace
svn del tests/ref/seek/vsynth2-mpeg2-ivlc-qprd
svn del tests/ref/seek/vsynth2-mpeg2-thread
svn del tests/ref/seek/vsynth2-mpeg2-thread-ivlc
svn del tests/ref/seek/vsynth2-mpeg4
svn del tests/ref/seek/vsynth2-mpeg4-adap
svn del tests/ref/seek/vsynth2-mpeg4-adv
svn del tests/ref/seek/vsynth2-mpeg4-error
svn del tests/ref/seek/vsynth2-mpeg4-nr
svn del tests/ref/seek/vsynth2-mpeg4-nsse
svn del tests/ref/seek/vsynth2-mpeg4-qpel
svn del tests/ref/seek/vsynth2-mpeg4-qprd
svn del tests/ref/seek/vsynth2-mpeg4-rc
svn del tests/ref/seek/vsynth2-mpeg4-thread
svn del tests/ref/seek/vsynth2-msmpeg4
svn del tests/ref/seek/vsynth2-msmpeg4v2
svn del tests/ref/seek/vsynth2-rgb
svn del tests/ref/seek/vsynth2-roqvideo
svn del tests/ref/seek/vsynth2-rv10
svn del tests/ref/seek/vsynth2-rv20
svn del tests/ref/seek/vsynth2-snow
svn del tests/ref/seek/vsynth2-snow-ll
svn del tests/ref/seek/vsynth2-svq1
svn del tests/ref/seek/vsynth2-wmv1
svn del tests/ref/seek/vsynth2-wmv2
svn del tests/ref/seek/vsynth2-yuv
svn del tests/ref/seek/vsynth_lena-asv1
svn del tests/ref/seek/vsynth_lena-asv2
svn del tests/ref/seek/vsynth_lena-dnxhd-1080i
svn del tests/ref/seek/vsynth_lena-dnxhd-720p
svn del tests/ref/seek/vsynth_lena-dnxhd-720p-rd
svn del tests/ref/seek/vsynth_lena-dv
svn del tests/ref/seek/vsynth_lena-dv-411
svn del tests/ref/seek/vsynth_lena-dv-50
svn del tests/ref/seek/vsynth_lena-ffv1
svn del tests/ref/seek/vsynth_lena-flashsv
svn del tests/ref/seek/vsynth_lena-flv
svn del tests/ref/seek/vsynth_lena-h261
svn del tests/ref/seek/vsynth_lena-h263
svn del tests/ref/seek/vsynth_lena-h263p
svn del tests/ref/seek/vsynth_lena-huffyuv
svn del tests/ref/seek/vsynth_lena-jpegls
svn del tests/ref/seek/vsynth_lena-ljpeg
svn del tests/ref/seek/vsynth_lena-mjpeg
svn del tests/ref/seek/vsynth_lena-mpeg1
svn del tests/ref/seek/vsynth_lena-mpeg1b
svn del tests/ref/seek/vsynth_lena-mpeg2-422
svn del tests/ref/seek/vsynth_lena-mpeg2-idct-int
svn del tests/ref/seek/vsynth_lena-mpeg2-ilace
svn del tests/ref/seek/vsynth_lena-mpeg2-ivlc-qprd
svn del tests/ref/seek/vsynth_lena-mpeg2-thread
svn del tests/ref/seek/vsynth_lena-mpeg2-thread-ivlc
svn del tests/ref/seek/vsynth_lena-mpeg4
svn del tests/ref/seek/vsynth_lena-mpeg4-adap
svn del tests/ref/seek/vsynth_lena-mpeg4-adv
svn del tests/ref/seek/vsynth_lena-mpeg4-error
svn del tests/ref/seek/vsynth_lena-mpeg4-nr
svn del tests/ref/seek/vsynth_lena-mpeg4-nsse
svn del tests/ref/seek/vsynth_lena-mpeg4-qpel
svn del tests/ref/seek/vsynth_lena-mpeg4-qprd
svn del tests/ref/seek/vsynth_lena-mpeg4-rc
svn del tests/ref/seek/vsynth_lena-mpeg4-thread
svn del tests/ref/seek/vsynth_lena-msmpeg4
svn del tests/ref/seek/vsynth_lena-msmpeg4v2
svn del tests/ref/seek/vsynth_lena-rgb
svn del tests/ref/seek/vsynth_lena-roqvideo
svn del tests/ref/seek/vsynth_lena-rv10
svn del tests/ref/seek/vsynth_lena-rv20
svn del tests/ref/seek/vsynth_lena-snow
svn del tests/ref/seek/vsynth_lena-snow-ll
svn del tests/ref/seek/vsynth_lena-svq1
svn del tests/ref/seek/vsynth_lena-wmv1
svn del tests/ref/seek/vsynth_lena-wmv2
svn del tests/ref/seek/vsynth_lena-yuv
svn del tests/ref/vsynth/vsynth1-cinepak
svn del tests/ref/vsynth/vsynth1-dnxhd-1080i-colr
svn del tests/ref/vsynth/vsynth1-mjpeg-trell
svn del tests/ref/vsynth/vsynth1-xface
svn del tests/ref/vsynth/vsynth2-cinepak
svn del tests/ref/vsynth/vsynth2-dnxhd-1080i-colr
svn del tests/ref/vsynth/vsynth2-dnxhd_1080i
svn del tests/ref/vsynth/vsynth2-dv_411
svn del tests/ref/vsynth/vsynth2-mjpeg-trell
svn del tests/ref/vsynth/vsynth2-xface
svn del tests/ref/vsynth/vsynth2-zmbv
svn del tests/ref/vsynth/vsynth3-dnxhd-1080i-colr
svn del tests/ref/vsynth/vsynth3-mjpeg-trell
svn del tests/ref/vsynth/vsynth3-xface
svn del tests/ref/vsynth/vsynth_lena-amv
svn del tests/ref/vsynth/vsynth_lena-asv1
svn del tests/ref/vsynth/vsynth_lena-asv2
svn del tests/ref/vsynth/vsynth_lena-avui
svn del tests/ref/vsynth/vsynth_lena-cinepak
svn del tests/ref/vsynth/vsynth_lena-cljr
svn del tests/ref/vsynth/vsynth_lena-dnxhd-1080i
svn del tests/ref/vsynth/vsynth_lena-dnxhd-1080i-colr
svn del tests/ref/vsynth/vsynth_lena-dnxhd-720p
svn del tests/ref/vsynth/vsynth_lena-dnxhd-720p-10bit
svn del tests/ref/vsynth/vsynth_lena-dnxhd-720p-rd
svn del tests/ref/vsynth/vsynth_lena-dnxhd_1080i
svn del tests/ref/vsynth/vsynth_lena-dv
svn del tests/ref/vsynth/vsynth_lena-dv-411
svn del tests/ref/vsynth/vsynth_lena-dv-50
svn del tests/ref/vsynth/vsynth_lena-dv_411
svn del tests/ref/vsynth/vsynth_lena-ffv1
svn del tests/ref/vsynth/vsynth_lena-ffv1.0
svn del tests/ref/vsynth/vsynth_lena-ffvhuff
svn del tests/ref/vsynth/vsynth_lena-ffvhuff420p12
svn del tests/ref/vsynth/vsynth_lena-ffvhuff422p10left
svn del tests/ref/vsynth/vsynth_lena-ffvhuff444
svn del tests/ref/vsynth/vsynth_lena-ffvhuff444p16
svn del tests/ref/vsynth/vsynth_lena-flashsv
svn del tests/ref/vsynth/vsynth_lena-flashsv2
svn del tests/ref/vsynth/vsynth_lena-flv
svn del tests/ref/vsynth/vsynth_lena-h261
svn del tests/ref/vsynth/vsynth_lena-h261-trellis
svn del tests/ref/vsynth/vsynth_lena-h263
svn del tests/ref/vsynth/vsynth_lena-h263-obmc
svn del tests/ref/vsynth/vsynth_lena-h263p
svn del tests/ref/vsynth/vsynth_lena-huffyuv
svn del tests/ref/vsynth/vsynth_lena-huffyuvbgr24
svn del tests/ref/vsynth/vsynth_lena-huffyuvbgra
svn del tests/ref/vsynth/vsynth_lena-jpeg2000
svn del tests/ref/vsynth/vsynth_lena-jpeg2000-97
svn del tests/ref/vsynth/vsynth_lena-jpegls
svn del tests/ref/vsynth/vsynth_lena-ljpeg
svn del tests/ref/vsynth/vsynth_lena-mjpeg
svn del tests/ref/vsynth/vsynth_lena-mjpeg-422
svn del tests/ref/vsynth/vsynth_lena-mjpeg-444
svn del tests/ref/vsynth/vsynth_lena-mjpeg-trell
svn del tests/ref/vsynth/vsynth_lena-mpeg1
svn del tests/ref/vsynth/vsynth_lena-mpeg1b
svn del tests/ref/vsynth/vsynth_lena-mpeg2
svn del tests/ref/vsynth/vsynth_lena-mpeg2-422
svn del tests/ref/vsynth/vsynth_lena-mpeg2-idct-int
svn del tests/ref/vsynth/vsynth_lena-mpeg2-ilace
svn del tests/ref/vsynth/vsynth_lena-mpeg2-ivlc-qprd
svn del tests/ref/vsynth/vsynth_lena-mpeg2-thread
svn del tests/ref/vsynth/vsynth_lena-mpeg2-thread-ivlc
svn del tests/ref/vsynth/vsynth_lena-mpeg4
svn del tests/ref/vsynth/vsynth_lena-mpeg4-adap
svn del tests/ref/vsynth/vsynth_lena-mpeg4-adv
svn del tests/ref/vsynth/vsynth_lena-mpeg4-error
svn del tests/ref/vsynth/vsynth_lena-mpeg4-nr
svn del tests/ref/vsynth/vsynth_lena-mpeg4-nsse
svn del tests/ref/vsynth/vsynth_lena-mpeg4-qpel
svn del tests/ref/vsynth/vsynth_lena-mpeg4-qprd
svn del tests/ref/vsynth/vsynth_lena-mpeg4-rc
svn del tests/ref/vsynth/vsynth_lena-mpeg4-thread
svn del tests/ref/vsynth/vsynth_lena-mpng
svn del tests/ref/vsynth/vsynth_lena-msmpeg4
svn del tests/ref/vsynth/vsynth_lena-msmpeg4v2
svn del tests/ref/vsynth/vsynth_lena-msvideo1
svn del tests/ref/vsynth/vsynth_lena-prores
svn del tests/ref/vsynth/vsynth_lena-prores_ks
svn del tests/ref/vsynth/vsynth_lena-qtrle
svn del tests/ref/vsynth/vsynth_lena-qtrlegray
svn del tests/ref/vsynth/vsynth_lena-r210
svn del tests/ref/vsynth/vsynth_lena-rgb
svn del tests/ref/vsynth/vsynth_lena-roqvideo
svn del tests/ref/vsynth/vsynth_lena-rv10
svn del tests/ref/vsynth/vsynth_lena-rv20
svn del tests/ref/vsynth/vsynth_lena-snow
svn del tests/ref/vsynth/vsynth_lena-snow-hpel
svn del tests/ref/vsynth/vsynth_lena-snow-ll
svn del tests/ref/vsynth/vsynth_lena-svq1
svn del tests/ref/vsynth/vsynth_lena-v210
svn del tests/ref/vsynth/vsynth_lena-v308
svn del tests/ref/vsynth/vsynth_lena-v408
svn del tests/ref/vsynth/vsynth_lena-wmv1
svn del tests/ref/vsynth/vsynth_lena-wmv2
svn del tests/ref/vsynth/vsynth_lena-xface
svn del tests/ref/vsynth/vsynth_lena-y41p
svn del tests/ref/vsynth/vsynth_lena-yuv
svn del tests/ref/vsynth/vsynth_lena-yuv4
svn del tests/ref/vsynth/vsynth_lena-zlib
svn del tests/ref/vsynth/vsynth_lena-zmbv
svn del tests/ref/vsynth2
svn del tests/ref/vsynth2/cljr
svn del tests/ref/vsynth2/huffyuv
svn del tests/ref/vsynth2/yuv
svn del tests/ref/vsynth_lena
svn del tests/ref/vsynth_lena/cljr
svn del tests/ref/vsynth_lena/huffyuv
svn del tests/ref/vsynth_lena/yuv
svn del tests/reference.pnm
svn del tools/coverity.c
svn del tools/sidxindex.c
