'\" t
.\"     Title: nutscan_scan_xml_http_range
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 04/02/2024
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.8.2
.\"  Language: English
.\"
.TH "NUTSCAN_SCAN_XML_HTT" "3" "04/02/2024" "Network UPS Tools 2\&.8\&.2" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nutscan_scan_xml_http_range \- Scan network for XML/HTTP devices\&.
.SH "SYNOPSIS"
.sp
.nf
#include <nut\-scan\&.h>
#include <unistd\&.h> /* useconds_t */
.fi
.sp
.nf
nutscan_device_t * nutscan_scan_xml_http_range(
       const char * start_ip,
       const char * end_ip,
       useconds_t usec_timeout,
       nutscan_xml_t * sec)
.fi
.SH "DESCRIPTION"
.sp
The \fBnutscan_scan_xml_http_range()\fR function tries to detect NUT compatible XML/HTTP devices\&.
.sp
If \fIstart_ip\fR is NULL, the function does this by issuing a broadcast message on currently configured network interfaces\&.
.sp
Otherwise, it queries every IP ranging from \fIstart_ip\fR to \fIstop_ip\fR\&. Those IP arguments may be either IPv4 or IPv6 addresses or host names\&.
.sp
It waits up to \fIusec_timeout\fR microseconds for a response from potential devices\&.
.sp
You MUST call \fBnutscan_init\fR(3) before using this function\&.
.SH "RETURN VALUE"
.sp
The \fBnutscan_scan_xml_http_range()\fR function returns a pointer to a nutscan_device_t structure containing all found devices or NULL if an error occurs or no device is found\&.
.SH "SEE ALSO"
.sp
\fBnutscan_init\fR(3), \fBnutscan_scan_usb\fR(3), \fBnutscan_scan_snmp\fR(3), \fBnutscan_scan_nut\fR(3), \fBnutscan_scan_avahi\fR(3), \fBnutscan_scan_ipmi\fR(3), \fBnutscan_display_sanity_check\fR(3), \fBnutscan_display_sanity_check_serial\fR(3), \fBnutscan_display_ups_conf_with_sanity_check\fR(3), \fBnutscan_display_ups_conf\fR(3), \fBnutscan_display_parsable\fR(3), \fBnutscan_new_device\fR(3), \fBnutscan_free_device\fR(3), \fBnutscan_add_option_to_device\fR(3), \fBnutscan_add_device_to_device\fR(3), \fBnutscan_scan_eaton_serial\fR(3)
