include $(TOP)/.config

MODPROBE:= modprobe
CONFIG_ATH_USER_REGD=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
CONFIG_LEDS_TRIGGERS=y
CONFIG_CFG80211_INTERNAL_REGDB=y
#CONFIG_PACKAGE_ATH_DEBUG=y

CONFIG_RT2800USB=y

REGPATH=crda
REGBIN=regulatory.bin
REGTXTORIG=db.txt
REGTXT=db-temp.txt

ifeq ($(CONFIG_RAIEXTRA),y)
REGTXTEXTRA=db-rai.txt
endif

ifeq ($(CONFIG_IDEXX),y)
ifeq ($(CONFIG_WZRHPAG300NH),y)
REGTXTORIG=regulatory/wzrhpag300h_idexx/db.txt
endif
endif

ifeq ($(CONFIG_ENEO),y)
ifeq ($(CONFIG_UBNTM),y)
REGTXTORIG=regulatory/ubntm_eneo/db.txt
endif
endif

ifeq ($(CONFIG_BUFFALO),y)
ifeq ($(CONFIG_WZRHPAG300NH),y)
REGTXTORIG=regulatory/wzrhpag300h/db.txt
endif
ifeq ($(CONFIG_WZR450HP2),y)
REGTXTORIG=regulatory/wzr450hp2/db.txt
endif
endif

ifeq ($(CONFIG_ATH5K),y)
CONFIG_PACKAGE_KMOD_ATH5K=y
ifeq ($(CONFIG_ATH5K_PCI),y)
CONFIG_PACKAGE_KMOD_ATH5K_PCI=y
endif
ifeq ($(CONFIG_ATH5K_AHB),y)
CONFIG_PACKAGE_KMOD_ATH5K_AHB=y
endif
endif

BUILDFLAGS:= \
	$(foreach opt,$(CONFOPTS),-DCONFIG_$(opt)) \
	$(if $(CONFIG_LEDS_TRIGGERS), -DCONFIG_MAC80211_LEDS -DCONFIG_LEDS_TRIGGERS) \
	$(if $(CONFIG_PACKAGE_MAC80211_DEBUGFS),-DCONFIG_CFG80211_DEBUGFS -DCONFIG_MAC80211_DEBUGFS -DCONFIG_ATH9K_DEBUGFS) \
	$(if $(CONFIG_PACKAGE_ATH_DEBUG),-DCONFIG_ATH_DEBUG -DCONFIG_ATH9K_PKTLOG) \
	$(if $(CONFIG_PACKAGE_KMOD_ATH5K),-DCONFIG_ATH5K_DEBUG) \
	$(if $(CONFIG_PACKAGE_KMOD_ATH5K_PCI),-DCONFIG_ATH5K_PCI) \
	$(if $(CONFIG_PACKAGE_KMOD_ATH5K_AHB),-DCONFIG_ATH5K_AHB) \
	$(if $(CONFIG_MAC80211_MESH),-DCONFIG_MAC80211_MESH) \
	-D__CONFIG_MAC80211_RC_DEFAULT=minstrel_ht \
	-DCONFIG_MAC80211_RC_MINSTREL_HT \
	$(if $(CONFIG_ATH_USER_REGD),-DATH_USER_REGD=1) \
	$(if $(CONFIG_CFG80211_INTERNAL_REGDB),-DCONFIG_CFG80211_INTERNAL_REGDB) \
	$(if $(CONFIG_RT2800USB),-DCONFIG_RT2800USB) \

MAKE_OPTS:=

ifeq ($(ARCHITECTURE),ap83)
  BUILDFLAGS += -DCONFIG_ATHEROS_AR71XX -DCONFIG_ATH9K_AHB
  MAKE_OPTS += CONFIG_ATH9K_AHB=y
else
ifeq ($(ARCHITECTURE),wasp)
  BUILDFLAGS += -DCONFIG_ATH9K_AHB
  MAKE_OPTS += CONFIG_ATH9K_AHB=y
  BUILDFLAGS += -DCONFIG_ATH9K_PCI
  MAKE_OPTS += CONFIG_ATH9K_PCI=y
else
ifeq ($(CONFIG_DIR615I),y)
  BUILDFLAGS += -DCONFIG_ATH9K_AHB
  MAKE_OPTS += CONFIG_ATH9K_AHB=y
else
ifeq ($(ARCHITECTURE),hornet)
  BUILDFLAGS += -DCONFIG_ATH9K_AHB
  MAKE_OPTS += CONFIG_ATH9K_AHB=y
else
  BUILDFLAGS += -DCONFIG_ATH9K_PCI
  MAKE_OPTS += CONFIG_ATH9K_PCI=y
endif
endif
endif
endif
ifeq ($(CONFIG_ATH10K),y)
  BUILDFLAGS += -DCONFIG_ATH10K=y
  BUILDFLAGS += -DCONFIG_ATH10K_PCI=y
  MAKE_OPTS += CONFIG_ATH10K=y
  MAKE_OPTS += CONFIG_ATH10K_PCI=y
endif
ifeq ($(CONFIG_SUPERCHANNEL),y)
  BUILDFLAGS += -DHAVE_SUPERCHANNEL
endif

KERNEL_ARCH=$(strip $(subst aarch64,arm64,$(subst i386,x86,$(subst armeb,arm,$(subst mipsel,mips,$(subst mips64,mips,$(subst mips64el,mips,$(subst sh2,sh,$(subst sh3,sh,$(subst sh4,sh,$(ARCH)))))))))))

MAKE_OPTS += \
	CROSS_COMPILE="ccache $(CROSS_COMPILE)" \
	ARCH="$(KERNEL_ARCH)" \
	EXTRA_CFLAGS="$(BUILDFLAGS)" \
	CONFIG_MAC80211=m \
	CONFIG_MAC80211_RC_MINSTREL=y \
	CONFIG_MAC80211_MESH=$(CONFIG_MAC80211_MESH) \
	CONFIG_MAC80211_LEDS=$(CONFIG_LEDS_TRIGGERS) \
	CONFIG_CFG80211_DEBUGFS=$(if $(CONFIG_PACKAGE_MAC80211_DEBUGFS),y) \
	CONFIG_MAC80211_DEBUGFS=$(if $(CONFIG_PACKAGE_MAC80211_DEBUGFS),y) \
	CONFIG_CFG80211_INTERNAL_REGDB=$(if $(CONFIG_CFG80211_INTERNAL_REGDB),y) \
	CONFIG_B43_PCMCIA=n CONFIG_B43_PIO=n \
	CONFIG_B43= \
	CONFIG_WIL6210= \
	CONFIG_MWIFIEX= \
	CONFIG_MWIFIEX_PCIE= \
	CONFIG_MWLWIFI= \
	CONFIG_BRCMFMAC= \
	CONFIG_COMPAT_MAC80211_HWSIM= \
	CONFIG_BRCMSMAC= \
	CONFIG_B43LEGACY= \
	CONFIG_B44= \
	CONFIG_ATL1C= \
	CONFIG_ATL1E= \
	CONFIG_ATL1= \
	CONFIG_ATL2= \
	CONFIG_ATH6KL= \
	CONFIG_ATH_COMMON=m \
	CONFIG_ATH_CARDS=m \
	CONFIG_COMPAT_STAGING= \
	CONFIG_COMPAT_BLUETOOTH= \
	CONFIG_COMPAT_BLUETOOTH_MODULES= \
	CONFIG_COMPAT_NET_USB_MODULES= \
	CONFIG_ATH5K=$(if $(CONFIG_PACKAGE_KMOD_ATH5K),m) \
	CONFIG_ATH5K_PCI=$(if $(CONFIG_PACKAGE_KMOD_ATH5K_PCI),y) \
	CONFIG_ATH5K_AHB=$(if $(CONFIG_PACKAGE_KMOD_ATH5K_AHB),y) \
	CONFIG_ATH5K_DEBUG=$(if $(CONFIG_PACKAGE_KMOD_ATH5K),y) \
	CONFIG_AR5523= \
	CONFIG_WIL6210= \
	CONFIG_ATH9K=m \
	CONFIG_ATH9K_HW=m \
	CONFIG_ATH9K_COMMON=m \
	CONFIG_ATH9K_DEBUGFS=$(if $(CONFIG_PACKAGE_MAC80211_DEBUGFS),y) \
	CONFIG_ZD1211RW= \
	CONFIG_CARL9170= \
	CONFIG_P54_COMMON= \
	CONFIG_P54_PCI= \
	CONFIG_P54_USB= \
	CONFIG_P54_SPI= \
	CONFIG_RT2X00= \
	CONFIG_RT2X00_LIB= \
	CONFIG_RT2X00_LIB_PCI= \
	CONFIG_RT2X00_LIB_USB= \
	CONFIG_RT2X00_LIB_SOC= \
	CONFIG_RT2X00_LIB_DEBUGFS= \
	CONFIG_RT2X00_LIB_CRYPTO= \
	CONFIG_RT2X00_LIB_FIRMWARE= \
	CONFIG_RT2X00_LIB_HT= \
	CONFIG_RT2X00_LIB_LEDS= \
	CONFIG_RT2400PCI= \
	CONFIG_RT2500PCI= \
	CONFIG_WL_TI= \
	CONFIG_RT2500USB= \
	CONFIG_RT61PCI= \
	CONFIG_RT73USB= \
	CONFIG_RT2800_LIB= \
	CONFIG_RT2800PCI= \
	CONFIG_RT2800PCI_PCI= \
	CONFIG_RT2800PCI_SOC= \
	CONFIG_RT2800USB=y \
	CONFIG_RTL8180= \
	CONFIG_RTLWIFI= \
	CONFIG_RTL8187= \
	CONFIG_RTL8192C_COMMON= \
	CONFIG_RTL8192CE= \
	CONFIG_RTL8192CU= \
	CONFIG_RTL8192SE= \
	CONFIG_MAC80211_HWSIM= \
	CONFIG_PCMCIA= \
	CONFIG_LIBIPW= \
	CONFIG_LIBERTAS= \
	CONFIG_LIBERTAS_CS= \
	CONFIG_LIBERTAS_SPI= \
	CONFIG_LIBERTAS_SDIO= \
	CONFIG_LIBERTAS_THINFIRM= \
	CONFIG_LIBERTAS_USB= \
	CONFIG_IPW2100= \
	CONFIG_IPW2200= \
	CONFIG_NL80211=y \
	CONFIG_LIB80211= \
	CONFIG_LIB80211_CRYPT_WEP= \
	CONFIG_LIB80211_CRYPT_CCMP= \
	CONFIG_LIB80211_CRYPT_TKIP= \
	CONFIG_COMPAT_IWLWIFI= \
	CONFIG_IWLAGN= \
	CONFIG_IWLWIFI= \
	CONFIG_MWL8K= \
	CONFIG_ATMEL= \
	CONFIG_PCMCIA_ATMEL= \
	CONFIG_ADM8211= \
	CONFIG_USB_NET_RNDIS_HOST= \
	CONFIG_USB_NET_RNDIS_WLAN= \
	CONFIG_USB_NET_CDCETHER= \
	CONFIG_USB_USBNET= \
	CONFIG_AT76C50X_USB= \
	CONFIG_WL12XX= \
	CONFIG_EEPROM_93CX6= \
	CONFIG_HERMES= \
	CONFIG_AR9170_USB= \
	CONFIG_AR9170_LEDS= \
	CONFIG_IWM= \
	CONFIG_ATH9K_HTC= \
	CONFIG_MAC80211_RC_MINSTREL_HT=y \
	CONFIG_RTL8192CE= \
	CONFIG_RTLWIFI= \
	CONFIG_IWLWIFI_LEGACY= \
	CONFIG_IWLEGACY= \
	CONFIG_COMPAT_KFIFO= \
	CONFIG_COMPAT_ZD1211RW= \
	MADWIFI= \
	OLD_IWL= \
	KLIB_BUILD="$(LINUXDIR)" \
	MODPROBE=: \
	KLIB=$(INSTALLDIR)/ath9k \
	KERNEL_SUBLEVEL=$(word 3,$(subst ., ,$(KERNELRELEASE)))

ifeq ($(ARCHITECTURE),ap83)
  MAKE_OPTS += CONFIG_ATHEROS_AR71XX=y
endif

IW_CFLAGS=-I$(TOP)/libnl-tiny/include \
	-DCONFIG_LIBNL20 \
	-D_GNU_SOURCE
IW_LDFLAGS=-L$(TOP)/libnl-tiny/

ath9k:
	cp $(REGPATH)/$(REGTXTORIG) $(REGPATH)/$(REGTXT)
ifdef REGTXTEXTRA
	cat $(REGPATH)/$(REGTXTEXTRA) >> $(REGPATH)/$(REGTXT)
	echo >> $(REGPATH)/$(REGTXT)
endif
ifeq ($(CONFIG_CFG80211_INTERNAL_REGDB),y)
	cp $(REGPATH)/$(REGTXT) $(TOP)/$(MAC80211_PATH)/net/wireless/db.txt
endif
	cd crda ; ./db2fw.py $(REGBIN) $(REGTXT)
	-rm -f $(TOP)/$(MAC80211_PATH)/include/linux/ath9k_platform.h
	rm -f $(MAC80211_PATH)/.config $(MAC80211_PATH)/.compat_autoconf_*
	MAKEFLAGS= KERNELRELEASE= CFLAGS= $(MAKE) -C $(MAC80211_PATH) $(MAKE_OPTS) modules

ath9k-install:
ifneq ($(CONFIG_NOWIFI),y)
	cd $(MAC80211_PATH) ; mkdir -p $(INSTALLDIR)/ath9k/lib/ath9k ; cp `find -name \*.ko` $(INSTALLDIR)/ath9k/lib/ath9k/
else
	@true
endif

ath9k-clean:
	rm -f $(MAC80211_PATH)/.config $(MAC80211_PATH)/.compat_autoconf_*
	MAKEFLAGS= KERNELRELEASE= CFLAGS= $(MAKE) -C $(MAC80211_PATH) $(MAKE_OPTS) clean

include $(TOP)/mac80211-rules/ath9k-userspace.mk
