#ifndef BB_CONFIG_H
#define BB_CONFIG_H
/*
 * Automatically generated header file: don't edit
 */

/* Version Number */
#define BB_VER "1.1.0"
#define BB_BT "2006.03.13-11:04+0000"

#define HAVE_DOT_CONFIG 1

/*
 * General Configuration
 */
#define ENABLE_FEATURE_BUFFERS_USE_MALLOC 0
#define CONFIG_FEATURE_BUFFERS_GO_ON_STACK 1
#define ENABLE_FEATURE_BUFFERS_GO_ON_STACK 1
#define ENABLE_FEATURE_BUFFERS_GO_IN_BSS 0
#define ENABLE_FEATURE_VERBOSE_USAGE 0
#define ENABLE_FEATURE_INSTALLER 0
#define ENABLE_LOCALE_SUPPORT 0
#define CONFIG_FEATURE_DEVFS 1
#define ENABLE_FEATURE_DEVFS 1
#define CONFIG_FEATURE_DEVPTS 1
#define ENABLE_FEATURE_DEVPTS 1
#define ENABLE_FEATURE_CLEAN_UP 0
#define CONFIG_FEATURE_SUID 1
#define ENABLE_FEATURE_SUID 1
#define ENABLE_FEATURE_SUID_CONFIG 0
#define ENABLE_FEATURE_SUID_CONFIG_QUIET 0
#define ENABLE_SELINUX 0

/*
 * Build Options
 */
#define ENABLE_STATIC 0
#define ENABLE_LFS 0
#define USING_CROSS_COMPILER 1
#define CROSS_COMPILER_PREFIX "mipsel-linux-uclibc-"
#define EXTRA_CFLAGS_OPTIONS "$(COPTS)"
#define CONFIG_FEATURE_SUSv2 1
#define ENABLE_FEATURE_SUSv2 1
#define ENABLE_FEATURE_SUSv2_OBSOLETE 0

/*
 * Installation Options
 */
#define ENABLE_INSTALL_NO_USR 0
#define CONFIG_INSTALL_APPLET_SYMLINKS 1
#define ENABLE_INSTALL_APPLET_SYMLINKS 1
#define ENABLE_INSTALL_APPLET_HARDLINKS 0
#define ENABLE_INSTALL_APPLET_DONT 0
#define PREFIX "./_install"

/*
 * Archival Utilities
 */
#define ENABLE_AR 0
#define ENABLE_FEATURE_AR_LONG_FILENAMES 0
#define ENABLE_BUNZIP2 0
#define ENABLE_CPIO 0
#define ENABLE_DPKG 0
#define ENABLE_DPKG_DEB 0
#define ENABLE_FEATURE_DPKG_DEB_EXTRACT_ONLY 0
#define ENABLE_GUNZIP 0
#define ENABLE_FEATURE_GUNZIP_UNCOMPRESS 0
#define ENABLE_GZIP 0
#define ENABLE_RPM2CPIO 0
#define ENABLE_RPM 0
#define CONFIG_TAR 1
#define ENABLE_TAR 1
#define CONFIG_FEATURE_TAR_CREATE 1
#define ENABLE_FEATURE_TAR_CREATE 1
#define CONFIG_FEATURE_TAR_BZIP2 1
#define ENABLE_FEATURE_TAR_BZIP2 1
#define ENABLE_FEATURE_TAR_FROM 0
#define CONFIG_FEATURE_TAR_GZIP 1
#define ENABLE_FEATURE_TAR_GZIP 1
#define ENABLE_FEATURE_TAR_COMPRESS 0
#define CONFIG_FEATURE_TAR_OLDGNU_COMPATABILITY 1
#define ENABLE_FEATURE_TAR_OLDGNU_COMPATABILITY 1
#define CONFIG_FEATURE_TAR_GNU_EXTENSIONS 1
#define ENABLE_FEATURE_TAR_GNU_EXTENSIONS 1
#define ENABLE_FEATURE_TAR_LONG_OPTIONS 0
#define ENABLE_UNCOMPRESS 0
#define ENABLE_UNZIP 0

/*
 * Common options for cpio and tar
 */
#define ENABLE_FEATURE_UNARCHIVE_TAPE 0
#define ENABLE_FEATURE_DEB_TAR_GZ 0
#define ENABLE_FEATURE_DEB_TAR_BZ2 0

/*
 * Coreutils
 */
#define CONFIG_BASENAME 1
#define ENABLE_BASENAME 1
#define ENABLE_CAL 0
#define CONFIG_CAT 1
#define ENABLE_CAT 1
#define CONFIG_CHGRP 1
#define ENABLE_CHGRP 1
#define CONFIG_CHMOD 1
#define ENABLE_CHMOD 1
#define CONFIG_CHOWN 1
#define ENABLE_CHOWN 1
#define CONFIG_CHROOT 1
#define ENABLE_CHROOT 1
#define CONFIG_CMP 1
#define ENABLE_CMP 1
#define ENABLE_COMM 0
#define CONFIG_CP 1
#define ENABLE_CP 1
#define CONFIG_CUT 1
#define ENABLE_CUT 1
#define CONFIG_DATE 1
#define ENABLE_DATE 1

/*
 * date (forced enabled for use with watch)
 */
#define CONFIG_FEATURE_DATE_ISOFMT 1
#define ENABLE_FEATURE_DATE_ISOFMT 1
#define CONFIG_DD 1
#define ENABLE_DD 1
#define CONFIG_DF 1
#define ENABLE_DF 1
#define CONFIG_DIRNAME 1
#define ENABLE_DIRNAME 1
#define ENABLE_DOS2UNIX 0
#define ENABLE_UNIX2DOS 0
#define CONFIG_DU 1
#define ENABLE_DU 1
#define CONFIG_FEATURE_DU_DEFALT_BLOCKSIZE_1K 1
#define ENABLE_FEATURE_DU_DEFALT_BLOCKSIZE_1K 1
#define CONFIG_ECHO 1
#define ENABLE_ECHO 1
#define CONFIG_FEATURE_FANCY_ECHO 1
#define ENABLE_FEATURE_FANCY_ECHO 1
#define CONFIG_ENV 1
#define ENABLE_ENV 1
#define CONFIG_EXPR 1
#define ENABLE_EXPR 1
#define CONFIG_FALSE 1
#define ENABLE_FALSE 1
#define ENABLE_FOLD 0
#define CONFIG_HEAD 1
#define ENABLE_HEAD 1
#define ENABLE_FEATURE_FANCY_HEAD 0
#define ENABLE_HOSTID 0
#define CONFIG_ID 1
#define ENABLE_ID 1
#define CONFIG_INSTALL 1
#define ENABLE_INSTALL 1
#define ENABLE_LENGTH 0
#define CONFIG_LN 1
#define ENABLE_LN 1
#define ENABLE_LOGNAME 0
#define CONFIG_LS 1
#define ENABLE_LS 1
#define CONFIG_FEATURE_LS_FILETYPES 1
#define ENABLE_FEATURE_LS_FILETYPES 1
#define CONFIG_FEATURE_LS_FOLLOWLINKS 1
#define ENABLE_FEATURE_LS_FOLLOWLINKS 1
#define CONFIG_FEATURE_LS_RECURSIVE 1
#define ENABLE_FEATURE_LS_RECURSIVE 1
#define CONFIG_FEATURE_LS_SORTFILES 1
#define ENABLE_FEATURE_LS_SORTFILES 1
#define CONFIG_FEATURE_LS_TIMESTAMPS 1
#define ENABLE_FEATURE_LS_TIMESTAMPS 1
#define CONFIG_FEATURE_LS_USERNAME 1
#define ENABLE_FEATURE_LS_USERNAME 1
#define CONFIG_FEATURE_LS_COLOR 1
#define ENABLE_FEATURE_LS_COLOR 1
#define CONFIG_FEATURE_LS_COLOR_IS_DEFAULT 1
#define ENABLE_FEATURE_LS_COLOR_IS_DEFAULT 1
#define CONFIG_MD5SUM 1
#define ENABLE_MD5SUM 1
#define CONFIG_MKDIR 1
#define ENABLE_MKDIR 1
#define CONFIG_MKFIFO 1
#define ENABLE_MKFIFO 1
#define ENABLE_MKNOD 0
#define CONFIG_MV 1
#define ENABLE_MV 1
#define ENABLE_NICE 0
#define CONFIG_NOHUP 1
#define ENABLE_NOHUP 1
#define ENABLE_OD 0
#define ENABLE_PRINTENV 0
#define CONFIG_PRINTF 1
#define ENABLE_PRINTF 1
#define CONFIG_PWD 1
#define ENABLE_PWD 1
#define ENABLE_REALPATH 0
#define CONFIG_RM 1
#define ENABLE_RM 1
#define CONFIG_RMDIR 1
#define ENABLE_RMDIR 1
#define ENABLE_SEQ 0
#define ENABLE_SHA1SUM 0
#define CONFIG_SLEEP 1
#define ENABLE_SLEEP 1
#define CONFIG_FEATURE_FANCY_SLEEP 1
#define ENABLE_FEATURE_FANCY_SLEEP 1
#define CONFIG_SORT 1
#define ENABLE_SORT 1
#define ENABLE_FEATURE_SORT_BIG 0
#define ENABLE_STAT 0
#define ENABLE_FEATURE_STAT_FORMAT 0
#define ENABLE_STTY 0
#define ENABLE_SUM 0
#define CONFIG_SYNC 1
#define ENABLE_SYNC 1
#define CONFIG_TAIL 1
#define ENABLE_TAIL 1
#define CONFIG_FEATURE_FANCY_TAIL 1
#define ENABLE_FEATURE_FANCY_TAIL 1
#define CONFIG_TEE 1
#define ENABLE_TEE 1
#define CONFIG_FEATURE_TEE_USE_BLOCK_IO 1
#define ENABLE_FEATURE_TEE_USE_BLOCK_IO 1
#define CONFIG_TEST 1
#define ENABLE_TEST 1

/*
 * test (forced enabled for use with shell)
 */
#define ENABLE_FEATURE_TEST_64 0
#define CONFIG_TOUCH 1
#define ENABLE_TOUCH 1
#define CONFIG_TR 1
#define ENABLE_TR 1
#define ENABLE_FEATURE_TR_CLASSES 0
#define ENABLE_FEATURE_TR_EQUIV 0
#define CONFIG_TRUE 1
#define ENABLE_TRUE 1
#define CONFIG_TTY 1
#define ENABLE_TTY 1
#define CONFIG_UNAME 1
#define ENABLE_UNAME 1
#define CONFIG_UNIQ 1
#define ENABLE_UNIQ 1
#define CONFIG_USLEEP 1
#define ENABLE_USLEEP 1
#define ENABLE_UUDECODE 0
#define ENABLE_UUENCODE 0
#define CONFIG_WATCH 1
#define ENABLE_WATCH 1
#define CONFIG_WC 1
#define ENABLE_WC 1
#define ENABLE_WHO 0
#define CONFIG_WHOAMI 1
#define ENABLE_WHOAMI 1
#define CONFIG_YES 1
#define ENABLE_YES 1

/*
 * Common options for cp and mv
 */
#define CONFIG_FEATURE_PRESERVE_HARDLINKS 1
#define ENABLE_FEATURE_PRESERVE_HARDLINKS 1

/*
 * Common options for ls and more
 */
#define CONFIG_FEATURE_AUTOWIDTH 1
#define ENABLE_FEATURE_AUTOWIDTH 1

/*
 * Common options for df, du, ls
 */
#define CONFIG_FEATURE_HUMAN_READABLE 1
#define ENABLE_FEATURE_HUMAN_READABLE 1

/*
 * Common options for md5sum, sha1sum
 */
#define ENABLE_FEATURE_MD5_SHA1_SUM_CHECK 0

/*
 * Console Utilities
 */
#define ENABLE_CHVT 0
#define CONFIG_CLEAR 1
#define ENABLE_CLEAR 1
#define ENABLE_DEALLOCVT 0
#define ENABLE_DUMPKMAP 0
#define ENABLE_LOADFONT 0
#define ENABLE_LOADKMAP 0
#define ENABLE_OPENVT 0
#define CONFIG_RESET 1
#define ENABLE_RESET 1
#define CONFIG_SETCONSOLE 1
#define ENABLE_SETCONSOLE 1
#define ENABLE_SETKEYCODES 0

/*
 * Debian Utilities
 */
#define ENABLE_MKTEMP 0
#define ENABLE_PIPE_PROGRESS 0
#define ENABLE_READLINK 0
#define ENABLE_FEATURE_READLINK_FOLLOW 0
#define CONFIG_RUN_PARTS 1
#define ENABLE_RUN_PARTS 1
#define ENABLE_START_STOP_DAEMON 0
#define CONFIG_WHICH 1
#define ENABLE_WHICH 1

/*
 * Linux Ext2 FS Progs
 */
#define ENABLE_CHATTR 0
#define ENABLE_E2FSCK 0
#define ENABLE_FSCK 0
#define ENABLE_LSATTR 0
#define ENABLE_MKE2FS 0
#define ENABLE_TUNE2FS 0
#define ENABLE_E2LABEL 0
#define ENABLE_FINDFS 0

/*
 * Editors
 */
#define CONFIG_AWK 1
#define ENABLE_AWK 1
#define ENABLE_FEATURE_AWK_MATH 0
#define ENABLE_PATCH 0
#define CONFIG_SED 1
#define ENABLE_SED 1
#define CONFIG_VI 1
#define ENABLE_VI 1
#define CONFIG_FEATURE_VI_COLON 1
#define ENABLE_FEATURE_VI_COLON 1
#define CONFIG_FEATURE_VI_YANKMARK 1
#define ENABLE_FEATURE_VI_YANKMARK 1
#define CONFIG_FEATURE_VI_SEARCH 1
#define ENABLE_FEATURE_VI_SEARCH 1
#define CONFIG_FEATURE_VI_USE_SIGNALS 1
#define ENABLE_FEATURE_VI_USE_SIGNALS 1
#define CONFIG_FEATURE_VI_DOT_CMD 1
#define ENABLE_FEATURE_VI_DOT_CMD 1
#define CONFIG_FEATURE_VI_READONLY 1
#define ENABLE_FEATURE_VI_READONLY 1
#define CONFIG_FEATURE_VI_SETOPTS 1
#define ENABLE_FEATURE_VI_SETOPTS 1
#define CONFIG_FEATURE_VI_SET 1
#define ENABLE_FEATURE_VI_SET 1
#define CONFIG_FEATURE_VI_WIN_RESIZE 1
#define ENABLE_FEATURE_VI_WIN_RESIZE 1
#define CONFIG_FEATURE_VI_OPTIMIZE_CURSOR 1
#define ENABLE_FEATURE_VI_OPTIMIZE_CURSOR 1

/*
 * Finding Utilities
 */
#define CONFIG_FIND 1
#define ENABLE_FIND 1
#define CONFIG_FEATURE_FIND_MTIME 1
#define ENABLE_FEATURE_FIND_MTIME 1
#define CONFIG_FEATURE_FIND_PERM 1
#define ENABLE_FEATURE_FIND_PERM 1
#define CONFIG_FEATURE_FIND_TYPE 1
#define ENABLE_FEATURE_FIND_TYPE 1
#define CONFIG_FEATURE_FIND_XDEV 1
#define ENABLE_FEATURE_FIND_XDEV 1
#define CONFIG_FEATURE_FIND_NEWER 1
#define ENABLE_FEATURE_FIND_NEWER 1
#define CONFIG_FEATURE_FIND_INUM 1
#define ENABLE_FEATURE_FIND_INUM 1
#define ENABLE_FEATURE_FIND_EXEC 0
#define CONFIG_GREP 1
#define ENABLE_GREP 1
#define CONFIG_FEATURE_GREP_EGREP_ALIAS 1
#define ENABLE_FEATURE_GREP_EGREP_ALIAS 1
#define CONFIG_FEATURE_GREP_FGREP_ALIAS 1
#define ENABLE_FEATURE_GREP_FGREP_ALIAS 1
#define CONFIG_FEATURE_GREP_CONTEXT 1
#define ENABLE_FEATURE_GREP_CONTEXT 1
#define CONFIG_XARGS 1
#define ENABLE_XARGS 1
#define CONFIG_FEATURE_XARGS_SUPPORT_CONFIRMATION 1
#define ENABLE_FEATURE_XARGS_SUPPORT_CONFIRMATION 1
#define CONFIG_FEATURE_XARGS_SUPPORT_QUOTES 1
#define ENABLE_FEATURE_XARGS_SUPPORT_QUOTES 1
#define CONFIG_FEATURE_XARGS_SUPPORT_TERMOPT 1
#define ENABLE_FEATURE_XARGS_SUPPORT_TERMOPT 1
#define CONFIG_FEATURE_XARGS_SUPPORT_ZERO_TERM 1
#define ENABLE_FEATURE_XARGS_SUPPORT_ZERO_TERM 1

/*
 * Init Utilities
 */
#define ENABLE_INIT 0
#define ENABLE_FEATURE_USE_INITTAB 0
#define ENABLE_FEATURE_INITRD 0
#define ENABLE_FEATURE_INIT_COREDUMPS 0
#define ENABLE_FEATURE_INIT_SCTTY 0
#define ENABLE_FEATURE_EXTRA_QUIET 0
#define ENABLE_HALT 0
#define CONFIG_MESG 1
#define ENABLE_MESG 1
#define ENABLE_POWEROFF 0
#define CONFIG_REBOOT 1
#define ENABLE_REBOOT 1

/*
 * Login/Password Management Utilities
 */
#define ENABLE_FEATURE_SHADOWPASSWDS 0
#define ENABLE_USE_BB_SHADOW 0
#define ENABLE_USE_BB_PWD_GRP 0
#define ENABLE_ADDGROUP 0
#define ENABLE_DELGROUP 0
#define ENABLE_ADDUSER 0
#define ENABLE_DELUSER 0
#define ENABLE_GETTY 0
#define ENABLE_FEATURE_UTMP 0
#define ENABLE_FEATURE_WTMP 0
#define CONFIG_LOGIN 1
#define ENABLE_LOGIN 1
#define ENABLE_FEATURE_SECURETTY 0
#define ENABLE_PASSWD 0
#define ENABLE_SU 0
#define ENABLE_SULOGIN 0
#define ENABLE_VLOCK 0

/*
 * Miscellaneous Utilities
 */
#define CONFIG_ADJTIMEX 1
#define ENABLE_ADJTIMEX 1
#define ENABLE_BBCONFIG 0
#define ENABLE_CROND 0
#define ENABLE_FEATURE_CROND_CALL_SENDMAIL 0
#define ENABLE_CRONTAB 0
#define CONFIG_DC 1
#define ENABLE_DC 1
#define ENABLE_DEVFSD 0
#define ENABLE_DEVFSD_MODLOAD 0
#define ENABLE_DEVFSD_FG_NP 0
#define ENABLE_DEVFSD_VERBOSE 0
#define ENABLE_EJECT 0
#define ENABLE_LAST 0
#define ENABLE_LESS 0
#define ENABLE_FEATURE_LESS_BRACKETS 0
#define ENABLE_FEATURE_LESS_FLAGS 0
#define ENABLE_FEATURE_LESS_FLAGCS 0
#define ENABLE_FEATURE_LESS_MARKS 0
#define ENABLE_FEATURE_LESS_REGEXP 0
#define ENABLE_HDPARM 0
#define ENABLE_FEATURE_HDPARM_GET_IDENTITY 0
#define ENABLE_FEATURE_HDPARM_HDIO_SCAN_HWIF 0
#define ENABLE_FEATURE_HDPARM_HDIO_UNREGISTER_HWIF 0
#define ENABLE_FEATURE_HDPARM_HDIO_DRIVE_RESET 0
#define ENABLE_FEATURE_HDPARM_HDIO_TRISTATE_HWIF 0
#define ENABLE_FEATURE_HDPARM_HDIO_GETSET_DMA 0
#define ENABLE_MAKEDEVS 0
#define ENABLE_FEATURE_MAKEDEVS_LEAF 0
#define ENABLE_FEATURE_MAKEDEVS_TABLE 0
#define ENABLE_MOUNTPOINT 0
#define ENABLE_MT 0
#undef BB_APPLET_RUNLEVEL
#define CONFIG_RX 1
#define ENABLE_RX 1
#define CONFIG_STRINGS 1
#define ENABLE_STRINGS 1
#define ENABLE_SETSID 0
#define CONFIG_TIME 1
#define ENABLE_TIME 1
#define ENABLE_WATCHDOG 0

/*
 * Linux Module Utilities
 */
#define CONFIG_INSMOD 1
#define ENABLE_INSMOD 1
#define ENABLE_FEATURE_INSMOD_VERSION_CHECKING 0
#define ENABLE_FEATURE_INSMOD_KSYMOOPS_SYMBOLS 0
#define ENABLE_FEATURE_INSMOD_LOADINKMEM 0
#define ENABLE_FEATURE_INSMOD_LOAD_MAP 0
#define ENABLE_FEATURE_INSMOD_LOAD_MAP_FULL 0
#define CONFIG_RMMOD 1
#define ENABLE_RMMOD 1
#define CONFIG_LSMOD 1
#define ENABLE_LSMOD 1
#define ENABLE_FEATURE_LSMOD_PRETTY_2_6_OUTPUT 0
#define ENABLE_MODPROBE 0
#define ENABLE_FEATURE_MODPROBE_MULTIPLE_OPTIONS 0

/*
 * Options common to multiple modutils
 */
#define ENABLE_FEATURE_CHECK_TAINTED_MODULE 0
#define CONFIG_FEATURE_2_4_MODULES 1
#define ENABLE_FEATURE_2_4_MODULES 1
#define ENABLE_FEATURE_2_6_MODULES 0
#define CONFIG_FEATURE_QUERY_MODULE_INTERFACE 1
#define ENABLE_FEATURE_QUERY_MODULE_INTERFACE 1

/*
 * Networking Utilities
 */
#define ENABLE_FEATURE_IPV6 0
#define ENABLE_ARPING 0
#define CONFIG_ETHER_WAKE 1
#define ENABLE_ETHER_WAKE 1
#define ENABLE_FAKEIDENTD 0
#define ENABLE_FTPGET 0
#define ENABLE_FTPPUT 0
#define CONFIG_HOSTNAME 1
#define ENABLE_HOSTNAME 1
#define ENABLE_HTTPD 0
#define ENABLE_FEATURE_HTTPD_USAGE_FROM_INETD_ONLY 0
#define ENABLE_FEATURE_HTTPD_BASIC_AUTH 0
#define ENABLE_FEATURE_HTTPD_AUTH_MD5 0
#define ENABLE_FEATURE_HTTPD_RELOAD_CONFIG_SIGHUP 0
#define ENABLE_FEATURE_HTTPD_SETUID 0
#define ENABLE_FEATURE_HTTPD_CONFIG_WITH_MIME_TYPES 0
#define ENABLE_FEATURE_HTTPD_CGI 0
#define ENABLE_FEATURE_HTTPD_SET_REMOTE_PORT_TO_ENV 0
#define ENABLE_FEATURE_HTTPD_ENCODE_URL_STR 0
#define CONFIG_IFCONFIG 1
#define ENABLE_IFCONFIG 1
#define CONFIG_FEATURE_IFCONFIG_STATUS 1
#define ENABLE_FEATURE_IFCONFIG_STATUS 1
#define ENABLE_FEATURE_IFCONFIG_SLIP 0
#define ENABLE_FEATURE_IFCONFIG_MEMSTART_IOADDR_IRQ 0
#define ENABLE_FEATURE_IFCONFIG_HW 0
#define CONFIG_FEATURE_IFCONFIG_BROADCAST_PLUS 1
#define ENABLE_FEATURE_IFCONFIG_BROADCAST_PLUS 1
#define CONFIG_IFUPDOWN 1
#define ENABLE_IFUPDOWN 1
#define ENABLE_FEATURE_IFUPDOWN_IP 0
#define CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN 1
#define ENABLE_FEATURE_IFUPDOWN_IP_BUILTIN 1
#define CONFIG_FEATURE_IFUPDOWN_IPV4 1
#define ENABLE_FEATURE_IFUPDOWN_IPV4 1
#define CONFIG_FEATURE_IFUPDOWN_IPV6 1
#define ENABLE_FEATURE_IFUPDOWN_IPV6 1
#define ENABLE_FEATURE_IFUPDOWN_IPX 0
#define ENABLE_FEATURE_IFUPDOWN_MAPPING 0
#define ENABLE_INETD 0
#define ENABLE_FEATURE_INETD_SUPPORT_BILTIN_ECHO 0
#define ENABLE_FEATURE_INETD_SUPPORT_BILTIN_DISCARD 0
#define ENABLE_FEATURE_INETD_SUPPORT_BILTIN_TIME 0
#define ENABLE_FEATURE_INETD_SUPPORT_BILTIN_DAYTIME 0
#define ENABLE_FEATURE_INETD_SUPPORT_BILTIN_CHARGEN 0
#define ENABLE_FEATURE_INETD_RPC 0
#define ENABLE_IP 0
#define ENABLE_FEATURE_IP_ADDRESS 0
#define ENABLE_FEATURE_IP_LINK 0
#define ENABLE_FEATURE_IP_ROUTE 0
#define ENABLE_FEATURE_IP_TUNNEL 0
#define ENABLE_IPCALC 0
#define ENABLE_FEATURE_IPCALC_FANCY 0
#define ENABLE_IPADDR 0
#define ENABLE_IPLINK 0
#define ENABLE_IPROUTE 0
#define ENABLE_IPTUNNEL 0
#define CONFIG_NAMEIF 1
#define ENABLE_NAMEIF 1
#define CONFIG_NC 1
#define ENABLE_NC 1
#define ENABLE_NC_GAPING_SECURITY_HOLE 0
#define CONFIG_NETSTAT 1
#define ENABLE_NETSTAT 1
#define CONFIG_NSLOOKUP 1
#define ENABLE_NSLOOKUP 1
#define CONFIG_PING 1
#define ENABLE_PING 1
#define CONFIG_FEATURE_FANCY_PING 1
#define ENABLE_FEATURE_FANCY_PING 1
#define ENABLE_PING6 0
#define ENABLE_FEATURE_FANCY_PING6 0
#define CONFIG_ROUTE 1
#define ENABLE_ROUTE 1
#define CONFIG_TELNET 1
#define ENABLE_TELNET 1
#define CONFIG_FEATURE_TELNET_TTYPE 1
#define ENABLE_FEATURE_TELNET_TTYPE 1
#define CONFIG_FEATURE_TELNET_AUTOLOGIN 1
#define ENABLE_FEATURE_TELNET_AUTOLOGIN 1
#define ENABLE_TELNETD 0
#define ENABLE_FEATURE_TELNETD_INETD 0
#define ENABLE_TFTP 0
#define ENABLE_FEATURE_TFTP_GET 0
#define ENABLE_FEATURE_TFTP_PUT 0
#define ENABLE_FEATURE_TFTP_BLOCKSIZE 0
#define ENABLE_FEATURE_TFTP_DEBUG 0
#define CONFIG_TRACEROUTE 1
#define ENABLE_TRACEROUTE 1
#define ENABLE_FEATURE_TRACEROUTE_VERBOSE 0
#define CONFIG_FEATURE_TRACEROUTE_SOURCE_ROUTE 1
#define ENABLE_FEATURE_TRACEROUTE_SOURCE_ROUTE 1
#define ENABLE_FEATURE_TRACEROUTE_USE_ICMP 0
#define CONFIG_VCONFIG 1
#define ENABLE_VCONFIG 1
#define CONFIG_WGET 1
#define ENABLE_WGET 1
#define CONFIG_FEATURE_WGET_STATUSBAR 1
#define ENABLE_FEATURE_WGET_STATUSBAR 1
#define ENABLE_FEATURE_WGET_AUTHENTICATION 0
#define ENABLE_FEATURE_WGET_IP6_LITERAL 0

/*
 * udhcp Server/Client
 */
#define ENABLE_UDHCPD 0
#define ENABLE_UDHCPC 0
#define ENABLE_DUMPLEASES 0
#define ENABLE_FEATURE_UDHCP_SYSLOG 0
#define ENABLE_FEATURE_UDHCP_DEBUG 0
#define ENABLE_ZCIP 0

/*
 * Process Utilities
 */
#define CONFIG_FREE 1
#define ENABLE_FREE 1
#define ENABLE_FUSER 0
#define CONFIG_KILL 1
#define ENABLE_KILL 1
#define CONFIG_KILLALL 1
#define ENABLE_KILLALL 1
#define CONFIG_PIDOF 1
#define ENABLE_PIDOF 1
#define ENABLE_FEATURE_PIDOF_SINGLE 0
#define ENABLE_FEATURE_PIDOF_OMIT 0
#define CONFIG_PS 1
#define ENABLE_PS 1
#define CONFIG_FEATURE_PS_WIDE 1
#define ENABLE_FEATURE_PS_WIDE 1
#define ENABLE_RENICE 0
#define ENABLE_BB_SYSCTL 0
#define CONFIG_TOP 1
#define ENABLE_TOP 1
#define CONFIG_FEATURE_TOP_CPU_USAGE_PERCENTAGE 1
#define ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE 1
#define CONFIG_UPTIME 1
#define ENABLE_UPTIME 1

/*
 * Shells
 */
#define CONFIG_FEATURE_SH_IS_ASH 1
#define ENABLE_FEATURE_SH_IS_ASH 1
#define ENABLE_FEATURE_SH_IS_HUSH 0
#define ENABLE_FEATURE_SH_IS_LASH 0
#define ENABLE_FEATURE_SH_IS_MSH 0
#define ENABLE_FEATURE_SH_IS_NONE 0
#define CONFIG_ASH 1
#define ENABLE_ASH 1

/*
 * Ash Shell Options
 */
#define CONFIG_ASH_JOB_CONTROL 1
#define ENABLE_ASH_JOB_CONTROL 1
#define ENABLE_ASH_READ_NCHARS 0
#define ENABLE_ASH_READ_TIMEOUT 0
#define CONFIG_ASH_ALIAS 1
#define ENABLE_ASH_ALIAS 1
#define CONFIG_ASH_MATH_SUPPORT 1
#define ENABLE_ASH_MATH_SUPPORT 1
#define ENABLE_ASH_MATH_SUPPORT_64 0
#define CONFIG_ASH_GETOPTS 1
#define ENABLE_ASH_GETOPTS 1
#define CONFIG_ASH_CMDCMD 1
#define ENABLE_ASH_CMDCMD 1
#define CONFIG_ASH_BUILTIN_ECHO 1
#define ENABLE_ASH_BUILTIN_ECHO 1
#define ENABLE_ASH_MAIL 0
#define CONFIG_ASH_OPTIMIZE_FOR_SIZE 1
#define ENABLE_ASH_OPTIMIZE_FOR_SIZE 1
#define ENABLE_ASH_RANDOM_SUPPORT 0
#define ENABLE_ASH_EXPAND_PRMT 0
#define ENABLE_HUSH 0
#define ENABLE_LASH 0
#define ENABLE_MSH 0

/*
 * Bourne Shell Options
 */
#define ENABLE_FEATURE_SH_EXTRA_QUIET 0
#define ENABLE_FEATURE_SH_STANDALONE_SHELL 0
#define CONFIG_FEATURE_COMMAND_EDITING 1
#define ENABLE_FEATURE_COMMAND_EDITING 1
#define ENABLE_FEATURE_COMMAND_EDITING_VI 0
#define CONFIG_FEATURE_COMMAND_HISTORY 15
#define ENABLE_FEATURE_COMMAND_HISTORY 15
#define CONFIG_FEATURE_COMMAND_SAVEHISTORY 1
#define ENABLE_FEATURE_COMMAND_SAVEHISTORY 1
#define CONFIG_FEATURE_COMMAND_TAB_COMPLETION 1
#define ENABLE_FEATURE_COMMAND_TAB_COMPLETION 1
#define ENABLE_FEATURE_COMMAND_USERNAME_COMPLETION 0
#define CONFIG_FEATURE_SH_FANCY_PROMPT 1
#define ENABLE_FEATURE_SH_FANCY_PROMPT 1

/*
 * System Logging Utilities
 */
#define CONFIG_SYSLOGD 1
#define ENABLE_SYSLOGD 1
#define CONFIG_FEATURE_ROTATE_LOGFILE 1
#define ENABLE_FEATURE_ROTATE_LOGFILE 1
#define CONFIG_FEATURE_REMOTE_LOG 1
#define ENABLE_FEATURE_REMOTE_LOG 1
#define CONFIG_FEATURE_IPC_SYSLOG 1
#define ENABLE_FEATURE_IPC_SYSLOG 1
#define CONFIG_FEATURE_IPC_SYSLOG_BUFFER_SIZE 16
#define ENABLE_FEATURE_IPC_SYSLOG_BUFFER_SIZE 16
#define CONFIG_LOGREAD 1
#define ENABLE_LOGREAD 1
#define ENABLE_FEATURE_LOGREAD_REDUCED_LOCKING 0
#define CONFIG_KLOGD 1
#define ENABLE_KLOGD 1
#define CONFIG_LOGGER 1
#define ENABLE_LOGGER 1

/*
 * Linux System Utilities
 */
#define CONFIG_DMESG 1
#define ENABLE_DMESG 1
#define ENABLE_FBSET 0
#define ENABLE_FEATURE_FBSET_FANCY 0
#define ENABLE_FEATURE_FBSET_READMODE 0
#define ENABLE_FDFLUSH 0
#define ENABLE_FDFORMAT 0
#define ENABLE_FDISK 0
#undef FDISK_SUPPORT_LARGE_DISKS
#define ENABLE_FEATURE_FDISK_WRITABLE 0
#define ENABLE_FEATURE_AIX_LABEL 0
#define ENABLE_FEATURE_SGI_LABEL 0
#define ENABLE_FEATURE_SUN_LABEL 0
#define ENABLE_FEATURE_OSF_LABEL 0
#define ENABLE_FEATURE_FDISK_ADVANCED 0
#define ENABLE_FREERAMDISK 0
#define ENABLE_FSCK_MINIX 0
#define ENABLE_MKFS_MINIX 0
#define ENABLE_FEATURE_MINIX2 0
#define CONFIG_GETOPT 1
#define ENABLE_GETOPT 1
#define CONFIG_HEXDUMP 1
#define ENABLE_HEXDUMP 1
#define ENABLE_HWCLOCK 0
#define ENABLE_FEATURE_HWCLOCK_LONGOPTIONS 0
#define ENABLE_FEATURE_HWCLOCK_ADJTIME_FHS 0
#define ENABLE_IPCRM 0
#define ENABLE_IPCS 0
#define ENABLE_LOSETUP 0
#define ENABLE_MDEV 0
#define ENABLE_FEATURE_MDEV_CONF 0
#define ENABLE_MKSWAP 0
#define CONFIG_MORE 1
#define ENABLE_MORE 1
#define CONFIG_FEATURE_USE_TERMIOS 1
#define ENABLE_FEATURE_USE_TERMIOS 1
#define CONFIG_PIVOT_ROOT 1
#define ENABLE_PIVOT_ROOT 1
#define ENABLE_SWITCH_ROOT 0
#define ENABLE_RDATE 0
#define ENABLE_READPROFILE 0
#define ENABLE_SWAPONOFF 0
#define CONFIG_MOUNT 1
#define ENABLE_MOUNT 1
#define ENABLE_FEATURE_MOUNT_NFS 0
#define CONFIG_UMOUNT 1
#define ENABLE_UMOUNT 1

/*
 * Common options for mount/umount
 */
#define CONFIG_FEATURE_MOUNT_LOOP 1
#define ENABLE_FEATURE_MOUNT_LOOP 1
#define ENABLE_FEATURE_MTAB_SUPPORT 0

/*
 * Debugging Options
 */
#define ENABLE_DEBUG 0
#define ENABLE_NO_DEBUG_LIB 0
#define ENABLE_DMALLOC 0
#define ENABLE_EFENCE 0
#endif
