static const struct {
	QmiProtocolError code;
	const char *text;
} qmi_errors[] = {
	{ QMI_CORE_ERROR_FAILED, "Operation failed" },
	{ QMI_CORE_ERROR_WRONG_STATE, "Operation cannot be executed in the current state" },
	{ QMI_CORE_ERROR_TIMEOUT, "Operation timed out" },
	{ QMI_CORE_ERROR_INVALID_ARGS, "Invalid arguments given" },
	{ QMI_CORE_ERROR_INVALID_MESSAGE, "QMI message is invalid" },
	{ QMI_CORE_ERROR_TLV_NOT_FOUND, "TLV not found" },
	{ QMI_CORE_ERROR_TLV_TOO_LONG, "TLV is too long" },
	{ QMI_CORE_ERROR_UNSUPPORTED, "Not supported" },
	{ QMI_CORE_ERROR_TLV_EMPTY, "TLV has no value" },
	{ QMI_CORE_ERROR_UNEXPECTED_MESSAGE, "QMI message is unexpected" },
	{ QMI_CORE_ERROR_INVALID_DATA, "Invalid data found in the message" },
	{ QMI_PROTOCOL_ERROR_NONE, "No error" },
	{ QMI_PROTOCOL_ERROR_MALFORMED_MESSAGE, "Malformed message" },
	{ QMI_PROTOCOL_ERROR_NO_MEMORY, "No memory" },
	{ QMI_PROTOCOL_ERROR_INTERNAL, "Internal" },
	{ QMI_PROTOCOL_ERROR_ABORTED, "Aborted" },
	{ QMI_PROTOCOL_ERROR_CLIENT_IDS_EXHAUSTED, "Client IDs exhausted" },
	{ QMI_PROTOCOL_ERROR_UNABORTABLE_TRANSACTION, "Unabortable transaction" },
	{ QMI_PROTOCOL_ERROR_INVALID_CLIENT_ID, "Invalid client ID" },
	{ QMI_PROTOCOL_ERROR_NO_THRESHOLDS_PROVIDED, "No thresholds provided" },
	{ QMI_PROTOCOL_ERROR_INVALID_HANDLE, "Invalid handle" },
	{ QMI_PROTOCOL_ERROR_INVALID_PROFILE, "Invalid profile" },
	{ QMI_PROTOCOL_ERROR_INVALID_PIN_ID, "Invalid PIN ID" },
	{ QMI_PROTOCOL_ERROR_INCORRECT_PIN, "Incorrect PIN" },
	{ QMI_PROTOCOL_ERROR_NO_NETWORK_FOUND, "No network found" },
	{ QMI_PROTOCOL_ERROR_CALL_FAILED, "Call failed" },
	{ QMI_PROTOCOL_ERROR_OUT_OF_CALL, "Out of call" },
	{ QMI_PROTOCOL_ERROR_NOT_PROVISIONED, "Not provisioned" },
	{ QMI_PROTOCOL_ERROR_MISSING_ARGUMENT, "Missing argument" },
	{ QMI_PROTOCOL_ERROR_ARGUMENT_TOO_LONG, "Argument too long" },
	{ QMI_PROTOCOL_ERROR_INVALID_TRANSACTION_ID, "Invalid transaction ID" },
	{ QMI_PROTOCOL_ERROR_DEVICE_IN_USE, "Device in use" },
	{ QMI_PROTOCOL_ERROR_NETWORK_UNSUPPORTED, "Network unsupported" },
	{ QMI_PROTOCOL_ERROR_DEVICE_UNSUPPORTED, "Device unsupported" },
	{ QMI_PROTOCOL_ERROR_NO_EFFECT, "No effect" },
	{ QMI_PROTOCOL_ERROR_NO_FREE_PROFILE, "No free profile" },
	{ QMI_PROTOCOL_ERROR_INVALID_PDP_TYPE, "Invalid PDP type" },
	{ QMI_PROTOCOL_ERROR_INVALID_TECHNOLOGY_PREFERENCE, "Invalid technology preference" },
	{ QMI_PROTOCOL_ERROR_INVALID_PROFILE_TYPE, "Invalid profile type" },
	{ QMI_PROTOCOL_ERROR_INVALID_SERVICE_TYPE, "Invalid service type" },
	{ QMI_PROTOCOL_ERROR_INVALID_REGISTER_ACTION, "Invalid register action" },
	{ QMI_PROTOCOL_ERROR_INVALID_PS_ATTACH_ACTION, "Invalid PS attach action" },
	{ QMI_PROTOCOL_ERROR_AUTHENTICATION_FAILED, "Authentication failed" },
	{ QMI_PROTOCOL_ERROR_PIN_BLOCKED, "PIN blocked" },
	{ QMI_PROTOCOL_ERROR_PIN_ALWAYS_BLOCKED, "PIN always blocked" },
	{ QMI_PROTOCOL_ERROR_UIM_UNINITIALIZED, "UIM uninitialized" },
	{ QMI_PROTOCOL_ERROR_MAXIMUM_QOS_REQUESTS_IN_USE, "Maximum QoS requests in use" },
	{ QMI_PROTOCOL_ERROR_INCORRECT_FLOW_FILTER, "Incorrect flow filter" },
	{ QMI_PROTOCOL_ERROR_NETWORK_QOS_UNAWARE, "Network QoS unaware" },
	{ QMI_PROTOCOL_ERROR_INVALID_QOS_ID, "Invalid QoS ID" },
	{ QMI_PROTOCOL_ERROR_REQUESTED_NUMBER_UNSUPPORTED, "Requested number unsupported" },
	{ QMI_PROTOCOL_ERROR_INTERFACE_NOT_FOUND, "Interface not found" },
	{ QMI_PROTOCOL_ERROR_FLOW_SUSPENDED, "Flow suspended" },
	{ QMI_PROTOCOL_ERROR_INVALID_DATA_FORMAT, "Invalid data format" },
	{ QMI_PROTOCOL_ERROR_GENERAL_ERROR, "General error" },
	{ QMI_PROTOCOL_ERROR_UNKNOWN_ERROR, "Unknown error" },
	{ QMI_PROTOCOL_ERROR_INVALID_ARGUMENT, "Invalid argument" },
	{ QMI_PROTOCOL_ERROR_INVALID_INDEX, "Invalid index" },
	{ QMI_PROTOCOL_ERROR_NO_ENTRY, "No entry" },
	{ QMI_PROTOCOL_ERROR_DEVICE_STORAGE_FULL, "Device storage full" },
	{ QMI_PROTOCOL_ERROR_DEVICE_NOT_READY, "Device not ready" },
	{ QMI_PROTOCOL_ERROR_NETWORK_NOT_READY, "Network not ready" },
	{ QMI_PROTOCOL_ERROR_WMS_CAUSE_CODE, "WMS cause code" },
	{ QMI_PROTOCOL_ERROR_WMS_MESSAGE_NOT_SENT, "WMS message not sent" },
	{ QMI_PROTOCOL_ERROR_WMS_MESSAGE_DELIVERY_FAILURE, "WMS message delivery failure" },
	{ QMI_PROTOCOL_ERROR_WMS_INVALID_MESSAGE_ID, "WMS invalid message ID" },
	{ QMI_PROTOCOL_ERROR_WMS_ENCODING, "WMS encoding" },
	{ QMI_PROTOCOL_ERROR_AUTHENTICATION_LOCK, "Authentication lock" },
	{ QMI_PROTOCOL_ERROR_INVALID_TRANSITION, "Invalid transition" },
	{ QMI_PROTOCOL_ERROR_NOT_MCAST_INTERFACE, "Not a multicast interface" },
	{ QMI_PROTOCOL_ERROR_MAXIMUM_MCAST_REQUESTS_IN_USE, "Maximum multicast requests in use" },
	{ QMI_PROTOCOL_ERROR_INVALID_MCAST_HANDLE, "Invalid mulitcast handle" },
	{ QMI_PROTOCOL_ERROR_INVALID_IP_FAMILY_PREFERENCE, "Invalid IP family preference" },
	{ QMI_PROTOCOL_ERROR_SESSION_INACTIVE, "Session inactive" },
	{ QMI_PROTOCOL_ERROR_SESSION_INVALID, "Session invalid" },
	{ QMI_PROTOCOL_ERROR_SESSION_OWNERSHIP, "Session ownership" },
	{ QMI_PROTOCOL_ERROR_INSUFFICIENT_RESOURCES, "Insufficient resources" },
	{ QMI_PROTOCOL_ERROR_DISABLED, "Disabled" },
	{ QMI_PROTOCOL_ERROR_INVALID_OPERATION, "Invalid operation" },
	{ QMI_PROTOCOL_ERROR_INVALID_QMI_COMMAND, "Invalid QMI command" },
	{ QMI_PROTOCOL_ERROR_WMS_SMSC_ADDRESS, "WMS SMSC address" },
	{ QMI_PROTOCOL_ERROR_INFORMATION_UNAVAILABLE, "Information unavailable" },
	{ QMI_PROTOCOL_ERROR_SEGMENT_TOO_LONG, "Segment too long" },
	{ QMI_PROTOCOL_ERROR_SEGMENT_ORDER, "Segment order" },
	{ QMI_PROTOCOL_ERROR_BUNDLING_NOT_SUPPORTED, "Bundling not supported" },
	{ QMI_PROTOCOL_ERROR_OPERATION_PARTIAL_FAILURE, "Operation partial failure" },
	{ QMI_PROTOCOL_ERROR_POLICY_MISMATCH, "Policy mismatch" },
	{ QMI_PROTOCOL_ERROR_SIM_FILE_NOT_FOUND, "SIM file not found" },
	{ QMI_PROTOCOL_ERROR_EXTENDED_INTERNAL, "Extended internal error" },
	{ QMI_PROTOCOL_ERROR_ACCESS_DENIED, "Access denied" },
	{ QMI_PROTOCOL_ERROR_HARDWARE_RESTRICTED, "Hardware restricted" },
	{ QMI_PROTOCOL_ERROR_ACK_NOT_SENT, "ACK not sent" },
	{ QMI_PROTOCOL_ERROR_INJECT_TIMEOUT, "Inject timeout" },
	{ QMI_PROTOCOL_ERROR_INCOMPATIBLE_STATE, "Incompatible state" },
	{ QMI_PROTOCOL_ERROR_FDN_RESTRICT, "FDN restrict" },
	{ QMI_PROTOCOL_ERROR_SUPS_FAILURE_CASE, "SUPS failure case" },
	{ QMI_PROTOCOL_ERROR_NO_RADIO, "No radio" },
	{ QMI_PROTOCOL_ERROR_NOT_SUPPORTED, "Not supported" },
	{ QMI_PROTOCOL_ERROR_NO_SUBSCRIPTION, "No subscription" },
	{ QMI_PROTOCOL_ERROR_CARD_CALL_CONTROL_FAILED, "Card call control failed" },
	{ QMI_PROTOCOL_ERROR_NETWORK_ABORTED, "Network aborted" },
	{ QMI_PROTOCOL_ERROR_MSG_BLOCKED, "Message blocked" },
	{ QMI_PROTOCOL_ERROR_INVALID_SESSION_TYPE, "Invalid session type" },
	{ QMI_PROTOCOL_ERROR_INVALID_PB_TYPE, "Invalid PB type" },
	{ QMI_PROTOCOL_ERROR_NO_SIM, "No SIM" },
	{ QMI_PROTOCOL_ERROR_PB_NOT_READY, "PB not ready" },
	{ QMI_PROTOCOL_ERROR_PIN_RESTRICTION, "PIN restriction" },
	{ QMI_PROTOCOL_ERROR_PIN2_RESTRICTION, "PIN2 restriction" },
	{ QMI_PROTOCOL_ERROR_PUK_RESTRICTION, "PUK restriction" },
	{ QMI_PROTOCOL_ERROR_PUK2_RESTRICTION, "PUK2 restriction" },
	{ QMI_PROTOCOL_ERROR_PB_ACCESS_RESTRICTED, "PB access restricted" },
	{ QMI_PROTOCOL_ERROR_PB_DELETE_IN_PROGRESS, "PB delete in progress" },
	{ QMI_PROTOCOL_ERROR_PB_TEXT_TOO_LONG, "PB text too long" },
	{ QMI_PROTOCOL_ERROR_PB_NUMBER_TOO_LONG, "PB number too long" },
	{ QMI_PROTOCOL_ERROR_PB_HIDDEN_KEY_RESTRICTION, "PB hidden key restriction" },
	{ QMI_PROTOCOL_ERROR_PB_NOT_AVAILABLE, "PB not available" },
	{ QMI_PROTOCOL_ERROR_DEVICE_MEMORY_ERROR, "Device memory error" },
	{ QMI_PROTOCOL_ERROR_NO_PERMISSION, "No permission" },
	{ QMI_PROTOCOL_ERROR_TOO_SOON, "Too soon" },
	{ QMI_PROTOCOL_ERROR_TIME_NOT_ACQUIRED, "Time not acquired" },
	{ QMI_PROTOCOL_ERROR_OPERATION_IN_PROGRESS, "Operation in progress" },
	{ QMI_PROTOCOL_ERROR_FW_WRITE_FAILED, "Firmware write failed" },
	{ QMI_PROTOCOL_ERROR_FW_INFO_READ_FAILED, "Firmware info read failed" },
	{ QMI_PROTOCOL_ERROR_FW_FILE_NOT_FOUND, "Firmware file not found" },
	{ QMI_PROTOCOL_ERROR_FW_DIR_NOT_FOUND, "Firmware dir not found" },
	{ QMI_PROTOCOL_ERROR_FW_ALREADY_ACTIVATED, "Firmware already activated" },
	{ QMI_PROTOCOL_ERROR_FW_CANNOT_GENERIC_IMAGE, "Firmware cannot generic image" },
	{ QMI_PROTOCOL_ERROR_FW_FILE_OPEN_FAILED, "Firmware file open failed" },
	{ QMI_PROTOCOL_ERROR_FW_UPDATE_DISCONTINUOUS_FRAME, "Firmware update discontinuous frame" },
	{ QMI_PROTOCOL_ERROR_FW_UPDATE_FAILED, "Firmware update failed" },
	{ QMI_PROTOCOL_ERROR_CAT_EVENT_REGISTRATION_FAILED, "Event registration failed" },
	{ QMI_PROTOCOL_ERROR_CAT_INVALID_TERMINAL_RESPONSE, "Invalid terminal response" },
	{ QMI_PROTOCOL_ERROR_CAT_INVALID_ENVELOPE_COMMAND, "Invalid envelope command" },
	{ QMI_PROTOCOL_ERROR_CAT_ENVELOPE_COMMAND_BUSY, "Envelope command busy" },
	{ QMI_PROTOCOL_ERROR_CAT_ENVELOPE_COMMAND_FAILED, "Envelope command failed" },
};
