#!/bin/sh

# log ip's
echo IPREMOTE = $1 >/tmp/ipup.log
echo IPLOCAL = $2 >>/tmp/ipup.log
 
# set default route
/sbin/route add default gw $1
kill `cat /var/run/ser.pid`
rm /var/run/ser.pid
killall rtpproxy
sleep 10
/usr/bin/rtpproxy -l $(ifconfig br0|awk 'sub("inet addr:","") {print $1}')/$2
sleep 10
/bin/cp /etc/ser/ser.cfg /var/ser.cfg.SRC
/bin/sed "s/fix_nated_contact(\"*[0-9]*\.*[0-9]*\.*[0-9]*\.*[0-9]*\"*/fix_nated_contact(\"$2\"/g" /var/ser.cfg.SRC > /tmp/ser/ser.cfg
/usr/sbin/ser -P /var/run/ser.pid -m 5
