.TH RVNAMED 8 "rvnamed Help Page"
.SH NAME
rvnamed \- reverse name resolution daemon for
.BR iptraf (8)

.SH DESCRIPTION
.B rvnamed
is a supplementary program distributed with iptraf.  This is a reverse name resolution daemon used by iptraf to resolve IP addresses to host names in the background, keeping iptraf from waiting until the lookup is completed.
.PP

This program is only used by iptraf and, therefore, is useless alone.

.SH FILES
 /var/log/iptraf/rvnamed.log - log file

.SH SEE ALSO
README.rvnamed - documentation from the author
.br

.SH AUTHOR
Gerard Paul Java (riker@mozcom.com)

.SH MANUAL AUTHOR
Frederic Peters (fpeters@debian.org), using README.rvnamed
General manual page modifications bu Gerard Paul Java (riker@mozcom.com)

