/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _DT_BINDINGS_PHY_QCOM_ETH_UNIPHY
#define _DT_BINDINGS_PHY_QCOM_ETH_UNIPHY

#define QCOM_ETH_UNIPHY_MODE_SGMII		0
#define QCOM_ETH_UNIPHY_MODE_SGMII_PLUS		1

#define QCOM_ETH_UNIPHY_CLKOUT_FREQ_25M		25000000
#define QCOM_ETH_UNIPHY_CLKOUT_FREQ_50M		50000000

#define QCOM_ETH_UNIPHY_CLKOUT_DS_1_5V		1500
#define QCOM_ETH_UNIPHY_CLKOUT_DS_2_8V		2800

#endif
