#include <linux/module.h>

#define _export(n) \
		void n(void); \
		EXPORT_SYMBOL(n);

_export(bcm947xx_sbh)

_export(sb_base)
_export(sb_attach)
_export(sb_kattach)
_export(sb_boardtype)
_export(sb_boardvendor)
_export(sb_btcgpiowar)
_export(sb_bus)
_export(sb_chip)
_export(sb_chiprev)
_export(sb_chipcrev)
_export(sb_chippkg)
_export(sb_clkctl_clk)
_export(sb_clkctl_fast_pwrup_delay)
_export(sb_clkctl_init)
_export(sb_clkctl_xtal)
_export(sb_core_disable)
_export(sb_core_reset)
_export(sb_core_tofixup)
_export(sb_coreflags)
_export(sb_coreflagshi)
_export(sb_coreidx)
_export(sb_coreregs)
_export(sb_corerev)
_export(sb_coreunit)
_export(sb_detach)
_export(sb_deviceremoved)
_export(sb_gpiosetcore)
_export(sb_gpiocontrol)
_export(sb_gpiointmask)
_export(sb_gpiointpolarity)
_export(sb_gpioled)
_export(sb_gpioin)
_export(sb_gpioout)
_export(sb_gpioouten)
_export(sb_gpiotimerval)
_export(sb_irq)
_export(sb_iscoreup)
_export(sb_pci_setup)
_export(sb_pcirev)
_export(sb_pcmcia_init)
_export(sb_pcmciarev)
_export(sb_register_intr_callback)
_export(sb_setcore)
_export(sb_setcoreidx)
_export(sb_war16165)
_export(sb_war32414_forceHT)
_export(sb_osh)
_export(bcmstrstr)
		
_export(getvar)
_export(getintvar)
_export(bcm_strtoul)
_export(bcm_binit)
_export(bcm_bitcount)
_export(bcm_bprintf)
_export(bcm_iovar_lencheck)
_export(bcm_next_tlv)
_export(bcm_parse_tlvs)
_export(bcm_parse_ordered_tlvs)
_export(bcm_ctype)
_export(bcmerrorstr)
_export(bcmstrcat)
_export(bcm_ether_ntoa)
_export(bcm_ether_atoe)
_export(bcm_atoi)

_export(osl_delay)
_export(osl_attach)
_export(osl_detach)
_export(osl_dma_alloc_consistent)
_export(osl_dma_free_consistent)
_export(osl_dma_map)
_export(osl_dma_unmap)
_export(osl_error)
_export(osl_malloc)
_export(osl_malloced)
_export(osl_mfree)
_export(osl_pktdup)
_export(osl_pktfree)
_export(osl_pktget)

_export(pktcopy)
_export(pktlast)
_export(pktq_deq)
_export(pktq_flush)
_export(pktq_init)
_export(pktq_mdeq)
_export(pktq_mlen)
_export(pktq_pdeq)
_export(pktq_pdeq_tail)
_export(pktq_peek_tail)
_export(pktq_penq)
_export(pktq_penq_head)
_export(pktq_setmax)
_export(pktq_pflush)
_export(pktsetprio)
_export(pkttotlen)

_export(getgpiopin)
_export(nvram_get)
_export(nvram_getall)
_export(nvram_set)
_export(nvram_unset)
_export(nvram_commit)

_export(srom_write)
_export(srom_read)

_export(hndcrc32)

_export(sb_alp_clock)
_export(sb_pmu_fast_pwrup_delay)
_export(sb_pmu_paref_ldo_enable);
_export(sb_pmu_set_ldo_voltage);