/* Generated by ./src/xlat/gen.sh from ./src/xlat/tcflsh_options.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat tcflsh_options in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data tcflsh_options_xdata[] = {
#if defined(TCIFLUSH) || (defined(HAVE_DECL_TCIFLUSH) && HAVE_DECL_TCIFLUSH)
  XLAT(TCIFLUSH),
 #define XLAT_VAL_0 ((unsigned) (TCIFLUSH))
 #define XLAT_STR_0 STRINGIFY(TCIFLUSH)
#endif
#if defined(TCOFLUSH) || (defined(HAVE_DECL_TCOFLUSH) && HAVE_DECL_TCOFLUSH)
  XLAT(TCOFLUSH),
 #define XLAT_VAL_1 ((unsigned) (TCOFLUSH))
 #define XLAT_STR_1 STRINGIFY(TCOFLUSH)
#endif
#if defined(TCIOFLUSH) || (defined(HAVE_DECL_TCIOFLUSH) && HAVE_DECL_TCIOFLUSH)
  XLAT(TCIOFLUSH),
 #define XLAT_VAL_2 ((unsigned) (TCIOFLUSH))
 #define XLAT_STR_2 STRINGIFY(TCIOFLUSH)
#endif
};
static
const struct xlat tcflsh_options[1] = { {
 .data = tcflsh_options_xdata,
 .size = ARRAY_SIZE(tcflsh_options_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
