svn add CMake/CurlCheckCSourceCompiles.cmake
svn add CMake/CurlCheckCSourceRuns.cmake
svn add CMake/FindGSS.cmake
svn add CMake/FindOpenSSL.cmake
svn add CMake/FindZLIB.cmake
svn add CMake/Macros.cmake
svn add Makefile.orig
svn add add.sh
svn add buildconf.bat
svn add curl.diff
svn add docs/CHECKSRC.md
svn add docs/CODE_OF_CONDUCT.md
svn add docs/CODE_STYLE.md
svn add docs/DISTRO-DILEMMA
svn add docs/HTTP-COOKIES
svn add docs/HTTP-COOKIES.md
svn add docs/HTTP2.md
svn add docs/LIBCURL-STRUCTS
svn add docs/RELEASE-PROCEDURE
svn add docs/ROADMAP.md
svn add docs/SECURITY
svn add docs/SSL-PROBLEMS
svn add docs/examples/getredirect.c
svn add docs/examples/http2-download.c
svn add docs/examples/http2-serverpush.c
svn add docs/examples/http2-upload.c
svn add docs/examples/imap-append.c
svn add docs/examples/imap-copy.c
svn add docs/examples/imap-create.c
svn add docs/examples/imap-delete.c
svn add docs/examples/imap-examine.c
svn add docs/examples/imap-fetch.c
svn add docs/examples/imap-list.c
svn add docs/examples/imap-lsub.c
svn add docs/examples/imap-multi.c
svn add docs/examples/imap-noop.c
svn add docs/examples/imap-search.c
svn add docs/examples/imap-ssl.c
svn add docs/examples/imap-store.c
svn add docs/examples/imap-tls.c
svn add docs/examples/imap.c
svn add docs/examples/pop3-dele.c
svn add docs/examples/pop3-list.c
svn add docs/examples/pop3-multi.c
svn add docs/examples/pop3-noop.c
svn add docs/examples/pop3-retr.c
svn add docs/examples/pop3-ssl.c
svn add docs/examples/pop3-stat.c
svn add docs/examples/pop3-tls.c
svn add docs/examples/pop3-top.c
svn add docs/examples/pop3-uidl.c
svn add docs/examples/pop3s.c
svn add docs/examples/pop3slist.c
svn add docs/examples/postinmemory.c
svn add docs/examples/sessioninfo.c
svn add docs/examples/simplesmtp.c
svn add docs/examples/smtp-expn.c
svn add docs/examples/smtp-mail.c
svn add docs/examples/smtp-ssl.c
svn add docs/examples/smtp-vrfy.c
svn add docs/libcurl/curl_multi_socket_all.3
svn add docs/libcurl/curl_multi_socket_all.html
svn add docs/libcurl/libcurl-symbols.3
svn add docs/libcurl/libcurl-symbols.html
svn add docs/libcurl/libcurl-thread.3
svn add docs/libcurl/libcurl-thread.html
svn add docs/libcurl/mksymbolsmanpage.pl
svn add docs/libcurl/opts
svn add include/curl/curlbuild.h.orig
svn add lib/Makefile.vc11
svn add lib/Makefile.vc12
svn add lib/Makefile.vc14
svn add lib/Makefile.vc7
svn add lib/README.ares
svn add lib/README.curl_off_t
svn add lib/README.curlx
svn add lib/README.encoding
svn add lib/README.hostip
svn add lib/README.httpauth
svn add lib/README.memoryleak
svn add lib/README.multi_socket
svn add lib/README.pingpong
svn add lib/README.pipelining
svn add lib/axtls.c
svn add lib/axtls.h
svn add lib/bundles.c
svn add lib/bundles.h
svn add lib/curl_darwinssl.c
svn add lib/curl_darwinssl.h
svn add lib/curl_des.c
svn add lib/curl_des.h
svn add lib/curl_endian.c
svn add lib/curl_endian.h
svn add lib/curl_ntlm.c
svn add lib/curl_ntlm.h
svn add lib/curl_ntlm_msgs.c
svn add lib/curl_ntlm_msgs.h
svn add lib/curl_printf.h
svn add lib/curl_schannel.c
svn add lib/curl_schannel.h
svn add lib/curl_sec.h
svn add lib/cyassl.c
svn add lib/cyassl.h
svn add lib/gskit.c
svn add lib/gskit.h
svn add lib/gtls.c
svn add lib/gtls.h
svn add lib/http2.c
svn add lib/http2.h
svn add lib/http_negotiate_sspi.c
svn add lib/http_ntlm.c
svn add lib/http_ntlm.h
svn add lib/krb4.c
svn add lib/krb4.h
svn add lib/nss.c
svn add lib/nssg.h
svn add lib/polarssl.c
svn add lib/polarssl.h
svn add lib/polarssl_threadlock.c
svn add lib/polarssl_threadlock.h
svn add lib/qssl.c
svn add lib/qssl.h
svn add lib/sigpipe.h
svn add lib/smb.c
svn add lib/smb.h
svn add lib/sslgen.c
svn add lib/sslgen.h
svn add lib/ssluse.c
svn add lib/ssluse.h
svn add lib/system_win32.c
svn add lib/system_win32.h
svn add lib/vauth
svn add lib/vtls
svn add mkinstalldirs
svn add projects
svn add scripts
svn add src/Makefile.vc11
svn add src/Makefile.vc12
svn add src/Makefile.vc14
svn add src/Makefile.vc7
svn add src/slist_wc.c
svn add src/slist_wc.h
svn add src/tool_strdup.c
svn add src/tool_strdup.h
svn add src/version.h
svn add test-driver
svn add tests/certs/Server-localhost-sv.pub.pem
svn add tests/certs/Server-localhost.nn-sv.pub.pem
svn add tests/certs/Server-localhost0h-sv.pub.pem
svn add tests/data/CMakeLists.txt
svn add tests/data/Makefile.inc
svn add tests/data/test1134
svn add tests/data/test1135
svn add tests/data/test1136
svn add tests/data/test1137
svn add tests/data/test1138
svn add tests/data/test1139
svn add tests/data/test1140
svn add tests/data/test1141
svn add tests/data/test1142
svn add tests/data/test1143
svn add tests/data/test1234
svn add tests/data/test1235
svn add tests/data/test1236
svn add tests/data/test1237
svn add tests/data/test1238
svn add tests/data/test1239
svn add tests/data/test1240
svn add tests/data/test1241
svn add tests/data/test1242
svn add tests/data/test1243
svn add tests/data/test1244
svn add tests/data/test1323
svn add tests/data/test1324
svn add tests/data/test1397
svn add tests/data/test1398
svn add tests/data/test1411
svn add tests/data/test1415
svn add tests/data/test1416
svn add tests/data/test1417
svn add tests/data/test1418
svn add tests/data/test1419
svn add tests/data/test1420
svn add tests/data/test1421
svn add tests/data/test1422
svn add tests/data/test1423
svn add tests/data/test1424
svn add tests/data/test1428
svn add tests/data/test1429
svn add tests/data/test1430
svn add tests/data/test1431
svn add tests/data/test1432
svn add tests/data/test1433
svn add tests/data/test1434
svn add tests/data/test1435
svn add tests/data/test1436
svn add tests/data/test1437
svn add tests/data/test1513
svn add tests/data/test1514
svn add tests/data/test1515
svn add tests/data/test1516
svn add tests/data/test1517
svn add tests/data/test1520
svn add tests/data/test1525
svn add tests/data/test1526
svn add tests/data/test1527
svn add tests/data/test1528
svn add tests/data/test1529
svn add tests/data/test1530
svn add tests/data/test1600
svn add tests/data/test1601
svn add tests/data/test1602
svn add tests/data/test1603
svn add tests/data/test1604
svn add tests/data/test1700
svn add tests/data/test1701
svn add tests/data/test1702
svn add tests/data/test1800
svn add tests/data/test1801
svn add tests/data/test2034
svn add tests/data/test2035
svn add tests/data/test2036
svn add tests/data/test2037
svn add tests/data/test2038
svn add tests/data/test2039
svn add tests/data/test2040
svn add tests/data/test2041
svn add tests/data/test2042
svn add tests/data/test2043
svn add tests/data/test2044
svn add tests/data/test2045
svn add tests/data/test2046
svn add tests/data/test2047
svn add tests/data/test2048
svn add tests/data/test2049
svn add tests/data/test2050
svn add tests/data/test2051
svn add tests/data/test2052
svn add tests/data/test325
svn add tests/data/test640
svn add tests/data/test641
svn add tests/data/test810
svn add tests/data/test811
svn add tests/data/test812
svn add tests/data/test813
svn add tests/data/test814
svn add tests/data/test815
svn add tests/data/test816
svn add tests/data/test817
svn add tests/data/test818
svn add tests/data/test819
svn add tests/data/test820
svn add tests/data/test821
svn add tests/data/test822
svn add tests/data/test823
svn add tests/data/test824
svn add tests/data/test825
svn add tests/data/test826
svn add tests/data/test827
svn add tests/data/test828
svn add tests/data/test829
svn add tests/data/test830
svn add tests/data/test831
svn add tests/data/test832
svn add tests/data/test833
svn add tests/data/test834
svn add tests/data/test835
svn add tests/data/test836
svn add tests/data/test837
svn add tests/data/test838
svn add tests/data/test839
svn add tests/data/test840
svn add tests/data/test841
svn add tests/data/test842
svn add tests/data/test843
svn add tests/data/test844
svn add tests/data/test845
svn add tests/data/test858
svn add tests/data/test859
svn add tests/data/test860
svn add tests/data/test861
svn add tests/data/test862
svn add tests/data/test863
svn add tests/data/test864
svn add tests/data/test865
svn add tests/data/test866
svn add tests/data/test867
svn add tests/data/test868
svn add tests/data/test869
svn add tests/data/test870
svn add tests/data/test871
svn add tests/data/test872
svn add tests/data/test873
svn add tests/data/test874
svn add tests/data/test875
svn add tests/data/test876
svn add tests/data/test877
svn add tests/data/test878
svn add tests/data/test879
svn add tests/data/test880
svn add tests/data/test881
svn add tests/data/test882
svn add tests/data/test883
svn add tests/data/test884
svn add tests/data/test885
svn add tests/data/test886
svn add tests/data/test887
svn add tests/data/test888
svn add tests/data/test889
svn add tests/data/test890
svn add tests/data/test912
svn add tests/data/test913
svn add tests/data/test914
svn add tests/data/test915
svn add tests/data/test916
svn add tests/data/test917
svn add tests/data/test918
svn add tests/data/test919
svn add tests/data/test920
svn add tests/data/test921
svn add tests/data/test922
svn add tests/data/test923
svn add tests/data/test924
svn add tests/data/test925
svn add tests/data/test926
svn add tests/data/test927
svn add tests/data/test928
svn add tests/data/test929
svn add tests/data/test930
svn add tests/data/test931
svn add tests/data/test932
svn add tests/data/test933
svn add tests/data/test934
svn add tests/data/test935
svn add tests/data/test936
svn add tests/data/test937
svn add tests/data/test938
svn add tests/data/test939
svn add tests/data/test940
svn add tests/data/test941
svn add tests/data/test942
svn add tests/data/test943
svn add tests/data/test944
svn add tests/data/test945
svn add tests/data/test946
svn add tests/data/test947
svn add tests/data/test948
svn add tests/data/test949
svn add tests/extern-scan.pl
svn add tests/http2-server.pl
svn add tests/libtest/CMakeLists.txt
svn add tests/libtest/lib1513.c
svn add tests/libtest/lib1514.c
svn add tests/libtest/lib1515.c
svn add tests/libtest/lib1517.c
svn add tests/libtest/lib1520.c
svn add tests/libtest/lib1525.c
svn add tests/libtest/lib1526.c
svn add tests/libtest/lib1527.c
svn add tests/libtest/lib1528.c
svn add tests/libtest/lib1529.c
svn add tests/libtest/lib1530.c
svn add tests/libtest/lib1531.c
svn add tests/manpage-scan.pl
svn add tests/nroff-scan.pl
svn add tests/pathhelp.pm
svn add tests/server/CMakeLists.txt
svn add tests/unit/unit1397.c
svn add tests/unit/unit1398.c
svn add tests/unit/unit1600.c
svn add tests/unit/unit1601.c
svn add tests/unit/unit1602.c
svn add tests/unit/unit1603.c
svn add tests/unit/unit1604.c
svn add vs
svn add vs/t
svn add vs/t/README
svn add vs/t/lib
svn add vs/t/lib/vc6_libcurl_dsp.foot
svn add vs/t/lib/vc6_libcurl_dsp.head
svn add vs/t/lib/vc8_libcurl_prj.foot
svn add vs/t/lib/vc8_libcurl_prj.head
svn add vs/vc6
svn add vs/vc6/lib
svn add vs/vc6/lib/vc6libcurl.dsp
svn add vs/vc6/lib/vc6libcurl.dsw
svn add vs/vc6/src
svn add vs/vc6/src/vc6curltool.dsp
svn add vs/vc6/src/vc6curltool.dsw
svn add vs/vc6/vc6curl.dsw
svn add vs/vc8
svn add vs/vc8/lib
svn add vs/vc8/lib/vc8libcurl.vcproj
