.TH MNDP 1 "February 27, 2011"
.SH NAME
mndp \- A tool for discovering other RouterOS or mactelnetd devices
.SH SYNOPSIS
.B mndp
.SH DESCRIPTION
This tool enables you to discover RouterOS or MAC-Telnetd enabled
devices. It will display the MAC-address software version, and uptime of
every device or machine it discovers.
.PP
To exit this application, use
.B Control + C
\.
.SH SEE ALSO
.BR mactelnet (1),
.BR macping (1),
.BR mactelnetd (1).
.SH AUTHOR
mndp was written by Håkon Nessjøen <haakon.nessjoen@gmail.com>.
.PP
This manual page was written by Håkon Nessjøen <haakon.nessjoen@gmail.com>,
for the Debian project (and may be used by others).
