svn add FLAC-vs2005.sln
svn add FLAC.dsw
svn add Makefile.deps
svn add add.sh
svn add all.dsp
svn add all_dynamic.dsp
svn add all_static.dsp
svn add ar-lib
svn add build/compile.mk
svn add compile
svn add configure.ac
svn add configure.in
svn add doc/Doxyfile
svn add doc/Doxyfile.in
svn add doc/html/api/+_2all_8h-source.html
svn add doc/html/api/+_2export_8h-source.html
svn add doc/html/api/+_2export_8h.html
svn add doc/html/api/+_2metadata_8h-source.html
svn add doc/html/api/+_2metadata_8h.html
svn add doc/html/api/all_8h-source.html
svn add doc/html/api/annotated.html
svn add doc/html/api/assert_8h-source.html
svn add doc/html/api/callback_8h-source.html
svn add doc/html/api/callback_8h.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1File-members.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1File.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1File.png
svn add doc/html/api/classFLAC_1_1Decoder_1_1Stream-members.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1Stream.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1Stream.png
svn add doc/html/api/classFLAC_1_1Decoder_1_1Stream_1_1State-members.html
svn add doc/html/api/classFLAC_1_1Decoder_1_1Stream_1_1State.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1File-members.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1File.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1File.png
svn add doc/html/api/classFLAC_1_1Encoder_1_1Stream-members.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1Stream.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1Stream.png
svn add doc/html/api/classFLAC_1_1Encoder_1_1Stream_1_1State-members.html
svn add doc/html/api/classFLAC_1_1Encoder_1_1Stream_1_1State.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Application-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Application.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Application.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1Chain-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Chain.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Chain_1_1Status-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Chain_1_1Status.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1CueSheet-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1CueSheet.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1CueSheet.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1CueSheet_1_1Track-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1CueSheet_1_1Track.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Iterator-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Iterator.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Padding-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Padding.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Padding.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1Picture-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Picture.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Picture.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1Prototype-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Prototype.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Prototype.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1SeekTable-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1SeekTable.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1SeekTable.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1SimpleIterator-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1SimpleIterator.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1SimpleIterator_1_1Status-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1SimpleIterator_1_1Status.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1StreamInfo-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1StreamInfo.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1StreamInfo.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1Unknown-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Unknown.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1Unknown.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1VorbisComment-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1VorbisComment.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1VorbisComment.png
svn add doc/html/api/classFLAC_1_1Metadata_1_1VorbisComment_1_1Entry-members.html
svn add doc/html/api/classFLAC_1_1Metadata_1_1VorbisComment_1_1Entry.html
svn add doc/html/api/classes.html
svn add doc/html/api/decoder_8h-source.html
svn add doc/html/api/decoder_8h.html
svn add doc/html/api/dir_000000.html
svn add doc/html/api/dir_000001.html
svn add doc/html/api/dir_000002.html
svn add doc/html/api/dirs.html
svn add doc/html/api/doxygen.css
svn add doc/html/api/doxygen.png
svn add doc/html/api/encoder_8h-source.html
svn add doc/html/api/encoder_8h.html
svn add doc/html/api/export_8h-source.html
svn add doc/html/api/export_8h.html
svn add doc/html/api/files.html
svn add doc/html/api/format_8h-source.html
svn add doc/html/api/format_8h.html
svn add doc/html/api/functions.html
svn add doc/html/api/functions_func.html
svn add doc/html/api/functions_vars.html
svn add doc/html/api/globals.html
svn add doc/html/api/globals_0x66.html
svn add doc/html/api/globals_0x67.html
svn add doc/html/api/globals_defs.html
svn add doc/html/api/globals_enum.html
svn add doc/html/api/globals_eval.html
svn add doc/html/api/globals_func.html
svn add doc/html/api/globals_type.html
svn add doc/html/api/globals_vars.html
svn add doc/html/api/group__flac.html
svn add doc/html/api/group__flac__callbacks.html
svn add doc/html/api/group__flac__decoder.html
svn add doc/html/api/group__flac__encoder.html
svn add doc/html/api/group__flac__export.html
svn add doc/html/api/group__flac__format.html
svn add doc/html/api/group__flac__metadata.html
svn add doc/html/api/group__flac__metadata__level0.html
svn add doc/html/api/group__flac__metadata__level1.html
svn add doc/html/api/group__flac__metadata__level2.html
svn add doc/html/api/group__flac__metadata__object.html
svn add doc/html/api/group__flac__stream__decoder.html
svn add doc/html/api/group__flac__stream__encoder.html
svn add doc/html/api/group__flacpp.html
svn add doc/html/api/group__flacpp__decoder.html
svn add doc/html/api/group__flacpp__encoder.html
svn add doc/html/api/group__flacpp__export.html
svn add doc/html/api/group__flacpp__metadata.html
svn add doc/html/api/group__flacpp__metadata__level0.html
svn add doc/html/api/group__flacpp__metadata__level1.html
svn add doc/html/api/group__flacpp__metadata__level2.html
svn add doc/html/api/group__flacpp__metadata__object.html
svn add doc/html/api/group__porting.html
svn add doc/html/api/group__porting__1__1__2__to__1__1__3.html
svn add doc/html/api/group__porting__1__1__3__to__1__1__4.html
svn add doc/html/api/group__porting__1__1__4__to__1__2__0.html
svn add doc/html/api/hierarchy.html
svn add doc/html/api/index.html
svn add doc/html/api/metadata_8h-source.html
svn add doc/html/api/metadata_8h.html
svn add doc/html/api/modules.html
svn add doc/html/api/ordinals_8h-source.html
svn add doc/html/api/stream__decoder_8h-source.html
svn add doc/html/api/stream__decoder_8h.html
svn add doc/html/api/stream__encoder_8h-source.html
svn add doc/html/api/stream__encoder_8h.html
svn add doc/html/api/structFLAC____EntropyCodingMethod-members.html
svn add doc/html/api/structFLAC____EntropyCodingMethod.html
svn add doc/html/api/structFLAC____EntropyCodingMethod__PartitionedRice-members.html
svn add doc/html/api/structFLAC____EntropyCodingMethod__PartitionedRice.html
svn add doc/html/api/structFLAC____EntropyCodingMethod__PartitionedRiceContents-members.html
svn add doc/html/api/structFLAC____EntropyCodingMethod__PartitionedRiceContents.html
svn add doc/html/api/structFLAC____Frame-members.html
svn add doc/html/api/structFLAC____Frame.html
svn add doc/html/api/structFLAC____FrameFooter-members.html
svn add doc/html/api/structFLAC____FrameFooter.html
svn add doc/html/api/structFLAC____FrameHeader-members.html
svn add doc/html/api/structFLAC____FrameHeader.html
svn add doc/html/api/structFLAC____IOCallbacks-members.html
svn add doc/html/api/structFLAC____IOCallbacks.html
svn add doc/html/api/structFLAC____StreamDecoder-members.html
svn add doc/html/api/structFLAC____StreamDecoder.html
svn add doc/html/api/structFLAC____StreamEncoder-members.html
svn add doc/html/api/structFLAC____StreamEncoder.html
svn add doc/html/api/structFLAC____StreamMetadata-members.html
svn add doc/html/api/structFLAC____StreamMetadata.html
svn add doc/html/api/structFLAC____StreamMetadata__Application-members.html
svn add doc/html/api/structFLAC____StreamMetadata__Application.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet-members.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet__Index-members.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet__Index.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet__Track-members.html
svn add doc/html/api/structFLAC____StreamMetadata__CueSheet__Track.html
svn add doc/html/api/structFLAC____StreamMetadata__Padding-members.html
svn add doc/html/api/structFLAC____StreamMetadata__Padding.html
svn add doc/html/api/structFLAC____StreamMetadata__Picture-members.html
svn add doc/html/api/structFLAC____StreamMetadata__Picture.html
svn add doc/html/api/structFLAC____StreamMetadata__SeekPoint-members.html
svn add doc/html/api/structFLAC____StreamMetadata__SeekPoint.html
svn add doc/html/api/structFLAC____StreamMetadata__SeekTable-members.html
svn add doc/html/api/structFLAC____StreamMetadata__SeekTable.html
svn add doc/html/api/structFLAC____StreamMetadata__StreamInfo-members.html
svn add doc/html/api/structFLAC____StreamMetadata__StreamInfo.html
svn add doc/html/api/structFLAC____StreamMetadata__Unknown-members.html
svn add doc/html/api/structFLAC____StreamMetadata__Unknown.html
svn add doc/html/api/structFLAC____StreamMetadata__VorbisComment-members.html
svn add doc/html/api/structFLAC____StreamMetadata__VorbisComment.html
svn add doc/html/api/structFLAC____StreamMetadata__VorbisComment__Entry-members.html
svn add doc/html/api/structFLAC____StreamMetadata__VorbisComment__Entry.html
svn add doc/html/api/structFLAC____Subframe-members.html
svn add doc/html/api/structFLAC____Subframe.html
svn add doc/html/api/structFLAC____Subframe__Constant-members.html
svn add doc/html/api/structFLAC____Subframe__Constant.html
svn add doc/html/api/structFLAC____Subframe__Fixed-members.html
svn add doc/html/api/structFLAC____Subframe__Fixed.html
svn add doc/html/api/structFLAC____Subframe__LPC-members.html
svn add doc/html/api/structFLAC____Subframe__LPC.html
svn add doc/html/api/structFLAC____Subframe__Verbatim-members.html
svn add doc/html/api/structFLAC____Subframe__Verbatim.html
svn add doc/html/comparison.html
svn add doc/html/comparison__chopin_prelude_24.html
svn add doc/html/comparison__dream_theater_600.html
svn add doc/html/comparison__eddie_warner_titus.html
svn add doc/html/comparison__fanfare_de_l_eventail_de_jeanne.html
svn add doc/html/comparison__gloria_estefan_conga.html
svn add doc/html/comparison__hand_in_my_pocket.html
svn add doc/html/comparison__l_sub_raga_sivapriya.html
svn add doc/html/comparison__laetatus_sum.html
svn add doc/html/comparison__mummified_in_barbed_wire.html
svn add doc/html/comparison__prokofiev_pcon3_3.html
svn add doc/html/comparison__ravel_sq4_4.html
svn add doc/html/comparison__scarlatti_k42.html
svn add doc/html/comparison__tool_forty_six_and_2.html
svn add doc/html/comparison__white_room.html
svn add doc/html/comparison_all_cpudectime.html
svn add doc/html/comparison_all_cpuenctime.html
svn add doc/html/comparison_all_procdectime.html
svn add doc/html/comparison_all_procenctime.html
svn add doc/html/comparison_all_ratio.html
svn add doc/html/documentation_tasks.html
svn add doc/html/documentation_tools_plugins.html
svn add doc/html/download.html
svn add doc/html/images/1x1.gif
svn add doc/html/images/cafebug.gif
svn add doc/html/images/hw
svn add doc/html/images/hw/Blackbird_Front_low3_325x87.jpg
svn add doc/html/images/hw/MS300frontsmall_270x108.jpg
svn add doc/html/images/hw/Makefile.am
svn add doc/html/images/hw/Makefile.in
svn add doc/html/images/hw/MediaBox_Frt_170x325.jpg
svn add doc/html/images/hw/SB_Hero_Black_325x182.jpg
svn add doc/html/images/hw/Sooloos-ControlOne_325x328.jpg
svn add doc/html/images/hw/Z500_front_325x94.jpg
svn add doc/html/images/hw/a2_01_325x252.jpg
svn add doc/html/images/hw/arcus_325x135.jpg
svn add doc/html/images/hw/bmp-1430_325x241.jpg
svn add doc/html/images/hw/cs505_front_lrg_325x113.jpg
svn add doc/html/images/hw/enus_3-4lft-hires_product_eva8000_325x127.jpg
svn add doc/html/images/hw/escient_ProductLine_325x163.jpg
svn add doc/html/images/hw/hifidelio_bl_front_Z_RGB_325x163.jpg
svn add doc/html/images/hw/i-station-mini-dx_325x237.jpg
svn add doc/html/images/hw/iwod-g10_325x257.jpg
svn add doc/html/images/hw/knc_hr-2800_325x209.jpg
svn add doc/html/images/hw/mediaready_prodmain_MRMCa_325x232.jpg
svn add doc/html/images/hw/meizu_m6_325x206.jpg
svn add doc/html/images/hw/musica_artwork_325x90.jpg
svn add doc/html/images/hw/neodigits_x5000_325x124.jpg
svn add doc/html/images/hw/onda-vx737_325x240.jpg
svn add doc/html/images/hw/request_n_front_325x103.jpg
svn add doc/html/images/hw/rio_karma_279x254.jpg
svn add doc/html/images/hw/sonos_family_RGB_325x200.jpg
svn add doc/html/images/hw/teclast-tl29_325x244.jpg
svn add doc/html/images/hw/transporter_hero_grey_325x208.jpg
svn add doc/html/images/hw/tvix-4000_325x204.jpg
svn add doc/html/images/hw/vibez_nofm_combi_black_b_325x220.jpg
svn add doc/html/images/logo.svg
svn add doc/html/images/logo100.gif
svn add doc/html/itunes.html
svn add doc/html/links.html
svn add doc/html/news.html
svn add doc/html/ru
svn add doc/html/ru/Makefile.am
svn add doc/html/ru/Makefile.in
svn add doc/html/ru/authors.html
svn add doc/html/ru/comparison.html
svn add doc/html/ru/developers.html
svn add doc/html/ru/documentation.html
svn add doc/html/ru/download.html
svn add doc/html/ru/features.html
svn add doc/html/ru/format.html
svn add doc/html/ru/goals.html
svn add doc/html/ru/id.html
svn add doc/html/ru/index.html
svn add doc/html/ru/links.html
svn add doc/html/ru/news.html
svn add doc/isoflac.txt
svn add examples/c/decode/file/example_c_decode_file.dsp
svn add examples/c/decode/file/example_c_decode_file.vcxproj
svn add examples/c/decode/file/example_c_decode_file.vcxproj.filters
svn add examples/c/encode/file/example_c_encode_file.dsp
svn add examples/c/encode/file/example_c_encode_file.vcxproj
svn add examples/c/encode/file/example_c_encode_file.vcxproj.filters
svn add examples/cpp/decode/file/example_cpp_decode_file.dsp
svn add examples/cpp/decode/file/example_cpp_decode_file.vcxproj
svn add examples/cpp/decode/file/example_cpp_decode_file.vcxproj.filters
svn add examples/cpp/encode/file/example_cpp_encode_file.dsp
svn add examples/cpp/encode/file/example_cpp_encode_file.vcxproj
svn add examples/cpp/encode/file/example_cpp_encode_file.vcxproj.filters
svn add examples/examples.dsp
svn add include/share/compat.h
svn add include/share/endswap.h
svn add include/share/macros.h
svn add include/share/private.h
svn add include/share/safe_str.h
svn add include/share/win_utf8_io.h
svn add include/share/windows_unicode_filenames.h
svn add m4/add_cflags.m4
svn add m4/add_cxxflags.m4
svn add m4/bswap.m4
svn add m4/clang.m4
svn add m4/codeset.m4
svn add m4/endian.m4
svn add m4/gcc_version.m4
svn add m4/iconv.m4
svn add m4/lib-ld.m4
svn add m4/lib-link.m4
svn add m4/lib-prefix.m4
svn add m4/libtool.m4
svn add m4/ltoptions.m4
svn add m4/ltsugar.m4
svn add m4/ltversion.m4
svn add m4/lt~obsolete.m4
svn add m4/really_gcc.m4
svn add m4/stack_protect.m4
svn add man/manpage.links
svn add man/manpage.log
svn add man/manpage.refs
svn add microbench
svn add mkinstalldirs
svn add obj
svn add obj/Makefile.am
svn add obj/Makefile.in
svn add obj/debug
svn add obj/debug/Makefile.am
svn add obj/debug/Makefile.in
svn add obj/debug/bin
svn add obj/debug/bin/Makefile.am
svn add obj/debug/bin/Makefile.in
svn add obj/debug/lib
svn add obj/debug/lib/Makefile.am
svn add obj/debug/lib/Makefile.in
svn add obj/release
svn add obj/release/Makefile.am
svn add obj/release/Makefile.in
svn add obj/release/bin
svn add obj/release/bin/Makefile.am
svn add obj/release/bin/Makefile.in
svn add obj/release/lib
svn add obj/release/lib/Makefile.am
svn add obj/release/lib/Makefile.in
svn add objs
svn add src/flac/flac.dsp
svn add src/flac/flac.vcxproj
svn add src/flac/flac.vcxproj.filters
svn add src/flac/iffscan.dsp
svn add src/flac/iffscan.vcxproj
svn add src/flac/iffscan.vcxproj.filters
svn add src/libFLAC/fixed_intrin_sse2.c
svn add src/libFLAC/fixed_intrin_ssse3.c
svn add src/libFLAC/ia32/bitreader_asm.nasm
svn add src/libFLAC/ia32/stream_encoder_asm.nasm
svn add src/libFLAC/include/private/macros.h
svn add src/libFLAC/include/private/stream_encoder.h
svn add src/libFLAC/libFLAC_dynamic.dsp
svn add src/libFLAC/libFLAC_dynamic.vcxproj
svn add src/libFLAC/libFLAC_dynamic.vcxproj.filters
svn add src/libFLAC/libFLAC_static.dsp
svn add src/libFLAC/libFLAC_static.vcxproj
svn add src/libFLAC/libFLAC_static.vcxproj.filters
svn add src/libFLAC/lpc_intrin_avx2.c
svn add src/libFLAC/lpc_intrin_sse.c
svn add src/libFLAC/lpc_intrin_sse2.c
svn add src/libFLAC/lpc_intrin_sse41.c
svn add src/libFLAC/ppc
svn add src/libFLAC/ppc/Makefile.am
svn add src/libFLAC/ppc/Makefile.in
svn add src/libFLAC/ppc/as
svn add src/libFLAC/ppc/as/Makefile.am
svn add src/libFLAC/ppc/as/Makefile.in
svn add src/libFLAC/ppc/as/lpc_asm.s
svn add src/libFLAC/ppc/gas
svn add src/libFLAC/ppc/gas/Makefile.am
svn add src/libFLAC/ppc/gas/Makefile.in
svn add src/libFLAC/ppc/gas/lpc_asm.s
svn add src/libFLAC/stream_encoder_intrin_avx2.c
svn add src/libFLAC/stream_encoder_intrin_sse2.c
svn add src/libFLAC/stream_encoder_intrin_ssse3.c
svn add src/libFLAC/windows_unicode_filenames.c
svn add src/libFLAC++/libFLAC++_dynamic.dsp
svn add src/libFLAC++/libFLAC++_dynamic.vcxproj
svn add src/libFLAC++/libFLAC++_dynamic.vcxproj.filters
svn add src/libFLAC++/libFLAC++_static.dsp
svn add src/libFLAC++/libFLAC++_static.vcxproj
svn add src/libFLAC++/libFLAC++_static.vcxproj.filters
svn add src/metaflac/metaflac.dsp
svn add src/metaflac/metaflac.vcxproj
svn add src/metaflac/metaflac.vcxproj.filters
svn add src/monkeys_audio_utilities
svn add src/monkeys_audio_utilities/Makefile.am
svn add src/monkeys_audio_utilities/Makefile.in
svn add src/monkeys_audio_utilities/flac_mac
svn add src/monkeys_audio_utilities/flac_mac/Makefile.am
svn add src/monkeys_audio_utilities/flac_mac/Makefile.in
svn add src/monkeys_audio_utilities/flac_mac/flac_mac.dsp
svn add src/monkeys_audio_utilities/flac_mac/flac_mac.vcproj
svn add src/monkeys_audio_utilities/flac_mac/main.c
svn add src/monkeys_audio_utilities/flac_ren
svn add src/monkeys_audio_utilities/flac_ren/Makefile.am
svn add src/monkeys_audio_utilities/flac_ren/Makefile.in
svn add src/monkeys_audio_utilities/flac_ren/flac_ren.dsp
svn add src/monkeys_audio_utilities/flac_ren/flac_ren.vcproj
svn add src/monkeys_audio_utilities/flac_ren/main.c
svn add src/plugin_common/plugin_common_static.dsp
svn add src/plugin_common/plugin_common_static.vcproj
svn add src/plugin_winamp2
svn add src/plugin_winamp2/Makefile.am
svn add src/plugin_winamp2/Makefile.in
svn add src/plugin_winamp2/configure.c
svn add src/plugin_winamp2/configure.h
svn add src/plugin_winamp2/in_flac.c
svn add src/plugin_winamp2/in_flac.dsp
svn add src/plugin_winamp2/in_flac.vcproj
svn add src/plugin_winamp2/include
svn add src/plugin_winamp2/include/Makefile.am
svn add src/plugin_winamp2/include/Makefile.in
svn add src/plugin_winamp2/include/winamp2
svn add src/plugin_winamp2/include/winamp2/Makefile.am
svn add src/plugin_winamp2/include/winamp2/Makefile.in
svn add src/plugin_winamp2/include/winamp2/in2.h
svn add src/plugin_winamp2/include/winamp2/out.h
svn add src/plugin_winamp2/infobox.c
svn add src/plugin_winamp2/infobox.h
svn add src/plugin_winamp2/playback.c
svn add src/plugin_winamp2/playback.h
svn add src/plugin_winamp2/resource.h
svn add src/plugin_winamp2/resource.rc
svn add src/plugin_winamp2/tagz.cpp
svn add src/plugin_winamp2/tagz.h
svn add src/share/getopt/Makefile.am
svn add src/share/getopt/Makefile.in
svn add src/share/getopt/getopt_static.dsp
svn add src/share/getopt/getopt_static.vcxproj
svn add src/share/getopt/getopt_static.vcxproj.filters
svn add src/share/grabbag/Makefile.am
svn add src/share/grabbag/Makefile.in
svn add src/share/grabbag/alloc.c
svn add src/share/grabbag/grabbag_static.dsp
svn add src/share/grabbag/grabbag_static.vcxproj
svn add src/share/grabbag/grabbag_static.vcxproj.filters
svn add src/share/grabbag/snprintf.c
svn add src/share/replaygain_analysis/Makefile.am
svn add src/share/replaygain_analysis/Makefile.in
svn add src/share/replaygain_analysis/replaygain_analysis_static.dsp
svn add src/share/replaygain_analysis/replaygain_analysis_static.vcxproj
svn add src/share/replaygain_analysis/replaygain_analysis_static.vcxproj.filters
svn add src/share/replaygain_synthesis/Makefile.am
svn add src/share/replaygain_synthesis/Makefile.in
svn add src/share/replaygain_synthesis/include
svn add src/share/replaygain_synthesis/include/Makefile.am
svn add src/share/replaygain_synthesis/include/Makefile.in
svn add src/share/replaygain_synthesis/include/private
svn add src/share/replaygain_synthesis/include/private/Makefile.am
svn add src/share/replaygain_synthesis/include/private/Makefile.in
svn add src/share/replaygain_synthesis/include/private/fast_float_math_hack.h
svn add src/share/replaygain_synthesis/replaygain_synthesis_static.dsp
svn add src/share/replaygain_synthesis/replaygain_synthesis_static.vcxproj
svn add src/share/replaygain_synthesis/replaygain_synthesis_static.vcxproj.filters
svn add src/share/utf8/Makefile.am
svn add src/share/utf8/Makefile.in
svn add src/share/utf8/charsetmap.h
svn add src/share/utf8/utf8_static.dsp
svn add src/share/utf8/utf8_static.vcxproj
svn add src/share/utf8/utf8_static.vcxproj.filters
svn add src/share/win_utf8_io
svn add src/test_grabbag/cuesheet/test_cuesheet.dsp
svn add src/test_grabbag/cuesheet/test_cuesheet.vcxproj
svn add src/test_grabbag/cuesheet/test_cuesheet.vcxproj.filters
svn add src/test_grabbag/picture/test_picture.dsp
svn add src/test_grabbag/picture/test_picture.vcxproj
svn add src/test_grabbag/picture/test_picture.vcxproj.filters
svn add src/test_libFLAC/endswap.c
svn add src/test_libFLAC/endswap.h
svn add src/test_libFLAC/md5.c
svn add src/test_libFLAC/md5.h
svn add src/test_libFLAC/test_libFLAC.dsp
svn add src/test_libFLAC/test_libFLAC.vcxproj
svn add src/test_libFLAC/test_libFLAC.vcxproj.filters
svn add src/test_libFLAC++/test_libFLAC++.dsp
svn add src/test_libFLAC++/test_libFLAC++.vcxproj
svn add src/test_libFLAC++/test_libFLAC++.vcxproj.filters
svn add src/test_libs_common/test_libs_common_static.dsp
svn add src/test_libs_common/test_libs_common_static.vcxproj
svn add src/test_libs_common/test_libs_common_static.vcxproj.filters
svn add src/test_seeking/test_seeking.dsp
svn add src/test_seeking/test_seeking.vcxproj
svn add src/test_seeking/test_seeking.vcxproj.filters
svn add src/test_streams/test_streams.dsp
svn add src/test_streams/test_streams.vcxproj
svn add src/test_streams/test_streams.vcxproj.filters
svn add src/utils
svn add test/common.sh.in
svn add test/cuesheets/good.005.quoted.isrc.cue
svn add test/test_bins.sh
svn add test/test_compression.sh
svn add test/test_replaygain.sh
svn add test/write_iff.pl
