#!/bin/bash

# NFT_TEST_REQUIRES(NFT_TEST_HAVE_chain_binding)
# NFT_TEST_REQUIRES(NFT_TEST_HAVE_netdev_chain_multidevice)

set -e

iface_cleanup() {
        ip link del d0 &>/dev/null || :
        ip link del d1 &>/dev/null || :
        ip link del d2 &>/dev/null || :
}
trap 'iface_cleanup' EXIT

ip link add d0 type dummy
ip link add d1 type dummy
ip link add d2 type dummy

load_ruleset() {
	family=$1

	# Test auto-removal of chain hook on device removal
	RULESET="table $family x {
	chain x {}
	chain w {
		ip daddr 8.7.6.0/24 jump {
			ip daddr vmap { 8.7.6.3 : jump x, 8.7.6.4 : jump x }
		}
	}
	chain y {
		type filter hook ingress devices = { d0, d1, d2 } priority 0;
		ip saddr { 1.2.3.4, 2.3.4.5 } counter
		ip daddr vmap { 5.4.3.0/24 : jump w, 8.9.0.0/24 : jump x }
	}
}"
	$NFT -c -f - <<< $RULESET
	$NFT -f - <<< $RULESET
}

load_ruleset "inet"
load_ruleset "netdev"
