
#include "main.c"
#include "noise.c" 
#include "device.c" 
#include "peer.c" 
#include "timers.c" 
#include "queueing.c" 
#include "send.c" 
#include "receive.c" 
#include "socket.c" 
#include "hashtables.c" 
#include "allowedips.c" 
#include "ratelimiter.c" 
#include "cookie.c" 
#include "netlink.c"
#include "crypto/curve25519.c" 
#include "crypto/chacha20poly1305.c" 
#include "crypto/blake2s.c"
