/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stackTraceTest1 */

#ifndef _Included_stackTraceTest1
#define _Included_stackTraceTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stackTraceTest1
 * Method:    b
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stackTraceTest1_b
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
