.TH SED "1" "VERSION" "User Commands"
.SH NAME
sed \- stream editor for filtering and transforming text
.SH SYNOPSIS
.B sed
[\fIOPTION\fR]... \fI{script-only-if-no-other-script} \fR[\fIinput-file\fR]...
.SH DESCRIPTION
.B OOOPS!
.B sed
manual page could not be built (missing perl or
cross-compilation).
.PP
For the full documentation for
.B sed
see
.UR https://www.gnu.org/software/sed
GNU SED Website (https://www.gnu.org/software/sed)
