AC_DEFUN([SAVE_KOBS_NG_VERSION], [
KOBS_NG_VERSION=$VERSION
echo $VERSION > $srcdir/version
AC_DEFINE_UNQUOTED(VERSION, "$KOBS_NG_VERSION", [KOBS NG version])
AC_SUBST(KOBS_NG_VERSION)
KOBS_NG_MAJOR=`echo $VERSION | cut -d . -f 1`
AC_SUBST(KOBS_NG_MAJOR)
KOBS_NG_MINOR=`echo $VERSION | cut -d . -f 2`
AC_SUBST(KOBS_NG_MINOR)
KOBS_NG_SUBMINOR=`echo $VERSION | cut -d . -f 3 | sed -e 's/pre[[0-9]]*//g'`
AC_SUBST(KOBS_NG_SUBMINOR)
])
