#!/bin/bash

# handles are shown last

$NFT add table test
$NFT add chain test test
$NFT add rule test test tcp dport 22 counter accept
$NFT -a list table test | grep 'accept # handle '[[:digit:]]$ >/dev/null
