#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_BPAUTO_BUILD_NLATTR 1
#define CPTCFG_BPAUTO_NEW_LEDS 1
#define CPTCFG_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BPAUTO_RHASHTABLE 1
#define CPTCFG_BPAUTO_BUCKET_LOCKS 1
#define CPTCFG_BPAUTO_REFCOUNT 1
#define CPTCFG_BPAUTO_CRYPTO_LIB_ARC4 1
#define CPTCFG_BPAUTO_BUILD_CRYPTO_LIB_ARC4 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_MAC80211_STA_HASH_MAX_SIZE 0
#define CPTCFG_WLAN 1
#define CPTCFG_ATH_COMMON_MODULE 1
#define CPTCFG_WLAN_VENDOR_ATH 1
#define CPTCFG_ATH_USER_REGD 1
#define CPTCFG_ATH9K_HW_MODULE 1
#define CPTCFG_ATH9K_COMMON_MODULE 1
#define CPTCFG_ATH9K_MODULE 1
#define CPTCFG_ATH9K_PCI 1
#define CPTCFG_ATH9K_DEBUGFS 1
#define CPTCFG_ATH9K_STATION_STATISTICS 1
#define CPTCFG_ATH9K_TX99 1
#define CPTCFG_ATH9K_DYNACK 1
#define CPTCFG_ATH10K_MODULE 1
#define CPTCFG_ATH10K_PCI_MODULE 1
#define CPTCFG_ATH10K_DEBUG 1
#define CPTCFG_ATH10K_DEBUGFS 1
#define CPTCFG_BACKPORTED_WIRELESS 1
#define CPTCFG_BACKPORTED_NET_CORE 1
#define CPTCFG_BACKPORTED_EXPERT 1
#define CPTCFG_BACKPORTED_BP_MODULES 1
#define CPTCFG_BACKPORTED_BPAUTO_BUILD_NLATTR 1
#define CPTCFG_BACKPORTED_BPAUTO_NEW_LEDS 1
#define CPTCFG_BACKPORTED_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BACKPORTED_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BACKPORTED_BPAUTO_RHASHTABLE 1
#define CPTCFG_BACKPORTED_BPAUTO_BUCKET_LOCKS 1
#define CPTCFG_BACKPORTED_BPAUTO_REFCOUNT 1
#define CPTCFG_BACKPORTED_BPAUTO_CRYPTO_LIB_ARC4 1
#define CPTCFG_BACKPORTED_BPAUTO_BUILD_CRYPTO_LIB_ARC4 1
#define CPTCFG_BACKPORTED_CFG80211_MODULE 1
#define CPTCFG_BACKPORTED_CFG80211_DEBUGFS 1
#define CPTCFG_BACKPORTED_CFG80211_WEXT 1
#define CPTCFG_BACKPORTED_MAC80211_MODULE 1
#define CPTCFG_BACKPORTED_MAC80211_HAS_RC 1
#define CPTCFG_BACKPORTED_MAC80211_RC_MINSTREL 1
#define CPTCFG_BACKPORTED_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_BACKPORTED_MAC80211_LEDS 1
#define CPTCFG_BACKPORTED_MAC80211_DEBUGFS 1
#define CPTCFG_BACKPORTED_WLAN 1
#define CPTCFG_BACKPORTED_ATH_COMMON_MODULE 1
#define CPTCFG_BACKPORTED_WLAN_VENDOR_ATH 1
#define CPTCFG_BACKPORTED_ATH9K_HW_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_COMMON_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_MODULE 1
#define CPTCFG_BACKPORTED_ATH9K_PCI 1
#define CPTCFG_BACKPORTED_ATH9K_DEBUGFS 1
#define CPTCFG_BACKPORTED_ATH9K_STATION_STATISTICS 1
#define CPTCFG_BACKPORTED_ATH9K_TX99 1
#define CPTCFG_BACKPORTED_ATH9K_DYNACK 1
#define CPTCFG_BACKPORTED_ATH10K_MODULE 1
#define CPTCFG_BACKPORTED_ATH10K_PCI_MODULE 1
#define CPTCFG_BACKPORTED_ATH10K_DEBUG 1
#define CPTCFG_BACKPORTED_ATH10K_DEBUGFS 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
