svn add NewTargets.cc
svn add NewTargets.h
svn add add.sh
svn add docs/3rd-party.xml
svn add docs/legal-notices.xml
svn add docs/licenses/zlib-license.txt
svn add docs/man-xlate/nmap-man-de.xml
svn add docs/man-xlate/nmap-man-es.xml
svn add docs/man-xlate/nmap-man-fr.xml
svn add docs/man-xlate/nmap-man-hr.xml
svn add docs/man-xlate/nmap-man-hu.xml
svn add docs/man-xlate/nmap-man-id.xml
svn add docs/man-xlate/nmap-man-it.xml
svn add docs/man-xlate/nmap-man-ja.xml
svn add docs/man-xlate/nmap-man-pl.xml
svn add docs/man-xlate/nmap-man-pt_BR.xml
svn add docs/man-xlate/nmap-man-pt_PT.xml
svn add docs/man-xlate/nmap-man-ro.xml
svn add docs/man-xlate/nmap-man-ru.xml
svn add docs/man-xlate/nmap-man-sk.xml
svn add docs/man-xlate/nmap-man-zh.xml
svn add docs/nmap-install.xml
svn add docs/nmap-man-enclosure.xml
svn add docs/nmap-update.xml
svn add docs/nmap-usage.xml
svn add docs/refguide.xml
svn add docs/scripting.xml
svn add docs/zenmap.xml
svn add libpcap/packaging
svn add libz/VERSION.1.2.8
svn add mswin32/OpenSSL
svn add mswin32/OpenSSL/bin
svn add mswin32/OpenSSL/include
svn add mswin32/OpenSSL/include/openssl
svn add mswin32/OpenSSL/lib
svn add mswin32/OpenSSL/lib/engines
svn add ncat/scripts/filters
svn add ncat/test/test-env-w32
svn add nmap-7.60-1.spec
svn add nmap-header-template.cc
svn add nmap.spec.in
svn add nping/nping-dev
svn add nse_zlib.cc
svn add nse_zlib.h
svn add nselib/data/idnaMappings.lua
svn add nselib/idna.lua
svn add nselib/punycode.lua
svn add nselib/zlib.luadoc
svn add nsock/examples
svn add scripts/deluge-rpc-brute.nse
svn add scripts/http-bigip-cookie.nse
svn add scripts/http-jsonp-detection.nse
svn add scripts/http-trane-info.nse
svn add scripts/rsa-vuln-roca.nse
svn add scripts/smb-enum-services.nse
svn add scripts/tls-alpn.nse
svn add zenmap-7.60-1.spec
svn add zenmap.spec.in
