'\" t
.\"     Title: mesg
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2022-05-11
.\"    Manual: User Commands
.\"    Source: util-linux 2.38.1
.\"  Language: English
.\"
.TH "MESG" "1" "2022-05-11" "util\-linux 2.38.1" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mesg \- display (or do not display) messages from other users
.SH "SYNOPSIS"
.sp
\fBmesg\fP [\fIoption\fP] [\fBn\fP|\fBy\fP]
.SH "DESCRIPTION"
.sp
The \fBmesg\fP utility is invoked by a user to control write access others have to the terminal device associated with standard error output. If write access is allowed, then programs such as \fBtalk\fP(1) and \fBwrite\fP(1) may display messages on the terminal.
.sp
Traditionally, write access is allowed by default. However, as users become more conscious of various security risks, there is a trend to remove write access by default, at least for the primary login shell. To make sure your ttys are set the way you want them to be set, \fBmesg\fP should be executed in your login scripts.
.sp
The \fBmesg\fP utility silently exits with error status 2 if not executed on terminal. In this case execute \fBmesg\fP is pointless. The command line option \fB\-\-verbose\fP forces mesg to print a warning in this situation. This behaviour has been introduced in version 2.33.
.SH "ARGUMENTS"
.sp
\fBn\fP
.RS 4
Disallow messages.
.RE
.sp
\fBy\fP
.RS 4
Allow messages to be displayed.
.RE
.sp
If no arguments are given, \fBmesg\fP shows the current message status on standard error output.
.SH "OPTIONS"
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Explain what is being done.
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display help text and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version and exit.
.RE
.SH "EXIT STATUS"
.sp
The \fBmesg\fP utility exits with one of the following values:
.sp
\fB0\fP
.RS 4
Messages are allowed.
.RE
.sp
\fB1\fP
.RS 4
Messages are not allowed.
.RE
.sp
\fB>1\fP
.RS 4
An error has occurred.
.RE
.SH "FILES"
.sp
\fI/dev/[pt]ty[pq]?\fP
.SH "HISTORY"
.sp
A \fBmesg\fP command appeared in Version 6 AT&T UNIX.
.SH "SEE ALSO"
.sp
\fBlogin\fP(1),
\fBtalk\fP(1),
\fBwrite\fP(1),
\fBwall\fP(1),
\fBxterm\fP(1)
.SH "REPORTING BUGS"
.sp
For bug reports, use the issue tracker at \c
.URL "https://github.com/util\-linux/util\-linux/issues" "" "."
.SH "AVAILABILITY"
.sp
The \fBmesg\fP command is part of the util\-linux package which can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."