dnl Generated by ./types/gen.sh from ./types/openat2.h; do not edit.
AC_DEFUN([st_CHECK_TYPES_OPENAT2],[
AC_CHECK_HEADERS([linux/openat2.h],[

AC_CHECK_TYPES([struct open_how],
[AC_CHECK_MEMBERS([struct open_how.resolve],,,[AC_INCLUDES_DEFAULT
#include <linux/openat2.h>])],,[AC_INCLUDES_DEFAULT
#include <linux/openat2.h>])
],[],[AC_INCLUDES_DEFAULT
])])
