# SPDX-License-Identifier: GPL-2.0
realtek-y			+= realtek_main.o
realtek-y			+= phy_patch.o
realtek-y			+= phy_patch_rtl826x.o
realtek-$(CONFIG_REALTEK_PHY_HWMON) += realtek_hwmon.o
obj-$(CONFIG_REALTEK_PHY)	+= realtek.o
obj-$(CONFIG_REALTEK_PHY_MULTIPORT) += realtek_multiport.o
