/* Do not modify, generated from ../include/autoconf.h.in */

#ifndef BAREFOOTD
#define BAREFOOTD 0
#endif

#ifndef HAVE_ARPA_NAMESER_H
#define HAVE_ARPA_NAMESER_H 0
#endif

#ifndef HAVE_BACKTRACE
#define HAVE_BACKTRACE 0
#endif

#ifndef HAVE_BINDRESVPORT
#define HAVE_BINDRESVPORT 0
#endif

#ifndef HAVE_BROKEN_INET_NTOA
#define HAVE_BROKEN_INET_NTOA 0
#endif

#ifndef HAVE_BSDAUTH
#define HAVE_BSDAUTH 0
#endif

#ifndef HAVE_BSD_AUTH_H
#define HAVE_BSD_AUTH_H 0
#endif

#ifndef HAVE_BZERO
#define HAVE_BZERO 0
#endif

#ifndef HAVE_CLOCK_GETTIME_MONOTONIC
#define HAVE_CLOCK_GETTIME_MONOTONIC 0
#endif

#ifndef HAVE_CMSGHDR
#define HAVE_CMSGHDR 0
#endif

#ifndef HAVE_CMSG_LEN
#define HAVE_CMSG_LEN 0
#endif

#ifndef HAVE_CMSG_SPACE
#define HAVE_CMSG_SPACE 0
#endif

#ifndef HAVE_COM_ERR_H
#define HAVE_COM_ERR_H 0
#endif

#ifndef HAVE_COM_ERR_IN_KRB5
#define HAVE_COM_ERR_IN_KRB5 0
#endif

#ifndef HAVE_COND_LIBWRAP
#define HAVE_COND_LIBWRAP 0
#endif

#ifndef HAVE_COND_LIVEDEBUG
#define HAVE_COND_LIVEDEBUG 0
#endif

#ifndef HAVE_COND_PAM
#define HAVE_COND_PAM 0
#endif

#ifndef HAVE_CONFENV_DISABLE
#define HAVE_CONFENV_DISABLE 0
#endif

#ifndef HAVE_COVERAGE
#define HAVE_COVERAGE 0
#endif

#ifndef HAVE_CPU_EQUAL
#define HAVE_CPU_EQUAL 0
#endif

#ifndef HAVE_CRYPT_H
#define HAVE_CRYPT_H 0
#endif

#ifndef HAVE_DAEMON
#define HAVE_DAEMON 0
#endif

#ifndef HAVE_DARWIN
#define HAVE_DARWIN 0
#endif

#ifndef HAVE_DECL_ATTRIBUTE
#define HAVE_DECL_ATTRIBUTE 0
#endif

#ifndef HAVE_DECL_BOUNDED
#define HAVE_DECL_BOUNDED 0
#endif

#ifndef HAVE_DECL_CONSTRUCTOR
#define HAVE_DECL_CONSTRUCTOR 0
#endif

#ifndef HAVE_DECL_FORMAT
#define HAVE_DECL_FORMAT 0
#endif

#ifndef HAVE_DECL_GETS
#define HAVE_DECL_GETS 0
#endif

#ifndef HAVE_DECL_KRB5_KT_FREE_ENTRY
#define HAVE_DECL_KRB5_KT_FREE_ENTRY 0
#endif

#ifndef HAVE_DECL_NONNULL
#define HAVE_DECL_NONNULL 0
#endif

#ifndef HAVE_DECL__IO_GETC
#define HAVE_DECL__IO_GETC 0
#endif

#ifndef HAVE_DECL__IO_PUTC
#define HAVE_DECL__IO_PUTC 0
#endif

#ifndef HAVE_DEC_PROTO
#define HAVE_DEC_PROTO 0
#endif

#ifndef HAVE_DIFFTIME
#define HAVE_DIFFTIME 0
#endif

#ifndef HAVE_DLFCN_H
#define HAVE_DLFCN_H 0
#endif

#ifndef HAVE_DOPRNT
#define HAVE_DOPRNT 0
#endif

#ifndef HAVE_DUPSOCKOPT_MAX
#define HAVE_DUPSOCKOPT_MAX 0
#endif

#ifndef HAVE_ENABLED_PIDFILE
#define HAVE_ENABLED_PIDFILE 0
#endif

#ifndef HAVE_ERROR_MESSAGE
#define HAVE_ERROR_MESSAGE 0
#endif

#ifndef HAVE_ERR_EAI_ADDRFAMILY
#define HAVE_ERR_EAI_ADDRFAMILY 0
#endif

#ifndef HAVE_ERR_EAI_AGAIN
#define HAVE_ERR_EAI_AGAIN 0
#endif

#ifndef HAVE_ERR_EAI_ALLDONE
#define HAVE_ERR_EAI_ALLDONE 0
#endif

#ifndef HAVE_ERR_EAI_BADEXTFLAGS
#define HAVE_ERR_EAI_BADEXTFLAGS 0
#endif

#ifndef HAVE_ERR_EAI_BADFLAGS
#define HAVE_ERR_EAI_BADFLAGS 0
#endif

#ifndef HAVE_ERR_EAI_BADHINTS
#define HAVE_ERR_EAI_BADHINTS 0
#endif

#ifndef HAVE_ERR_EAI_CANCELED
#define HAVE_ERR_EAI_CANCELED 0
#endif

#ifndef HAVE_ERR_EAI_FAIL
#define HAVE_ERR_EAI_FAIL 0
#endif

#ifndef HAVE_ERR_EAI_FAMILY
#define HAVE_ERR_EAI_FAMILY 0
#endif

#ifndef HAVE_ERR_EAI_IDN_ENCODE
#define HAVE_ERR_EAI_IDN_ENCODE 0
#endif

#ifndef HAVE_ERR_EAI_INPROGRESS
#define HAVE_ERR_EAI_INPROGRESS 0
#endif

#ifndef HAVE_ERR_EAI_INTR
#define HAVE_ERR_EAI_INTR 0
#endif

#ifndef HAVE_ERR_EAI_MEMORY
#define HAVE_ERR_EAI_MEMORY 0
#endif

#ifndef HAVE_ERR_EAI_NODATA
#define HAVE_ERR_EAI_NODATA 0
#endif

#ifndef HAVE_ERR_EAI_NONAME
#define HAVE_ERR_EAI_NONAME 0
#endif

#ifndef HAVE_ERR_EAI_NOTCANCELED
#define HAVE_ERR_EAI_NOTCANCELED 0
#endif

#ifndef HAVE_ERR_EAI_OVERFLOW
#define HAVE_ERR_EAI_OVERFLOW 0
#endif

#ifndef HAVE_ERR_EAI_PROTOCOL
#define HAVE_ERR_EAI_PROTOCOL 0
#endif

#ifndef HAVE_ERR_EAI_SERVICE
#define HAVE_ERR_EAI_SERVICE 0
#endif

#ifndef HAVE_ERR_EAI_SOCKTYPE
#define HAVE_ERR_EAI_SOCKTYPE 0
#endif

#ifndef HAVE_ERR_EAI_SYSTEM
#define HAVE_ERR_EAI_SYSTEM 0
#endif

#ifndef HAVE_ET_COM_ERR_H
#define HAVE_ET_COM_ERR_H 0
#endif

#ifndef HAVE_EXECINFO_H
#define HAVE_EXECINFO_H 0
#endif

#ifndef HAVE_EXTRA_OSF_SYMBOLS
#define HAVE_EXTRA_OSF_SYMBOLS 0
#endif

#ifndef HAVE_FCNTL_H
#define HAVE_FCNTL_H 0
#endif

#ifndef HAVE_FDMASK
#define HAVE_FDMASK 0
#endif

#ifndef HAVE_FREEADDRINFO
#define HAVE_FREEADDRINFO 0
#endif

#ifndef HAVE_FREEIFADDRS
#define HAVE_FREEIFADDRS 0
#endif

#ifndef HAVE_GETADDRINFO
#define HAVE_GETADDRINFO 0
#endif

#ifndef HAVE_GETHOSTBYNAME2
#define HAVE_GETHOSTBYNAME2 0
#endif

#ifndef HAVE_GETIFADDRS
#define HAVE_GETIFADDRS 0
#endif

#ifndef HAVE_GETIPNODEBYNAME
#define HAVE_GETIPNODEBYNAME 0
#endif

#ifndef HAVE_GETNAMEINFO
#define HAVE_GETNAMEINFO 0
#endif

#ifndef HAVE_GETPASS
#define HAVE_GETPASS 0
#endif

#ifndef HAVE_GETPRPWNAM
#define HAVE_GETPRPWNAM 0
#endif

#ifndef HAVE_GETPWNAM_SHADOW
#define HAVE_GETPWNAM_SHADOW 0
#endif

#ifndef HAVE_GETSPNAM
#define HAVE_GETSPNAM 0
#endif

#ifndef HAVE_GET_INIT_CREDS_KEYTAB
#define HAVE_GET_INIT_CREDS_KEYTAB 0
#endif

#ifndef HAVE_GET_INIT_CREDS_OPT_ALLOC
#define HAVE_GET_INIT_CREDS_OPT_ALLOC 0
#endif

#ifndef HAVE_GET_INIT_CREDS_OPT_FREE_CTX
#define HAVE_GET_INIT_CREDS_OPT_FREE_CTX 0
#endif

#ifndef HAVE_GSSAPI
#define HAVE_GSSAPI 0
#endif

#ifndef HAVE_GSSAPI_GSSAPI_EXT_H
#define HAVE_GSSAPI_GSSAPI_EXT_H 0
#endif

#ifndef HAVE_GSSAPI_GSSAPI_GENERIC_H
#define HAVE_GSSAPI_GSSAPI_GENERIC_H 0
#endif

#ifndef HAVE_GSSAPI_GSSAPI_H
#define HAVE_GSSAPI_GSSAPI_H 0
#endif

#ifndef HAVE_GSSAPI_GSSAPI_KRB5_H
#define HAVE_GSSAPI_GSSAPI_KRB5_H 0
#endif

#ifndef HAVE_GSSAPI_H
#define HAVE_GSSAPI_H 0
#endif

#ifndef HAVE_GSSKRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT
#define HAVE_GSSKRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT 0
#endif

#ifndef HAVE_GSS_MAP_ANY_TO_ANY
#define HAVE_GSS_MAP_ANY_TO_ANY 0
#endif

#ifndef HAVE_GSS_MAP_NAME_TO_ANY
#define HAVE_GSS_MAP_NAME_TO_ANY 0
#endif

#ifndef HAVE_HEIMDAL_KERBEROS
#define HAVE_HEIMDAL_KERBEROS 0
#endif

#ifndef HAVE_HSTRERROR
#define HAVE_HSTRERROR 0
#endif

#ifndef HAVE_IFADDRS_H
#define HAVE_IFADDRS_H 0
#endif

#ifndef HAVE_IN6_ADDR
#define HAVE_IN6_ADDR 0
#endif

#ifndef HAVE_INET_PTON
#define HAVE_INET_PTON 0
#endif

#ifndef HAVE_INT16_T
#define HAVE_INT16_T 0
#endif

#ifndef HAVE_INT32_T
#define HAVE_INT32_T 0
#endif

#ifndef HAVE_INT8_T
#define HAVE_INT8_T 0
#endif

#ifndef HAVE_INTTYPES_H
#define HAVE_INTTYPES_H 0
#endif

#ifndef HAVE_IN_ADDR_T
#define HAVE_IN_ADDR_T 0
#endif

#ifndef HAVE_IN_PORT_T
#define HAVE_IN_PORT_T 0
#endif

#ifndef HAVE_IPV6_2292DSTOPTS
#define HAVE_IPV6_2292DSTOPTS 0
#endif

#ifndef HAVE_IPV6_2292HOPLIMIT
#define HAVE_IPV6_2292HOPLIMIT 0
#endif

#ifndef HAVE_IPV6_2292HOPOPTS
#define HAVE_IPV6_2292HOPOPTS 0
#endif

#ifndef HAVE_IPV6_2292PKTINFO
#define HAVE_IPV6_2292PKTINFO 0
#endif

#ifndef HAVE_IPV6_2292PKTOPTIONS
#define HAVE_IPV6_2292PKTOPTIONS 0
#endif

#ifndef HAVE_IPV6_2292RTHDR
#define HAVE_IPV6_2292RTHDR 0
#endif

#ifndef HAVE_IPV6_ADDRFORM
#define HAVE_IPV6_ADDRFORM 0
#endif

#ifndef HAVE_IPV6_ADDR_PREFERENCES
#define HAVE_IPV6_ADDR_PREFERENCES 0
#endif

#ifndef HAVE_IPV6_ADD_MEMBERSHIP
#define HAVE_IPV6_ADD_MEMBERSHIP 0
#endif

#ifndef HAVE_IPV6_AIXRAWSOCKET
#define HAVE_IPV6_AIXRAWSOCKET 0
#endif

#ifndef HAVE_IPV6_AUTHHDR
#define HAVE_IPV6_AUTHHDR 0
#endif

#ifndef HAVE_IPV6_AUTH_LEVEL
#define HAVE_IPV6_AUTH_LEVEL 0
#endif

#ifndef HAVE_IPV6_AUTOFLOWLABEL
#define HAVE_IPV6_AUTOFLOWLABEL 0
#endif

#ifndef HAVE_IPV6_CHECKSUM
#define HAVE_IPV6_CHECKSUM 0
#endif

#ifndef HAVE_IPV6_DONTFRAG
#define HAVE_IPV6_DONTFRAG 0
#endif

#ifndef HAVE_IPV6_DROP_MEMBERSHIP
#define HAVE_IPV6_DROP_MEMBERSHIP 0
#endif

#ifndef HAVE_IPV6_DSTOPTS
#define HAVE_IPV6_DSTOPTS 0
#endif

#ifndef HAVE_IPV6_ESP_NETWORK_LEVEL
#define HAVE_IPV6_ESP_NETWORK_LEVEL 0
#endif

#ifndef HAVE_IPV6_ESP_TRANS_LEVEL
#define HAVE_IPV6_ESP_TRANS_LEVEL 0
#endif

#ifndef HAVE_IPV6_FLOWINFO
#define HAVE_IPV6_FLOWINFO 0
#endif

#ifndef HAVE_IPV6_FLOWINFO_SEND
#define HAVE_IPV6_FLOWINFO_SEND 0
#endif

#ifndef HAVE_IPV6_FLOWLABEL_MGR
#define HAVE_IPV6_FLOWLABEL_MGR 0
#endif

#ifndef HAVE_IPV6_HOPLIMIT
#define HAVE_IPV6_HOPLIMIT 0
#endif

#ifndef HAVE_IPV6_HOPOPTS
#define HAVE_IPV6_HOPOPTS 0
#endif

#ifndef HAVE_IPV6_IPCOMP_LEVEL
#define HAVE_IPV6_IPCOMP_LEVEL 0
#endif

#ifndef HAVE_IPV6_IPSEC_POLICY
#define HAVE_IPV6_IPSEC_POLICY 0
#endif

#ifndef HAVE_IPV6_JOIN_ANYCAST
#define HAVE_IPV6_JOIN_ANYCAST 0
#endif

#ifndef HAVE_IPV6_JOIN_GROUP
#define HAVE_IPV6_JOIN_GROUP 0
#endif

#ifndef HAVE_IPV6_LEAVE_ANYCAST
#define HAVE_IPV6_LEAVE_ANYCAST 0
#endif

#ifndef HAVE_IPV6_LEAVE_GROUP
#define HAVE_IPV6_LEAVE_GROUP 0
#endif

#ifndef HAVE_IPV6_MINHOPCOUNT
#define HAVE_IPV6_MINHOPCOUNT 0
#endif

#ifndef HAVE_IPV6_MIPDSTOPTS
#define HAVE_IPV6_MIPDSTOPTS 0
#endif

#ifndef HAVE_IPV6_MTU
#define HAVE_IPV6_MTU 0
#endif

#ifndef HAVE_IPV6_MTU_DISCOVER
#define HAVE_IPV6_MTU_DISCOVER 0
#endif

#ifndef HAVE_IPV6_MULTICAST_HOPS
#define HAVE_IPV6_MULTICAST_HOPS 0
#endif

#ifndef HAVE_IPV6_MULTICAST_IF
#define HAVE_IPV6_MULTICAST_IF 0
#endif

#ifndef HAVE_IPV6_MULTICAST_LOOP
#define HAVE_IPV6_MULTICAST_LOOP 0
#endif

#ifndef HAVE_IPV6_NEXTHOP
#define HAVE_IPV6_NEXTHOP 0
#endif

#ifndef HAVE_IPV6_NOPROBE
#define HAVE_IPV6_NOPROBE 0
#endif

#ifndef HAVE_IPV6_ORIGDSTADDR
#define HAVE_IPV6_ORIGDSTADDR 0
#endif

#ifndef HAVE_IPV6_PATHMTU
#define HAVE_IPV6_PATHMTU 0
#endif

#ifndef HAVE_IPV6_PIPEX
#define HAVE_IPV6_PIPEX 0
#endif

#ifndef HAVE_IPV6_PKTINFO
#define HAVE_IPV6_PKTINFO 0
#endif

#ifndef HAVE_IPV6_PKTOPTIONS
#define HAVE_IPV6_PKTOPTIONS 0
#endif

#ifndef HAVE_IPV6_PORTRANGE
#define HAVE_IPV6_PORTRANGE 0
#endif

#ifndef HAVE_IPV6_RECVDSTADDR
#define HAVE_IPV6_RECVDSTADDR 0
#endif

#ifndef HAVE_IPV6_RECVDSTOPTS
#define HAVE_IPV6_RECVDSTOPTS 0
#endif

#ifndef HAVE_IPV6_RECVERR
#define HAVE_IPV6_RECVERR 0
#endif

#ifndef HAVE_IPV6_RECVHOPLIMIT
#define HAVE_IPV6_RECVHOPLIMIT 0
#endif

#ifndef HAVE_IPV6_RECVHOPOPTS
#define HAVE_IPV6_RECVHOPOPTS 0
#endif

#ifndef HAVE_IPV6_RECVHOPS
#define HAVE_IPV6_RECVHOPS 0
#endif

#ifndef HAVE_IPV6_RECVIF
#define HAVE_IPV6_RECVIF 0
#endif

#ifndef HAVE_IPV6_RECVOPTS
#define HAVE_IPV6_RECVOPTS 0
#endif

#ifndef HAVE_IPV6_RECVORIGDSTADDR
#define HAVE_IPV6_RECVORIGDSTADDR 0
#endif

#ifndef HAVE_IPV6_RECVPATHMTU
#define HAVE_IPV6_RECVPATHMTU 0
#endif

#ifndef HAVE_IPV6_RECVPKTINFO
#define HAVE_IPV6_RECVPKTINFO 0
#endif

#ifndef HAVE_IPV6_RECVRETOPTS
#define HAVE_IPV6_RECVRETOPTS 0
#endif

#ifndef HAVE_IPV6_RECVRTHDR
#define HAVE_IPV6_RECVRTHDR 0
#endif

#ifndef HAVE_IPV6_RECVSRCRT
#define HAVE_IPV6_RECVSRCRT 0
#endif

#ifndef HAVE_IPV6_RECVTCLASS
#define HAVE_IPV6_RECVTCLASS 0
#endif

#ifndef HAVE_IPV6_RETOPTS
#define HAVE_IPV6_RETOPTS 0
#endif

#ifndef HAVE_IPV6_ROUTER_ALERT
#define HAVE_IPV6_ROUTER_ALERT 0
#endif

#ifndef HAVE_IPV6_RTHDR
#define HAVE_IPV6_RTHDR 0
#endif

#ifndef HAVE_IPV6_RTHDRDSTOPTS
#define HAVE_IPV6_RTHDRDSTOPTS 0
#endif

#ifndef HAVE_IPV6_SENDIF
#define HAVE_IPV6_SENDIF 0
#endif

#ifndef HAVE_IPV6_TCLASS
#define HAVE_IPV6_TCLASS 0
#endif

#ifndef HAVE_IPV6_TRANSPARENT
#define HAVE_IPV6_TRANSPARENT 0
#endif

#ifndef HAVE_IPV6_UNICAST_HOPS
#define HAVE_IPV6_UNICAST_HOPS 0
#endif

#ifndef HAVE_IPV6_USE_MIN_MTU
#define HAVE_IPV6_USE_MIN_MTU 0
#endif

#ifndef HAVE_IPV6_V6ONLY
#define HAVE_IPV6_V6ONLY 0
#endif

#ifndef HAVE_IPV6_XFRM_POLICY
#define HAVE_IPV6_XFRM_POLICY 0
#endif

#ifndef HAVE_IP_ADDRFORM
#define HAVE_IP_ADDRFORM 0
#endif

#ifndef HAVE_IP_ADD_MEMBERSHIP
#define HAVE_IP_ADD_MEMBERSHIP 0
#endif

#ifndef HAVE_IP_ADD_SOURCE_MEMBERSHIP
#define HAVE_IP_ADD_SOURCE_MEMBERSHIP 0
#endif

#ifndef HAVE_IP_AUTH_LEVEL
#define HAVE_IP_AUTH_LEVEL 0
#endif

#ifndef HAVE_IP_BLOCK_SOURCE
#define HAVE_IP_BLOCK_SOURCE 0
#endif

#ifndef HAVE_IP_BROADCAST_IF
#define HAVE_IP_BROADCAST_IF 0
#endif

#ifndef HAVE_IP_DHCPMODE
#define HAVE_IP_DHCPMODE 0
#endif

#ifndef HAVE_IP_DONTFRAG
#define HAVE_IP_DONTFRAG 0
#endif

#ifndef HAVE_IP_DROP_MEMBERSHIP
#define HAVE_IP_DROP_MEMBERSHIP 0
#endif

#ifndef HAVE_IP_DROP_SOURCE_MEMBERSHIP
#define HAVE_IP_DROP_SOURCE_MEMBERSHIP 0
#endif

#ifndef HAVE_IP_ESP_NETWORK_LEVEL
#define HAVE_IP_ESP_NETWORK_LEVEL 0
#endif

#ifndef HAVE_IP_ESP_TRANS_LEVEL
#define HAVE_IP_ESP_TRANS_LEVEL 0
#endif

#ifndef HAVE_IP_FINDPMTU
#define HAVE_IP_FINDPMTU 0
#endif

#ifndef HAVE_IP_FREEBIND
#define HAVE_IP_FREEBIND 0
#endif

#ifndef HAVE_IP_HDRINCL
#define HAVE_IP_HDRINCL 0
#endif

#ifndef HAVE_IP_IPCOMP_LEVEL
#define HAVE_IP_IPCOMP_LEVEL 0
#endif

#ifndef HAVE_IP_MINTTL
#define HAVE_IP_MINTTL 0
#endif

#ifndef HAVE_IP_MTU_DISCOVER
#define HAVE_IP_MTU_DISCOVER 0
#endif

#ifndef HAVE_IP_MULTICAST_HOPS
#define HAVE_IP_MULTICAST_HOPS 0
#endif

#ifndef HAVE_IP_MULTICAST_IF
#define HAVE_IP_MULTICAST_IF 0
#endif

#ifndef HAVE_IP_MULTICAST_LOOP
#define HAVE_IP_MULTICAST_LOOP 0
#endif

#ifndef HAVE_IP_MULTICAST_TTL
#define HAVE_IP_MULTICAST_TTL 0
#endif

#ifndef HAVE_IP_OPTIONS
#define HAVE_IP_OPTIONS 0
#endif

#ifndef HAVE_IP_PMTUAGE
#define HAVE_IP_PMTUAGE 0
#endif

#ifndef HAVE_IP_PORTRANGE
#define HAVE_IP_PORTRANGE 0
#endif

#ifndef HAVE_IP_RECVDSTADDR
#define HAVE_IP_RECVDSTADDR 0
#endif

#ifndef HAVE_IP_RECVIF
#define HAVE_IP_RECVIF 0
#endif

#ifndef HAVE_IP_RECVIFINFO
#define HAVE_IP_RECVIFINFO 0
#endif

#ifndef HAVE_IP_RECVINTERFACE
#define HAVE_IP_RECVINTERFACE 0
#endif

#ifndef HAVE_IP_RECVMACHDR
#define HAVE_IP_RECVMACHDR 0
#endif

#ifndef HAVE_IP_RECVTOS
#define HAVE_IP_RECVTOS 0
#endif

#ifndef HAVE_IP_RECVTTL
#define HAVE_IP_RECVTTL 0
#endif

#ifndef HAVE_IP_SOURCE_FILTER
#define HAVE_IP_SOURCE_FILTER 0
#endif

#ifndef HAVE_IP_TOS
#define HAVE_IP_TOS 0
#endif

#ifndef HAVE_IP_TRANSPARENT
#define HAVE_IP_TRANSPARENT 0
#endif

#ifndef HAVE_IP_TTL
#define HAVE_IP_TTL 0
#endif

#ifndef HAVE_IP_UNBLOCK_SOURCE
#define HAVE_IP_UNBLOCK_SOURCE 0
#endif

#ifndef HAVE_IP_UNICAST_HOPS
#define HAVE_IP_UNICAST_HOPS 0
#endif

#ifndef HAVE_ISSETUGID
#define HAVE_ISSETUGID 0
#endif

#ifndef HAVE_KERBEROSV5_COM_ERR_H
#define HAVE_KERBEROSV5_COM_ERR_H 0
#endif

#ifndef HAVE_KERBEROSV5_KRB5_H
#define HAVE_KERBEROSV5_KRB5_H 0
#endif

#ifndef HAVE_KRB5
#define HAVE_KRB5 0
#endif

#ifndef HAVE_KRB5_GET_ERROR_MESSAGE
#define HAVE_KRB5_GET_ERROR_MESSAGE 0
#endif

#ifndef HAVE_KRB5_GET_ERR_TEXT
#define HAVE_KRB5_GET_ERR_TEXT 0
#endif

#ifndef HAVE_KRB5_H
#define HAVE_KRB5_H 0
#endif

#ifndef HAVE_KRB5_KT_FREE_ENTRY
#define HAVE_KRB5_KT_FREE_ENTRY 0
#endif

#ifndef HAVE_KRB5_MEMORY_CACHE
#define HAVE_KRB5_MEMORY_CACHE 0
#endif

#ifndef HAVE_KRB5_MEMORY_KEYTAB
#define HAVE_KRB5_MEMORY_KEYTAB 0
#endif

#ifndef HAVE_KRB5_PAC
#define HAVE_KRB5_PAC 0
#endif

#ifndef HAVE_LBER_H
#define HAVE_LBER_H 0
#endif

#ifndef HAVE_LDAP
#define HAVE_LDAP 0
#endif

#ifndef HAVE_LDAPSSL_CLIENT_INIT
#define HAVE_LDAPSSL_CLIENT_INIT 0
#endif

#ifndef HAVE_LDAP_H
#define HAVE_LDAP_H 0
#endif

#ifndef HAVE_LDAP_REBINDPROC_CALLBACK
#define HAVE_LDAP_REBINDPROC_CALLBACK 0
#endif

#ifndef HAVE_LDAP_REBIND_FUNCTION
#define HAVE_LDAP_REBIND_FUNCTION 0
#endif

#ifndef HAVE_LDAP_REBIND_PROC
#define HAVE_LDAP_REBIND_PROC 0
#endif

#ifndef HAVE_LDAP_SCOPE_DEFAULT
#define HAVE_LDAP_SCOPE_DEFAULT 0
#endif

#ifndef HAVE_LDAP_URL_DESC2STR
#define HAVE_LDAP_URL_DESC2STR 0
#endif

#ifndef HAVE_LDAP_URL_LUD_SCHEME
#define HAVE_LDAP_URL_LUD_SCHEME 0
#endif

#ifndef HAVE_LDAP_URL_PARSE
#define HAVE_LDAP_URL_PARSE 0
#endif

#ifndef HAVE_LIBASN1
#define HAVE_LIBASN1 0
#endif

#ifndef HAVE_LIBCFAIL
#define HAVE_LIBCFAIL 0
#endif

#ifndef HAVE_LIBCOM_ERR
#define HAVE_LIBCOM_ERR 0
#endif

#ifndef HAVE_LIBCRYPT
#define HAVE_LIBCRYPT 0
#endif

#ifndef HAVE_LIBC_ENABLE_SECURE
#define HAVE_LIBC_ENABLE_SECURE 0
#endif

#ifndef HAVE_LIBC_ENABLE_SECURE_DISABLED
#define HAVE_LIBC_ENABLE_SECURE_DISABLED 0
#endif

#ifndef HAVE_LIBDES
#define HAVE_LIBDES 0
#endif

#ifndef HAVE_LIBDES425
#define HAVE_LIBDES425 0
#endif

#ifndef HAVE_LIBGSS
#define HAVE_LIBGSS 0
#endif

#ifndef HAVE_LIBGSSAPI
#define HAVE_LIBGSSAPI 0
#endif

#ifndef HAVE_LIBGSSAPI_KRB5
#define HAVE_LIBGSSAPI_KRB5 0
#endif

#ifndef HAVE_LIBK5CRYPTO
#define HAVE_LIBK5CRYPTO 0
#endif

#ifndef HAVE_LIBKRB5
#define HAVE_LIBKRB5 0
#endif

#ifndef HAVE_LIBKSVC
#define HAVE_LIBKSVC 0
#endif

#ifndef HAVE_LIBLBER
#define HAVE_LIBLBER 0
#endif

#ifndef HAVE_LIBLDAP
#define HAVE_LIBLDAP 0
#endif

#ifndef HAVE_LIBLDAP60
#define HAVE_LIBLDAP60 0
#endif

#ifndef HAVE_LIBMINIUPNP
#define HAVE_LIBMINIUPNP 0
#endif

#ifndef HAVE_LIBMINIUPNP13
#define HAVE_LIBMINIUPNP13 0
#endif

#ifndef HAVE_LIBMINIUPNP14
#define HAVE_LIBMINIUPNP14 0
#endif

#ifndef HAVE_LIBMINIUPNP17
#define HAVE_LIBMINIUPNP17 0
#endif

#ifndef HAVE_LIBMINIUPNP228
#define HAVE_LIBMINIUPNP228 0
#endif

#ifndef HAVE_LIBPRLDAP60
#define HAVE_LIBPRLDAP60 0
#endif

#ifndef HAVE_LIBPTHREAD
#define HAVE_LIBPTHREAD 0
#endif

#ifndef HAVE_LIBRESOLV
#define HAVE_LIBRESOLV 0
#endif

#ifndef HAVE_LIBROKEN
#define HAVE_LIBROKEN 0
#endif

#ifndef HAVE_LIBSASL2
#define HAVE_LIBSASL2 0
#endif

#ifndef HAVE_LIBSSLDAP60
#define HAVE_LIBSSLDAP60 0
#endif

#ifndef HAVE_LIMITS_H
#define HAVE_LIMITS_H 0
#endif

#ifndef HAVE_LINUX_BBKERNEL_H
#define HAVE_LINUX_BBKERNEL_H 0
#endif

#ifndef HAVE_LINUX_BUGS
#define HAVE_LINUX_BUGS 0
#endif

#ifndef HAVE_LINUX_GLIBC_WORKAROUND
#define HAVE_LINUX_GLIBC_WORKAROUND 0
#endif

#ifndef HAVE_MALLOC_H
#define HAVE_MALLOC_H 0
#endif

#ifndef HAVE_MALLOC_OPTIONS
#define HAVE_MALLOC_OPTIONS 0
#endif

#ifndef HAVE_MAX_HOSTIDS
#define HAVE_MAX_HOSTIDS 0
#endif

#ifndef HAVE_MEMMOVE
#define HAVE_MEMMOVE 0
#endif

#ifndef HAVE_MEMORY_H
#define HAVE_MEMORY_H 0
#endif

#ifndef HAVE_MODULE_BANDWIDTH
#define HAVE_MODULE_BANDWIDTH 0
#endif

#ifndef HAVE_MODULE_CHECKMODULE
#define HAVE_MODULE_CHECKMODULE 0
#endif

#ifndef HAVE_MODULE_CONVERT_SID
#define HAVE_MODULE_CONVERT_SID 0
#endif

#ifndef HAVE_MODULE_LDAP
#define HAVE_MODULE_LDAP 0
#endif

#ifndef HAVE_MODULE_PAC
#define HAVE_MODULE_PAC 0
#endif

#ifndef HAVE_MODULE_REDIRECT
#define HAVE_MODULE_REDIRECT 0
#endif

#ifndef HAVE_MONCONTROL
#define HAVE_MONCONTROL 0
#endif

#ifndef HAVE_MOZILLA_LDAP_SDK
#define HAVE_MOZILLA_LDAP_SDK 0
#endif

#ifndef HAVE_MOZLDAP_LDAP_H
#define HAVE_MOZLDAP_LDAP_H 0
#endif

#ifndef HAVE_MSG_WAITALL
#define HAVE_MSG_WAITALL 0
#endif

#ifndef HAVE_NETINET_IN_H
#define HAVE_NETINET_IN_H 0
#endif

#ifndef HAVE_NETINET_IP_H
#define HAVE_NETINET_IP_H 0
#endif

#ifndef HAVE_NETINET_IP_VAR_H
#define HAVE_NETINET_IP_VAR_H 0
#endif

#ifndef HAVE_NETINET_TCP_FSM_H
#define HAVE_NETINET_TCP_FSM_H 0
#endif

#ifndef HAVE_NET_IF_DL_H
#define HAVE_NET_IF_DL_H 0
#endif

#ifndef HAVE_NOMALLOC_REALLOC
#define HAVE_NOMALLOC_REALLOC 0
#endif

#ifndef HAVE_NONULL_FREE
#define HAVE_NONULL_FREE 0
#endif

#ifndef HAVE_NO_RESOLVESTUFF
#define HAVE_NO_RESOLVESTUFF 0
#endif

#ifndef HAVE_NO_SYMBOL_UNDERSCORE
#define HAVE_NO_SYMBOL_UNDERSCORE 0
#endif

#ifndef HAVE_OPENBSD_BUGS
#define HAVE_OPENBSD_BUGS 0
#endif

#ifndef HAVE_OPENLDAP
#define HAVE_OPENLDAP 0
#endif

#ifndef HAVE_OPENLOG_LOG_PERROR
#define HAVE_OPENLOG_LOG_PERROR 0
#endif

#ifndef HAVE_PAC
#define HAVE_PAC 0
#endif

#ifndef HAVE_PATHS_H
#define HAVE_PATHS_H 0
#endif

#ifndef HAVE_PIPEBUFFER_RECV_BASED
#define HAVE_PIPEBUFFER_RECV_BASED 0
#endif

#ifndef HAVE_PIPEBUFFER_SEND_BASED
#define HAVE_PIPEBUFFER_SEND_BASED 0
#endif

#ifndef HAVE_PIPEBUFFER_UNKNOWN
#define HAVE_PIPEBUFFER_UNKNOWN 0
#endif

#ifndef HAVE_PRAGMA_SUPPORT
#define HAVE_PRAGMA_SUPPORT 0
#endif

#ifndef HAVE_PRELOAD
#define HAVE_PRELOAD 0
#endif

#ifndef HAVE_PRIVILEGES
#define HAVE_PRIVILEGES 0
#endif

#ifndef HAVE_PRIV_H
#define HAVE_PRIV_H 0
#endif

#ifndef HAVE_PROCESSOR_BIND
#define HAVE_PROCESSOR_BIND 0
#endif

#ifndef HAVE_PROFILING
#define HAVE_PROFILING 0
#endif

#ifndef HAVE_PROGNAME
#define HAVE_PROGNAME 0
#endif

#ifndef HAVE_PROT_ACCEPT_0
#define HAVE_PROT_ACCEPT_0 0
#endif

#ifndef HAVE_PROT_ACCEPT_1
#define HAVE_PROT_ACCEPT_1 0
#endif

#ifndef HAVE_PROT_ACCEPT_2
#define HAVE_PROT_ACCEPT_2 0
#endif

#ifndef HAVE_PROT_ACCEPT_3
#define HAVE_PROT_ACCEPT_3 0
#endif

#ifndef HAVE_PROT_BIND_0
#define HAVE_PROT_BIND_0 0
#endif

#ifndef HAVE_PROT_BIND_1
#define HAVE_PROT_BIND_1 0
#endif

#ifndef HAVE_PROT_BIND_2
#define HAVE_PROT_BIND_2 0
#endif

#ifndef HAVE_PROT_BIND_3
#define HAVE_PROT_BIND_3 0
#endif

#ifndef HAVE_PROT_CONNECT_0
#define HAVE_PROT_CONNECT_0 0
#endif

#ifndef HAVE_PROT_CONNECT_1
#define HAVE_PROT_CONNECT_1 0
#endif

#ifndef HAVE_PROT_CONNECT_2
#define HAVE_PROT_CONNECT_2 0
#endif

#ifndef HAVE_PROT_CONNECT_3
#define HAVE_PROT_CONNECT_3 0
#endif

#ifndef HAVE_PROT_FCLOSE_0
#define HAVE_PROT_FCLOSE_0 0
#endif

#ifndef HAVE_PROT_FCLOSE_1
#define HAVE_PROT_FCLOSE_1 0
#endif

#ifndef HAVE_PROT_FFLUSH_0
#define HAVE_PROT_FFLUSH_0 0
#endif

#ifndef HAVE_PROT_FFLUSH_1
#define HAVE_PROT_FFLUSH_1 0
#endif

#ifndef HAVE_PROT_FGETC_0
#define HAVE_PROT_FGETC_0 0
#endif

#ifndef HAVE_PROT_FGETC_1
#define HAVE_PROT_FGETC_1 0
#endif

#ifndef HAVE_PROT_FGETS_0
#define HAVE_PROT_FGETS_0 0
#endif

#ifndef HAVE_PROT_FGETS_1
#define HAVE_PROT_FGETS_1 0
#endif

#ifndef HAVE_PROT_FGETS_2
#define HAVE_PROT_FGETS_2 0
#endif

#ifndef HAVE_PROT_FGETS_3
#define HAVE_PROT_FGETS_3 0
#endif

#ifndef HAVE_PROT_FPRINTF_0
#define HAVE_PROT_FPRINTF_0 0
#endif

#ifndef HAVE_PROT_FPRINTF_1
#define HAVE_PROT_FPRINTF_1 0
#endif

#ifndef HAVE_PROT_FPRINTF_2
#define HAVE_PROT_FPRINTF_2 0
#endif

#ifndef HAVE_PROT_FPRINTF_3
#define HAVE_PROT_FPRINTF_3 0
#endif

#ifndef HAVE_PROT_FPUTC_0
#define HAVE_PROT_FPUTC_0 0
#endif

#ifndef HAVE_PROT_FPUTC_1
#define HAVE_PROT_FPUTC_1 0
#endif

#ifndef HAVE_PROT_FPUTC_2
#define HAVE_PROT_FPUTC_2 0
#endif

#ifndef HAVE_PROT_FPUTS_0
#define HAVE_PROT_FPUTS_0 0
#endif

#ifndef HAVE_PROT_FPUTS_1
#define HAVE_PROT_FPUTS_1 0
#endif

#ifndef HAVE_PROT_FPUTS_2
#define HAVE_PROT_FPUTS_2 0
#endif

#ifndef HAVE_PROT_FREAD_0
#define HAVE_PROT_FREAD_0 0
#endif

#ifndef HAVE_PROT_FREAD_1
#define HAVE_PROT_FREAD_1 0
#endif

#ifndef HAVE_PROT_FREAD_2
#define HAVE_PROT_FREAD_2 0
#endif

#ifndef HAVE_PROT_FREAD_3
#define HAVE_PROT_FREAD_3 0
#endif

#ifndef HAVE_PROT_FREAD_4
#define HAVE_PROT_FREAD_4 0
#endif

#ifndef HAVE_PROT_FWRITE_0
#define HAVE_PROT_FWRITE_0 0
#endif

#ifndef HAVE_PROT_FWRITE_1
#define HAVE_PROT_FWRITE_1 0
#endif

#ifndef HAVE_PROT_FWRITE_2
#define HAVE_PROT_FWRITE_2 0
#endif

#ifndef HAVE_PROT_FWRITE_3
#define HAVE_PROT_FWRITE_3 0
#endif

#ifndef HAVE_PROT_FWRITE_4
#define HAVE_PROT_FWRITE_4 0
#endif

#ifndef HAVE_PROT_GETC_0
#define HAVE_PROT_GETC_0 0
#endif

#ifndef HAVE_PROT_GETC_1
#define HAVE_PROT_GETC_1 0
#endif

#ifndef HAVE_PROT_GETHOSTBYADDR_0
#define HAVE_PROT_GETHOSTBYADDR_0 0
#endif

#ifndef HAVE_PROT_GETHOSTBYADDR_1
#define HAVE_PROT_GETHOSTBYADDR_1 0
#endif

#ifndef HAVE_PROT_GETHOSTBYADDR_2
#define HAVE_PROT_GETHOSTBYADDR_2 0
#endif

#ifndef HAVE_PROT_GETHOSTBYADDR_3
#define HAVE_PROT_GETHOSTBYADDR_3 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_0
#define HAVE_PROT_GETNAMEINFO_0 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_1
#define HAVE_PROT_GETNAMEINFO_1 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_2
#define HAVE_PROT_GETNAMEINFO_2 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_3
#define HAVE_PROT_GETNAMEINFO_3 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_4
#define HAVE_PROT_GETNAMEINFO_4 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_5
#define HAVE_PROT_GETNAMEINFO_5 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_6
#define HAVE_PROT_GETNAMEINFO_6 0
#endif

#ifndef HAVE_PROT_GETNAMEINFO_7
#define HAVE_PROT_GETNAMEINFO_7 0
#endif

#ifndef HAVE_PROT_GETPEERNAME_0
#define HAVE_PROT_GETPEERNAME_0 0
#endif

#ifndef HAVE_PROT_GETPEERNAME_1
#define HAVE_PROT_GETPEERNAME_1 0
#endif

#ifndef HAVE_PROT_GETPEERNAME_2
#define HAVE_PROT_GETPEERNAME_2 0
#endif

#ifndef HAVE_PROT_GETPEERNAME_3
#define HAVE_PROT_GETPEERNAME_3 0
#endif

#ifndef HAVE_PROT_GETSOCKNAME_0
#define HAVE_PROT_GETSOCKNAME_0 0
#endif

#ifndef HAVE_PROT_GETSOCKNAME_1
#define HAVE_PROT_GETSOCKNAME_1 0
#endif

#ifndef HAVE_PROT_GETSOCKNAME_2
#define HAVE_PROT_GETSOCKNAME_2 0
#endif

#ifndef HAVE_PROT_GETSOCKNAME_3
#define HAVE_PROT_GETSOCKNAME_3 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_0
#define HAVE_PROT_GETSOCKOPT_0 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_1
#define HAVE_PROT_GETSOCKOPT_1 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_2
#define HAVE_PROT_GETSOCKOPT_2 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_3
#define HAVE_PROT_GETSOCKOPT_3 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_4
#define HAVE_PROT_GETSOCKOPT_4 0
#endif

#ifndef HAVE_PROT_GETSOCKOPT_5
#define HAVE_PROT_GETSOCKOPT_5 0
#endif

#ifndef HAVE_PROT_GETS_0
#define HAVE_PROT_GETS_0 0
#endif

#ifndef HAVE_PROT_GETS_1
#define HAVE_PROT_GETS_1 0
#endif

#ifndef HAVE_PROT_LISTEN_0
#define HAVE_PROT_LISTEN_0 0
#endif

#ifndef HAVE_PROT_LISTEN_1
#define HAVE_PROT_LISTEN_1 0
#endif

#ifndef HAVE_PROT_LISTEN_2
#define HAVE_PROT_LISTEN_2 0
#endif

#ifndef HAVE_PROT_PRINTF_0
#define HAVE_PROT_PRINTF_0 0
#endif

#ifndef HAVE_PROT_PRINTF_1
#define HAVE_PROT_PRINTF_1 0
#endif

#ifndef HAVE_PROT_PRINTF_2
#define HAVE_PROT_PRINTF_2 0
#endif

#ifndef HAVE_PROT_PUTC_0
#define HAVE_PROT_PUTC_0 0
#endif

#ifndef HAVE_PROT_PUTC_1
#define HAVE_PROT_PUTC_1 0
#endif

#ifndef HAVE_PROT_PUTC_2
#define HAVE_PROT_PUTC_2 0
#endif

#ifndef HAVE_PROT_PUTS_0
#define HAVE_PROT_PUTS_0 0
#endif

#ifndef HAVE_PROT_PUTS_1
#define HAVE_PROT_PUTS_1 0
#endif

#ifndef HAVE_PROT_READV_0
#define HAVE_PROT_READV_0 0
#endif

#ifndef HAVE_PROT_READV_1
#define HAVE_PROT_READV_1 0
#endif

#ifndef HAVE_PROT_READV_2
#define HAVE_PROT_READV_2 0
#endif

#ifndef HAVE_PROT_READV_3
#define HAVE_PROT_READV_3 0
#endif

#ifndef HAVE_PROT_READ_0
#define HAVE_PROT_READ_0 0
#endif

#ifndef HAVE_PROT_READ_1
#define HAVE_PROT_READ_1 0
#endif

#ifndef HAVE_PROT_READ_2
#define HAVE_PROT_READ_2 0
#endif

#ifndef HAVE_PROT_READ_3
#define HAVE_PROT_READ_3 0
#endif

#ifndef HAVE_PROT_RECVFROM_0
#define HAVE_PROT_RECVFROM_0 0
#endif

#ifndef HAVE_PROT_RECVFROM_1
#define HAVE_PROT_RECVFROM_1 0
#endif

#ifndef HAVE_PROT_RECVFROM_2
#define HAVE_PROT_RECVFROM_2 0
#endif

#ifndef HAVE_PROT_RECVFROM_3
#define HAVE_PROT_RECVFROM_3 0
#endif

#ifndef HAVE_PROT_RECVFROM_4
#define HAVE_PROT_RECVFROM_4 0
#endif

#ifndef HAVE_PROT_RECVFROM_5
#define HAVE_PROT_RECVFROM_5 0
#endif

#ifndef HAVE_PROT_RECVFROM_6
#define HAVE_PROT_RECVFROM_6 0
#endif

#ifndef HAVE_PROT_RECVMSG_0
#define HAVE_PROT_RECVMSG_0 0
#endif

#ifndef HAVE_PROT_RECVMSG_1
#define HAVE_PROT_RECVMSG_1 0
#endif

#ifndef HAVE_PROT_RECVMSG_2
#define HAVE_PROT_RECVMSG_2 0
#endif

#ifndef HAVE_PROT_RECVMSG_3
#define HAVE_PROT_RECVMSG_3 0
#endif

#ifndef HAVE_PROT_RECV_0
#define HAVE_PROT_RECV_0 0
#endif

#ifndef HAVE_PROT_RECV_1
#define HAVE_PROT_RECV_1 0
#endif

#ifndef HAVE_PROT_RECV_2
#define HAVE_PROT_RECV_2 0
#endif

#ifndef HAVE_PROT_RECV_3
#define HAVE_PROT_RECV_3 0
#endif

#ifndef HAVE_PROT_RECV_4
#define HAVE_PROT_RECV_4 0
#endif

#ifndef HAVE_PROT_SENDMSG_0
#define HAVE_PROT_SENDMSG_0 0
#endif

#ifndef HAVE_PROT_SENDMSG_1
#define HAVE_PROT_SENDMSG_1 0
#endif

#ifndef HAVE_PROT_SENDMSG_2
#define HAVE_PROT_SENDMSG_2 0
#endif

#ifndef HAVE_PROT_SENDMSG_3
#define HAVE_PROT_SENDMSG_3 0
#endif

#ifndef HAVE_PROT_SENDTO_0
#define HAVE_PROT_SENDTO_0 0
#endif

#ifndef HAVE_PROT_SENDTO_1
#define HAVE_PROT_SENDTO_1 0
#endif

#ifndef HAVE_PROT_SENDTO_2
#define HAVE_PROT_SENDTO_2 0
#endif

#ifndef HAVE_PROT_SENDTO_3
#define HAVE_PROT_SENDTO_3 0
#endif

#ifndef HAVE_PROT_SENDTO_4
#define HAVE_PROT_SENDTO_4 0
#endif

#ifndef HAVE_PROT_SENDTO_5
#define HAVE_PROT_SENDTO_5 0
#endif

#ifndef HAVE_PROT_SENDTO_6
#define HAVE_PROT_SENDTO_6 0
#endif

#ifndef HAVE_PROT_SEND_0
#define HAVE_PROT_SEND_0 0
#endif

#ifndef HAVE_PROT_SEND_1
#define HAVE_PROT_SEND_1 0
#endif

#ifndef HAVE_PROT_SEND_2
#define HAVE_PROT_SEND_2 0
#endif

#ifndef HAVE_PROT_SEND_3
#define HAVE_PROT_SEND_3 0
#endif

#ifndef HAVE_PROT_SEND_4
#define HAVE_PROT_SEND_4 0
#endif

#ifndef HAVE_PROT_VFPRINTF_0
#define HAVE_PROT_VFPRINTF_0 0
#endif

#ifndef HAVE_PROT_VFPRINTF_1
#define HAVE_PROT_VFPRINTF_1 0
#endif

#ifndef HAVE_PROT_VFPRINTF_2
#define HAVE_PROT_VFPRINTF_2 0
#endif

#ifndef HAVE_PROT_VFPRINTF_3
#define HAVE_PROT_VFPRINTF_3 0
#endif

#ifndef HAVE_PROT_VPRINTF_0
#define HAVE_PROT_VPRINTF_0 0
#endif

#ifndef HAVE_PROT_VPRINTF_1
#define HAVE_PROT_VPRINTF_1 0
#endif

#ifndef HAVE_PROT_VPRINTF_2
#define HAVE_PROT_VPRINTF_2 0
#endif

#ifndef HAVE_PROT_WRITEV_0
#define HAVE_PROT_WRITEV_0 0
#endif

#ifndef HAVE_PROT_WRITEV_1
#define HAVE_PROT_WRITEV_1 0
#endif

#ifndef HAVE_PROT_WRITEV_2
#define HAVE_PROT_WRITEV_2 0
#endif

#ifndef HAVE_PROT_WRITEV_3
#define HAVE_PROT_WRITEV_3 0
#endif

#ifndef HAVE_PROT_WRITE_0
#define HAVE_PROT_WRITE_0 0
#endif

#ifndef HAVE_PROT_WRITE_1
#define HAVE_PROT_WRITE_1 0
#endif

#ifndef HAVE_PROT_WRITE_2
#define HAVE_PROT_WRITE_2 0
#endif

#ifndef HAVE_PROT_WRITE_3
#define HAVE_PROT_WRITE_3 0
#endif

#ifndef HAVE_PROT__IO_GETC_0
#define HAVE_PROT__IO_GETC_0 0
#endif

#ifndef HAVE_PROT__IO_GETC_1
#define HAVE_PROT__IO_GETC_1 0
#endif

#ifndef HAVE_PROT__IO_PUTC_0
#define HAVE_PROT__IO_PUTC_0 0
#endif

#ifndef HAVE_PROT__IO_PUTC_1
#define HAVE_PROT__IO_PUTC_1 0
#endif

#ifndef HAVE_PROT__IO_PUTC_2
#define HAVE_PROT__IO_PUTC_2 0
#endif

#ifndef HAVE_PROT__READ_CHK_0
#define HAVE_PROT__READ_CHK_0 0
#endif

#ifndef HAVE_PROT__READ_CHK_1
#define HAVE_PROT__READ_CHK_1 0
#endif

#ifndef HAVE_PROT__READ_CHK_2
#define HAVE_PROT__READ_CHK_2 0
#endif

#ifndef HAVE_PROT__READ_CHK_3
#define HAVE_PROT__READ_CHK_3 0
#endif

#ifndef HAVE_PROT__READ_CHK_4
#define HAVE_PROT__READ_CHK_4 0
#endif

#ifndef HAVE_PSELECT
#define HAVE_PSELECT 0
#endif

#ifndef HAVE_PTHREAD_H
#define HAVE_PTHREAD_H 0
#endif

#ifndef HAVE_RECVBUF_IOCTL
#define HAVE_RECVBUF_IOCTL 0
#endif

#ifndef HAVE_RESOLV_H
#define HAVE_RESOLV_H 0
#endif

#ifndef HAVE_ROUTEINFO_BSD
#define HAVE_ROUTEINFO_BSD 0
#endif

#ifndef HAVE_ROUTEINFO_LINUX
#define HAVE_ROUTEINFO_LINUX 0
#endif

#ifndef HAVE_ROUTE_SOURCE
#define HAVE_ROUTE_SOURCE 0
#endif

#ifndef HAVE_RPC_RPC_H
#define HAVE_RPC_RPC_H 0
#endif

#ifndef HAVE_RRESVPORT
#define HAVE_RRESVPORT 0
#endif

#ifndef HAVE_RTLD_NEXT
#define HAVE_RTLD_NEXT 0
#endif

#ifndef HAVE_SASL
#define HAVE_SASL 0
#endif

#ifndef HAVE_SASL_DARWIN
#define HAVE_SASL_DARWIN 0
#endif

#ifndef HAVE_SASL_H
#define HAVE_SASL_H 0
#endif

#ifndef HAVE_SASL_SASL_H
#define HAVE_SASL_SASL_H 0
#endif

#ifndef HAVE_SCHED_H
#define HAVE_SCHED_H 0
#endif

#ifndef HAVE_SCHED_SETAFFINITY
#define HAVE_SCHED_SETAFFINITY 0
#endif

#ifndef HAVE_SCHED_SETSCHEDULER
#define HAVE_SCHED_SETSCHEDULER 0
#endif

#ifndef HAVE_SECURITY_PAM_APPL_H
#define HAVE_SECURITY_PAM_APPL_H 0
#endif

#ifndef HAVE_SELECT_MAXTIMEOUT
#define HAVE_SELECT_MAXTIMEOUT 0
#endif

#ifndef HAVE_SENDBUF_IOCTL
#define HAVE_SENDBUF_IOCTL 0
#endif

#ifndef HAVE_SENDMSG_DEADLOCK
#define HAVE_SENDMSG_DEADLOCK 0
#endif

#ifndef HAVE_SETEGID
#define HAVE_SETEGID 0
#endif

#ifndef HAVE_SETEUID
#define HAVE_SETEUID 0
#endif

#ifndef HAVE_SETPROCTITLE
#define HAVE_SETPROCTITLE 0
#endif

#ifndef HAVE_SHADOW_H
#define HAVE_SHADOW_H 0
#endif

#ifndef HAVE_SIGNAL_SIGINFO
#define HAVE_SIGNAL_SIGINFO 0
#endif

#ifndef HAVE_SIG_ATOMIC_T
#define HAVE_SIG_ATOMIC_T 0
#endif

#ifndef HAVE_SIOCGIFHWADDR
#define HAVE_SIOCGIFHWADDR 0
#endif

#ifndef HAVE_SOCKADDR_SA_LEN
#define HAVE_SOCKADDR_SA_LEN 0
#endif

#ifndef HAVE_SOCKADDR_STORAGE_SS_LEN
#define HAVE_SOCKADDR_STORAGE_SS_LEN 0
#endif

#ifndef HAVE_SOCKATMARK
#define HAVE_SOCKATMARK 0
#endif

#ifndef HAVE_SOCKOPTVALSYM_MAX
#define HAVE_SOCKOPTVALSYM_MAX 0
#endif

#ifndef HAVE_SOCKOPTVAL_MAX
#define HAVE_SOCKOPTVAL_MAX 0
#endif

#ifndef HAVE_SOLARIS_BUGS
#define HAVE_SOLARIS_BUGS 0
#endif

#ifndef HAVE_SOLARIS_PRIVS
#define HAVE_SOLARIS_PRIVS 0
#endif

#ifndef HAVE_SO_ACCEPTCONN
#define HAVE_SO_ACCEPTCONN 0
#endif

#ifndef HAVE_SO_AUDIT
#define HAVE_SO_AUDIT 0
#endif

#ifndef HAVE_SO_BINDANY
#define HAVE_SO_BINDANY 0
#endif

#ifndef HAVE_SO_BROADCAST
#define HAVE_SO_BROADCAST 0
#endif

#ifndef HAVE_SO_CKSUMRECV
#define HAVE_SO_CKSUMRECV 0
#endif

#ifndef HAVE_SO_DEBUG
#define HAVE_SO_DEBUG 0
#endif

#ifndef HAVE_SO_DONTROUTE
#define HAVE_SO_DONTROUTE 0
#endif

#ifndef HAVE_SO_ERROR
#define HAVE_SO_ERROR 0
#endif

#ifndef HAVE_SO_JUMBO
#define HAVE_SO_JUMBO 0
#endif

#ifndef HAVE_SO_KEEPALIVE
#define HAVE_SO_KEEPALIVE 0
#endif

#ifndef HAVE_SO_KERNACCEPT
#define HAVE_SO_KERNACCEPT 0
#endif

#ifndef HAVE_SO_LINGER
#define HAVE_SO_LINGER 0
#endif

#ifndef HAVE_SO_NOMULTIPATH
#define HAVE_SO_NOMULTIPATH 0
#endif

#ifndef HAVE_SO_NOREUSEADDR
#define HAVE_SO_NOREUSEADDR 0
#endif

#ifndef HAVE_SO_OOBINLINE
#define HAVE_SO_OOBINLINE 0
#endif

#ifndef HAVE_SO_PEERID
#define HAVE_SO_PEERID 0
#endif

#ifndef HAVE_SO_PRIORITY
#define HAVE_SO_PRIORITY 0
#endif

#ifndef HAVE_SO_RCVBUF
#define HAVE_SO_RCVBUF 0
#endif

#ifndef HAVE_SO_RCVBUFFORCE
#define HAVE_SO_RCVBUFFORCE 0
#endif

#ifndef HAVE_SO_RCVLOWAT
#define HAVE_SO_RCVLOWAT 0
#endif

#ifndef HAVE_SO_RCVTIMEO
#define HAVE_SO_RCVTIMEO 0
#endif

#ifndef HAVE_SO_REUSEADDR
#define HAVE_SO_REUSEADDR 0
#endif

#ifndef HAVE_SO_REUSEPORT
#define HAVE_SO_REUSEPORT 0
#endif

#ifndef HAVE_SO_SNDBUF
#define HAVE_SO_SNDBUF 0
#endif

#ifndef HAVE_SO_SNDBUFFORCE
#define HAVE_SO_SNDBUFFORCE 0
#endif

#ifndef HAVE_SO_SNDLOWAT
#define HAVE_SO_SNDLOWAT 0
#endif

#ifndef HAVE_SO_SNDTIMEO
#define HAVE_SO_SNDTIMEO 0
#endif

#ifndef HAVE_SO_TIMESTAMP
#define HAVE_SO_TIMESTAMP 0
#endif

#ifndef HAVE_SO_TYPE
#define HAVE_SO_TYPE 0
#endif

#ifndef HAVE_SO_USELOOPBACK
#define HAVE_SO_USELOOPBACK 0
#endif

#ifndef HAVE_SO_USE_IFBUFS
#define HAVE_SO_USE_IFBUFS 0
#endif

#ifndef HAVE_STDDEF_H
#define HAVE_STDDEF_H 0
#endif

#ifndef HAVE_STDINT_H
#define HAVE_STDINT_H 0
#endif

#ifndef HAVE_STDLIB_H
#define HAVE_STDLIB_H 0
#endif

#ifndef HAVE_STRFTIME
#define HAVE_STRFTIME 0
#endif

#ifndef HAVE_STRINGS_H
#define HAVE_STRINGS_H 0
#endif

#ifndef HAVE_STRING_H
#define HAVE_STRING_H 0
#endif

#ifndef HAVE_STRLCPY
#define HAVE_STRLCPY 0
#endif

#ifndef HAVE_STRUCT_IPOPTS
#define HAVE_STRUCT_IPOPTS 0
#endif

#ifndef HAVE_STRVIS
#define HAVE_STRVIS 0
#endif

#ifndef HAVE_SUN_LDAP_SDK
#define HAVE_SUN_LDAP_SDK 0
#endif

#ifndef HAVE_SYSLOG_H
#define HAVE_SYSLOG_H 0
#endif

#ifndef HAVE_SYSTEM_XMSG_MAGIC
#define HAVE_SYSTEM_XMSG_MAGIC 0
#endif

#ifndef HAVE_SYS_FILE_H
#define HAVE_SYS_FILE_H 0
#endif

#ifndef HAVE_SYS_IOCTL_H
#define HAVE_SYS_IOCTL_H 0
#endif

#ifndef HAVE_SYS_IPC_H
#define HAVE_SYS_IPC_H 0
#endif

#ifndef HAVE_SYS_PSTAT_H
#define HAVE_SYS_PSTAT_H 0
#endif

#ifndef HAVE_SYS_SELECT_H
#define HAVE_SYS_SELECT_H 0
#endif

#ifndef HAVE_SYS_SEM_H
#define HAVE_SYS_SEM_H 0
#endif

#ifndef HAVE_SYS_SHM_H
#define HAVE_SYS_SHM_H 0
#endif

#ifndef HAVE_SYS_SOCKIO_H
#define HAVE_SYS_SOCKIO_H 0
#endif

#ifndef HAVE_SYS_STAT_H
#define HAVE_SYS_STAT_H 0
#endif

#ifndef HAVE_SYS_TIME_H
#define HAVE_SYS_TIME_H 0
#endif

#ifndef HAVE_SYS_TYPES_H
#define HAVE_SYS_TYPES_H 0
#endif

#ifndef HAVE_SYS_WAIT_H
#define HAVE_SYS_WAIT_H 0
#endif

#ifndef HAVE_TCPD_H
#define HAVE_TCPD_H 0
#endif

#ifndef HAVE_TCP_CORK
#define HAVE_TCP_CORK 0
#endif

#ifndef HAVE_TCP_CWND
#define HAVE_TCP_CWND 0
#endif

#ifndef HAVE_TCP_CWND_DF
#define HAVE_TCP_CWND_DF 0
#endif

#ifndef HAVE_TCP_CWND_IF
#define HAVE_TCP_CWND_IF 0
#endif

#ifndef HAVE_TCP_EXP1
#define HAVE_TCP_EXP1 0
#endif

#ifndef HAVE_TCP_INFO
#define HAVE_TCP_INFO 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_ADVMSS
#define HAVE_TCP_INFO_TCPI_ADVMSS 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_ATO
#define HAVE_TCP_INFO_TCPI_ATO 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_BACKOFF
#define HAVE_TCP_INFO_TCPI_BACKOFF 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_CA_STATE
#define HAVE_TCP_INFO_TCPI_CA_STATE 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_FACKETS
#define HAVE_TCP_INFO_TCPI_FACKETS 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_LAST_ACK_RECV
#define HAVE_TCP_INFO_TCPI_LAST_ACK_RECV 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_LAST_ACK_SENT
#define HAVE_TCP_INFO_TCPI_LAST_ACK_SENT 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_LAST_DATA_RECV
#define HAVE_TCP_INFO_TCPI_LAST_DATA_RECV 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_LAST_DATA_SENT
#define HAVE_TCP_INFO_TCPI_LAST_DATA_SENT 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_LOST
#define HAVE_TCP_INFO_TCPI_LOST 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_PMTU
#define HAVE_TCP_INFO_TCPI_PMTU 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_PROBES
#define HAVE_TCP_INFO_TCPI_PROBES 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_RCV_RTT
#define HAVE_TCP_INFO_TCPI_RCV_RTT 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_RCV_SPACE
#define HAVE_TCP_INFO_TCPI_RCV_SPACE 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_RCV_SSTHRESH
#define HAVE_TCP_INFO_TCPI_RCV_SSTHRESH 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_REORDERING
#define HAVE_TCP_INFO_TCPI_REORDERING 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_RETRANS
#define HAVE_TCP_INFO_TCPI_RETRANS 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_RETRANSMITS
#define HAVE_TCP_INFO_TCPI_RETRANSMITS 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_SACKED
#define HAVE_TCP_INFO_TCPI_SACKED 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_TOTAL_RETRANS
#define HAVE_TCP_INFO_TCPI_TOTAL_RETRANS 0
#endif

#ifndef HAVE_TCP_INFO_TCPI_UNACKED
#define HAVE_TCP_INFO_TCPI_UNACKED 0
#endif

#ifndef HAVE_TCP_INIT_CWND
#define HAVE_TCP_INIT_CWND 0
#endif

#ifndef HAVE_TCP_IPA
#define HAVE_TCP_IPA 0
#endif

#ifndef HAVE_TCP_KEEPCNT
#define HAVE_TCP_KEEPCNT 0
#endif

#ifndef HAVE_TCP_KEEPIDLE
#define HAVE_TCP_KEEPIDLE 0
#endif

#ifndef HAVE_TCP_KEEPINTVL
#define HAVE_TCP_KEEPINTVL 0
#endif

#ifndef HAVE_TCP_LINGER2
#define HAVE_TCP_LINGER2 0
#endif

#ifndef HAVE_TCP_MAXRT
#define HAVE_TCP_MAXRT 0
#endif

#ifndef HAVE_TCP_MAXSEG
#define HAVE_TCP_MAXSEG 0
#endif

#ifndef HAVE_TCP_MD5SIG
#define HAVE_TCP_MD5SIG 0
#endif

#ifndef HAVE_TCP_NODELAY
#define HAVE_TCP_NODELAY 0
#endif

#ifndef HAVE_TCP_NODELAYACK
#define HAVE_TCP_NODELAYACK 0
#endif

#ifndef HAVE_TCP_NOOPT
#define HAVE_TCP_NOOPT 0
#endif

#ifndef HAVE_TCP_NOPUSH
#define HAVE_TCP_NOPUSH 0
#endif

#ifndef HAVE_TCP_NOREDUCE_CWND_EXIT_FRXMT
#define HAVE_TCP_NOREDUCE_CWND_EXIT_FRXMT 0
#endif

#ifndef HAVE_TCP_NOREDUCE_CWND_IN_FRXMT
#define HAVE_TCP_NOREDUCE_CWND_IN_FRXMT 0
#endif

#ifndef HAVE_TCP_NOTENTER_SSTART
#define HAVE_TCP_NOTENTER_SSTART 0
#endif

#ifndef HAVE_TCP_RFC1323
#define HAVE_TCP_RFC1323 0
#endif

#ifndef HAVE_TCP_SACK_ENABLE
#define HAVE_TCP_SACK_ENABLE 0
#endif

#ifndef HAVE_TCP_STDURG
#define HAVE_TCP_STDURG 0
#endif

#ifndef HAVE_TCP_SYNCNT
#define HAVE_TCP_SYNCNT 0
#endif

#ifndef HAVE_TCP_WINDOW_CLAMP
#define HAVE_TCP_WINDOW_CLAMP 0
#endif

#ifndef HAVE_THREADS_EINTR_PROBLEMS
#define HAVE_THREADS_EINTR_PROBLEMS 0
#endif

#ifndef HAVE_TIMER_MACROS
#define HAVE_TIMER_MACROS 0
#endif

#ifndef HAVE_UDP_CORK
#define HAVE_UDP_CORK 0
#endif

#ifndef HAVE_UINT16_T
#define HAVE_UINT16_T 0
#endif

#ifndef HAVE_UINT32_T
#define HAVE_UINT32_T 0
#endif

#ifndef HAVE_UINT8_T
#define HAVE_UINT8_T 0
#endif

#ifndef HAVE_UNIFIED_BUFFERCACHE
#define HAVE_UNIFIED_BUFFERCACHE 0
#endif

#ifndef HAVE_UNISTD_H
#define HAVE_UNISTD_H 0
#endif

#ifndef HAVE_UTIME_H
#define HAVE_UTIME_H 0
#endif

#ifndef HAVE_UTIME_NULL
#define HAVE_UTIME_NULL 0
#endif

#ifndef HAVE_VALGRIND_VALGRIND_H
#define HAVE_VALGRIND_VALGRIND_H 0
#endif

#ifndef HAVE_VOLATILE_SIG_ATOMIC_T
#define HAVE_VOLATILE_SIG_ATOMIC_T 0
#endif

#ifndef HAVE_VPRINTF
#define HAVE_VPRINTF 0
#endif

#ifndef HAVE_VSYSLOG
#define HAVE_VSYSLOG 0
#endif

#ifndef HAVE_WORKING_GETPWNAM
#define HAVE_WORKING_GETPWNAM 0
#endif

#ifndef HAVE__IO_GETC
#define HAVE__IO_GETC 0
#endif

#ifndef HAVE__IO_PUTC
#define HAVE__IO_PUTC 0
#endif

#ifndef HAVE___FPRINTF_CHK
#define HAVE___FPRINTF_CHK 0
#endif

#ifndef HAVE___READ_CHK
#define HAVE___READ_CHK 0
#endif

#ifndef HAVE___VFPRINTF_CHK
#define HAVE___VFPRINTF_CHK 0
#endif

#ifndef NEED_AF_LOCAL
#define NEED_AF_LOCAL 0
#endif

#ifndef NEED_EXIT_FAILURE
#define NEED_EXIT_FAILURE 0
#endif

#ifndef NEED_GETSOCKOPT_CAST
#define NEED_GETSOCKOPT_CAST 0
#endif

#ifndef NEED_SA_RESTART
#define NEED_SA_RESTART 0
#endif

#ifndef NEED_SYS_SOCKIO_H
#define NEED_SYS_SOCKIO_H 0
#endif

#ifndef SOCKS_DIRECTROUTE_FALLBACK
#define SOCKS_DIRECTROUTE_FALLBACK 0
#endif
