#include "third_party/include/ndpi_sha1.h"
#include "third_party/include/ndpi_sha256.h"

#include "third_party/src/ndpi_md5.c"
#include "third_party/src/ndpi_sha1.c"
#include "third_party/src/ndpi_sha256.c"
#include "third_party/src/ahocorasick.c"
#include "third_party/src/libcache.c"
#include "third_party/src/ndpi_patricia.c"
#include "third_party/src/gcrypt_light.c"
#include "third_party/src/btlib.c"
#include "third_party/src/hll/MurmurHash3.c"

#undef NDPI_CURRENT_PROTO
#include "protocols/afp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ajp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/amazon_video.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/among_us.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/amqp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/apple_push.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/armagetron.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/avast_securedns.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bgp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bittorrent.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bjnp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/capwap.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/cassandra.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/checkmk.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ciscovpn.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/citrix.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/coap.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/collectd.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/corba.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/cpha.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/crossfire.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dcerpc.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dhcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dhcpv6.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/diameter.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dnp3.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dns.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dnscrypt.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dofus.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/drda.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dropbox.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/eaq.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/edonkey.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ethernet_ip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/fix.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ftp_control.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ftp_data.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/genshin_impact.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/git.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/gnutella.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/gtp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/guildwars.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/h323.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/halflife2_and_mods.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/thrift.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hpvirtgrp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hsrp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/http.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/i3d.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/iax.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/icecast.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/iec60870-5-104.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/imo.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ipp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ipsec.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/irc.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/jabber.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/kakaotalk_voice.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/kerberos.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ldap.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/lisp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/lotus_notes.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mail_imap.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mail_pop.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mail_smtp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/maplestory.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/megaco.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/memcached.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mgcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mining.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/modbus.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mongodb.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mpegdash.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mpegts.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mqtt.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mssql_tds.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mysql.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nats.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nest_log_sink.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/netbios.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/netflow.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nfs.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nintendo.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/noe.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/non_tcp_udp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ntp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ookla.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/openvpn.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/oracle.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/postgres.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/pptp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/qq.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/quic.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/raknet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rdp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/riotgames.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rsh.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rsync.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rtmp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rtp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rtsp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rx.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/s7comm.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/sd_rtn.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/sflow.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/sip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/skinny.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/smb.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/smpp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/snmp_proto.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/soap.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/socks45.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/someip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/spotify.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ssdp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ssh.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/starcraft.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/steam.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/stun.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/syslog.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tcp_udp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/teamspeak.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/teamviewer.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/telegram.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/telnet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/teredo.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tftp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/threema.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tinc.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tls.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tocaboca.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ubntac2.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ultrasurf.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/usenet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/vhua.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/viber.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/vmware.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/vnc.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/vxlan.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/warcraft3.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/websocket.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/whatsapp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/whoisdas.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/wireguard.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/world_of_kung_fu.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/world_of_warcraft.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/wsd.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/xbox.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/xdmcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/xiaomi.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/z3950.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/zabbix.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/zattoo.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/zeromq.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/discord.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/avast.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/alicloud.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/activision.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/crynet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/fastcgi.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/kismet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/line.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/munin.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/natpmp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/softether.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/syncthing.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tivoconnect.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tplink_shp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/elastic_search.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tailscale.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tuya_lp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/merakicloud.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bacnet.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hots.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/oicq.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/source_engine.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bitcoin.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/epicgames.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/slp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/haproxy.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hislip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/beckhoff_ads.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/can.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ethereum.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ethersbus.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ethersio.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/fins.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hart-ip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ieee-c37118.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/iso9506-1-mms.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/monero.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/opc-ua.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/profinet_io.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/protobuf.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ptpv2.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rmcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/rtps.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/http2.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ceph.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/cip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/gaijin_entertainment.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/gearman.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/hl7.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/iec62056.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/json-rpc.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/kafka.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/kcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/mumble.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nomachine.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/openflow.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/radmin.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/raft.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/resp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/roughtime.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/steam_datagram_relay.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/stomp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/tencent_games.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/uftp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/yojimbo.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/zoom.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/flute.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/pfcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/c1222.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/lol_wild_rift.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/path_of_exile.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/dlep.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bfd.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/netease_games.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/bfcp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/cod_mobile.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/egd.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/iqiyi.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/knxnet_ip.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ldp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/teso.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/zug.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/radius_proto.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/cloudflare_warp.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/jrmi.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/nano.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/openwire.c"
#undef NDPI_CURRENT_PROTO
#include "protocols/ripe_atlas.c"
#undef NDPI_CURRENT_PROTO
