# Copyright (c) 2022 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

#IMPORTANT NOTE:
# 1. Duplicate entries for same board name should not be added. Please modify only the values and not add new lines for same board
# 2. Do not add boardname search strings in comments. As the host script search patterns are for boardnames in the file and does not ignore comments
#############################################################################################################
### Miami RDPs
ap-mi01.1_enable_daemon_support=1
ap-mi01.1_enable_cold_boot_support=1
ap-mi01.1_enable_qdss_tracing=1

ap-mi01.1_qcn9224_pci1_enable_daemon_support=1
ap-mi01.1_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.1_qcn9224_pci1_enable_qdss_tracing=1

#Old config
ap-mi01.2_enable_daemon_support=1
ap-mi01.2_enable_cold_boot_support=1
ap-mi01.2_enable_qdss_tracing=1

ap-mi01.2_qcn9224_pci0_enable_daemon_support=1
ap-mi01.2_qcn9224_pci0_enable_cold_boot_support=1
ap-mi01.2_qcn9224_pci0_enable_qdss_tracing=1

ap-mi01.2_qcn9224_pci1_enable_daemon_support=1
ap-mi01.2_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.2_qcn9224_pci1_enable_qdss_tracing=1

#New config for 13.0
ap-mi01.2-qcn9160-c1_enable_daemon_support=1
ap-mi01.2-qcn9160-c1_enable_cold_boot_support=1
ap-mi01.2-qcn9160-c1_enable_qdss_tracing=1
 
ap-mi01.2-qcn9160-c1_qcn9224_pci1_enable_daemon_support=1
ap-mi01.2-qcn9160-c1_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.2-qcn9160-c1_qcn9224_pci1_enable_qdss_tracing=1
 
ap-mi01.2-qcn9160-c1_pci0_enable_daemon_support=1
ap-mi01.2-qcn9160-c1_pci0_enable_cold_boot_support=1
ap-mi01.2-qcn9160-c1_pci0_enable_qdss_tracing=1

ap-mi01.4_enable_daemon_support=1
ap-mi01.4_enable_cold_boot_support=1
ap-mi01.4_enable_qdss_tracing=1

ap-mi01.4_qcn9224_pci1_enable_daemon_support=1
ap-mi01.4_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.4_qcn9224_pci1_enable_qdss_tracing=1

ap-mi01.6_enable_daemon_support=1
ap-mi01.6_enable_cold_boot_support=1
ap-mi01.6_enable_qdss_tracing=1

ap-mi01.6_qcn9224_pci1_enable_daemon_support=1
ap-mi01.6_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.6_qcn9224_pci1_enable_qdss_tracing=1

ap-mi01.2-qca81xx_enable_cold_boot_support=1
ap-mi01.2-qca81xx_enable_qdss_tracing=1
ap-mi01.2-qca81xx_qcn9224_pci0_enable_cold_boot_support=1
ap-mi01.2-qca81xx_qcn9224_pci0_enable_qdss_tracing=1
ap-mi01.2-qca81xx_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.2-qca81xx_qcn9224_pci1_enable_qdss_tracing=1

ap-mi01.2-qca81xx-i2c_enable_cold_boot_support=1
ap-mi01.2-qca81xx-i2c_enable_qdss_tracing=1
ap-mi01.2-qca81xx-i2c_qcn9224_pci0_enable_cold_boot_support=1
ap-mi01.2-qca81xx-i2c_qcn9224_pci0_enable_qdss_tracing=1
ap-mi01.2-qca81xx-i2c_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.2-qca81xx-i2c_qcn9224_pci1_enable_qdss_tracing=1

ipq5332-ap-mi01.2-qca81xx-i2c_enable_cold_boot_support=1
ipq5332-ap-mi01.2-qca81xx-i2c_enable_qdss_tracing=1
ipq5332-ap-mi01.2-qca81xx-i2c_qcn9224_pci0_enable_cold_boot_support=1
ipq5332-ap-mi01.2-qca81xx-i2c_qcn9224_pci0_enable_qdss_tracing=1
ipq5332-ap-mi01.2-qca81xx-i2c_qcn9224_pci1_enable_cold_boot_support=1
ipq5332-ap-mi01.2-qca81xx-i2c_qcn9224_pci1_enable_qdss_tracing=1

#Miami + pebble RDPs
ap-mi01.3_enable_daemon_support=1
ap-mi01.3_enable_cold_boot_support=1
ap-mi01.3_enable_qdss_tracing=1

ap-mi01.3_qcn6432_pci0_enable_daemon_support=1
ap-mi01.3_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.3_qcn6432_pci0_enable_qdss_tracing=1

ap-mi01.3_qcn6432_pci1_enable_daemon_support=1
ap-mi01.3_qcn6432_pci1_enable_cold_boot_support=1
ap-mi01.3_qcn6432_pci1_enable_qdss_tracing=1

ap-mi01.3-c5_enable_daemon_support=1
ap-mi01.3-c5_enable_cold_boot_support=1
ap-mi01.3-c5_enable_qdss_tracing=1
 
ap-mi01.3-c5_qcn6432_pci0_enable_daemon_support=1
ap-mi01.3-c5_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.3-c5_qcn6432_pci0_enable_qdss_tracing=1
 
ap-mi01.3-c5_qcn6432_pci1_enable_daemon_support=1
ap-mi01.3-c5_qcn6432_pci1_enable_cold_boot_support=1
ap-mi01.3-c5_qcn6432_pci1_enable_qdss_tracing=1

ap-mi04.1_enable_daemon_support=1
ap-mi04.1_enable_cold_boot_support=1
ap-mi04.1_enable_qdss_tracing=1

#Old config for backward compatibility
ap-mi04.1_qcn6432_pci0_enable_daemon_support=1
ap-mi04.1_qcn6432_pci0_enable_cold_boot_support=1
ap-mi04.1_qcn6432_pci0_enable_qdss_tracing=1

#New config for 13.0
ap-mi04.1_qcn6432_pci1_enable_daemon_support=1
ap-mi04.1_qcn6432_pci1_enable_cold_boot_support=1
ap-mi04.1_qcn6432_pci1_enable_qdss_tracing=1

ap-mi04.1_qcn6432_pci2_enable_daemon_support=1
ap-mi04.1_qcn6432_pci2_enable_cold_boot_support=1
ap-mi04.1_qcn6432_pci2_enable_qdss_tracing=1

ap-mi_default_enable_daemon_support=1
ap-mi_default_enable_cold_boot_support=1
ap-mi_default_enable_qdss_tracing=0

ap-mi01.9_enable_daemon_support=1
ap-mi01.9_enable_cold_boot_support=1
ap-mi01.9_enable_qdss_tracing=1

ap-mi01.9_qcn9224_pci0_enable_daemon_support=1
ap-mi01.9_qcn9224_pci0_enable_cold_boot_support=1
ap-mi01.9_qcn9224_pci0_enable_qdss_tracing=1

ap-mi01.9_qcn9224_pci1_enable_daemon_support=1
ap-mi01.9_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.9_qcn9224_pci1_enable_qdss_tracing=1

ap-mi01.3-c2_enable_daemon_support=1
ap-mi01.3-c2_enable_cold_boot_support=0
ap-mi01.3-c2_enable_qdss_tracing=1

ap-mi01.3-c2_qcn6432_pci0_enable_daemon_support=1
ap-mi01.3-c2_qcn6432_pci0_enable_cold_boot_support=0
ap-mi01.3-c2_qcn6432_pci0_enable_qdss_tracing=1

#RDP478
ap-mi04.1-c2_enable_daemon_support=1
ap-mi04.1-c2_enable_cold_boot_support=0
ap-mi04.1-c2_enable_qdss_tracing=1

#Old config for backward compatibility
ap-mi04.1-c2_qcn6432_pci0_enable_daemon_support=1
ap-mi04.1-c2_qcn6432_pci0_enable_cold_boot_support=0
ap-mi04.1-c2_qcn6432_pci0_enable_qdss_tracing=1

#New config for 13.0
ap-mi04.1-c2_qcn6432_pci1_enable_daemon_support=1
ap-mi04.1-c2_qcn6432_pci1_enable_cold_boot_support=0
ap-mi04.1-c2_qcn6432_pci1_enable_qdss_tracing=1

#RDP 486
ap-mi01.3-c3_enable_daemon_support=1
ap-mi01.3-c3_enable_cold_boot_support=1
ap-mi01.3-c3_enable_qdss_tracing=1

ap-mi01.3-c3_qcn6432_pci0_enable_daemon_support=1
ap-mi01.3-c3_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.3-c3_qcn6432_pci0_enable_qdss_tracing=1

#RDP483
ap-mi04.3_enable_daemon_support=1
ap-mi04.3_enable_cold_boot_support=0
ap-mi04.3_enable_qdss_tracing=1

#Old config for backward compatibility
ap-mi04.3_qcn6432_pci0_enable_daemon_support=1
ap-mi04.3_qcn6432_pci0_enable_cold_boot_support=0
ap-mi04.3_qcn6432_pci0_enable_qdss_tracing=1

#New config for 13.0
ap-mi04.3_qcn6432_pci1_enable_daemon_support=1
ap-mi04.3_qcn6432_pci1_enable_cold_boot_support=0
ap-mi04.3_qcn6432_pci1_enable_qdss_tracing=1

#RDP484
ap-mi01.2-c2_enable_daemon_support=1
ap-mi01.2-c2_enable_cold_boot_support=1
ap-mi01.2-c2_enable_qdss_tracing=1

ap-mi01.2-c2_qcn9224_pci0_enable_daemon_support=1
ap-mi01.2-c2_qcn9224_pci0_enable_cold_boot_support=1
ap-mi01.2-c2_qcn9224_pci0_enable_qdss_tracing=1

ap-mi01.2-c2_qcn9224_pci1_enable_daemon_support=1
ap-mi01.2-c2_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.2-c2_qcn9224_pci1_enable_qdss_tracing=1

#Miami + Waikki + Pebble RDPs
#RDP 479
ap-mi01.12_enable_daemon_support=1
ap-mi01.12_enable_cold_boot_support=1
ap-mi01.12_enable_qdss_tracing=1
 
ap-mi01.12_qcn6432_pci0_enable_daemon_support=1
ap-mi01.12_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.12_qcn6432_pci0_enable_qdss_tracing=1
 
ap-mi01.12_qcn9224_pci1_enable_daemon_support=1
ap-mi01.12_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.12_qcn9224_pci1_enable_qdss_tracing=1

#RDP 481
ap-mi01.14_enable_daemon_support=1
ap-mi01.14_enable_cold_boot_support=1
ap-mi01.14_enable_qdss_tracing=1
 
ap-mi01.14_qcn6432_pci0_enable_daemon_support=1
ap-mi01.14_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.14_qcn6432_pci0_enable_qdss_tracing=1
 
ap-mi01.14_qcn9224_pci1_enable_daemon_support=1
ap-mi01.14_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.14_qcn9224_pci1_enable_qdss_tracing=1

#Miami + Pebble + York + Waikiki
#MPPY RDP473
ap-mi01.7_enable_daemon_support=1
ap-mi01.7_enable_cold_boot_support=1
ap-mi01.7_enable_qdss_tracing=1

ap-mi01.7_qcn6432_pci0_enable_daemon_support=1
ap-mi01.7_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.7_qcn6432_pci0_enable_qdss_tracing=1

ap-mi01.7_qcn6432_pci1_enable_daemon_support=1
ap-mi01.7_qcn6432_pci1_enable_cold_boot_support=1
ap-mi01.7_qcn6432_pci1_enable_qdss_tracing=1

ap-mi01.7_qcn9160_pci2_enable_daemon_support=1
ap-mi01.7_qcn9160_pci2_enable_cold_boot_support=1
ap-mi01.7_qcn9160_pci2_enable_qdss_tracing=1

#MPWY RDP480
ap-mi01.13_enable_daemon_support=1
ap-mi01.13_enable_cold_boot_support=1
ap-mi01.13_enable_qdss_tracing=1

ap-mi01.13_qcn6432_pci0_enable_daemon_support=1
ap-mi01.13_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.13_qcn6432_pci0_enable_qdss_tracing=1

ap-mi01.13_qcn9224_pci1_enable_daemon_support=1
ap-mi01.13_qcn9224_pci1_enable_cold_boot_support=1
ap-mi01.13_qcn9224_pci1_enable_qdss_tracing=1

#Old config for backward compatibility
ap-mi01.13_qcn9160_pci1_enable_daemon_support=1
ap-mi01.13_qcn9160_pci1_enable_cold_boot_support=1
ap-mi01.13_qcn9160_pci1_enable_qdss_tracing=1

#New config for 13.0
ap-mi01.13_qcn9160_pci2_enable_daemon_support=1
ap-mi01.13_qcn9160_pci2_enable_cold_boot_support=1
ap-mi01.13_qcn9160_pci2_enable_qdss_tracing=1

#RDP 494
ap-mi04.5_enable_daemon_support=1
ap-mi04.5_enable_cold_boot_support=1
ap-mi04.5_enable_qdss_tracing=1

ap-mi04.5_qcn6432_pci1_enable_daemon_support=1
ap-mi04.5_qcn6432_pci1_enable_cold_boot_support=1
ap-mi04.5_qcn6432_pci1_enable_qdss_tracing=1

#RDP509
ap-mi01.3-c5_enable_daemon_support=1
ap-mi01.3-c5_enable_cold_boot_support=1
ap-mi01.3-c5_enable_qdss_tracing=1

ap-mi01.3-c5_qcn6432_pci0_enable_daemon_support=1
ap-mi01.3-c5_qcn6432_pci0_enable_cold_boot_support=1
ap-mi01.3-c5_qcn6432_pci0_enable_qdss_tracing=1

ap-mi01.3-c5_qcn6432_pci1_enable_daemon_support=1
ap-mi01.3-c5_qcn6432_pci1_enable_cold_boot_support=1
ap-mi01.3-c5_qcn6432_pci1_enable_qdss_tracing=1
