if(DEFINED RESOURCES_PROFILES_SUGAR_CMAKE_)
  return()
else()
  set(RESOURCES_PROFILES_SUGAR_CMAKE_ 1)
endif()

include(sugar_files)

sugar_files(
  RESOURCES_SOURCES
  "Android.xml"
  "Asus Transformer Prime TF201.xml"
  "Chrome.xml"
  "Chromecast.xml"
  "cloudsync.xml"
  "Firefox.xml"
  "Generic.xml"
  "HTML TV App.xml"
  "Internet Explorer.xml"
  "iOS-iPad-1,1.xml"
  "iOS-iPhone-1,1.xml"
  "iOS-iPhone-1,2.xml"
  "iOS-iPhone-2,1.xml"
  "iOS-iPhone-3,1.xml"
  "iOS-iPhone-3,2.xml"
  "iOS-iPhone-3,3.xml"
  "iOS-iPod-1,1.xml"
  "iOS-iPod-2,1.xml"
  "iOS-iPod-3,1.xml"
  "iOS-iPod-4,1.xml"
  "iOS.xml"
  "Konvergo.xml"
  "Microsoft Edge.xml"
  "Mystery 3.xml"
  "Mystery 4.xml"
  "Mystery 5.xml"
  "Opera TV App.xml"
  "Opera.xml"
  "Panasonic Viera 3D TV.xml"
  "PlayStation 3 App.xml"
  "PlayStation 3.xml"
  "PlayStation 4 App.xml"
  "Plexamp.xml"
  "Plex Home Theater-RaspberryPi.xml"
  "Plex Home Theater.xml"
  "Popcorn Hour.xml"
  "Roku-3.1.xml"
  "Roku-5.x.xml"
  "Roku-5000X-6.0.xml"
  "Roku-6.x.xml"
  "Roku-7.x.xml"
  "Roku.xml"
  "RokuDLNA-3.1.xml"
  "RokuDLNA-4400X-7.x.xml"
  "RokuDLNA-5.1.xml"
  "RokuDLNA-5000X-6.x.xml"
  "RokuDLNA-5000X-7.x.xml"
  "RokuDLNA-6.x.xml"
  "RokuDLNA-6000X-7.x.xml"
  "Safari.xml"
  "Samsung SmartTV.xml"
  "Samsung Tizen.xml"
  "Samsung.xml"
  "Sony Blu-ray 2013.xml"
  "Sony Blu-ray.xml"
  "Sony Bravia 2010.xml"
  "Sony Bravia 2011.xml"
  "Sony Bravia 2012.xml"
  "Sony Bravia 2013.xml"
  "Sony Streaming Player.xml"
  "tvOS.xml"
  "Universal Mobile.xml"
  "Universal Recording.xml"
  "Universal TV.xml"
  "Unknown Browser.xml"
  "Vivaldi.xml"
  "Web.xml"
  "Western Digital TV Live.xml"
  "Wii U.xml"
  "Windows 10 Desktop.xml"
  "Windows 10 Mobile.xml"
  "Windows Phone.xml"
  "Windows.xml"
  "Xbox 360.xml"
  "Xbox 360 App.xml"
  "Xbox One.xml"
  "ZP.xml"
)
