language: php

php:
    # We only specify one version so we only get one worker
    - 5.4

notifications:
    email: 
       on_failure: change

env:
    global:
      - MYSQL_TEST_HOST=127.0.0.1
      - MYSQL_TEST_USER=travis
      - PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=test"
      - PDO_MYSQL_TEST_USER=travis
      - PDO_MYSQL_TEST_PASS=
      - PDO_MYSQL_TEST_HOST=127.0.0.1
      - REPORT_EXIT_STATUS=1
    matrix:
      - ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1

before_script:
    # Compile PHP
    - ./travis/compile.sh
    # Setup Extensions 
    - . ./travis/ext/mysql/setup.sh
    - . ./travis/ext/mysqli/setup.sh
    - . ./travis/ext/pdo_mysql/setup.sh
    - . ./travis/ext/pgsql/setup.sh
    - . ./travis/ext/pdo_pgsql/setup.sh

# Run PHPs run-tests.php 
script: ./sapi/cli/php run-tests.php -p `pwd`/sapi/cli/php -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --show-diff --set-timeout 120
