svn add Zend/tests/bug65419.phpt
svn add Zend/tests/bug66609.phpt
svn add Zend/tests/bug67111.phpt
svn add Zend/tests/bug67314.phpt
svn add Zend/tests/bug68118.phpt
svn add Zend/tests/bug68370.phpt
svn add Zend/tests/bug68652.phpt
svn add Zend/tests/bug69017.phpt
svn add Zend/tests/bug69174.phpt
svn add Zend/tests/bug69212.phpt
svn add Zend/tests/bug69221.phpt
svn add Zend/tests/bug69221_2.phpt
svn add Zend/tests/bug69420.phpt
svn add Zend/tests/bug69467.phpt
svn add Zend/tests/generators/bug69419.phpt
svn add Zend/tests/traits/bug65576a.phpt
svn add Zend/tests/traits/bug65576b.phpt
svn add Zend/zend_ini_parser.c.orig
svn add Zend/zend_language_parser.c
svn add Zend/zend_language_parser.c.orig
svn add Zend/zend_language_scanner.c
svn add add.sh
svn add configure.orig
svn add ext/curl/tests/bug67643.phpt
svn add ext/curl/tests/bug69316.phpt
svn add ext/curl/tests/curl_multi_init_param.phpt
svn add ext/date/tests/68062.phpt
svn add ext/date/tests/bug45081.phpt
svn add ext/date/tests/bug68942.phpt
svn add ext/date/tests/bug68942_2.phpt
svn add ext/date/tests/bug69336.phpt
svn add ext/date/tests/date_interval_create_from_date_string.phpt
svn add ext/date/tests/date_interval_create_from_date_string_nullparam.phpt
svn add ext/date/tests/date_interval_create_from_date_string_wrongparam_001.phpt
svn add ext/date/tests/date_interval_create_from_date_string_wrongparam_002.phpt
svn add ext/date/tests/date_timestamp_set.phpt
svn add ext/date/tests/date_timestamp_set_nullparam.phpt
svn add ext/date/tests/date_timestamp_set_nullparam2.phpt
svn add ext/date/tests/date_timestamp_set_wrongparam_001.phpt
svn add ext/date/tests/date_timestamp_set_wrongparam_002.phpt
svn add ext/date/tests/date_timestamp_set_wrongparam_003.phpt
svn add ext/date/tests/date_timestamp_set_wrongparam_004.phpt
svn add ext/date/tests/timezone_version_get.phpt
svn add ext/date/tests/timezone_version_get_basic1.phpt
svn add ext/exif/tests/bug68799.phpt
svn add ext/fileinfo/libmagic/readelf.c
svn add ext/fileinfo/libmagic/readelf.h
svn add ext/fileinfo/tests/bug68735.phpt
svn add ext/fileinfo/tests/bug68819_001.phpt
svn add ext/fileinfo/tests/bug68819_002.phpt
svn add ext/filter/tests/bug69202.phpt
svn add ext/filter/tests/bug69203.phpt
svn add ext/gd/tests/imagealphablending_error1.phpt
svn add ext/gd/tests/imagecolorresolvealpha_error3.phpt
svn add ext/gd/tests/imagepalettetotruecolor_basic.phpt
svn add ext/gd/tests/imagepalettetotruecolor_error1.phpt
svn add ext/gd/tests/imagepalettetotruecolor_error2.phpt
svn add ext/gd/tests/imagepalettetotruecolor_error3.phpt
svn add ext/gd/tests/imagesavealpha_error2.phpt
svn add ext/gettext/tests/66265
svn add ext/gettext/tests/bug66267.phpt
svn add ext/iconv/iconv.c.orig
svn add ext/iconv/tests/bug48147.phpt
svn add ext/iconv/tests/iconv_basic_001-win32.phpt
svn add ext/iconv/tests/iconv_basic_001.phpt
svn add ext/intl/tests/bug67052-win32.phpt
svn add ext/intl/tests/collator_create4.phpt
svn add ext/intl/tests/collator_get_sort_key_variant4.phpt
svn add ext/intl/tests/dateformat_calendars_variant3.phpt
svn add ext/intl/tests/dateformat_create_cal_arg_variant3.phpt
svn add ext/intl/tests/dateformat_create_cal_arg_variant4.phpt
svn add ext/intl/tests/dateformat_formatObject_calendar_variant3.phpt
svn add ext/intl/tests/dateformat_formatObject_calendar_variant4.phpt
svn add ext/intl/tests/dateformat_formatObject_datetime_variant3.phpt
svn add ext/intl/tests/dateformat_formatObject_datetime_variant4.phpt
svn add ext/intl/tests/dateformat_get_set_calendar_variant3.phpt
svn add ext/intl/tests/dateformat_get_set_calendar_variant4.phpt
svn add ext/intl/tests/dateformat_get_set_timezone_variant3.phpt
svn add ext/intl/tests/dateformat_get_set_timezone_variant4.phpt
svn add ext/intl/tests/dateformat_timezone_arg_variations3.phpt
svn add ext/intl/tests/dateformat_timezone_arg_variations4.phpt
svn add ext/intl/tests/formatter_format5.phpt
svn add ext/intl/tests/msgfmt_format_intlcalendar_variant3.phpt
svn add ext/intl/tests/msgfmt_format_intlcalendar_variant4.phpt
svn add ext/json/tests/bug64695.phpt
svn add ext/mbstring/tests/bug68846.phpt
svn add ext/mysqlnd/mysql_float_to_double.h
svn add ext/odbc/tests/bug68087.phpt
svn add ext/odbc/tests/bug69354.phpt
svn add ext/opcache/tests/bug69038.phpt
svn add ext/opcache/tests/bug69125.phpt
svn add ext/opcache/tests/bug69281.phpt
svn add ext/opcache/tests/bug695449.phpt
svn add ext/openssl/tests/bug67403.phpt
svn add ext/pcre/pcrelib/pcre_jit_compile.c
svn add ext/pcre/pcrelib/pcre_printint.src
svn add ext/pcre/pcrelib/sljit
svn add ext/pdo_mysql/tests/bug68371.phpt
svn add ext/pdo_mysql/tests/pdo_mysql_attr_multi_statements.phpt
svn add ext/pdo_mysql/tests/pdo_mysql_multi_stmt_nextrowset.phpt
svn add ext/pdo_pgsql/tests/bug66584.phpt
svn add ext/pdo_pgsql/tests/bug67462.phpt
svn add ext/pdo_pgsql/tests/bug68371.phpt
svn add ext/pgsql/tests/bug65119.phpt
svn add ext/pgsql/tests/bug68638.phpt
svn add ext/pgsql/tests/pg_insert_002.phpt
svn add ext/phar/tests/bug64931
svn add ext/phar/tests/bug69324.phpt
svn add ext/phar/tests/bug69441.phpt
svn add ext/phar/tests/bug69453.phpt
svn add ext/phar/tests/tar/bug64343.phpt
svn add ext/phar/tests/tar/bug67761.phpt
svn add ext/readline/tests/bug69054.phpt
svn add ext/readline/tests/readline_read_history_error_001.phpt
svn add ext/reflection/tests/bug67068.phpt
svn add ext/session/tests/bug68063.phpt
svn add ext/soap/tests/bug68361.phpt
svn add ext/soap/tests/bugs/bug69085.phpt
svn add ext/spl/tests/SplFileInfo_setFileClass_basic.phpt
svn add ext/spl/tests/SplFileInfo_setFileClass_error.phpt
svn add ext/spl/tests/SplFileInfo_setInfoClass_basic.phpt
svn add ext/spl/tests/SplFileInfo_setInfoClass_error.phpt
svn add ext/spl/tests/bug65213.phpt
svn add ext/spl/tests/bug65967.phpt
svn add ext/spl/tests/bug66405.phpt
svn add ext/spl/tests/bug68128.phpt
svn add ext/spl/tests/bug68479.phpt
svn add ext/spl/tests/bug68557.phpt
svn add ext/spl/tests/bug69108.phpt
svn add ext/spl/tests/bug69227.phpt
svn add ext/sqlite3/tests/bug66550.phpt
svn add ext/sqlite3/tests/bug68760.phpt
svn add ext/standard/tests/file/bug65272.phpt
svn add ext/standard/tests/file/bug68335.phpt
svn add ext/standard/tests/file/bug68532.phpt
svn add ext/standard/tests/file/bug69628.phpt
svn add ext/standard/tests/http/bug69337.phpt
svn add ext/standard/tests/mail/mail_basic6.phpt
svn add ext/standard/tests/misc/exec_basic1.phpt
svn add ext/standard/tests/network/bug68925.phpt
svn add ext/standard/tests/network/news.rss
svn add ext/standard/tests/serialize/bug68545.phpt
svn add ext/standard/tests/serialize/bug68594.phpt
svn add ext/standard/tests/serialize/bug68976.phpt
svn add ext/standard/tests/serialize/bug69139.phpt
svn add ext/standard/tests/serialize/bug69152.phpt
svn add ext/standard/tests/streams/bug67626.phpt
svn add ext/standard/tests/streams/stream_multi_filters_close.phpt
svn add ext/standard/tests/strings/bug65230.phpt
svn add ext/standard/tests/strings/bug65769.phpt
svn add ext/standard/tests/strings/bug68710.phpt
svn add ext/standard/tests/strings/bug69522.phpt
svn add ext/standard/tests/strings/crypt_des_error.phpt
svn add ext/standard/tests/url/bug68917.phpt
svn add ext/standard/url_scanner_ex.c
svn add ext/standard/url_scanner_ex.c.orig
svn add ext/standard/var_unserializer.c
svn add ext/standard/var_unserializer.c.orig
svn add ext/xmlwriter/tests/011.phpt
svn add ext/xmlwriter/tests/012.phpt
svn add ext/xmlwriter/tests/OO_010.phpt
svn add ext/xmlwriter/tests/OO_011.phpt
svn add ext/xsl/tests/xsltprocessor_hasExsltSupport.phpt
svn add ext/xsl/tests/xsltprocessor_hasExsltSupport_not_available_extension.phpt
svn add ext/xsl/tests/xsltprocessor_hasExsltSupport_wrongparam_001.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc_nullparam.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc_wrongparam_001.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc_wrongparam_002.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc_wrongparam_003.phpt
svn add ext/xsl/tests/xsltprocessor_transformToDoc_wrongparam_004.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI_nullparam.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI_wrongparam_001.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI_wrongparam_002.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI_wrongparam_003.phpt
svn add ext/xsl/tests/xsltprocessor_transformToURI_wrongparam_004.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML_nullparam.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML_wrongparam_001.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML_wrongparam_002.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML_wrongparam_003.phpt
svn add ext/xsl/tests/xsltprocessor_transformToXML_wrongparam_004.phpt
svn add ext/zlib/tests/bug_52944-darwin.phpt
svn add sapi/cli/tests/bug67741.phpt
svn add sapi/cli/tests/bug67741_stub.inc
svn add sapi/cli/tests/bug68745.phpt
svn add sapi/fpm/tests
svn add tests/output/bug65593.phpt
svn add travis/install.sh
