Document: inadyn-mt
Title: Debian inadyn-mt Manual
Author: <insert document author here>
Abstract: This manual describes what inadyn-mt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inadyn-mt/inadyn-mt.sgml.gz

Format: postscript
Files: /usr/share/doc/inadyn-mt/inadyn-mt.ps.gz

Format: text
Files: /usr/share/doc/inadyn-mt/inadyn-mt.text.gz

Format: HTML
Index: /usr/share/doc/inadyn-mt/html/index.html
Files: /usr/share/doc/inadyn-mt/html/*.html
