#!/bin/sh

set -e

# begin-remove-after: released:trixie
if test "$1" = remove || test "$1" = upgrade -o "$1" = failed-upgrade -o "$1" = abort-install -o "$1" = abort-upgrade && dpkg --compare-versions "$2" lt 1.47.2~rc1-1~; then
    # DEP17 P1 mitigation.
    for cmd in /sbin/mount.fuse-ext2 /sbin/mount.fuseext2; do
        dpkg-divert --package fuse2fs --no-rename --divert "$cmd.usr-is-merged" --remove "$cmd"
    done
fi
# end-remove-after: released:trixie

#DEBHELPER#
