# $Id: Makefile,v 1.1.1.1 2005/06/13 16:47:44 bogdan_iancu Exp $
#
# registrar module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=registrar.so
LIBS=

DEFS+=-I../.. -I../usrloc

include ../../Makefile.modules
