/* Warning ! This is a generated file. Use build_mathnamespace to regenerate it */
#define acos ClasspathMath_acos
#define asin ClasspathMath_asin
#define atan ClasspathMath_atan
#define atan2 ClasspathMath_atan2
#define cos ClasspathMath_cos
#define sin ClasspathMath_sin
#define tan ClasspathMath_tan
#define cosh ClasspathMath_cosh
#define sinh ClasspathMath_sinh
#define tanh ClasspathMath_tanh
#define exp ClasspathMath_exp
#define frexp ClasspathMath_frexp
#define ldexp ClasspathMath_ldexp
#define expm1 ClasspathMath_expm1
#define log ClasspathMath_log
#define log10 ClasspathMath_log10
#define log1p ClasspathMath_log1p
#define modf ClasspathMath_modf
#define pow ClasspathMath_pow
#define sqrt ClasspathMath_sqrt
#define ceil ClasspathMath_ceil
#define fabs ClasspathMath_fabs
#define floor ClasspathMath_floor
#define fmod ClasspathMath_fmod
#define erf ClasspathMath_erf
#define erfc ClasspathMath_erfc
#define gamma ClasspathMath_gamma
#define hypot ClasspathMath_hypot
#define finite ClasspathMath_finite
#define j0 ClasspathMath_j0
#define j1 ClasspathMath_j1
#define jn ClasspathMath_jn
#define lgamma ClasspathMath_lgamma
#define y0 ClasspathMath_y0
#define y1 ClasspathMath_y1
#define yn ClasspathMath_yn
#define acosh ClasspathMath_acosh
#define asinh ClasspathMath_asinh
#define cbrt ClasspathMath_cbrt
#define logb ClasspathMath_logb
#define nextafter ClasspathMath_nextafter
#define remainder ClasspathMath_remainder
#define logb ClasspathMath_logb
#define scalb ClasspathMath_scalb
#define significand ClasspathMath_significand
#define logbf ClasspathMath_logbf
#define scalbf ClasspathMath_scalbf
#define significandf ClasspathMath_significandf
#define copysign ClasspathMath_copysign
#define ilogb ClasspathMath_ilogb
#define rint ClasspathMath_rint
#define rintf ClasspathMath_rintf
#define scalbn ClasspathMath_scalbn
#define __ieee754_sqrt ClasspathMath___ieee754_sqrt
#define __ieee754_asin ClasspathMath___ieee754_asin
#define __ieee754_asin ClasspathMath___ieee754_asin
#define __ieee754_atan2 ClasspathMath___ieee754_atan2
#define __ieee754_exp ClasspathMath___ieee754_exp
#define __ieee754_fmod ClasspathMath___ieee754_fmod
#define __ieee754_log ClasspathMath___ieee754_log
#define __ieee754_pow ClasspathMath___ieee754_pow
#define __ieee754_rem_pio2 ClasspathMath___ieee754_rem_pio2
#define __ieee754_remainder ClasspathMath___ieee754_remainder
#define __ieee754_scalb ClasspathMath___ieee754_scalb
#define __ieee754_acos ClasspathMath___ieee754_acos
#define __kernel_cos ClasspathMath___kernel_cos
#define __kernel_sin ClasspathMath___kernel_sin
#define __kernel_tan ClasspathMath___kernel_tan
#define __kernel_rem_pio2 ClasspathMath___kernel_rem_pio2
