codecov:
  max_report_age: false
  notify:
    wait_for_ci: true
  require_ci_to_pass: false

comment:
  require_base: false
  require_head: false

coverage:
  status:
    project:
      default:
        target: 80%      # Target 80% project coverage
        threshold: 10    # Allow pass even when project coverage drops by 10% (because of AVX512)
        paths:
          - "!test/"     # Don't count coverage of tests towards project coverage
          - "!tools/"    #               --"--     tools     --"--
    patch:
      default:
        target: auto
        threshold: 10    # Allow 10% worse coverage of changed code

component_management:
  default_rules: # Defaults inherited by all components
    statuses:
      - type: project
        target: auto
        threshold: 0.2   # Most components should have only minimal coverage changes
  individual_components:
    - component_id: deflate
      name: deflate
      paths:
        - compare*
        - compress*
        - deflate*
        - insert*
        - match*
        - arch/generic/compare*
        - arch/generic/slide*
    - component_id: inflate
      name: inflate
      paths:
        - chunkset*
        - inf*
        - uncompr*
        - arch/generic/chunk*
    - component_id: gzlib
      name: gzlib
      paths:
        - gz*
    - component_id: adler32
      name: adler32
      paths:
        - adler32*
        - arch/generic/adler32*
    - component_id: crc32
      name: crc32
      paths:
        - crc32*
        - arch/generic/crc32*
    - component_id: common
      name: common
      statuses:
        - threshold: 2       # CI changes between AVX2 and AVX-512 capable hosts
      paths:
        - arch_functions.h
        - cpu*
        - fallback*
        - functable*
        - trees*
        - zbuild*
        - zendian*
        - zlib*
        - zmemory*
        - zutil*
        - arch/generic/generic_functions.h
    - component_id: arch_arm
      name: arch_arm
      paths:
        - arch/arm/**
    - component_id: arch_loongarch
      name: arch_loongarch
      paths:
        - arch/loongarch/**
    - component_id: arch_power
      name: arch_power
      paths:
        - arch/power/**
    - component_id: arch_riscv
      name: arch_riscv
      paths:
        - arch/riscv/**
    - component_id: arch_s390
      name: arch_s390
      paths:
        - arch/s390/**
    - component_id: arch_x86
      name: arch_x86
      statuses:
        - threshold: 10      # CI changes between AVX2 and AVX-512 capable hosts
      paths:
        - arch/x86/**
    - component_id: minigzip
      name: minigzip
      paths:
        - test/minigzip.c
    - component_id: minideflate
      name: minideflate
      paths:
        - test/minideflate.c
    - component_id: tools
      name: tools
      paths:
        - tools/**
    - component_id: tests
      name: tests
      paths:
        - test/**
        - "!test/minigzip.c"
        - "!test/minideflate.c"

github_checks:
  annotations: false

fixes:
  - '/home/actions-runner/_work/zlib-ng/zlib-ng::'
  - '/home/actions-runner/_work/zlib-ng/zlib-ng/build/::'

ignore:
  - test/benchmarks/**
  - "**/benchmark_*"
  - usr/include/.*
  - /usr/include/.*
  - /build/usr/include/.*
  - usr/lib/.*
  - /usr/lib/.*
  - /build/usr/lib/.*
  - usr/lib64/.*
  - /usr/lib64/.*
  - /build/usr/lib64/.*
  - _deps/**
