# Copyright (c) Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

#IMPORTANT NOTE:
# 1. Duplicate entries for same board name should not be added. Please modify only the values and not add new lines for same board
# 2. Do not add boardname search strings in comments. As the host script search patterns are for boardnames in the file and does not ignore comments
#############################################################################################################
### Marina RDPs

#MR-01.1
ipq5424-rdp464_enable_cold_boot_support=1
ipq5424-rdp464_enable_qdss_tracing=1
ipq5424-rdp464_qcn9224_pci1_enable_cold_boot_support=1
ipq5424-rdp464_qcn9224_pci1_enable_qdss_tracing=1
ipq5424-rdp464_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp464_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp464_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp464_qcn9224_pci3_enable_qdss_tracing=1

#MR-02.1
ipq5424-rdp466_enable_cold_boot_support=1
ipq5424-rdp466_enable_qdss_tracing=1
ipq5424-rdp466_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp466_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp466_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp466_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp466-c2_enable_cold_boot_support=1
ipq5424-rdp466-c2_enable_qdss_tracing=1
ipq5424-rdp466-c2_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp466-c2_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp466-c2_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp466-c2_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp466-rffe-c2_enable_cold_boot_support=1
ipq5424-rdp466-rffe-c2_enable_qdss_tracing=1
ipq5424-rdp466-rffe-c2_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp466-rffe-c2_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp466-rffe-c2_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp466-rffe-c2_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp466-c3_enable_cold_boot_support=1
ipq5424-rdp466-c3_enable_qdss_tracing=1
ipq5424-rdp466-c3_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp466-c3_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp466-c3_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp466-c3_qcn9224_pci3_enable_qdss_tracing=1

#MR-02.2
ipq5424-rdp485_enable_cold_boot_support=1
ipq5424-rdp485_enable_qdss_tracing=1
ipq5424-rdp485_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp485_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp485_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp485_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp485-c3_enable_cold_boot_support=1
ipq5424-rdp485-c3_enable_qdss_tracing=1
ipq5424-rdp485-c3_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp485-c3_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp485-c3_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp485-c3_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp496_enable_cold_boot_support=1
ipq5424-rdp496_enable_qdss_tracing=1
ipq5424-rdp496_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp496_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp496_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp496_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp466-rffe_enable_cold_boot_support=1
ipq5424-rdp466-rffe_enable_qdss_tracing=1
ipq5424-rdp466-rffe_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp466-rffe_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp466-rffe_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp466-rffe_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp485-c2_enable_cold_boot_support=1
ipq5424-rdp485-c2_enable_qdss_tracing=1
ipq5424-rdp485-c2_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp485-c2_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp485-c2_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp485-c2_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp485-rffe_enable_cold_boot_support=1
ipq5424-rdp485-rffe_enable_qdss_tracing=1
ipq5424-rdp485-rffe_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp485-rffe_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp485-rffe_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp485-rffe_qcn9224_pci3_enable_qdss_tracing=1

ipq5424-rdp485-rffe-c2_enable_cold_boot_support=1
ipq5424-rdp485-rffe-c2_enable_qdss_tracing=1
ipq5424-rdp485-rffe-c2_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp485-rffe-c2_qcn9224_pci2_enable_qdss_tracing=1
ipq5424-rdp485-rffe-c2_qcn9224_pci3_enable_cold_boot_support=1
ipq5424-rdp485-rffe-c2_qcn9224_pci3_enable_qdss_tracing=1

#MR-03.1
ipq5424-rdp487_enable_cold_boot_support=1
ipq5424-rdp487_enable_qdss_tracing=1
ipq5424-rdp487_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp487_qcn9224_pci2_enable_qdss_tracing=1

ipq5424-rdp487-c2_enable_cold_boot_support=1
ipq5424-rdp487-c2_enable_qdss_tracing=1
ipq5424-rdp487-c2_qcn9224_pci2_enable_cold_boot_support=1
ipq5424-rdp487-c2_qcn9224_pci2_enable_qdss_tracing=1

