.TH NAMEIF 8 "2008\-10\-03" "net\-tools" "Linux System Administrator's Manual"
.SH NAME
nameif \- name network interfaces based on MAC addresses
.SH SYNOPSIS
.B "nameif [\-c configfile] [\-s]"
.br
.B "nameif [\-c configfile] [\-s] {interface macaddress}"
.SH DESCRIPTION
.B nameif 
renames network interfaces based on mac addresses. When no arguments are
given 
.I /etc/mactab
is read. Each line  of it contains an interface name and a Ethernet MAC 
address. Comments are allowed starting with #. 
Otherwise the interfaces specified on the command line are processed.
.I nameif
looks for the interface with the given MAC address and renames it to the
name given.

When the 
.I \-s
argument is given all error messages go to the syslog.

When the 
.I \-c 
argument is given with a file name that file is read instead of /etc/mactab.

.SH NOTES
.I nameif
should be run before the interface is up, otherwise it'll fail.

.SH FILES
/etc/mactab
.SH BUGS
Only works for Ethernet currently.
