#!/bin/sh
# DD-WRT V22 Preinit script by Sebastian Gottschall (BrainSlayer). (some parts are taken from OpenWRT)

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/jffs/sbin:/jffs/bin:/jffs/usr/sbin:/jffs/usr/bin
export LD_LIBRARY_PATH=/lib:/usr/lib:/jffs/lib:/jffs/usr/lib
nvram set expert_mode=1


if [ -z "$(nvram get router_version)" ]; then
    nvram set boardtype="Avila Gateworks"
    nvram set boardnum=0x0
    nvram set router_version=211005
fi

if [ -z "$(nvram get ipv6_enable)" ]; then
    nvram set ipv6_enable=0
    nvram set ipv6_enable0=0
    nvram set need_commit=1
fi
if [ -z "$(nvram get ipv6_enable0)" ]; then
    nvram set ipv6_enable=0
    nvram set ipv6_enable0=0
    nvram set need_commit=1
fi

if [ -z "$(nvram get enable_jffs2)" ]; then
    nvram set enable_jffs2=0
    nvram set clean_jffs2=0
    nvram set sys_enable_jffs2=0
    nvram set sys_clean_jffs2=0
    nvram set need_commit=1
fi

if [ -z "$(nvram get http_enable)" ]; then
    nvram set http_enable=1
    nvram set need_commit=1
fi

