#define GPIO_MINOR_LAST 31
#define GPIO_MAJOR	120	// Experiemental

#define GPIO_IRQ_NBR	12

#define GPIOBASEADDR		(IO_ADDRESS(0x021000000))

#define GPIODATAOUTOFF		0x00
#define GPIODATAINOFF		0x04
#define GPIOPINDIROFF		0x08
#define GPIOPINBYPASSOFF	0x0C
#define GPIODATASETOFF		0x10
#define GPIODATACLEAROFF	0x14
#define GPIOPINPULLENBOFF	0x18
#define GPIOPINPULLTPOFF	0x1C
#define GPIOINTRENBOFF		0x20
#define GPIOINTRRAWSOFF		0x24
#define GPIOINTRMASKEDSTATEOFF	0x28
#define GPIOINTRMASKOFF		0x2C
#define GPIOINTRCLEAROFF	0x30
#define GPIOINTRTRIGGEROFF	0x34
#define GPIOINTRBOTHOFF		0x38
#define GPIOINTRRISENEGOFF	0x3C
#define GPIOBNCEENBOFF		0x40
#define GPIOBNCEPRESOFF		0x44

#define GPIO_IOCTRL_SETDIR	0x20
#define GPIO_IOCTRL_SET		0x40
#define GPIO_IOCTRL_CLEAR	0x50
#define GPIO_IOCTRL_ENBINT	0x60
#define GPIO_IOCTRL_MASKINT	0x70
#define GPIO_IOCTRL_LVLTRIG	0x75
#define GPIO_IOCTRL_EDGINT	0x77
#define GPIO_IOCTRL_EDGPOLINT	0x78
#define GPIO_IOCTRL_BYPASS	0x30
#define GPIO_IOCTRL_PRESCLK	0x80
#define GPIO_IOCTRL_CLKVAL	0x90
#define GPIO_IOCTRL_PULLENB	0xA0
#define GPIO_IOCTRL_PULLTYPE	0xA8


#define GPIO_MAJOR	120	/* experimental MAJOR number */
				// Minor - 0 : 31 gpio pins

#define GPIO_SET	0x01
#define GPIO_CLEAR	0x01

#define GPIO_INPUT	0
#define GPIO_OUTPUT	1
#define GPIO_EDGEINTR 	0
#define GPIO_EDGESINGL	0
#define GPIO_EDGEBOTH	1
#define GPIO_POSITIVE	0
#define GPIO_ENBINT	1
#define GPIO_DISABLEMASK	1
#define GPIO_PULLDOWN	0
#define GPIO_PULLUP	1
#define GPIO_ENABLEPULL	1
#define GPIO_DISABLEPULL	0
