#!/bin/bash

# NFT_TEST_REQUIRES(NFT_TEST_HAVE_bitshift)

set -e

RULESET="
  add table t
  add chain t c { type filter hook input priority filter; }
  add rule t c meta mark set ip dscp lshift 26 or 0x10
"

$NFT -f - <<< "$RULESET"
