#!/bin/bash

# NFT_TEST_REQUIRES(NFT_TEST_HAVE_bitshift)

set -e

RULESET="
  add table ip6 t
  add chain ip6 t c { type filter hook output priority filter; }
  add rule ip6 t c ct mark set ip6 dscp lshift 26 or 0x10
"

$NFT -f - <<< "$RULESET"
