#!/bin/bash

# NFT_TEST_REQUIRES(NFT_TEST_HAVE_bitshift)

set -e

RULESET="
  add table t
  add chain t c { type filter hook output priority filter; }
  add rule t c ct mark set ip dscp lshift 2 or 0x10
"

$NFT -f - <<< "$RULESET"
