=head1 NAME

bt-monitor - a bluetooth monitor

=head1 SYNOPSIS

bt-monitor [OPTION...]

Help Options:
  -h, --help

Application Options:
  -a, --adapter=<name|mac>

=head1 DESCRIPTION

This utility is used to capture DBus signals of bluetoothd. Captured next signals:

B<Manager signals>:
  AdapterAdded
  AdapterRemoved
  DefaultAdapterChanged

B<Adapter signals>:
  DeviceCreated
  DeviceDisappeared
  DeviceFound
  DeviceRemoved
  AdapterPropertyChanged

B<Device signals>:
  DisconnectRequested
  DevicePropertyChanged

B<Services signals>:
  AudioServiceConnected
  InputServiceConnected
  NetworkServiceConnected

=head1 OPTIONS

B<-h, --help>
    Show help

B<-a, --adapter E<lt>name|macE<gt>>
    Specify adapter to capture by his Name or MAC address
    (if this option does not defined - all adapters captured)

=head1 AUTHOR

Alexander Orlenko <zxteam@gmail.com>.

=head1 SEE ALSO

bt-adapter(1) bt-agent(1) bt-audio(1) bt-device(1) bt-input(1) bt-network(1) bt-serial(1)
