/* Generated by ./xlat/gen.sh from ./xlat/bpf_map_lookup_elem_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(BPF_ANY) || (defined(HAVE_DECL_BPF_ANY) && HAVE_DECL_BPF_ANY)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_ANY) == (0), "BPF_ANY != 0");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_ANY 0
#endif
#if defined(BPF_F_LOCK) || (defined(HAVE_DECL_BPF_F_LOCK) && HAVE_DECL_BPF_F_LOCK)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((BPF_F_LOCK) == (4), "BPF_F_LOCK != 4");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define BPF_F_LOCK 4
#endif

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat bpf_map_lookup_elem_flags in mpers mode

# else

static const struct xlat_data bpf_map_lookup_elem_flags_xdata[] = {
 XLAT(BPF_ANY),
 XLAT(BPF_F_LOCK),
};
static
const struct xlat bpf_map_lookup_elem_flags[1] = { {
 .data = bpf_map_lookup_elem_flags_xdata,
 .size = ARRAY_SIZE(bpf_map_lookup_elem_flags_xdata),
 .type = XT_NORMAL,
} };

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
