/* Generated by ./xlat/gen.sh from ./xlat/evdev_ff_status.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(FF_STATUS_STOPPED) || (defined(HAVE_DECL_FF_STATUS_STOPPED) && HAVE_DECL_FF_STATUS_STOPPED)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((FF_STATUS_STOPPED) == (0x00), "FF_STATUS_STOPPED != 0x00");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define FF_STATUS_STOPPED 0x00
#endif
#if defined(FF_STATUS_PLAYING) || (defined(HAVE_DECL_FF_STATUS_PLAYING) && HAVE_DECL_FF_STATUS_PLAYING)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((FF_STATUS_PLAYING) == (0x01), "FF_STATUS_PLAYING != 0x01");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define FF_STATUS_PLAYING 0x01
#endif

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat evdev_ff_status in mpers mode

# else

static const struct xlat_data evdev_ff_status_xdata[] = {
 [FF_STATUS_STOPPED] = XLAT(FF_STATUS_STOPPED),
 #define XLAT_VAL_0 ((unsigned) (FF_STATUS_STOPPED))
 #define XLAT_STR_0 STRINGIFY(FF_STATUS_STOPPED)
 [FF_STATUS_PLAYING] = XLAT(FF_STATUS_PLAYING),
 #define XLAT_VAL_1 ((unsigned) (FF_STATUS_PLAYING))
 #define XLAT_STR_1 STRINGIFY(FF_STATUS_PLAYING)
};
static
const struct xlat evdev_ff_status[1] = { {
 .data = evdev_ff_status_xdata,
 .size = ARRAY_SIZE(evdev_ff_status_xdata),
 .type = XT_INDEXED,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
