/* Generated by ./xlat/gen.sh from ./xlat/netlink_new_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat netlink_new_flags in mpers mode

# else

static const struct xlat_data netlink_new_flags_xdata[] = {
#if defined(NLM_F_REPLACE) || (defined(HAVE_DECL_NLM_F_REPLACE) && HAVE_DECL_NLM_F_REPLACE)
  XLAT(NLM_F_REPLACE),
 #define XLAT_VAL_0 ((unsigned) (NLM_F_REPLACE))
 #define XLAT_STR_0 STRINGIFY(NLM_F_REPLACE)
#endif
#if defined(NLM_F_EXCL) || (defined(HAVE_DECL_NLM_F_EXCL) && HAVE_DECL_NLM_F_EXCL)
  XLAT(NLM_F_EXCL),
 #define XLAT_VAL_1 ((unsigned) (NLM_F_EXCL))
 #define XLAT_STR_1 STRINGIFY(NLM_F_EXCL)
#endif
#if defined(NLM_F_CREATE) || (defined(HAVE_DECL_NLM_F_CREATE) && HAVE_DECL_NLM_F_CREATE)
  XLAT(NLM_F_CREATE),
 #define XLAT_VAL_2 ((unsigned) (NLM_F_CREATE))
 #define XLAT_STR_2 STRINGIFY(NLM_F_CREATE)
#endif
#if defined(NLM_F_APPEND) || (defined(HAVE_DECL_NLM_F_APPEND) && HAVE_DECL_NLM_F_APPEND)
  XLAT(NLM_F_APPEND),
 #define XLAT_VAL_3 ((unsigned) (NLM_F_APPEND))
 #define XLAT_STR_3 STRINGIFY(NLM_F_APPEND)
#endif
};
static
const struct xlat netlink_new_flags[1] = { {
 .data = netlink_new_flags_xdata,
 .size = ARRAY_SIZE(netlink_new_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
#  ifdef XLAT_VAL_2
  | XLAT_VAL_2
#  endif
#  ifdef XLAT_VAL_3
  | XLAT_VAL_3
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
#  ifdef XLAT_STR_2
  + sizeof(XLAT_STR_2)
#  endif
#  ifdef XLAT_STR_3
  + sizeof(XLAT_STR_3)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
#  undef XLAT_STR_2
#  undef XLAT_VAL_2
#  undef XLAT_STR_3
#  undef XLAT_VAL_3
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
