/* Generated by ./xlat/gen.sh from ./xlat/sigsys_codes.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#if defined(SYS_SECCOMP) || (defined(HAVE_DECL_SYS_SECCOMP) && HAVE_DECL_SYS_SECCOMP)
DIAG_PUSH_IGNORE_TAUTOLOGICAL_COMPARE
static_assert((SYS_SECCOMP) == (1), "SYS_SECCOMP != 1");
DIAG_POP_IGNORE_TAUTOLOGICAL_COMPARE
#else
# define SYS_SECCOMP 1
#endif

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

extern const struct xlat sigsys_codes[];

# else

static const struct xlat_data sigsys_codes_xdata[] = {
 XLAT(SYS_SECCOMP),
 #define XLAT_VAL_0 ((unsigned) (SYS_SECCOMP))
 #define XLAT_STR_0 STRINGIFY(SYS_SECCOMP)
};
#  if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
#  endif
const struct xlat sigsys_codes[1] = { {
 .data = sigsys_codes_xdata,
 .size = ARRAY_SIZE(sigsys_codes_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
