/* Generated by ./xlat/gen.sh from ./xlat/sock_ipx_options.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat sock_ipx_options in mpers mode

# else

static const struct xlat_data sock_ipx_options_xdata[] = {
#if defined(IPX_TYPE) || (defined(HAVE_DECL_IPX_TYPE) && HAVE_DECL_IPX_TYPE)
  XLAT(IPX_TYPE),
 #define XLAT_VAL_0 ((unsigned) (IPX_TYPE))
 #define XLAT_STR_0 STRINGIFY(IPX_TYPE)
#endif
};
static
const struct xlat sock_ipx_options[1] = { {
 .data = sock_ipx_options_xdata,
 .size = ARRAY_SIZE(sock_ipx_options_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
