/* Generated by ./xlat/gen.sh from ./xlat/uffd_zeropage_flags.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uffd_zeropage_flags in mpers mode

# else

static const struct xlat_data uffd_zeropage_flags_xdata[] = {
#if defined(UFFDIO_ZEROPAGE_MODE_DONTWAKE) || (defined(HAVE_DECL_UFFDIO_ZEROPAGE_MODE_DONTWAKE) && HAVE_DECL_UFFDIO_ZEROPAGE_MODE_DONTWAKE)
  XLAT_TYPE(uint64_t, UFFDIO_ZEROPAGE_MODE_DONTWAKE),
 #define XLAT_VAL_0 ((uint64_t) (UFFDIO_ZEROPAGE_MODE_DONTWAKE))
 #define XLAT_STR_0 STRINGIFY(UFFDIO_ZEROPAGE_MODE_DONTWAKE)
#endif
};
static
const struct xlat uffd_zeropage_flags[1] = { {
 .data = uffd_zeropage_flags_xdata,
 .size = ARRAY_SIZE(uffd_zeropage_flags_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
  ,
} };

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
