/* Generated by ./xlat/gen.sh from ./xlat/unix_diag_attrs.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"


#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat unix_diag_attrs in mpers mode

# else

static
const struct xlat unix_diag_attrs[] = {
 XLAT(UNIX_DIAG_NAME),
 XLAT(UNIX_DIAG_VFS),
 XLAT(UNIX_DIAG_PEER),
 XLAT(UNIX_DIAG_ICONS),
 XLAT(UNIX_DIAG_RQLEN),
 XLAT(UNIX_DIAG_MEMINFO),
 XLAT(UNIX_DIAG_SHUTDOWN),
 XLAT_END
};

# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
