/*******************************************************************************
 *
 *   Copyright (c) 2009 Cavium Networks 
 *
 *   This program is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License as published by the Free
 *   Software Foundation; either version 2 of the License, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *   more details.
 *
 *   You should have received a copy of the GNU General Public License along with
 *   this program; if not, write to the Free Software Foundation, Inc., 59
 *   Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 *   The full GNU General Public License is included in this distribution in the
 *   file called LICENSE.
 *
 ********************************************************************************/

// the symbol define memory map register.

#ifndef CNS3XXX_SYMBOL_H
#define CNS3XXX_SYMBOL_H

#define DRV_VERSION "Cavium CNS3XXX Switch Driver-0.0.1"


#define LINUX_KERNEL // if don't define LINUX_KERNEL, mean u-boot

#if defined(LINUX_KERNEL)
// linux kernel
#include <mach/board.h>

#define SWITCH_REG_VALUE(offset) (*((volatile unsigned int *)(CNS3XXX_SWITCH_BASE_VIRT+offset)))
#define PMU_REG_VALUE(offset) (*((volatile unsigned int *)(CNS3XXX_PM_BASE_VIRT+offset)))
#define MISC_REG_VALUE(offset) (*((volatile unsigned int *)(CNS3XXX_MISC_BASE_VIRT+offset)))


#define NETDEV_SIZE 4097+3

#define PORT0_NETDEV_INDEX NETDEV_SIZE-3
#define PORT1_NETDEV_INDEX NETDEV_SIZE-2
#define PORT2_NETDEV_INDEX NETDEV_SIZE-1

#if defined (CONFIG_CNS3XXX_SPPE)
#define FP_NETDEV_INDEX NETDEV_SIZE-4
#endif

#define PORT0_NETDEV net_dev_array[PORT0_NETDEV_INDEX]
#define PORT1_NETDEV net_dev_array[PORT1_NETDEV_INDEX]
#define PORT2_NETDEV net_dev_array[PORT2_NETDEV_INDEX]

#if defined (CONFIG_CNS3XXX_SPPE)
#define FP_NETDEV net_dev_array[FP_NETDEV_INDEX]
#endif

#else // u-boot
#include <malloc.h> // for u8, u32

#include "cns3000.h"
#define CAVM_OK 0
#define CAVM_ERR 1
#define CAVM_NOT_FOUND 2
#define CAVM_FOUND 3
#define CAVM_FAIL -1 // use minus 

#define SWITCH_REG_VALUE(addr) (*((volatile unsigned int *)(CNS3000_VEGA_SWITCH_BASE+addr)))
#define PMU_REG_VALUE(addr) (*((volatile unsigned int *)(CNS3000_VEGA_PM_BASE+addr)))
#define MISC_REG_VALUE(offset) (*((volatile unsigned int *)(CNS3000_VEGA_MISC_BASE+offset)))

#endif

// for VLAN and ARL table MB_PMAP
#define MAC_PORT0_PMAP 1
#define MAC_PORT1_PMAP (1 << 1)
#define MAC_PORT2_PMAP (1 << 4)
#define CPU_PORT_PMAP (1 << 2)



// memory map register definition

//#define PHY_CTRL_REG (*(u32 volatile*(0xff)))
#define PHY_CTRL_REG SWITCH_REG_VALUE(0x0)
#define PHY_AUTO_ADDR_REG SWITCH_REG_VALUE(0x04)

#define MAC_GLOB_CFG_REG SWITCH_REG_VALUE(0x08)
#define MAC_GLOB_CFG_EXT_REG SWITCH_REG_VALUE(0xf4)
#define MAC0_CFG_REG SWITCH_REG_VALUE(0x0c)
#define MAC1_CFG_REG SWITCH_REG_VALUE(0x10)
#define MAC2_CFG_REG SWITCH_REG_VALUE(0x18)
#define CPU_CFG_REG SWITCH_REG_VALUE(0x14)

#define MAC0_PRI_CTRL_REG SWITCH_REG_VALUE(0x1c)
#define MAC1_PRI_CTRL_REG SWITCH_REG_VALUE(0x20)
#define CPU_PRI_CTRL_REG SWITCH_REG_VALUE(0x24)
#define HNAT_PRI_CTRL_REG SWITCH_REG_VALUE(0x28)
#define MAC2_PRI_CTRL_REG SWITCH_REG_VALUE(0x2c)

#define MAC0_PRI_CTRL_EXT_REG SWITCH_REG_VALUE(0x30)

#define ETYPE1_ETYPE0_REG SWITCH_REG_VALUE(0x34)
#define ETYPE3_ETYPE2_REG SWITCH_REG_VALUE(0x38)

#define UDP_RANGE0_REG SWITCH_REG_VALUE(0x3c)
#define UDP_RANGE1_REG SWITCH_REG_VALUE(0x40)
#define UDP_RANGE2_REG SWITCH_REG_VALUE(0x44)
#define UDP_RANGE3_REG SWITCH_REG_VALUE(0x48)


#define PRIO_ETYPE_UDP_REG SWITCH_REG_VALUE(0x4c)

#define PRIO_IPDSCP_7_0_REG SWITCH_REG_VALUE(0x50)
#define PRIO_IPDSCP_15_8_REG SWITCH_REG_VALUE(0x54)
#define PRIO_IPDSCP_23_16_REG SWITCH_REG_VALUE(0x58)
#define PRIO_IPDSCP_31_24_REG SWITCH_REG_VALUE(0x5c)
#define PRIO_IPDSCP_39_32_REG SWITCH_REG_VALUE(0x60)
#define PRIO_IPDSCP_47_40_REG SWITCH_REG_VALUE(0x64)
#define PRIO_IPDSCP_55_48_REG SWITCH_REG_VALUE(0x68)
#define PRIO_IPDSCP_63_56_REG SWITCH_REG_VALUE(0x6c)

#define TC_CTRL_REG SWITCH_REG_VALUE(0x70)
#define RATE_CTRL_REG SWITCH_REG_VALUE(0x74)

#define FC_GLOB_THRS_REG SWITCH_REG_VALUE(0x78)
#define FC_PORT_THRS_REG SWITCH_REG_VALUE(0x7c)
#define MC_GLOB_THRS_REG SWITCH_REG_VALUE(0x80)
#define DC_GLOB_THRS_REG SWITCH_REG_VALUE(0x84)

#define ARL_VLAN_CMD_REG SWITCH_REG_VALUE(0x88)

#define ARL_CTRL0_REG SWITCH_REG_VALUE(0x8c)
#define ARL_CTRL1_REG SWITCH_REG_VALUE(0x90)
#define ARL_CTRL2_REG SWITCH_REG_VALUE(0x94)

#define VLAN_CFG SWITCH_REG_VALUE(0x098)

#define MAC1_MAC0_PVID_REG SWITCH_REG_VALUE(0x9c)
#define MAC2_CPU_PVID_REG SWITCH_REG_VALUE(0xa0)

#define VLAN_CTRL0_REG SWITCH_REG_VALUE(0xa4)
#define VLAN_CTRL1_REG SWITCH_REG_VALUE(0xa8)
#define VLAN_CTRL2_REG SWITCH_REG_VALUE(0xac)

#define SESSION_ID_1_0_REG SWITCH_REG_VALUE(0xb0)
#define SESSION_ID_3_2_REG SWITCH_REG_VALUE(0xb4)
#define SESSION_ID_5_4_REG SWITCH_REG_VALUE(0xb8)
#define SESSION_ID_7_6_REG SWITCH_REG_VALUE(0xbc)
#define SESSION_ID_9_8_REG SWITCH_REG_VALUE(0xc0)
#define SESSION_ID_11_10_REG SWITCH_REG_VALUE(0xc4)
#define SESSION_ID_13_12_REG SWITCH_REG_VALUE(0xc8)
#define SESSION_ID_15_14_REG SWITCH_REG_VALUE(0xcc)

#define INTR_STAT_REG SWITCH_REG_VALUE(0xd0)
#define INTR_MASK_REG SWITCH_REG_VALUE(0xd4)

#define SRAM_TEST_REG SWITCH_REG_VALUE(0xd8)

#define MEM_QUEUE_REG SWITCH_REG_VALUE(0xdc)

#define SARL_CTRL_REG SWITCH_REG_VALUE(0xe0)
#define SARL_OQ_GTH_REG SWITCH_REG_VALUE(0xe4)
#define SARL_OQ_YTH_REG SWITCH_REG_VALUE(0xe8)
#define SARL_OQ_RTH_REG SWITCH_REG_VALUE(0xec)

#define SLK_SKEW_CTRL_REG SWITCH_REG_VALUE(0xf0)

#define DMA_RING_CTRL_REG SWITCH_REG_VALUE(0x100)

#define DMA_AUTO_POLL_CFG_REG SWITCH_REG_VALUE(0x104)

#define DELAY_INTR_CFG_REG SWITCH_REG_VALUE(0x108)

#define TS_DMA_CTRL0_REG SWITCH_REG_VALUE(0x110)
#define TS_DESC_PTR0_REG  SWITCH_REG_VALUE(0x114)
#define TS_DESC_BASE_ADDR0_REG SWITCH_REG_VALUE(0x118)

#define FS_DMA_CTRL0_REG  SWITCH_REG_VALUE(0x120)
#define FS_DESC_PTR0_REG  SWITCH_REG_VALUE(0x124)
#define FS_DESC_BASE_ADDR0_REG SWITCH_REG_VALUE(0x128)

#define TS_DMA_CTRL1_REG  SWITCH_REG_VALUE(0x130)
#define TS_DESC_PTR1_REG  SWITCH_REG_VALUE(0x134)
#define TS_DESC_BASE_ADDR1_REG SWITCH_REG_VALUE(0x138)

#define FS_DMA_CTRL1_REG  SWITCH_REG_VALUE(0x140)
#define FS_DESC_PTR1_REG  SWITCH_REG_VALUE(0x144)
#define FS_DESC_BASE_ADDR1_REG SWITCH_REG_VALUE(0x148)

#define TS_DMA_STA_REG  SWITCH_REG_VALUE(0x150)
#define FS_DMA_STA_REG  SWITCH_REG_VALUE(0x154)

#define TS_MRD_CMD_CNT_REG  SWITCH_REG_VALUE(0x158)
#define TS_MWT_CMD_CNT_REG  SWITCH_REG_VALUE(0x15c)

#define FS_MRD_CMD_CNT_REG  SWITCH_REG_VALUE(0x160)
#define FS_MWT_CMD_CNT_REG  SWITCH_REG_VALUE(0x164)

#define C_RXOKPKT_MAC0_REG  SWITCH_REG_VALUE(0x300)
#define C_RXOKBYTE_MAC0_REG  SWITCH_REG_VALUE(0x304)
#define C_RXRUNT_MAC0_REG  SWITCH_REG_VALUE(0x308)
#define C_RXLONG_MAC0_REG  SWITCH_REG_VALUE(0x30c)
#define C_RXDROP_MAC0_REG  SWITCH_REG_VALUE(0x310)
#define C_RXCRC_MAC0_REG  SWITCH_REG_VALUE(0x314)
#define C_RXARLDROP_MAC0_REG  SWITCH_REG_VALUE(0x318)
#define C_VIDROP_MAC0_REG  SWITCH_REG_VALUE(0x31c)
#define C_VEDROP_MAC0_REG  SWITCH_REG_VALUE(0x320)
#define C_RXRL_MAC0_REG  SWITCH_REG_VALUE(0x324)
#define C_RXPAUSE_MAC0_REG  SWITCH_REG_VALUE(0x328)

#define C_TXOKPKT_MAC0_REG  SWITCH_REG_VALUE(0x32c)
#define C_TXOKBYTE_MAC0_REG  SWITCH_REG_VALUE(0x330)
#define C_TXPAUSECOL_MAC0_REG  SWITCH_REG_VALUE(0x334)

#define C_RXOKPKT_MAC1_REG  SWITCH_REG_VALUE(0x400)
#define C_RXOKBYTE_MAC1_REG  SWITCH_REG_VALUE(0x404)
#define C_RXRUNT_MAC1_REG  SWITCH_REG_VALUE(0x408)
#define C_RXLONG_MAC1_REG  SWITCH_REG_VALUE(0x40c)
#define C_RXDROP_MAC1_REG  SWITCH_REG_VALUE(0x410)
#define C_RXCRC_MAC1_REG  SWITCH_REG_VALUE(0x414)
#define C_RXARLDROP_MAC1_REG  SWITCH_REG_VALUE(0x418)
#define C_VIDROP_MAC1_REG  SWITCH_REG_VALUE(0x41c)
#define C_VEDROP_MAC1_REG  SWITCH_REG_VALUE(0x420)
#define C_RXRL_MAC1_REG  SWITCH_REG_VALUE(0x424)
#define C_RXPAUSE_MAC1_REG  SWITCH_REG_VALUE(0x428)

#define C_TXOKPKT_MAC1_REG  SWITCH_REG_VALUE(0x42c)
#define C_TXOKBYTE_MAC1_REG  SWITCH_REG_VALUE(0x430)
#define C_TXPAUSECOL_MAC1_REG  SWITCH_REG_VALUE(0x434)

#define C_TSOKPKT_CPU_REG  SWITCH_REG_VALUE(0x500)
#define C_TSOKBYTE_CPU_REG  SWITCH_REG_VALUE(0x504)
#define C_TSRUNT_CPU_REG  SWITCH_REG_VALUE(0x508)
#define C_TSLONG_CPU_REG  SWITCH_REG_VALUE(0x50c)
#define C_TSNODSTDROP_CPU_REG  SWITCH_REG_VALUE(0x510)
#define C_TSARLDROP_CPU_REG  SWITCH_REG_VALUE(0x514)
#define C_TSVIDROP_CPU_REG  SWITCH_REG_VALUE(0x518)
#define C_TSVEDROP_CPU_REG  SWITCH_REG_VALUE(0x51c)
#define C_TSRL_CPU_REG  SWITCH_REG_VALUE(0x520)

#define C_FSOKPKT_CPU_REG  SWITCH_REG_VALUE(0x524)
#define C_FSOKBYTE_CPU_REG  SWITCH_REG_VALUE(0x528)

#define C_RXOKPKT_MAC2_REG  SWITCH_REG_VALUE(0x600)
#define C_RXOKBYTE_MAC2_REG  SWITCH_REG_VALUE(0x604)
#define C_RXRUNT_MAC2_REG  SWITCH_REG_VALUE(0x608)
#define C_RXLONG_MAC2_REG  SWITCH_REG_VALUE(0x60c)
#define C_RXDROP_MAC2_REG  SWITCH_REG_VALUE(0x610)
#define C_RXCRC_MAC2_REG  SWITCH_REG_VALUE(0x614)
#define C_RXARLDROP_MAC2_REG  SWITCH_REG_VALUE(0x618)
#define C_VIDROP_MAC2_REG  SWITCH_REG_VALUE(0x61c)
#define C_VEDROP_MAC2_REG  SWITCH_REG_VALUE(0x620)
#define C_RXRL_MAC2_REG  SWITCH_REG_VALUE(0x624)
#define C_RXPAUSE_MAC2_REG  SWITCH_REG_VALUE(0x628)

#define C_TXOKPKT_MAC2_REG  SWITCH_REG_VALUE(0x62c)
#define C_TXOKBYTE_MAC2_REG  SWITCH_REG_VALUE(0x630)
#define C_TXPAUSECOL_MAC2_REG  SWITCH_REG_VALUE(0x634)

#define C_TXOKPKT_MAC0_EXT_REG  SWITCH_REG_VALUE(0x72c)
#define C_TXOKBYTE_MAC0_EXT_REG  SWITCH_REG_VALUE(0x730)

#define CLK_GATE_REG PMU_REG_VALUE(0x0) 
#define SOFT_RST_REG PMU_REG_VALUE(0x4)
#define PLL_HM_PD_CTRL_REG PMU_REG_VALUE(0x1c)

#define GPIOB_PIN_EN_REG MISC_REG_VALUE(0x18)
#define IOCDA_REG MISC_REG_VALUE(0x1c)

#define LEVEL_HIGH 0
#define RISING_EDGE 1

#ifdef CONFIG_SILICON

#define STATUS_INTERRUPT_ID 49

#define FSRC_RING0_INTERRUPT_ID 51
#define FSQF_RING0_INTERRUPT_ID 53

#define FSRC_RING1_INTERRUPT_ID 55
#define FSQF_RING1_INTERRUPT_ID 57

#define TSTC_RING0_INTERRUPT_ID 50

#define TSTC_RING1_INTERRUPT_ID 54

#define HNAT_INTERRUPT_ID 58

#else

//#define STATUS_INTERRUPT_ID 49
#define STATUS_INTERRUPT_ID 38
//#define FSRC_RING0_INTERRUPT_ID 51
#define FSRC_RING0_INTERRUPT_ID  40

#define TSQE_RING0_INTERRUPT_ID 52

//#define FSQF_RING0_INTERRUPT_ID 53
#define FSQF_RING0_INTERRUPT_ID 42

#define FSQF_RING1_INTERRUPT_ID 46
#define FSRC_RING1_INTERRUPT_ID 44

//#define FSRC_RING1_INTERRUPT_ID 55

#define TSTC_RING0_INTERRUPT_ID 39
#define TSTC_RING1_INTERRUPT_ID 43

#define TSQE_RING1_INTERRUPT_ID 56
#define HNAT_INTERRUPT_ID 58
#endif // #ifdef CONFIG_SILICON

#endif
