/*
 * Copyright 2006, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h,v 1.1.1.27 2006/04/30 06:13:19 honor Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	4

#define	EPI_MINOR_VERSION	80

#define	EPI_RC_NUMBER		17

#define	EPI_INCREMENTAL_NUMBER	2

#define	EPI_BUILD_NUMBER	0

#define	EPI_VERSION		4, 80, 17, 0

#define	EPI_VERSION_NUM		0x04501100

/* Driver Version String, ASCII, 32 chars max */
#define	EPI_VERSION_STR		"4.80.17.0"
#define	EPI_ROUTER_VERSION_STR	"4.81.17.0"

#endif /* _epivers_h_ */
