#!/bin/bash

set -e

RULESET="
table inet t {
	set s1 {
		type ipv4_addr
		flags interval
		elements = { 192.0.0.0/2, 10.0.0.0/8 }
	}
	set s2 {
		type ipv6_addr
		flags interval
		elements = { ff00::/8, fe80::/10 }
	}
	chain c {
		ip saddr @s1 accept
		ip6 daddr @s2 accept
	}
}"

$NFT -f - <<< "$RULESET"
