#!/bin/sh

. ../eval_tools.sh

HEADER snmpv2c traps are sent by snmpd API

SKIPIFNOT USING_EXAMPLES_EXAMPLE_MODULE

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv3config
CONFIGAGENT trap2sink localhost public $SNMP_SNMPTRAPD_PORT

STARTTRAPD

AGENT_FLAGS="$AGENT_FLAGS"
STARTAGENT

#DELAY
CAPTURE "snmpset -On -t 3 -r 0 $SNMP_FLAGS -v 3 -a MD5 -A initial_test_pass_auth -l anp -u initial udp:localhost:$SNMP_SNMPD_PORT ucdavis.254.8.0 i 1"

STOPAGENT

STOPTRAPD

CHECKTRAPD "life the universe and everything"

FINISHED
