/* module to include the various ucd-snmp specific extension modules. */
config_require(ucd-snmp/proc)
config_require(ucd-snmp/versioninfo)
config_require(ucd-snmp/pass)
config_require(ucd-snmp/pass_persist)
config_require(ucd-snmp/disk)
config_require(ucd-snmp/loadave)
config_require(agent/extend)
config_require(ucd-snmp/errormib)
config_require(ucd-snmp/file)
config_require(ucd-snmp/dlmod)
config_require(ucd-snmp/proxy)
config_require(ucd-snmp/logmatch)
config_require(ucd-snmp/memory)
config_require(ucd-snmp/vmstat)
config_add_mib(UCD-SNMP-MIB)
config_add_mib(UCD-DEMO-MIB)
