/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_CLK_QCOM_NSS_CC_IPQ5210_H
#define _DT_BINDINGS_CLK_QCOM_NSS_CC_IPQ5210_H

#define	NSS_CC_PPE_CLK_SRC			0
#define	NSS_CC_PPE_SWITCH_IPE_CLK		1
#define	NSS_CC_PPE_SWITCH_BTQ_CLK		2
#define	NSS_CC_PPE_SWITCH_CLK			3
#define	NSS_CC_PPE_SWITCH_CFG_CLK		4
#define	NSS_CC_PPE_EDMA_CLK			5
#define	NSS_CC_PPE_EDMA_CFG_CLK			6
#define	NSS_CC_PORT1_MAC_CLK			7
#define	NSS_CC_PORT1_RX_CLK			8
#define	NSS_CC_PORT1_RX_CLK_SRC			9
#define	NSS_CC_PORT1_RX_DIV_CLK_SRC		10
#define	NSS_CC_PORT1_TX_CLK			11
#define	NSS_CC_PORT1_TX_CLK_SRC			12
#define	NSS_CC_PORT1_TX_DIV_CLK_SRC		13
#define	NSS_CC_PORT2_MAC_CLK			14
#define	NSS_CC_PORT2_RX_CLK			15
#define	NSS_CC_PORT2_RX_CLK_SRC			16
#define	NSS_CC_PORT2_RX_DIV_CLK_SRC		17
#define	NSS_CC_PORT2_TX_CLK			18
#define	NSS_CC_PORT2_TX_CLK_SRC			19
#define	NSS_CC_PORT2_TX_DIV_CLK_SRC		20
#define	NSS_CC_PORT3_MAC_CLK			21
#define	NSS_CC_PORT3_RX_CLK			22
#define	NSS_CC_PORT3_RX_CLK_SRC			23
#define	NSS_CC_PORT3_RX_DIV_CLK_SRC		24
#define	NSS_CC_PORT3_TX_CLK			25
#define	NSS_CC_PORT3_TX_CLK_SRC			26
#define	NSS_CC_PORT3_TX_DIV_CLK_SRC		27
#define	NSS_CC_PORT4_MAC_CLK			28
#define	NSS_CC_PORT4_RX_CLK			29
#define	NSS_CC_PORT4_RX_CLK_SRC			30
#define	NSS_CC_PORT4_RX_DIV_CLK_SRC		31
#define	NSS_CC_PORT4_TX_CLK			32
#define	NSS_CC_PORT4_TX_CLK_SRC			33
#define	NSS_CC_PORT4_TX_DIV_CLK_SRC		34
#define	NSS_CC_PORT5_MAC_CLK			35
#define	NSS_CC_PORT5_RX_CLK			36
#define	NSS_CC_PORT5_RX_CLK_SRC			37
#define	NSS_CC_PORT5_RX_DIV_CLK_SRC		38
#define	NSS_CC_PORT5_TX_CLK			39
#define	NSS_CC_PORT5_TX_CLK_SRC			40
#define	NSS_CC_PORT5_TX_DIV_CLK_SRC		41
#define	NSS_CC_PORT6_MAC_CLK			42
#define	NSS_CC_PORT6_RX_CLK			43
#define	NSS_CC_PORT6_RX_CLK_SRC			44
#define	NSS_CC_PORT6_RX_DIV_CLK_SRC		45
#define	NSS_CC_PORT6_TX_CLK			46
#define	NSS_CC_PORT6_TX_CLK_SRC			47
#define	NSS_CC_PORT6_TX_DIV_CLK_SRC		48
#define	NSS_CC_NSSNOC_PPE_CLK			49
#define	NSS_CC_NSSNOC_PPE_CFG_CLK		50
#define	NSS_CC_UNIPHY_PORT1_RX_CLK		51
#define	NSS_CC_UNIPHY_PORT1_TX_CLK		52
#define	NSS_CC_UNIPHY_PORT2_RX_CLK		53
#define	NSS_CC_UNIPHY_PORT2_TX_CLK		54
#define	NSS_CC_UNIPHY_PORT3_RX_CLK		55
#define	NSS_CC_UNIPHY_PORT3_TX_CLK		56
#define	NSS_CC_UNIPHY_PORT4_RX_CLK		57
#define	NSS_CC_UNIPHY_PORT4_TX_CLK		58
#define	NSS_CC_UNIPHY_PORT5_RX_CLK		59
#define	NSS_CC_UNIPHY_PORT5_TX_CLK		60
#define	NSS_CC_UNIPHY_PORT6_RX_CLK		61
#define	NSS_CC_UNIPHY_PORT6_TX_CLK		62
#define	NSS_CC_XGMAC0_PTP_REF_CLK		63
#define	NSS_CC_XGMAC0_PTP_REF_DIV_CLK_SRC	64
#define	NSS_CC_XGMAC1_PTP_REF_CLK		65
#define	NSS_CC_XGMAC1_PTP_REF_DIV_CLK_SRC	66
#define	NSS_CC_XGMAC2_PTP_REF_CLK		67
#define	NSS_CC_XGMAC2_PTP_REF_DIV_CLK_SRC	68
#define	NSS_CC_PON_CLK				69
#define	NSS_CC_EPHY_RX_CLK_SRC			70
#define	NSS_CC_EPHY_RX_CLK			71
#define	NSS_CC_EPHY_TX_CLK_SRC			72
#define	NSS_CC_EPHY_TX_CLK			73
#define	NSS_CC_UNIPHY_PORT1_RX_DIV4_CLK_SRC	74
#define	NSS_CC_UNIPHY_PORT1_TX_DIV4_CLK_SRC	75
#define	NSS_CC_UNIPHY_PORT2_RX_DIV4_CLK_SRC	76
#define	NSS_CC_UNIPHY_PORT2_TX_DIV4_CLK_SRC	77
#define	NSS_CC_UNIPHY_PORT3_RX_DIV4_CLK_SRC	78
#define	NSS_CC_UNIPHY_PORT3_TX_DIV4_CLK_SRC	79
#define	NSS_CC_UNIPHY_PORT4_RX_DIV4_CLK_SRC	80
#define	NSS_CC_UNIPHY_PORT4_TX_DIV4_CLK_SRC	81
#define	NSS_CC_UNIPHY_PORT1_RX_DIV4_CLK		82
#define	NSS_CC_UNIPHY_PORT1_TX_DIV4_CLK		83
#define	NSS_CC_UNIPHY_PORT2_RX_DIV4_CLK		84
#define	NSS_CC_UNIPHY_PORT2_TX_DIV4_CLK		85
#define	NSS_CC_UNIPHY_PORT3_RX_DIV4_CLK		86
#define	NSS_CC_UNIPHY_PORT3_TX_DIV4_CLK		87
#define	NSS_CC_UNIPHY_PORT4_RX_DIV4_CLK		88
#define	NSS_CC_UNIPHY_PORT4_TX_DIV4_CLK		89
#define	NSS_CC_EIP_BFDCD_CLK_SRC		90
#define	NSS_CC_EIP_CLK				91
#define	NSS_CC_NSSNOC_EIP_CLK			92
#define	NSS_CC_CFG_CLK_SRC			93
#define	NSS_CC_NSS_CSR_CLK			94
#define	NSS_CC_NSSNOC_NSS_CSR_CLK		95

#endif
