/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_CLK_QCOM_NSS_CC_IPQ9650_H
#define _DT_BINDINGS_CLK_QCOM_NSS_CC_IPQ9650_H

#define NSS_CC_PPE_CLK_SRC				0
#define NSS_CC_PPE_SWITCH_IPE_CLK			1
#define NSS_CC_PPE_SWITCH_BTQ_CLK			2
#define NSS_CC_PPE_SWITCH_CLK				3
#define NSS_CC_PPE_SWITCH_CFG_CLK			4
#define NSS_CC_PPE_EDMA_CLK				5
#define NSS_CC_PPE_EDMA_CFG_CLK				6
#define NSS_CC_EIP_PPE_CLK				7
#define NSS_CC_PORT1_MAC_CLK				8
#define NSS_CC_PORT1_RX_CLK				9
#define NSS_CC_PORT1_RX_CLK_SRC				10
#define NSS_CC_PORT1_RX_DIV_CLK_SRC			11
#define NSS_CC_PORT1_TX_CLK				12
#define NSS_CC_PORT1_TX_CLK_SRC				13
#define NSS_CC_PORT1_TX_DIV_CLK_SRC			14
#define NSS_CC_PORT2_MAC_CLK				15
#define NSS_CC_PORT2_RX_CLK				16
#define NSS_CC_PORT2_RX_CLK_SRC				17
#define NSS_CC_PORT2_RX_DIV_CLK_SRC			18
#define NSS_CC_PORT2_TX_CLK				19
#define NSS_CC_PORT2_TX_CLK_SRC				20
#define NSS_CC_PORT2_TX_DIV_CLK_SRC			21
#define NSS_CC_PORT3_MAC_CLK				22
#define NSS_CC_PORT3_RX_CLK				23
#define NSS_CC_PORT3_RX_CLK_SRC				24
#define NSS_CC_PORT3_RX_DIV_CLK_SRC			25
#define NSS_CC_PORT3_TX_CLK				26
#define NSS_CC_PORT3_TX_CLK_SRC				27
#define NSS_CC_PORT3_TX_DIV_CLK_SRC			28
#define NSS_CC_PORT4_MAC_CLK				29
#define NSS_CC_PORT4_RX_CLK				30
#define NSS_CC_PORT4_RX_CLK_SRC				31
#define NSS_CC_PORT4_RX_DIV_CLK_SRC			32
#define NSS_CC_PORT4_TX_CLK				33
#define NSS_CC_PORT4_TX_CLK_SRC				34
#define NSS_CC_PORT4_TX_DIV_CLK_SRC			35
#define NSS_CC_PORT5_MAC_CLK				36
#define NSS_CC_PORT5_RX_CLK				37
#define NSS_CC_PORT5_RX_CLK_SRC				38
#define NSS_CC_PORT5_RX_DIV_CLK_SRC			39
#define NSS_CC_PORT5_TX_CLK				40
#define NSS_CC_PORT5_TX_CLK_SRC				41
#define NSS_CC_PORT5_TX_DIV_CLK_SRC			42
#define NSS_CC_PORT6_MAC_CLK				43
#define NSS_CC_PORT6_RX_CLK				44
#define NSS_CC_PORT6_RX_CLK_SRC				45
#define NSS_CC_PORT6_RX_DIV_CLK_SRC			46
#define NSS_CC_PORT6_TX_CLK				47
#define NSS_CC_PORT6_TX_CLK_SRC				48
#define NSS_CC_PORT6_TX_DIV_CLK_SRC			49
#define NSS_CC_NSSNOC_PPE_CLK				50
#define NSS_CC_NSSNOC_PPE_CFG_CLK			51
#define NSS_CC_UNIPHY_PORT1_RX_CLK			52
#define NSS_CC_UNIPHY_PORT1_TX_CLK			53
#define NSS_CC_UNIPHY_PORT2_RX_CLK			54
#define NSS_CC_UNIPHY_PORT2_TX_CLK			55
#define NSS_CC_UNIPHY_PORT3_RX_CLK			56
#define NSS_CC_UNIPHY_PORT3_TX_CLK			57
#define NSS_CC_UNIPHY_PORT4_RX_CLK			58
#define NSS_CC_UNIPHY_PORT4_TX_CLK			59
#define NSS_CC_UNIPHY_PORT5_RX_CLK			60
#define NSS_CC_UNIPHY_PORT5_TX_CLK			61
#define NSS_CC_UNIPHY_PORT6_RX_CLK			62
#define NSS_CC_UNIPHY_PORT6_TX_CLK			63
#define NSS_CC_XGMAC0_PTP_REF_CLK			64
#define NSS_CC_XGMAC0_PTP_REF_DIV_CLK_SRC		65
#define NSS_CC_XGMAC1_PTP_REF_CLK			66
#define NSS_CC_XGMAC1_PTP_REF_DIV_CLK_SRC		67
#define NSS_CC_XGMAC2_PTP_REF_CLK			68
#define NSS_CC_XGMAC2_PTP_REF_DIV_CLK_SRC		69
#define NSS_CC_XGMAC3_PTP_REF_CLK			70
#define NSS_CC_XGMAC3_PTP_REF_DIV_CLK_SRC		71
#define NSS_CC_XGMAC4_PTP_REF_CLK			72
#define NSS_CC_XGMAC4_PTP_REF_DIV_CLK_SRC		73
#define NSS_CC_XGMAC5_PTP_REF_CLK			74
#define NSS_CC_XGMAC5_PTP_REF_DIV_CLK_SRC		75
#define NSS_CC_CE_CLK_SRC				76
#define NSS_CC_CE_APB_CLK				77
#define NSS_CC_NSSNOC_CE_APB_CLK			78
#define NSS_CC_CE_DIV_CLK_SRC				79
#define NSS_CC_CE_AXI_CLK				80
#define NSS_CC_NSSNOC_CE_AXI_CLK			81
#define NSS_CC_EIP_BFDCD_CLK_SRC			82
#define NSS_CC_EIP_CLK					83
#define NSS_CC_NSSNOC_EIP_CLK				84
#define NSS_CC_CFG_CLK_SRC				85
#define NSS_CC_NSS_CSR_CLK				86
#define NSS_CC_NSSNOC_NSS_CSR_CLK			87

#endif
