.TH chkpib2 1 "November 2013" "open-plc-utils-0.0.3" "Qualcomm Atheros Open Powerline Toolkit"

.SH NAME
chkpib2 - Qualcomm Atheros PLC Parameter File Inspector

.SH SYNOPSIS
.BR chkpib2
.RI [ options ]
.IR file
.RI [ file ]
[...]

.SH DESCRIPTION
This program checks Atheros HomePlug AV parameter files for obvious errors, including obsolete format, wrong file size, bad checksums and read errors.
It makes no attempt to check internal information other than file length and checksum.

.PP
This program handles both the older \fBThunderbolt\fR and \fBLightning\fR and the newer \fBPanther\fR and \fBLynx\fR parameter file formats.
It validates files directly from memory and so it is faster than program \fBchkpib\fR but needs more memory at runtime.

.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBAMP\fR man page for an overview and installation instructions.

.SH OPTIONS

.TP
.RB - m
Display manifest content, if present.
The manifest is a special module, included in some image chains, that contains useful information about the chain.
This option suppresses the summary 'looks good' message.

.TP
.RB - q
Suppresses printing of progress messages.

.TP
.RB - v
Print additional information such as the PIB header for each file processed.
This information can be used to confirm pib version and distinguish one PIB file from another.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH ARGUMENTS

.TP
.IR file
The name of a runtime parameter file.
By convention, runtime parameter files have a \fB.pib\fR extention but this program does not enforce that convention.

.SH DISCLAIMER
Qualcomm Atheros parameter file structure and content is proprietary to Qualcomm Atheros, Ocala FL USA.
Consequently, public information is not available.
Qualcomm Atheros reserves the right to change parameter file structure or content or change the name or behavior of any program that inspects or changes parameter files, in future software releases without any obligation to notify or compensate users of such programs.

.SH EXAMPLES
The next example reads file \fBabc.pib\fR and validates it.
The message shown indicates that the PIB version is recent, the file is the correct size, the checksum is valid computes and there are no read errors.

.PP
   # chkpib2 abc.pib
   abc.pib looks good

.PP
The next example reads three files and reports on each one.
You can suppress good news with the \fB-q\fR option.
Remember that "\fBlooking good\fR" does not mean "\fBis good\fR".

.PP
   # chkpib2 INT6400.pib AR7400.pib AR7420.pib
   INT6400.pib looks good
   AR7400.pib looks good
   AR7420.pib looks good

.PP
The next example reads three files and displays selected information about each one because option \fB-v\fR is present.

.PP
   # chkpib2 -v INT6400.pib AR7400.pib AR7420.pib
   ------- INT6400.pib -------
           PIB 4-2 10888 bytes
           MAC 00:B0:52:BA:BE:00
           DAK 68:9F:07:4B:8B:02:75:A2:71:0B:0B:57:79:AD:16:30 (HomePlugAV)
           NMK 50:D3:E4:93:3F:85:5B:70:40:78:4D:F8:15:AA:8D:B7 (HomePlugAV)
           NID B0:F2:E6:95:66:6B:03
           NET Intellon Enabled Network
           MFG Intellon HomePlug AV Device
           USR Intellon Enabled Product
           CCo Auto
           MDU N/A
   ------- AR7400.pib -------
           PIB 7-1 16352 bytes
           MAC 00:B0:52:00:00:08
           DAK F0:84:B4:E8:F6:06:9F:F1:30:0C:9B:DB:81:23:67:FF (HomePlugAV0123)
           NMK 50:D3:E4:93:3F:85:5B:70:40:78:4D:F8:15:AA:8D:B7 (HomePlugAV)
           NID B0:F2:E6:95:66:6B:03
           NET Atheros Enabled Network
           MFG Atheros HomePlug AV Device
           USR Intergalactic Software Pirates
           CCo Never
           MDU Slave
   ------- AR7420.pib -------
           PIB 0-2 10904 bytes
           MAC 00:B0:52:00:00:01
           DAK 68:9F:07:4B:8B:02:75:A2:71:0B:0B:57:79:AD:16:30 (HomePlugAV)
           NMK 50:D3:E4:93:3F:85:5B:70:40:78:4D:F8:15:AA:8D:B7 (HomePlugAV)
           NID B0:F2:E6:95:66:6B:03
           NET Atheros Enabled Network
           MFG Atheros HomePlug AV Device
           USR Atheros Enabled Product
           CCo Auto
           MDU N/A

.PP
This example prints the manifest found inside newer parameter files.
This can be used to distinguish parameter files from firmware files, determine exact firmware or parameter file revisions and so forth.
Observe that we specified several files on the command line but only one file, \fBAR7420.pib\fR, contained a manifest.

.PP
   # chkpib2 -m INT6400.pib AR7400.pib AR7420.pib
   ------- AR7420.pib (0) -------
           Signature: 1234ABCD
           Hardware Compatibility: AR74200
           Chain Major Version: 0
           Chain Minor Version: 1
           Chain Type: Parameter Block
           Build Major Version: 0
           Build Minor Version: 0
           Build Type: Special
           Manifest Version: 1
           Build Number: 0
           Build Date: 20110811
           Build Time: 203853
           Device Type: 29728
           Build Hostname: TOR-SW-SIM04
           Build Username: buildbot
           Build Description: Custom
           Build Version String: AR-7420-FW-0_0-0_2-20110811:203853-buildbot:TOR-SW-SIM04-1-0_1

.SH SEE ALSO
.BR chkpib (7),
.BR getpib (7 ),
.BR modpib ( 1 ),
.BR pib2xml ( 1 ),
.BR pibcomp ( 1 ),
.BR pibdump ( 1 ),
.BR setpib ( 1 ),
.BR xml2pib ( 1 )

.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>
 Nathaniel Houghton <nhoughto@qca.qualcomm.com>

