.TH psout 1 "November 2013" "open-plc-utils-0.0.3" "Qualcomm Atheros Open Powerline Toolkit"

.SH NAME
psout - Export PIB Prescalers

.SH SYNOPSIS
.BR psout 
.RI [ options ]
.IR file 
.RI [> stdout ]

.SH DESCRIPTION
Export the prescaler section of a PIB file as an amplitude map suitable for input to program \fBpsin\fR or the Qualcomm Atheros Windows Device Manager.
Prescalers are stored in the PIB in binary format but the amplitude map is in text format so that values may be changed using an ordinary text editor.
Program \fBpsin\fR can be used to import an amplitude map into the original or another PIB file.

.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBAMP\fR man page for an overview and installation instructions.

.SH OPTIONS
None.

.SH ARGUMENTS

.TP
.IR file
The name of an Atheros Parameter Information Block (\fBPIB\fR) file.
This file is not modified.
By convention, PIB files have a \fB.pib\fR extension but this program does not enforce that convention and does not make any assumption based on filename or extension but the program will reject invalid PIB files.
Only one filename is permitted on the command line.

.SH FILES
An amplitude map consists of 1155 frequency-amplitude pairs.
Each pair consists of a decimal \fBindex\fR and a hexadecimal \fBscaler\fR.
The index represents a frequecy from 1.8 mhz through 30 mhz.
The \fBscaler\fR represents the amplitude attenuation applied at that frequency.
The frequency and attenuation are computed as follows.

.PP
	\fBfrequency = 40.96 * (index + 74)\fR 

.PP
	\fBindex = (frequency / 40.96) - 74\fR

.PP
	\fBdecibels = 20 * log10 (scaler / 256)\fR

.PP
	\fBscaler = 256 * pow (decibels / 20)\fR

.SH EXAMPLES
The following example prints the prescaler section of file \fBabc.pib\fR on stdout as an amplitude map.
The output has been abbreviated here to save space.
A single comment line identifies the prescaler source file.
Output may be directed to a text file, edited using a text editor and read into the same or another PIB file with program \fBpsin\fR.

.PP
   # psout abc.pib
   # file: abc.pib
   00000000 00000000
   00000001 00000000
   00000002 00000000
   00000003 00000000
   ...
   00000027 000000D0
   00000028 000000D0
   00000029 000000D1
   00000030 000000D1
   ...
   00000214 00000000
   00000215 00000000
   00000216 00000000
   ...
   00001155 00000000

.PP
The next example copies prescalers from file \fBabc.pib\fR to \fBdef.pib\fR using a command line pipe.

.PP
   # psout abc.pib | psin def.pib

.SH DISCLAIMER
PIB file structure and content is proprietary to Qualcomm Atheros, Ocala FL USA.
Consequently, public information is not available.
Qualcomm Atheros reserves the right to modify PIB file structure or content in future firmware releases without any obligation to notify or compensate users of this program.

.PP
Tampering with prescaler settings may violate national or international electo-magnetic emission standards and lead to fines or penalties.
Qualcomm Atheros shall not be held responsible for any consequences of modifications made to prescaler sets provided to their customers.

.SH SEE ALSO
.BR psgraph ( 1 ),
.BR pskey ( 1 ),
.BR psin ( 1 )

.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>

