/* Automatically generated with enum2debug.pl: Don't edit! */

#include <stdio.h>

#include "vpnc-debug.h"
#include "isakmp.h"

const char *val_to_string(unsigned int val, const struct debug_strings *dstrings)
{
	static const char *unknown = " (unknown)";
	static const char *na = "";
	unsigned int i;
	
	if (dstrings == NULL)
		return na;
	
	for (i = 0; dstrings[i].id != 0 || dstrings[i].string != NULL; i++)
		if (dstrings[i].id == val)
			return dstrings[i].string;
	return unknown;
}

const struct debug_strings isakmp_payload_enum_array[] = {
	{ ISAKMP_PAYLOAD_NONE,	" (ISAKMP_PAYLOAD_NONE)" },
	{ ISAKMP_PAYLOAD_SA,	" (ISAKMP_PAYLOAD_SA)" },
	{ ISAKMP_PAYLOAD_P,	" (ISAKMP_PAYLOAD_P)" },
	{ ISAKMP_PAYLOAD_T,	" (ISAKMP_PAYLOAD_T)" },
	{ ISAKMP_PAYLOAD_KE,	" (ISAKMP_PAYLOAD_KE)" },
	{ ISAKMP_PAYLOAD_ID,	" (ISAKMP_PAYLOAD_ID)" },
	{ ISAKMP_PAYLOAD_CERT,	" (ISAKMP_PAYLOAD_CERT)" },
	{ ISAKMP_PAYLOAD_CR,	" (ISAKMP_PAYLOAD_CR)" },
	{ ISAKMP_PAYLOAD_HASH,	" (ISAKMP_PAYLOAD_HASH)" },
	{ ISAKMP_PAYLOAD_SIG,	" (ISAKMP_PAYLOAD_SIG)" },
	{ ISAKMP_PAYLOAD_NONCE,	" (ISAKMP_PAYLOAD_NONCE)" },
	{ ISAKMP_PAYLOAD_N,	" (ISAKMP_PAYLOAD_N)" },
	{ ISAKMP_PAYLOAD_D,	" (ISAKMP_PAYLOAD_D)" },
	{ ISAKMP_PAYLOAD_VID,	" (ISAKMP_PAYLOAD_VID)" },
	{ ISAKMP_PAYLOAD_MODECFG_ATTR,	" (ISAKMP_PAYLOAD_MODECFG_ATTR)" },
	{ ISAKMP_PAYLOAD_SAK,	" (ISAKMP_PAYLOAD_SAK)" },
	{ ISAKMP_PAYLOAD_SAT,	" (ISAKMP_PAYLOAD_SAT)" },
	{ ISAKMP_PAYLOAD_KD,	" (ISAKMP_PAYLOAD_KD)" },
	{ ISAKMP_PAYLOAD_SEQNO,	" (ISAKMP_PAYLOAD_SEQNO)" },
	{ ISAKMP_PAYLOAD_POP,	" (ISAKMP_PAYLOAD_POP)" },
	{ ISAKMP_PAYLOAD_NAT_D,	" (ISAKMP_PAYLOAD_NAT_D)" },
	{ ISAKMP_PAYLOAD_NAT_OA,	" (ISAKMP_PAYLOAD_NAT_OA)" },
	{ ISAKMP_PAYLOAD_NAT_D_OLD,	" (ISAKMP_PAYLOAD_NAT_D_OLD)" },
	{ ISAKMP_PAYLOAD_FRAG,	" (ISAKMP_PAYLOAD_FRAG)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_exchange_enum_array[] = {
	{ ISAKMP_EXCHANGE_NONE,	" (ISAKMP_EXCHANGE_NONE)" },
	{ ISAKMP_EXCHANGE_BASE,	" (ISAKMP_EXCHANGE_BASE)" },
	{ ISAKMP_EXCHANGE_IDENTITY,	" (ISAKMP_EXCHANGE_IDENTITY)" },
	{ ISAKMP_EXCHANGE_AUTH_ONLY,	" (ISAKMP_EXCHANGE_AUTH_ONLY)" },
	{ ISAKMP_EXCHANGE_AGGRESSIVE,	" (ISAKMP_EXCHANGE_AGGRESSIVE)" },
	{ ISAKMP_EXCHANGE_INFORMATIONAL,	" (ISAKMP_EXCHANGE_INFORMATIONAL)" },
	{ ISAKMP_EXCHANGE_MODECFG_TRANSACTION,	" (ISAKMP_EXCHANGE_MODECFG_TRANSACTION)" },
	{ ISAKMP_EXCHANGE_IKE_QUICK,	" (ISAKMP_EXCHANGE_IKE_QUICK)" },
	{ ISAKMP_EXCHANGE_IKE_NEW_GROUP,	" (ISAKMP_EXCHANGE_IKE_NEW_GROUP)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_doi_enum_array[] = {
	{ ISAKMP_DOI_GENERIC,	" (ISAKMP_DOI_GENERIC)" },
	{ ISAKMP_DOI_IPSEC,	" (ISAKMP_DOI_IPSEC)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_notify_enum_array[] = {
	{ ISAKMP_N_INVALID_PAYLOAD_TYPE,	" (ISAKMP_N_INVALID_PAYLOAD_TYPE)" },
	{ ISAKMP_N_DOI_NOT_SUPPORTED,	" (ISAKMP_N_DOI_NOT_SUPPORTED)" },
	{ ISAKMP_N_SITUATION_NOT_SUPPORTED,	" (ISAKMP_N_SITUATION_NOT_SUPPORTED)" },
	{ ISAKMP_N_INVALID_COOKIE,	" (ISAKMP_N_INVALID_COOKIE)" },
	{ ISAKMP_N_INVALID_MAJOR_VERSION,	" (ISAKMP_N_INVALID_MAJOR_VERSION)" },
	{ ISAKMP_N_INVALID_MINOR_VERSION,	" (ISAKMP_N_INVALID_MINOR_VERSION)" },
	{ ISAKMP_N_INVALID_EXCHANGE_TYPE,	" (ISAKMP_N_INVALID_EXCHANGE_TYPE)" },
	{ ISAKMP_N_INVALID_FLAGS,	" (ISAKMP_N_INVALID_FLAGS)" },
	{ ISAKMP_N_INVALID_MESSAGE_ID,	" (ISAKMP_N_INVALID_MESSAGE_ID)" },
	{ ISAKMP_N_INVALID_PROTOCOL_ID,	" (ISAKMP_N_INVALID_PROTOCOL_ID)" },
	{ ISAKMP_N_INVALID_SPI,	" (ISAKMP_N_INVALID_SPI)" },
	{ ISAKMP_N_INVALID_TRANSFORM_ID,	" (ISAKMP_N_INVALID_TRANSFORM_ID)" },
	{ ISAKMP_N_ATTRIBUTES_NOT_SUPPORTED,	" (ISAKMP_N_ATTRIBUTES_NOT_SUPPORTED)" },
	{ ISAKMP_N_NO_PROPOSAL_CHOSEN,	" (ISAKMP_N_NO_PROPOSAL_CHOSEN)" },
	{ ISAKMP_N_BAD_PROPOSAL_SYNTAX,	" (ISAKMP_N_BAD_PROPOSAL_SYNTAX)" },
	{ ISAKMP_N_PAYLOAD_MALFORMED,	" (ISAKMP_N_PAYLOAD_MALFORMED)" },
	{ ISAKMP_N_INVALID_KEY_INFORMATION,	" (ISAKMP_N_INVALID_KEY_INFORMATION)" },
	{ ISAKMP_N_INVALID_ID_INFORMATION,	" (ISAKMP_N_INVALID_ID_INFORMATION)" },
	{ ISAKMP_N_INVALID_CERT_ENCODING,	" (ISAKMP_N_INVALID_CERT_ENCODING)" },
	{ ISAKMP_N_INVALID_CERTIFICATE,	" (ISAKMP_N_INVALID_CERTIFICATE)" },
	{ ISAKMP_N_CERT_TYPE_UNSUPPORTED,	" (ISAKMP_N_CERT_TYPE_UNSUPPORTED)" },
	{ ISAKMP_N_INVALID_CERT_AUTHORITY,	" (ISAKMP_N_INVALID_CERT_AUTHORITY)" },
	{ ISAKMP_N_INVALID_HASH_INFORMATION,	" (ISAKMP_N_INVALID_HASH_INFORMATION)" },
	{ ISAKMP_N_AUTHENTICATION_FAILED,	" (ISAKMP_N_AUTHENTICATION_FAILED)" },
	{ ISAKMP_N_INVALID_SIGNATURE,	" (ISAKMP_N_INVALID_SIGNATURE)" },
	{ ISAKMP_N_ADDRESS_NOTIFICATION,	" (ISAKMP_N_ADDRESS_NOTIFICATION)" },
	{ ISAKMP_N_NOTIFY_SA_LIFETIME,	" (ISAKMP_N_NOTIFY_SA_LIFETIME)" },
	{ ISAKMP_N_CERTIFICATE_UNAVAILABLE,	" (ISAKMP_N_CERTIFICATE_UNAVAILABLE)" },
	{ ISAKMP_N_UNSUPPORTED_EXCHANGE_TYPE,	" (ISAKMP_N_UNSUPPORTED_EXCHANGE_TYPE)" },
	{ ISAKMP_N_UNEQUAL_PAYLOAD_LENGTHS,	" (ISAKMP_N_UNEQUAL_PAYLOAD_LENGTHS)" },
	{ ISAKMP_N_CONNECTED,	" (ISAKMP_N_CONNECTED)" },
	{ ISAKMP_N_IPSEC_RESPONDER_LIFETIME,	" (ISAKMP_N_IPSEC_RESPONDER_LIFETIME)" },
	{ ISAKMP_N_IPSEC_REPLAY_STATUS,	" (ISAKMP_N_IPSEC_REPLAY_STATUS)" },
	{ ISAKMP_N_IPSEC_INITIAL_CONTACT,	" (ISAKMP_N_IPSEC_INITIAL_CONTACT)" },
	{ ISAKMP_N_CISCO_HELLO,	" (ISAKMP_N_CISCO_HELLO)" },
	{ ISAKMP_N_CISCO_WWTEBR,	" (ISAKMP_N_CISCO_WWTEBR)" },
	{ ISAKMP_N_CISCO_SHUT_UP,	" (ISAKMP_N_CISCO_SHUT_UP)" },
	{ ISAKMP_N_IOS_KEEP_ALIVE_REQ,	" (ISAKMP_N_IOS_KEEP_ALIVE_REQ)" },
	{ ISAKMP_N_IOS_KEEP_ALIVE_ACK,	" (ISAKMP_N_IOS_KEEP_ALIVE_ACK)" },
	{ ISAKMP_N_R_U_THERE,	" (ISAKMP_N_R_U_THERE)" },
	{ ISAKMP_N_R_U_THERE_ACK,	" (ISAKMP_N_R_U_THERE_ACK)" },
	{ ISAKMP_N_CISCO_LOAD_BALANCE,	" (ISAKMP_N_CISCO_LOAD_BALANCE)" },
	{ ISAKMP_N_CISCO_PRESHARED_KEY_HASH,	" (ISAKMP_N_CISCO_PRESHARED_KEY_HASH)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings dwr_ike_delete_array[] = {
	{ IKE_DELETE_SERVER_SHUTDOWN,	" (IKE_DELETE_SERVER_SHUTDOWN)" },
	{ IKE_DELETE_SERVER_REBOOT,	" (IKE_DELETE_SERVER_REBOOT)" },
	{ IKE_DELETE_MAX_CONNECT_TIME,	" (IKE_DELETE_MAX_CONNECT_TIME)" },
	{ IKE_DELETE_BY_USER_COMMAND,	" (IKE_DELETE_BY_USER_COMMAND)" },
	{ IKE_DELETE_BY_ERROR,	" (IKE_DELETE_BY_ERROR)" },
	{ IKE_DELETE_NO_ERROR,	" (IKE_DELETE_NO_ERROR)" },
	{ IKE_DELETE_IDLE_TIMEOUT,	" (IKE_DELETE_IDLE_TIMEOUT)" },
	{ IKE_DELETE_P2_PROPOSAL_MISMATCH,	" (IKE_DELETE_P2_PROPOSAL_MISMATCH)" },
	{ IKE_DELETE_FIREWALL_MISMATCH,	" (IKE_DELETE_FIREWALL_MISMATCH)" },
	{ IKE_DELETE_CERT_EXPIRED,	" (IKE_DELETE_CERT_EXPIRED)" },
	{ IKE_DELETE_BY_EXPIRED_LIFETIME,	" (IKE_DELETE_BY_EXPIRED_LIFETIME)" },
	{ DEL_REASON_RESET_SADB,	" (DEL_REASON_RESET_SADB)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_certificate_enum_array[] = {
	{ ISAKMP_CERT_NONE,	" (ISAKMP_CERT_NONE)" },
	{ ISAKMP_CERT_PKCS7_X509,	" (ISAKMP_CERT_PKCS7_X509)" },
	{ ISAKMP_CERT_PGP,	" (ISAKMP_CERT_PGP)" },
	{ ISAKMP_CERT_DNS_SIG_KEY,	" (ISAKMP_CERT_DNS_SIG_KEY)" },
	{ ISAKMP_CERT_X509_SIG,	" (ISAKMP_CERT_X509_SIG)" },
	{ ISAKMP_CERT_X509_KEX_EXCHANGE,	" (ISAKMP_CERT_X509_KEX_EXCHANGE)" },
	{ ISAKMP_CERT_KERBEROS_TOKENS,	" (ISAKMP_CERT_KERBEROS_TOKENS)" },
	{ ISAKMP_CERT_CRL,	" (ISAKMP_CERT_CRL)" },
	{ ISAKMP_CERT_ARL,	" (ISAKMP_CERT_ARL)" },
	{ ISAKMP_CERT_SPKI,	" (ISAKMP_CERT_SPKI)" },
	{ ISAKMP_CERT_X509_ATTRIBUTE,	" (ISAKMP_CERT_X509_ATTRIBUTE)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_attr_enum_array[] = {
	{ IKE_ATTRIB_ENC,	" (IKE_ATTRIB_ENC)" },
	{ IKE_ATTRIB_HASH,	" (IKE_ATTRIB_HASH)" },
	{ IKE_ATTRIB_AUTH_METHOD,	" (IKE_ATTRIB_AUTH_METHOD)" },
	{ IKE_ATTRIB_GROUP_DESC,	" (IKE_ATTRIB_GROUP_DESC)" },
	{ IKE_ATTRIB_GROUP_TYPE,	" (IKE_ATTRIB_GROUP_TYPE)" },
	{ IKE_ATTRIB_GROUP_PRIME,	" (IKE_ATTRIB_GROUP_PRIME)" },
	{ IKE_ATTRIB_GROUP_GEN_1,	" (IKE_ATTRIB_GROUP_GEN_1)" },
	{ IKE_ATTRIB_GROUP_GEN_2,	" (IKE_ATTRIB_GROUP_GEN_2)" },
	{ IKE_ATTRIB_GROUP_CURVE_A,	" (IKE_ATTRIB_GROUP_CURVE_A)" },
	{ IKE_ATTRIB_GROUP_CURVE_B,	" (IKE_ATTRIB_GROUP_CURVE_B)" },
	{ IKE_ATTRIB_LIFE_TYPE,	" (IKE_ATTRIB_LIFE_TYPE)" },
	{ IKE_ATTRIB_LIFE_DURATION,	" (IKE_ATTRIB_LIFE_DURATION)" },
	{ IKE_ATTRIB_PRF,	" (IKE_ATTRIB_PRF)" },
	{ IKE_ATTRIB_KEY_LENGTH,	" (IKE_ATTRIB_KEY_LENGTH)" },
	{ IKE_ATTRIB_FIELD_SIZE,	" (IKE_ATTRIB_FIELD_SIZE)" },
	{ IKE_ATTRIB_GROUP_ORDER,	" (IKE_ATTRIB_GROUP_ORDER)" },
	{ IKE_ATTRIB_BLOCK_SIZE,	" (IKE_ATTRIB_BLOCK_SIZE)" },
	{ IKE_ATTRIB_NORTEL_UNKNOWN,	" (IKE_ATTRIB_NORTEL_UNKNOWN)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_enc_enum_array[] = {
	{ IKE_ENC_NO_CBC,	" (IKE_ENC_NO_CBC)" },
	{ IKE_ENC_DES_CBC,	" (IKE_ENC_DES_CBC)" },
	{ IKE_ENC_IDEA_CBC,	" (IKE_ENC_IDEA_CBC)" },
	{ IKE_ENC_BLOWFISH_CBC,	" (IKE_ENC_BLOWFISH_CBC)" },
	{ IKE_ENC_RC5_R16_B16_CBC,	" (IKE_ENC_RC5_R16_B16_CBC)" },
	{ IKE_ENC_3DES_CBC,	" (IKE_ENC_3DES_CBC)" },
	{ IKE_ENC_CAST_CBC,	" (IKE_ENC_CAST_CBC)" },
	{ IKE_ENC_AES_CBC,	" (IKE_ENC_AES_CBC)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_hash_enum_array[] = {
	{ IKE_HASH_MD5,	" (IKE_HASH_MD5)" },
	{ IKE_HASH_SHA,	" (IKE_HASH_SHA)" },
	{ IKE_HASH_TIGER,	" (IKE_HASH_TIGER)" },
	{ IKE_HASH_SHA2_256,	" (IKE_HASH_SHA2_256)" },
	{ IKE_HASH_SHA2_384,	" (IKE_HASH_SHA2_384)" },
	{ IKE_HASH_SHA2_512,	" (IKE_HASH_SHA2_512)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_auth_enum_array[] = {
	{ IKE_AUTH_PRESHARED,	" (IKE_AUTH_PRESHARED)" },
	{ IKE_AUTH_DSS,	" (IKE_AUTH_DSS)" },
	{ IKE_AUTH_RSA_SIG,	" (IKE_AUTH_RSA_SIG)" },
	{ IKE_AUTH_RSA_ENC,	" (IKE_AUTH_RSA_ENC)" },
	{ IKE_AUTH_RSA_ENC_2,	" (IKE_AUTH_RSA_ENC_2)" },
	{ IKE_AUTH_EL_GAMAL_ENC,	" (IKE_AUTH_EL_GAMAL_ENC)" },
	{ IKE_AUTH_EL_GAMAL_ENC_REV,	" (IKE_AUTH_EL_GAMAL_ENC_REV)" },
	{ IKE_AUTH_ECDSA_SIG,	" (IKE_AUTH_ECDSA_SIG)" },
	{ IKE_AUTH_HybridInitRSA,	" (IKE_AUTH_HybridInitRSA)" },
	{ IKE_AUTH_HybridRespRSA,	" (IKE_AUTH_HybridRespRSA)" },
	{ IKE_AUTH_HybridInitDSS,	" (IKE_AUTH_HybridInitDSS)" },
	{ IKE_AUTH_HybridRespDSS,	" (IKE_AUTH_HybridRespDSS)" },
	{ IKE_AUTH_XAUTHInitPreShared,	" (IKE_AUTH_XAUTHInitPreShared)" },
	{ IKE_AUTH_XAUTHRespPreShared,	" (IKE_AUTH_XAUTHRespPreShared)" },
	{ IKE_AUTH_XAUTHInitDSS,	" (IKE_AUTH_XAUTHInitDSS)" },
	{ IKE_AUTH_XAUTHRespDSS,	" (IKE_AUTH_XAUTHRespDSS)" },
	{ IKE_AUTH_XAUTHInitRSA,	" (IKE_AUTH_XAUTHInitRSA)" },
	{ IKE_AUTH_XAUTHRespRSA,	" (IKE_AUTH_XAUTHRespRSA)" },
	{ IKE_AUTH_XAUTHInitRSAEncryption,	" (IKE_AUTH_XAUTHInitRSAEncryption)" },
	{ IKE_AUTH_XAUTHRespRSAEncryption,	" (IKE_AUTH_XAUTHRespRSAEncryption)" },
	{ IKE_AUTH_XAUTHInitRSARevisedEncryption,	" (IKE_AUTH_XAUTHInitRSARevisedEncryption)" },
	{ IKE_AUTH_XAUTHRespRSARevisedEncryption,	" (IKE_AUTH_XAUTHRespRSARevisedEncryption)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_group_enum_array[] = {
	{ IKE_GROUP_MODP_768,	" (IKE_GROUP_MODP_768)" },
	{ IKE_GROUP_MODP_1024,	" (IKE_GROUP_MODP_1024)" },
	{ IKE_GROUP_EC2N_155,	" (IKE_GROUP_EC2N_155)" },
	{ IKE_GROUP_EC2N_185,	" (IKE_GROUP_EC2N_185)" },
	{ IKE_GROUP_MODP_1536,	" (IKE_GROUP_MODP_1536)" },
	{ IKE_GROUP_EC2N_163sect,	" (IKE_GROUP_EC2N_163sect)" },
	{ IKE_GROUP_EC2N_163K,	" (IKE_GROUP_EC2N_163K)" },
	{ IKE_GROUP_EC2N_283sect,	" (IKE_GROUP_EC2N_283sect)" },
	{ IKE_GROUP_EC2N_283K,	" (IKE_GROUP_EC2N_283K)" },
	{ IKE_GROUP_EC2N_409sect,	" (IKE_GROUP_EC2N_409sect)" },
	{ IKE_GROUP_EC2N_409K,	" (IKE_GROUP_EC2N_409K)" },
	{ IKE_GROUP_EC2N_571sect,	" (IKE_GROUP_EC2N_571sect)" },
	{ IKE_GROUP_EC2N_571K,	" (IKE_GROUP_EC2N_571K)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_group_type_enum_array[] = {
	{ IKE_GROUP_TYPE_MODP,	" (IKE_GROUP_TYPE_MODP)" },
	{ IKE_GROUP_TYPE_ECP,	" (IKE_GROUP_TYPE_ECP)" },
	{ IKE_GROUP_TYPE_EC2N,	" (IKE_GROUP_TYPE_EC2N)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ike_life_enum_array[] = {
	{ IKE_LIFE_TYPE_SECONDS,	" (IKE_LIFE_TYPE_SECONDS)" },
	{ IKE_LIFE_TYPE_K,	" (IKE_LIFE_TYPE_K)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_sit_enum_array[] = {
	{ ISAKMP_IPSEC_SIT_IDENTITY_ONLY,	" (ISAKMP_IPSEC_SIT_IDENTITY_ONLY)" },
	{ ISAKMP_IPSEC_SIT_SECRECY,	" (ISAKMP_IPSEC_SIT_SECRECY)" },
	{ ISAKMP_IPSEC_SIT_INTEGRITY,	" (ISAKMP_IPSEC_SIT_INTEGRITY)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_id_enum_array[] = {
	{ ISAKMP_IPSEC_ID_RESERVED,	" (ISAKMP_IPSEC_ID_RESERVED)" },
	{ ISAKMP_IPSEC_ID_IPV4_ADDR,	" (ISAKMP_IPSEC_ID_IPV4_ADDR)" },
	{ ISAKMP_IPSEC_ID_FQDN,	" (ISAKMP_IPSEC_ID_FQDN)" },
	{ ISAKMP_IPSEC_ID_USER_FQDN,	" (ISAKMP_IPSEC_ID_USER_FQDN)" },
	{ ISAKMP_IPSEC_ID_IPV4_ADDR_SUBNET,	" (ISAKMP_IPSEC_ID_IPV4_ADDR_SUBNET)" },
	{ ISAKMP_IPSEC_ID_IPV6_ADDR,	" (ISAKMP_IPSEC_ID_IPV6_ADDR)" },
	{ ISAKMP_IPSEC_ID_IPV6_ADDR_SUBNET,	" (ISAKMP_IPSEC_ID_IPV6_ADDR_SUBNET)" },
	{ ISAKMP_IPSEC_ID_IPV4_ADDR_RANGE,	" (ISAKMP_IPSEC_ID_IPV4_ADDR_RANGE)" },
	{ ISAKMP_IPSEC_ID_IPV6_ADDR_RANGE,	" (ISAKMP_IPSEC_ID_IPV6_ADDR_RANGE)" },
	{ ISAKMP_IPSEC_ID_DER_ASN1_DN,	" (ISAKMP_IPSEC_ID_DER_ASN1_DN)" },
	{ ISAKMP_IPSEC_ID_DER_ASN1_GN,	" (ISAKMP_IPSEC_ID_DER_ASN1_GN)" },
	{ ISAKMP_IPSEC_ID_KEY_ID,	" (ISAKMP_IPSEC_ID_KEY_ID)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_proto_enum_array[] = {
	{ ISAKMP_IPSEC_PROTO_RESERVED,	" (ISAKMP_IPSEC_PROTO_RESERVED)" },
	{ ISAKMP_IPSEC_PROTO_ISAKMP,	" (ISAKMP_IPSEC_PROTO_ISAKMP)" },
	{ ISAKMP_IPSEC_PROTO_IPSEC_AH,	" (ISAKMP_IPSEC_PROTO_IPSEC_AH)" },
	{ ISAKMP_IPSEC_PROTO_IPSEC_ESP,	" (ISAKMP_IPSEC_PROTO_IPSEC_ESP)" },
	{ ISAKMP_IPSEC_PROTO_IPCOMP,	" (ISAKMP_IPSEC_PROTO_IPCOMP)" },
	{ ISAKMP_IPSEC_PROTO_MODECFG,	" (ISAKMP_IPSEC_PROTO_MODECFG)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_key_enum_array[] = {
	{ ISAKMP_IPSEC_KEY_RESERVED,	" (ISAKMP_IPSEC_KEY_RESERVED)" },
	{ ISAKMP_IPSEC_KEY_IKE,	" (ISAKMP_IPSEC_KEY_IKE)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_ah_enum_array[] = {
	{ ISAKMP_IPSEC_AH_RESERVED,	" (ISAKMP_IPSEC_AH_RESERVED)" },
	{ ISAKMP_IPSEC_AH_MD5,	" (ISAKMP_IPSEC_AH_MD5)" },
	{ ISAKMP_IPSEC_AH_SHA,	" (ISAKMP_IPSEC_AH_SHA)" },
	{ ISAKMP_IPSEC_AH_DES,	" (ISAKMP_IPSEC_AH_DES)" },
	{ ISAKMP_IPSEC_AH_SHA2_256,	" (ISAKMP_IPSEC_AH_SHA2_256)" },
	{ ISAKMP_IPSEC_AH_SHA2_384,	" (ISAKMP_IPSEC_AH_SHA2_384)" },
	{ ISAKMP_IPSEC_AH_SHA2_512,	" (ISAKMP_IPSEC_AH_SHA2_512)" },
	{ ISAKMP_IPSEC_AH_RIPEMD,	" (ISAKMP_IPSEC_AH_RIPEMD)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_esp_enum_array[] = {
	{ ISAKMP_IPSEC_ESP_RESERVED,	" (ISAKMP_IPSEC_ESP_RESERVED)" },
	{ ISAKMP_IPSEC_ESP_DES_IV64,	" (ISAKMP_IPSEC_ESP_DES_IV64)" },
	{ ISAKMP_IPSEC_ESP_DES,	" (ISAKMP_IPSEC_ESP_DES)" },
	{ ISAKMP_IPSEC_ESP_3DES,	" (ISAKMP_IPSEC_ESP_3DES)" },
	{ ISAKMP_IPSEC_ESP_RC5,	" (ISAKMP_IPSEC_ESP_RC5)" },
	{ ISAKMP_IPSEC_ESP_IDEA,	" (ISAKMP_IPSEC_ESP_IDEA)" },
	{ ISAKMP_IPSEC_ESP_CAST,	" (ISAKMP_IPSEC_ESP_CAST)" },
	{ ISAKMP_IPSEC_ESP_BLOWFISH,	" (ISAKMP_IPSEC_ESP_BLOWFISH)" },
	{ ISAKMP_IPSEC_ESP_3IDEA,	" (ISAKMP_IPSEC_ESP_3IDEA)" },
	{ ISAKMP_IPSEC_ESP_DES_IV32,	" (ISAKMP_IPSEC_ESP_DES_IV32)" },
	{ ISAKMP_IPSEC_ESP_RC4,	" (ISAKMP_IPSEC_ESP_RC4)" },
	{ ISAKMP_IPSEC_ESP_NULL,	" (ISAKMP_IPSEC_ESP_NULL)" },
	{ ISAKMP_IPSEC_ESP_AES,	" (ISAKMP_IPSEC_ESP_AES)" },
	{ ISAKMP_IPSEC_ESP_AES_128_CTR,	" (ISAKMP_IPSEC_ESP_AES_128_CTR)" },
	{ ISAKMP_IPSEC_ESP_AES_MARS,	" (ISAKMP_IPSEC_ESP_AES_MARS)" },
	{ ISAKMP_IPSEC_ESP_AES_RC6,	" (ISAKMP_IPSEC_ESP_AES_RC6)" },
	{ ISAKMP_IPSEC_ESP_AES_RIJNDAEL,	" (ISAKMP_IPSEC_ESP_AES_RIJNDAEL)" },
	{ ISAKMP_IPSEC_ESP_AES_SERPENT,	" (ISAKMP_IPSEC_ESP_AES_SERPENT)" },
	{ ISAKMP_IPSEC_ESP_AES_TWOFISH,	" (ISAKMP_IPSEC_ESP_AES_TWOFISH)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_attr_enum_array[] = {
	{ ISAKMP_IPSEC_ATTRIB_SA_LIFE_TYPE,	" (ISAKMP_IPSEC_ATTRIB_SA_LIFE_TYPE)" },
	{ ISAKMP_IPSEC_ATTRIB_SA_LIFE_DURATION,	" (ISAKMP_IPSEC_ATTRIB_SA_LIFE_DURATION)" },
	{ ISAKMP_IPSEC_ATTRIB_GROUP_DESC,	" (ISAKMP_IPSEC_ATTRIB_GROUP_DESC)" },
	{ ISAKMP_IPSEC_ATTRIB_ENCAP_MODE,	" (ISAKMP_IPSEC_ATTRIB_ENCAP_MODE)" },
	{ ISAKMP_IPSEC_ATTRIB_AUTH_ALG,	" (ISAKMP_IPSEC_ATTRIB_AUTH_ALG)" },
	{ ISAKMP_IPSEC_ATTRIB_KEY_LENGTH,	" (ISAKMP_IPSEC_ATTRIB_KEY_LENGTH)" },
	{ ISAKMP_IPSEC_ATTRIB_KEY_ROUNDS,	" (ISAKMP_IPSEC_ATTRIB_KEY_ROUNDS)" },
	{ ISAKMP_IPSEC_ATTRIB_COMP_DICT_SIZE,	" (ISAKMP_IPSEC_ATTRIB_COMP_DICT_SIZE)" },
	{ ISAKMP_IPSEC_ATTRIB_COMP_PRIVATE_ALG,	" (ISAKMP_IPSEC_ATTRIB_COMP_PRIVATE_ALG)" },
	{ ISAKMP_IPSEC_ATTRIB_ECN_TUNNEL,	" (ISAKMP_IPSEC_ATTRIB_ECN_TUNNEL)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_ipsec_ipcomp_enum_array[] = {
	{ ISAKMP_IPSEC_IPCOMP_RESERVED,	" (ISAKMP_IPSEC_IPCOMP_RESERVED)" },
	{ ISAKMP_IPSEC_IPCOMP_OUI,	" (ISAKMP_IPSEC_IPCOMP_OUI)" },
	{ ISAKMP_IPSEC_IPCOMP_DEFLATE,	" (ISAKMP_IPSEC_IPCOMP_DEFLATE)" },
	{ ISAKMP_IPSEC_IPCOMP_LZS,	" (ISAKMP_IPSEC_IPCOMP_LZS)" },
	{ ISAKMP_IPSEC_IPCOMP_V42BIS,	" (ISAKMP_IPSEC_IPCOMP_V42BIS)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ipsec_life_enum_array[] = {
	{ IPSEC_LIFE_SECONDS,	" (IPSEC_LIFE_SECONDS)" },
	{ IPSEC_LIFE_K,	" (IPSEC_LIFE_K)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ipsec_encap_enum_array[] = {
	{ IPSEC_ENCAP_TUNNEL,	" (IPSEC_ENCAP_TUNNEL)" },
	{ IPSEC_ENCAP_TRANSPORT,	" (IPSEC_ENCAP_TRANSPORT)" },
	{ IPSEC_ENCAP_UDP_TUNNEL,	" (IPSEC_ENCAP_UDP_TUNNEL)" },
	{ IPSEC_ENCAP_UDP_TRANSPORT,	" (IPSEC_ENCAP_UDP_TRANSPORT)" },
	{ IPSEC_ENCAP_UDP_TUNNEL_OLD,	" (IPSEC_ENCAP_UDP_TUNNEL_OLD)" },
	{ IPSEC_ENCAP_UDP_TRANSPORT_OLD,	" (IPSEC_ENCAP_UDP_TRANSPORT_OLD)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings ipsec_auth_enum_array[] = {
	{ IPSEC_AUTH_HMAC_MD5,	" (IPSEC_AUTH_HMAC_MD5)" },
	{ IPSEC_AUTH_HMAC_SHA,	" (IPSEC_AUTH_HMAC_SHA)" },
	{ IPSEC_AUTH_DES_MAC,	" (IPSEC_AUTH_DES_MAC)" },
	{ IPSEC_AUTH_KPDK,	" (IPSEC_AUTH_KPDK)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_modecfg_cfg_enum_array[] = {
	{ ISAKMP_MODECFG_CFG_REQUEST,	" (ISAKMP_MODECFG_CFG_REQUEST)" },
	{ ISAKMP_MODECFG_CFG_REPLY,	" (ISAKMP_MODECFG_CFG_REPLY)" },
	{ ISAKMP_MODECFG_CFG_SET,	" (ISAKMP_MODECFG_CFG_SET)" },
	{ ISAKMP_MODECFG_CFG_ACK,	" (ISAKMP_MODECFG_CFG_ACK)" },
	{ 0,	(const char *) 0 }
};

const struct debug_strings isakmp_modecfg_attrib_enum_array[] = {
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_ADDRESS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_ADDRESS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_NETMASK,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_NETMASK)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_DNS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_DNS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_NBNS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_NBNS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_ADDRESS_EXPIRY,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_ADDRESS_EXPIRY)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_DHCP,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_DHCP)" },
	{ ISAKMP_MODECFG_ATTRIB_APPLICATION_VERSION,	" (ISAKMP_MODECFG_ATTRIB_APPLICATION_VERSION)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_ADDRESS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_ADDRESS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_NETMASK,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_NETMASK)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_DNS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_DNS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_NBNS,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_NBNS)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_DHCP,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_DHCP)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_SUBNET,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP4_SUBNET)" },
	{ ISAKMP_MODECFG_ATTRIB_SUPPORTED_ATTRIBUTES,	" (ISAKMP_MODECFG_ATTRIB_SUPPORTED_ATTRIBUTES)" },
	{ ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_SUBNET,	" (ISAKMP_MODECFG_ATTRIB_INTERNAL_IP6_SUBNET)" },
	{ ISAKMP_XAUTH_06_ATTRIB_TYPE,	" (ISAKMP_XAUTH_06_ATTRIB_TYPE)" },
	{ ISAKMP_XAUTH_06_ATTRIB_USER_NAME,	" (ISAKMP_XAUTH_06_ATTRIB_USER_NAME)" },
	{ ISAKMP_XAUTH_06_ATTRIB_USER_PASSWORD,	" (ISAKMP_XAUTH_06_ATTRIB_USER_PASSWORD)" },
	{ ISAKMP_XAUTH_06_ATTRIB_PASSCODE,	" (ISAKMP_XAUTH_06_ATTRIB_PASSCODE)" },
	{ ISAKMP_XAUTH_06_ATTRIB_MESSAGE,	" (ISAKMP_XAUTH_06_ATTRIB_MESSAGE)" },
	{ ISAKMP_XAUTH_06_ATTRIB_CHALLENGE,	" (ISAKMP_XAUTH_06_ATTRIB_CHALLENGE)" },
	{ ISAKMP_XAUTH_06_ATTRIB_DOMAIN,	" (ISAKMP_XAUTH_06_ATTRIB_DOMAIN)" },
	{ ISAKMP_XAUTH_06_ATTRIB_STATUS,	" (ISAKMP_XAUTH_06_ATTRIB_STATUS)" },
	{ ISAKMP_XAUTH_06_ATTRIB_NEXT_PIN,	" (ISAKMP_XAUTH_06_ATTRIB_NEXT_PIN)" },
	{ ISAKMP_XAUTH_06_ATTRIB_ANSWER,	" (ISAKMP_XAUTH_06_ATTRIB_ANSWER)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_BANNER,	" (ISAKMP_MODECFG_ATTRIB_CISCO_BANNER)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_SAVE_PW,	" (ISAKMP_MODECFG_ATTRIB_CISCO_SAVE_PW)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_DEF_DOMAIN,	" (ISAKMP_MODECFG_ATTRIB_CISCO_DEF_DOMAIN)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_SPLIT_DNS,	" (ISAKMP_MODECFG_ATTRIB_CISCO_SPLIT_DNS)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_SPLIT_INC,	" (ISAKMP_MODECFG_ATTRIB_CISCO_SPLIT_INC)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_UDP_ENCAP_PORT,	" (ISAKMP_MODECFG_ATTRIB_CISCO_UDP_ENCAP_PORT)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_UNKNOWN,	" (ISAKMP_MODECFG_ATTRIB_CISCO_UNKNOWN)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_DO_PFS,	" (ISAKMP_MODECFG_ATTRIB_CISCO_DO_PFS)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_FW_TYPE,	" (ISAKMP_MODECFG_ATTRIB_CISCO_FW_TYPE)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_BACKUP_SERVER,	" (ISAKMP_MODECFG_ATTRIB_CISCO_BACKUP_SERVER)" },
	{ ISAKMP_MODECFG_ATTRIB_CISCO_DDNS_HOSTNAME,	" (ISAKMP_MODECFG_ATTRIB_CISCO_DDNS_HOSTNAME)" },
	{ ISAKMP_XAUTH_ATTRIB_CISCOEXT_VENDOR,	" (ISAKMP_XAUTH_ATTRIB_CISCOEXT_VENDOR)" },
	{ 0,	(const char *) 0 }
};

