
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#ifdef __cplusplus
#include <stdlib.h>
#endif
#define SYS_LINUX 1
#define SYSCONF_LOC "/tmp/kismet/etc"
#define LOCALSTATE_DIR "/tmp/kismet/var"
#define BIN_LOC "/tmp/kismet/bin"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ERRNO_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_STDLIB_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_STRING_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_UNISTD_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYSHEADERS 1
#define HAVE_GETOPT_H 1
#define TIME_WITH_SYS_TIME 1
#define STDC_HEADERS 1
#define RETSIGTYPE void
#define HAVE_STAT_EMPTY_STRING_BUG 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_MEMSET 1
#define HAVE_SELECT 1
#define HAVE_SOCKET 1
#define HAVE_STRCASECMP 1
#define HAVE_STRFTIME 1
#define HAVE_STRSTR 1
#define HAVE_GETOPT_LONG 1
#define HAVE_STDINT_H 1
#define HAVE_SOCKLEN_T 1
#define _FILE_OFFSET_BITS 64
#define HAVE_GPS 1
#define HAVE_LIBPCAP 1
#define HAVE_WSP100 1
#define USE_LOCAL_DUMP 1
#define HAVE_PTHREAD 1
