svn add .gitignore
svn add .gitreview
svn add 1391.diff
svn add aclocal.m4
svn add add.sh
svn add addons/.gitignore
svn add agi/.gitignore
svn add asterisk-13.3.2-summary.html
svn add asterisk-13.3.2-summary.txt
svn add asterisk-13.9.1-summary.html
svn add asterisk-13.9.1-summary.txt
svn add autoconf/ast_check_raii.m4
svn add autoconf/ast_check_strsep_array_bounds.m4
svn add autom4te.cache
svn add build_tools/.gitignore
svn add build_tools/make_check_alembic
svn add channels/pjsip/cli_commands.c
svn add channels/pjsip/include/cli_functions.h
svn add configs/basic-pbx/cdr.conf
svn add configs/basic-pbx/cdr_custom.conf
svn add configs/basic-pbx/confbridge.conf
svn add configs/basic-pbx/queues.conf
svn add configs/samples/pjproject.conf.sample
svn add contrib/ast-db-manage/config/versions/136885b81223_add_regcontext_to_pj.py
svn add contrib/ast-db-manage/config/versions/154177371065_add_default_from_user.py
svn add contrib/ast-db-manage/config/versions/189a235b3fd7_add_keep_alive_interval.py
svn add contrib/ast-db-manage/config/versions/1c688d9a003c_pjsip_voicemail_extension.py
svn add contrib/ast-db-manage/config/versions/23530d604b96_add_rpid_immediate.py
svn add contrib/ast-db-manage/config/versions/26d7f3bf0fa5_add_bind_rtp_to_media_address_to_pjsip.py
svn add contrib/ast-db-manage/config/versions/26f10cadc157_add_pjsip_timeout_options.py
svn add contrib/ast-db-manage/config/versions/28b8e71e541f_add_g726_non_standard.py
svn add contrib/ast-db-manage/config/versions/28ce1e718f05_add_fatal_response_interval.py
svn add contrib/ast-db-manage/config/versions/2d078ec071b7_increaes_contact_column_size.py
svn add contrib/ast-db-manage/config/versions/31cd4f4891ec_add_auto_dtmf_mode.py
svn add contrib/ast-db-manage/config/versions/3bcc0b5bc2c9_add_allow_reload_to_ps_transports.py
svn add contrib/ast-db-manage/config/versions/423f34ad36e2_fix_pjsip_qualify_ti.py
svn add contrib/ast-db-manage/config/versions/461d7d691209_add_pjsip_qualify_timeout.py
svn add contrib/ast-db-manage/config/versions/498357a710ae_add_rtp_keepalive.py
svn add contrib/ast-db-manage/config/versions/5813202e92be_add_contact_expiration_check_interval_.py
svn add contrib/ast-db-manage/config/versions/a541e0b5e89_add_pjsip_max_initial_qualify_time.py
svn add contrib/ast-db-manage/config/versions/dbc44d5a908_add_missing_columns_to_sys_and_reg.py
svn add contrib/asterisk-ng-doxygen
svn add contrib/docker
svn add contrib/realtime/mssql
svn add contrib/realtime/sqlserver
svn add contrib/realtime/sqlserver/mssql_cdr.sql
svn add contrib/realtime/sqlserver/mssql_config.sql
svn add contrib/realtime/sqlserver/mssql_voicemail.sql
svn add contrib/scripts/astversion
svn add contrib/scripts/clang-scan-build
svn add doc/.gitignore
svn add doc/asterisk-ng-doxygen.in
svn add funcs/func_holdintercept.c
svn add include/asterisk/.gitignore
svn add include/asterisk/max_forwards.h
svn add include/asterisk/named_locks.h
svn add include/asterisk/res_odbc_transaction.h
svn add include/asterisk/res_pjproject.h
svn add main/.gitignore
svn add main/editline/.gitignore
svn add main/libasteriskpj.c
svn add main/max_forwards.c
svn add main/named_locks.c
svn add main/pbx_app.c
svn add main/pbx_builtins.c
svn add main/pbx_functions.c
svn add main/pbx_hangup_handler.c
svn add main/pbx_private.h
svn add main/pbx_switch.c
svn add main/pbx_timing.c
svn add main/pbx_variables.c
svn add main/stringfields.c
svn add menuselect/.gitignore
svn add res/ael/.gitignore
svn add res/res_endpoint_stats.c
svn add res/res_format_attr_vp8.c
svn add res/res_jabber.exports.in
svn add res/res_odbc_transaction.c
svn add res/res_odbc_transaction.exports.in
svn add res/res_pjproject.c
svn add res/res_pjproject.exports.in
svn add res/res_pjsip_dlg_options.c
svn add res/res_pjsip_history.c
svn add res/res_pjsip_keepalive.c
svn add res/res_pjsip_log_forwarder.c
svn add res/res_pjsip_transport_management.c
svn add res/res_sorcery_memory_cache.c
svn add tests/test_named_lock.c
svn add tests/test_sorcery_memory_cache_thrash.c
svn add tests/test_vector.c
svn add third-party
svn add utils/.gitignore
