.TH pev 1 "November 2013" "open-plc-utils-0.0.3" "Qualcomm Atheros Open Powerline Toolkit"

.SH NAME
pev - Qualcomm Atheros Plug-in Electric Vehicle Emulator

.SH SYNOPSIS
.BR pev
.RI [ options ] 

.SH DESCRIPTION
Emulate the PEV part of the HomePlug AV Signal Level Attentuation Characterization (SLAC) protocol where a \fBPEV\fR is a "\fBPlug-in Electric Vehicle\fR" and an \fBEVSE\fR is an "\fBElectric Vehicle Supply Equipment\fR" or charging station.
This program will remain active until it detects and connects to an available EVSE-HLE on the powerline network.
Once connected, it charges a virtual vehicle for about 10 seconds then disconnects and terminates.
See the \fIHomePlug Green PHY Specification Release Version 1.1\fR for more information on this protocol.

.PP
Signal Level Attenuation Characterization (SLAC) enables a station to measure the signal level of its transmission at other stations in the network.
It is designed for automotive applications where there are multiple plug-in vehicle (PEVs) and electric vehicle supply equipment (EVSE) on the network.
The PEV signal level is measured at multiple EVSEs to determine which EVSE the PEV is actually plugged into.
The process leading to this determination is called "\fBGreen PHY PEV-EVSE Association\fB" (GreenPPEA).

.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBplc\fR man page for an overview and installation instructions.

.SH OPTIONS

.TP
.RB - c
Print the PEV-HLE configuration profile on stdout.
The configuration profile specifies program defaults in a format that you, as a user, can edit and save.
Use options \fB-p\fR and \fB-s\fR to read named profiles and sections.

.TP
.RB - d
Print the contents of the PEV-HLE session variable on stdout.
The session variable is an program data structure that stores information passed between the PEV-HLE and EVSE-HLE during SLAC association.
This option is used to inspect and veriify information relevant to the process.
If the program was compiled with variable SLAC_DEBUG defined then this option also prints MME message fields before messages are sent or after they are received.
Interested parties can follow along in the source code.

.TP
.RB - i
Select the host Ethernet interface.
All requests are sent via this host interface and only reponses received via this host interface are recognized.
The default interface is \fBeth1\fR because most people use \fBeth0\fR as their principle network connection; however, if environment string "PLC" is defined then it takes precedence over the default interface.
This option then takes precedence over either default.

.TP
-\fBp \fIprofile\fR
The PEV-HLE configuration profile name.
The program will supply default values for missing profile elements.
See the example profile shown below.
The default profile name is "\fBpev.ini\fR".

.TP
.RB - q
Enter quiet mode.
Progress messages are suppressed.

.TP
-\fBs \fIsection\fR
The configuration profile section name.
The program will supply default values for missing configuration profile elements.
See the example profile shown below.
The default section name is "\fBdefault\fR".

.TP
.RB - v 
Enter verbose mode.
All Etherenet frames sent or received by the program are displayed on stdout.

.TP
-\fB?\fR, --\fBhelp\fR
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
-\fB!\fR, --\fBversion\fR
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH PROFILES
The default configuration profile for this program is "\fBpev.ini\fR".
The default profile section is "\fBdefault\fR".
Users may create addition profiles and reference them with option \fB-p\fr or add additional sections to an existing profiles and reference them with option \fB-s\fR.

.TP
.B Attenuation Theshold
The average attenuation above which the PEV will not connect to an EVSE.
The default value is \fB10\fRdb.

.TP
.B MSound Pause
The time in milliseconds between each MSound sent by the PEV-HLE to the EVSE-HLE.
Sending MSounds too frequently overloads the EVSE-PLC.
Sending them too infrequently wastes time.
This value is derived and does not appear in the HPGP specification.
The default pause is \fB10\fR milliseconds.

.TP
.B Vehicle Identifier
Vehicle identification.
The 17-byte Vehicle Identification Number to be placed in CM_MNBC_SOUND.IND.SenderID.
This value is not used but is can be changed here so that the field is easy to spot within network message traces.

.TP
.B Network Membership Key
The 16-byte Network Memberhip Key (NMK) for the PEV-PLC device.
This program uses CM_SET_KEY to sets the PEV-PLC NMK to this value after disconnecting.
The default value is the key for Network Password "\fBHomePlugAV\fR".

.TP
.B Network Identifier
The 7-byte Network Identifier (NID) for the PEV-PLC device.
This program uses CM_SET_KEY to sets the PEV-PLC NID to this value after disconnecting.
The default value is the same as that for Network Password "\fBHomePlugAV\fR".

.SH REFERENCES
See the \fIQualcomm Atheros AR7420, QCA6410 IEEE 1901, HomePlug AV and QCA7000 HomePlug Green PHY PLC Chipset Programmer''s Guide\fR or the \fIHomePlug Green PHY Specification Release Version 1.1\fR for more information on this protocol.

.SH EXAMPLES
The following example starts a PEV session on interface \fBeth0\fR and wait up to 2000 milliseconds (or 2 seconds) for the EVSE to respond during any given exchange.

.PP
   # pev -ieth0 -w2000

.PP
The default PEV-HLE configuration profile, "\fBpev.ini\fR", looks something like this but it can be changed using a normal text editor.
Use option \fB-P\fR to produce a template profile, if one is needed.

.PP
   # file: pev.ini
   # ====================================================================
   # PEV-HLE initialization;
   # --------------------------------------------------------------------
   [default]
   attenuation threshold = 10
   msound pause = 10
   vehicle identifier = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   network membership key = 50D3E4933F855B7040784DF815AA8DB7
   network identifier = B0F2E695666B03

.SH SEE ALSO
.BR plc ( 1 ),
.BR evse ( 1 )

.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>

