#!/bin/bash

# NFT_TEST_REQUIRES(NFT_TEST_HAVE_catchall_element)

$NFT "add table ip test ;
     add map ip test testmap { type ipv4_addr : verdict; };
     add chain ip test testchain;
     add element ip test testmap { * : jump testchain }" || exit 1

$NFT "flush map ip test testmap; delete map ip test testmap; delete map ip test testmap" 2>/dev/null && exit 1
$NFT "flush map ip test testmap; delete map ip test testmap; delete element ip test testmap { * : jump testchain }" 2>/dev/null && exit 1

$NFT "flush map ip test testmap; delete map ip test testmap" || exit 1
