/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.17.14
 * Tue Oct 24 11:58:28 2006
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86_32 1
#define CONFIG_SEMAPHORE_SLEEPERS 1
#define CONFIG_X86 1
#define CONFIG_MMU 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_GENERIC_IOMAP 1
#define CONFIG_GENERIC_HWEIGHT 1
#define CONFIG_ARCH_MAY_HAVE_PC_FDC 1
#define CONFIG_DMI 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_LOCALVERSION_AUTO 1
#undef CONFIG_SWAP
#define CONFIG_SYSVIPC 1
#undef CONFIG_POSIX_MQUEUE
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#undef CONFIG_IKCONFIG
#undef CONFIG_RELAY
#define CONFIG_INITRAMFS_SOURCE ""
#define CONFIG_UID16 1
#define CONFIG_VM86 1
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_HOTPLUG 1
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#undef CONFIG_ELF_CORE
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_SLAB 1
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0
#undef CONFIG_SLOB
#define CONFIG_OBSOLETE_INTERMODULE 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_MODULE_FORCE_UNLOAD 1
#undef CONFIG_MODVERSIONS
#undef CONFIG_MODULE_SRCVERSION_ALL
#undef CONFIG_KMOD

/*
 * Block layer
 */
#define CONFIG_LBD 1
#undef CONFIG_BLK_DEV_IO_TRACE
#define CONFIG_LSF 1

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#undef CONFIG_IOSCHED_AS
#undef CONFIG_IOSCHED_DEADLINE
#undef CONFIG_IOSCHED_CFQ
#undef CONFIG_DEFAULT_AS
#undef CONFIG_DEFAULT_DEADLINE
#undef CONFIG_DEFAULT_CFQ
#define CONFIG_DEFAULT_NOOP 1
#define CONFIG_DEFAULT_IOSCHED "noop"

/*
 * Processor type and features
 */
#define CONFIG_SCx200HR_TIMER 1
#undef CONFIG_SMP
#define CONFIG_X86_PC 1
#undef CONFIG_X86_ELAN
#undef CONFIG_X86_VOYAGER
#undef CONFIG_X86_NUMAQ
#undef CONFIG_X86_SUMMIT
#undef CONFIG_X86_BIGSMP
#undef CONFIG_X86_VISWS
#undef CONFIG_X86_GENERICARCH
#undef CONFIG_X86_ES7000
#undef CONFIG_M386
#undef CONFIG_M486
#undef CONFIG_M586
#undef CONFIG_M586TSC
#undef CONFIG_M586MMX
#undef CONFIG_M686
#undef CONFIG_MPENTIUMII
#undef CONFIG_MPENTIUMIII
#undef CONFIG_MPENTIUMM
#undef CONFIG_MPENTIUM4
#undef CONFIG_MK6
#undef CONFIG_MK7
#undef CONFIG_MK8
#undef CONFIG_MCRUSOE
#undef CONFIG_MEFFICEON
#undef CONFIG_MWINCHIPC6
#undef CONFIG_MWINCHIP2
#undef CONFIG_MWINCHIP3D
#undef CONFIG_MGEODEGX1
#define CONFIG_MGEODE_LX 1
#undef CONFIG_MCYRIXIII
#undef CONFIG_MVIAC3_2
#define CONFIG_X86_GENERIC 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_X86_XADD 1
#define CONFIG_X86_L1_CACHE_SHIFT 7
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_X86_WP_WORKS_OK 1
#define CONFIG_X86_INVLPG 1
#define CONFIG_X86_BSWAP 1
#define CONFIG_X86_POPAD_OK 1
#define CONFIG_X86_CMPXCHG64 1
#define CONFIG_X86_INTEL_USERCOPY 1
#define CONFIG_X86_USE_PPRO_CHECKSUM 1
#define CONFIG_X86_USE_3DNOW 1
#define CONFIG_X86_TSC 1
#define CONFIG_HPET_TIMER 1
#define CONFIG_HPET_EMULATE_RTC 1
#define CONFIG_PREEMPT_NONE 1
#undef CONFIG_PREEMPT_VOLUNTARY
#undef CONFIG_PREEMPT
#define CONFIG_X86_UP_APIC 1
#define CONFIG_X86_UP_IOAPIC 1
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_MCE 1
#undef CONFIG_X86_MCE_NONFATAL
#define CONFIG_X86_MCE_P4THERMAL 1
#define CONFIG_TOSHIBA_MODULE 1
#define CONFIG_I8K_MODULE 1
#define CONFIG_X86_REBOOTFIXUPS 1
#define CONFIG_MICROCODE_MODULE 1
#define CONFIG_X86_MSR_MODULE 1
#define CONFIG_X86_CPUID_MODULE 1

/*
 * Firmware Drivers
 */
#undef CONFIG_EDD
#undef CONFIG_DELL_RBU
#define CONFIG_DCDBAS_MODULE 1
#undef CONFIG_NOHIGHMEM
#define CONFIG_HIGHMEM4G 1
#undef CONFIG_HIGHMEM64G
#define CONFIG_VMSPLIT_3G 1
#undef CONFIG_VMSPLIT_3G_OPT
#undef CONFIG_VMSPLIT_2G
#undef CONFIG_VMSPLIT_1G
#define CONFIG_PAGE_OFFSET 0xC0000000
#define CONFIG_HIGHMEM 1
#define CONFIG_ARCH_FLATMEM_ENABLE 1
#define CONFIG_ARCH_SPARSEMEM_ENABLE 1
#define CONFIG_ARCH_SELECT_MEMORY_MODEL 1
#define CONFIG_SELECT_MEMORY_MODEL 1
#define CONFIG_FLATMEM_MANUAL 1
#undef CONFIG_DISCONTIGMEM_MANUAL
#undef CONFIG_SPARSEMEM_MANUAL
#define CONFIG_FLATMEM 1
#define CONFIG_FLAT_NODE_MEM_MAP 1
#define CONFIG_SPARSEMEM_STATIC 1
#define CONFIG_SPLIT_PTLOCK_CPUS 4
#undef CONFIG_HIGHPTE
#undef CONFIG_MATH_EMULATION
#define CONFIG_MTRR 1
#undef CONFIG_EFI
#define CONFIG_REGPARM 1
#define CONFIG_SECCOMP 1
#undef CONFIG_HZ_100
#define CONFIG_HZ_250 1
#undef CONFIG_HZ_1000
#define CONFIG_HZ 250
#undef CONFIG_KEXEC
#undef CONFIG_CRASH_DUMP
#define CONFIG_PHYSICAL_START 0x100000
#define CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG 1

/*
 * Power management options (ACPI, APM)
 */
#define CONFIG_PM 1
#define CONFIG_PM_LEGACY 1
#undef CONFIG_PM_DEBUG

/*
 * ACPI (Advanced Configuration and Power Interface) Support
 */
#define CONFIG_ACPI 1
#define CONFIG_ACPI_SLEEP 1
#define CONFIG_ACPI_SLEEP_PROC_FS 1
#undef CONFIG_ACPI_SLEEP_PROC_SLEEP
#define CONFIG_ACPI_AC 1
#define CONFIG_ACPI_BATTERY 1
#define CONFIG_ACPI_BUTTON 1
#define CONFIG_ACPI_VIDEO 1
#undef CONFIG_ACPI_HOTKEY
#define CONFIG_ACPI_FAN 1
#define CONFIG_ACPI_PROCESSOR 1
#define CONFIG_ACPI_THERMAL 1
#define CONFIG_ACPI_ASUS 1
#define CONFIG_ACPI_IBM 1
#define CONFIG_ACPI_IBM_DOCK 1
#define CONFIG_ACPI_TOSHIBA 1
#undef CONFIG_ACPI_CUSTOM_DSDT
#define CONFIG_ACPI_BLACKLIST_YEAR 0
#undef CONFIG_ACPI_DEBUG
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_SYSTEM 1
#define CONFIG_X86_PM_TIMER 1
#undef CONFIG_ACPI_CONTAINER

/*
 * APM (Advanced Power Management) BIOS Support
 */
#undef CONFIG_APM

/*
 * CPU Frequency scaling
 */
#define CONFIG_CPU_FREQ 1
#define CONFIG_CPU_FREQ_TABLE 1
#undef CONFIG_CPU_FREQ_DEBUG
#define CONFIG_CPU_FREQ_STAT 1
#undef CONFIG_CPU_FREQ_STAT_DETAILS
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_GOV_POWERSAVE
#undef CONFIG_CPU_FREQ_GOV_USERSPACE
#undef CONFIG_CPU_FREQ_GOV_ONDEMAND
#define CONFIG_CPU_FREQ_GOV_CONSERVATIVE 1

/*
 * CPUFreq processor drivers
 */
#define CONFIG_X86_ACPI_CPUFREQ 1
#define CONFIG_X86_POWERNOW_K6 1
#define CONFIG_X86_POWERNOW_K7 1
#define CONFIG_X86_POWERNOW_K7_ACPI 1
#define CONFIG_X86_POWERNOW_K8 1
#define CONFIG_X86_POWERNOW_K8_ACPI 1
#define CONFIG_X86_GX_SUSPMOD 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_ACPI 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_TABLE 1
#define CONFIG_X86_SPEEDSTEP_ICH 1
#define CONFIG_X86_SPEEDSTEP_SMI 1
#define CONFIG_X86_P4_CLOCKMOD 1
#define CONFIG_X86_CPUFREQ_NFORCE2 1
#define CONFIG_X86_LONGRUN 1

/*
 * shared options
 */
#undef CONFIG_X86_ACPI_CPUFREQ_PROC_INTF
#define CONFIG_X86_SPEEDSTEP_LIB 1
#undef CONFIG_X86_SPEEDSTEP_RELAXED_CAP_CHECK

/*
 * Bus options (PCI, PCMCIA, EISA, MCA, ISA)
 */
#define CONFIG_PCI 1
#undef CONFIG_PCI_GOBIOS
#undef CONFIG_PCI_GOMMCONFIG
#undef CONFIG_PCI_GODIRECT
#define CONFIG_PCI_GOANY 1
#define CONFIG_PCI_BIOS 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_MMCONFIG 1
#define CONFIG_PCIEPORTBUS 1
#undef CONFIG_PCI_MSI
#define CONFIG_PCI_LEGACY_PROC 1
#define CONFIG_ISA_DMA_API 1
#undef CONFIG_ISA
#undef CONFIG_MCA
#define CONFIG_SCx200 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA 1
#define CONFIG_PCMCIA_LOAD_CIS 1
#define CONFIG_PCMCIA_IOCTL 1
#define CONFIG_CARDBUS 1

/*
 * PC-card bridges
 */
#define CONFIG_YENTA 1
#define CONFIG_YENTA_O2 1
#define CONFIG_YENTA_RICOH 1
#define CONFIG_YENTA_TI 1
#define CONFIG_YENTA_ENE_TUNE 1
#define CONFIG_YENTA_TOSHIBA 1
#define CONFIG_PD6729 1
#define CONFIG_I82092 1
#define CONFIG_PCCARD_NONSTATIC 1

/*
 * PCI Hotplug Support
 */
#undef CONFIG_HOTPLUG_PCI

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#undef CONFIG_BINFMT_MISC

/*
 * Networking
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#undef CONFIG_NETDEBUG
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#undef CONFIG_NET_KEY
#define CONFIG_RING 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_ASK_IP_FIB_HASH 1
#undef CONFIG_IP_FIB_TRIE
#define CONFIG_IP_FIB_HASH 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#define CONFIG_IP_ROUTE_FWMARK 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
#undef CONFIG_IP_ROUTE_MULTIPATH_CACHED
#undef CONFIG_IP_ROUTE_VERBOSE
#define CONFIG_IP_PNP 1
#undef CONFIG_IP_PNP_DHCP
#define CONFIG_IP_PNP_BOOTP 1
#undef CONFIG_IP_PNP_RARP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#undef CONFIG_INET_AH
#undef CONFIG_INET_ESP
#undef CONFIG_INET_IPCOMP
#undef CONFIG_INET_XFRM_TUNNEL
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_INET_DIAG 1
#define CONFIG_INET_TCP_DIAG 1
#define CONFIG_TCP_CONG_ADVANCED 1

/*
 * TCP congestion control
 */
#define CONFIG_TCP_CONG_BIC 1
#define CONFIG_TCP_CONG_CUBIC 1
#define CONFIG_TCP_CONG_WESTWOOD 1
#define CONFIG_TCP_CONG_HTCP 1
#define CONFIG_TCP_CONG_HSTCP 1
#define CONFIG_TCP_CONG_HYBLA 1
#define CONFIG_TCP_CONG_VEGAS 1
#define CONFIG_TCP_CONG_SCALABLE 1

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#define CONFIG_IPV6_MODULE 1
#undef CONFIG_IPV6_PRIVACY
#undef CONFIG_IPV6_ROUTER_PREF
#undef CONFIG_INET6_AH
#undef CONFIG_INET6_ESP
#undef CONFIG_INET6_IPCOMP
#undef CONFIG_INET6_XFRM_TUNNEL
#undef CONFIG_INET6_TUNNEL
#undef CONFIG_IPV6_TUNNEL
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * Core Netfilter Configuration
 */
#define CONFIG_NETFILTER_NETLINK 1
#define CONFIG_NETFILTER_NETLINK_QUEUE 1
#define CONFIG_NETFILTER_NETLINK_LOG 1
#define CONFIG_NETFILTER_XTABLES 1
#define CONFIG_NETFILTER_XT_TARGET_CLASSIFY 1
#define CONFIG_NETFILTER_XT_TARGET_CONNMARK 1
#define CONFIG_NETFILTER_XT_TARGET_MARK 1
#define CONFIG_NETFILTER_XT_TARGET_NFQUEUE 1
#define CONFIG_NETFILTER_XT_TARGET_NOTRACK 1
#define CONFIG_NETFILTER_XT_MATCH_COMMENT 1
#define CONFIG_NETFILTER_XT_MATCH_CONNBYTES 1
#define CONFIG_NETFILTER_XT_MATCH_CONNMARK 1
#define CONFIG_NETFILTER_XT_MATCH_CONNTRACK 1
#define CONFIG_NETFILTER_XT_MATCH_DCCP 1
#define CONFIG_NETFILTER_XT_MATCH_ESP 1
#define CONFIG_NETFILTER_XT_MATCH_HELPER 1
#define CONFIG_NETFILTER_XT_MATCH_LENGTH 1
#define CONFIG_NETFILTER_XT_MATCH_LIMIT 1
#define CONFIG_NETFILTER_XT_MATCH_MAC 1
#define CONFIG_NETFILTER_XT_MATCH_MARK 1
#define CONFIG_NETFILTER_XT_MATCH_MULTIPORT 1
#undef CONFIG_NETFILTER_XT_MATCH_PHYSDEV
#define CONFIG_NETFILTER_XT_MATCH_PKTTYPE 1
#define CONFIG_NETFILTER_XT_MATCH_REALM 1
#define CONFIG_NETFILTER_XT_MATCH_SCTP 1
#define CONFIG_NETFILTER_XT_MATCH_STATE 1
#define CONFIG_NETFILTER_XT_MATCH_STRING 1
#define CONFIG_NETFILTER_XT_MATCH_TCPMSS 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#undef CONFIG_IP_NF_CONNTRACK_EVENTS
#undef CONFIG_IP_NF_CONNTRACK_NETLINK
#define CONFIG_IP_NF_CT_PROTO_SCTP 1
#define CONFIG_IP_NF_FTP 1
#define CONFIG_IP_NF_IRC 1
#define CONFIG_IP_NF_NETBIOS_NS 1
#define CONFIG_IP_NF_TFTP 1
#define CONFIG_IP_NF_AMANDA 1
#define CONFIG_IP_NF_PPTP_MODULE 1
#define CONFIG_IP_NF_SIP 1
#define CONFIG_IP_NF_H323 1
#undef CONFIG_IP_NF_RTSP
#undef CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_IPTABLES 1
#define CONFIG_IP_NF_MATCH_IPRANGE 1
#define CONFIG_IP_NF_MATCH_LAYER7 1
#undef CONFIG_IP_NF_MATCH_LAYER7_DEBUG
#define CONFIG_IP_NF_MATCH_IPP2P 1
#define CONFIG_IP_NF_MATCH_TOS 1
#define CONFIG_IP_NF_MATCH_RECENT 1
#define CONFIG_IP_NF_MATCH_ECN 1
#define CONFIG_IP_NF_MATCH_DSCP 1
#define CONFIG_IP_NF_MATCH_AH 1
#define CONFIG_IP_NF_MATCH_TTL 1
#define CONFIG_IP_NF_MATCH_OWNER 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE 1
#define CONFIG_IP_NF_MATCH_HASHLIMIT 1
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#define CONFIG_IP_NF_TARGET_IMQ 1
#define CONFIG_IP_NF_TARGET_LOG 1
#define CONFIG_IP_NF_TARGET_ULOG 1
#define CONFIG_IP_NF_TARGET_TCPMSS 1
#define CONFIG_IP_NF_NAT 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE 1
#define CONFIG_IP_NF_TARGET_REDIRECT 1
#define CONFIG_IP_NF_TARGET_NETMAP 1
#define CONFIG_IP_NF_TARGET_SAME 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC 1
#define CONFIG_IP_NF_NAT_IRC 1
#define CONFIG_IP_NF_NAT_FTP 1
#define CONFIG_IP_NF_NAT_TFTP 1
#define CONFIG_IP_NF_NAT_AMANDA 1
#define CONFIG_IP_NF_NAT_PPTP_MODULE 1
#define CONFIG_IP_NF_NAT_SIP 1
#define CONFIG_IP_NF_NAT_H323 1
#define CONFIG_IP_NF_MANGLE 1
#define CONFIG_IP_NF_TARGET_TOS 1
#define CONFIG_IP_NF_TARGET_ECN 1
#define CONFIG_IP_NF_TARGET_DSCP 1
#define CONFIG_IP_NF_TARGET_TTL 1
#define CONFIG_IP_NF_TARGET_CLUSTERIP 1
#define CONFIG_IP_NF_RAW 1
#undef CONFIG_IP_NF_ARPTABLES
#define CONFIG_IP_NF_MATCH_WEBSTR 1
#define CONFIG_IP_NF_AUTOFW 1
#define CONFIG_IP_NF_TARGET_TRIGGER 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP6_NF_QUEUE
#undef CONFIG_IP6_NF_IPTABLES

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_BRIDGE_EBT_ULOG_MODULE 1

/*
 * DCCP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_DCCP

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP

/*
 * TIPC Configuration (EXPERIMENTAL)
 */
#undef CONFIG_TIPC
#undef CONFIG_ATM
#define CONFIG_BRIDGE 1
#define CONFIG_VLAN_8021Q 1
#undef CONFIG_DECNET
#define CONFIG_LLC 1
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU

/*
 * Queueing/Scheduling
 */
#define CONFIG_NET_SCH_CBQ 1
#define CONFIG_NET_SCH_HTB 1
#define CONFIG_NET_SCH_HFSC 1
#define CONFIG_NET_SCH_PRIO 1
#define CONFIG_NET_SCH_RED 1
#define CONFIG_NET_SCH_SFQ 1
#define CONFIG_NET_SCH_TEQL 1
#define CONFIG_NET_SCH_TBF 1
#define CONFIG_NET_SCH_GRED 1
#define CONFIG_NET_SCH_DSMARK 1
#undef CONFIG_NET_SCH_NETEM
#define CONFIG_NET_SCH_INGRESS 1

/*
 * Classification
 */
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC 1
#define CONFIG_NET_CLS_TCINDEX 1
#define CONFIG_NET_CLS_ROUTE4 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW 1
#define CONFIG_NET_CLS_U32 1
#undef CONFIG_CLS_U32_PERF
#undef CONFIG_CLS_U32_MARK
#define CONFIG_NET_CLS_RSVP 1
#define CONFIG_NET_CLS_RSVP6 1
#undef CONFIG_NET_EMATCH
#undef CONFIG_NET_CLS_ACT
#define CONFIG_NET_CLS_POLICE 1
#undef CONFIG_NET_CLS_IND
#define CONFIG_NET_ESTIMATOR 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#undef CONFIG_IEEE80211
#define CONFIG_WIRELESS_EXT 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#undef CONFIG_STANDALONE
#undef CONFIG_PREVENT_FIRMWARE_BUILD
#define CONFIG_FW_LOADER 1

/*
 * Connector - unified userspace <-> kernelspace linker
 */
#undef CONFIG_CONNECTOR

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef CONFIG_MTD_DEBUG
#define CONFIG_MTD_CONCAT 1
#define CONFIG_MTD_PARTITIONS 1
#define CONFIG_MTD_REDBOOT_PARTS 1
#define CONFIG_MTD_REDBOOT_DIRECTORY_BLOCK -1
#undef CONFIG_MTD_REDBOOT_PARTS_UNALLOCATED
#undef CONFIG_MTD_REDBOOT_PARTS_READONLY
#undef CONFIG_MTD_CMDLINE_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL
#undef CONFIG_RFD_FTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#undef CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_GEN_PROBE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT 1
#undef CONFIG_MTD_CFI_AMDSTD
#undef CONFIG_MTD_CFI_STAA
#define CONFIG_MTD_CFI_UTIL 1
#undef CONFIG_MTD_RAM
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT
#undef CONFIG_MTD_OBSOLETE_CHIPS

/*
 * Mapping drivers for chip access
 */
#define CONFIG_MTD_COMPLEX_MAPPINGS 1
#undef CONFIG_MTD_PHYSMAP
#undef CONFIG_MTD_PNC2000
#undef CONFIG_MTD_SC520CDP
#undef CONFIG_MTD_NETSC520
#undef CONFIG_MTD_TS5500
#undef CONFIG_MTD_SBC_GXX
#undef CONFIG_MTD_SCx200_DOCFLASH
#undef CONFIG_MTD_DILNETPC
#undef CONFIG_MTD_PCI
#undef CONFIG_MTD_PLATRAM

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_PMC551
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#undef CONFIG_MTD_NAND

/*
 * OneNAND Flash Device Drivers
 */
#undef CONFIG_MTD_ONENAND

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */
#undef CONFIG_PNP

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#undef CONFIG_BLK_DEV_DAC960
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#define CONFIG_BLK_DEV_CRYPTOLOOP 1
#define CONFIG_BLK_DEV_NBD 1
#undef CONFIG_BLK_DEV_SX8
#undef CONFIG_BLK_DEV_UB
#undef CONFIG_BLK_DEV_RAM
#undef CONFIG_BLK_DEV_INITRD
#undef CONFIG_CDROM_PKTCDVD
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#undef CONFIG_BLK_DEV_HD_IDE
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#undef CONFIG_BLK_DEV_IDECS
#define CONFIG_BLK_DEV_IDECD 1
#undef CONFIG_BLK_DEV_IDETAPE
#define CONFIG_BLK_DEV_IDEFLOPPY 1
#undef CONFIG_BLK_DEV_IDESCSI
#undef CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#undef CONFIG_BLK_DEV_CMD640
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_BLK_DEV_GENERIC 1
#define CONFIG_BLK_DEV_OPTI621 1
#undef CONFIG_BLK_DEV_RZ1000
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#undef CONFIG_IDEDMA_PCI_AUTO
#define CONFIG_BLK_DEV_AEC62XX_MODULE 1
#define CONFIG_BLK_DEV_ALI15X3_MODULE 1
#undef CONFIG_WDC_ALI15X3
#define CONFIG_BLK_DEV_AMD74XX_MODULE 1
#define CONFIG_BLK_DEV_ATIIXP_MODULE 1
#define CONFIG_BLK_DEV_CMD64X_MODULE 1
#define CONFIG_BLK_DEV_TRIFLEX_MODULE 1
#define CONFIG_BLK_DEV_CY82C693_MODULE 1
#define CONFIG_BLK_DEV_CS5520_MODULE 1
#define CONFIG_BLK_DEV_CS5530_MODULE 1
#define CONFIG_BLK_DEV_CS5535_MODULE 1
#define CONFIG_BLK_DEV_HPT34X_MODULE 1
#define CONFIG_HPT34X_AUTODMA 1
#define CONFIG_BLK_DEV_HPT366_MODULE 1
#define CONFIG_BLK_DEV_SC1200_MODULE 1
#define CONFIG_BLK_DEV_PIIX_MODULE 1
#define CONFIG_BLK_DEV_IT821X_MODULE 1
#define CONFIG_BLK_DEV_NS87415_MODULE 1
#define CONFIG_BLK_DEV_PDC202XX_OLD_MODULE 1
#define CONFIG_PDC202XX_BURST 1
#define CONFIG_BLK_DEV_PDC202XX_NEW_MODULE 1
#define CONFIG_BLK_DEV_SVWKS_MODULE 1
#define CONFIG_BLK_DEV_SIIMAGE_MODULE 1
#define CONFIG_BLK_DEV_SIS5513_MODULE 1
#define CONFIG_BLK_DEV_SLC90E66_MODULE 1
#define CONFIG_BLK_DEV_TRM290_MODULE 1
#define CONFIG_BLK_DEV_VIA82CXXX_MODULE 1
#undef CONFIG_IDE_ARM
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#undef CONFIG_IDEDMA_AUTO
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#undef CONFIG_RAID_ATTRS
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD_MODULE 1
#undef CONFIG_CHR_DEV_ST
#undef CONFIG_CHR_DEV_OSST
#define CONFIG_BLK_DEV_SR_MODULE 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG_MODULE 1
#undef CONFIG_CHR_DEV_SCH

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#undef CONFIG_SCSI_CONSTANTS
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1
#undef CONFIG_SCSI_SAS_ATTRS

/*
 * SCSI low-level drivers
 */
#define CONFIG_ISCSI_TCP_MODULE 1
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#define CONFIG_SCSI_3W_9XXX_MODULE 1
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 32
#define CONFIG_AIC7XXX_RESET_DELAY_MS 5000
#undef CONFIG_AIC7XXX_BUILD_FIRMWARE
#define CONFIG_AIC7XXX_DEBUG_ENABLE 1
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#define CONFIG_AIC7XXX_REG_PRETTY_PRINT 1
#define CONFIG_SCSI_AIC7XXX_OLD_MODULE 1
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 32
#define CONFIG_AIC79XX_RESET_DELAY_MS 5000
#undef CONFIG_AIC79XX_BUILD_FIRMWARE
#define CONFIG_AIC79XX_ENABLE_RD_STRM 1
#define CONFIG_AIC79XX_DEBUG_ENABLE 1
#define CONFIG_AIC79XX_DEBUG_MASK 0
#define CONFIG_AIC79XX_REG_PRETTY_PRINT 1
#define CONFIG_SCSI_DPT_I2O_MODULE 1
#define CONFIG_SCSI_ADVANSYS_MODULE 1
#define CONFIG_MEGARAID_NEWGEN 1
#define CONFIG_MEGARAID_MM_MODULE 1
#define CONFIG_MEGARAID_MAILBOX_MODULE 1
#define CONFIG_MEGARAID_LEGACY_MODULE 1
#define CONFIG_MEGARAID_SAS_MODULE 1
#define CONFIG_SCSI_SATA_MODULE 1
#define CONFIG_SCSI_SATA_AHCI_MODULE 1
#define CONFIG_SCSI_SATA_SVW_MODULE 1
#define CONFIG_SCSI_ATA_PIIX_MODULE 1
#define CONFIG_SCSI_SATA_MV_MODULE 1
#define CONFIG_SCSI_SATA_NV_MODULE 1
#define CONFIG_SCSI_PDC_ADMA_MODULE 1
#define CONFIG_SCSI_SATA_QSTOR_MODULE 1
#define CONFIG_SCSI_SATA_PROMISE_MODULE 1
#define CONFIG_SCSI_SATA_SX4_MODULE 1
#define CONFIG_SCSI_SATA_SIL_MODULE 1
#define CONFIG_SCSI_SATA_SIL24_MODULE 1
#define CONFIG_SCSI_SATA_SIS_MODULE 1
#define CONFIG_SCSI_SATA_ULI_MODULE 1
#define CONFIG_SCSI_SATA_VIA_MODULE 1
#define CONFIG_SCSI_SATA_VITESSE_MODULE 1
#define CONFIG_SCSI_SATA_INTEL_COMBINED 1
#define CONFIG_SCSI_BUSLOGIC_MODULE 1
#undef CONFIG_SCSI_OMIT_FLASHPOINT
#define CONFIG_SCSI_DMX3191D_MODULE 1
#define CONFIG_SCSI_EATA_MODULE 1
#undef CONFIG_SCSI_EATA_TAGGED_QUEUE
#undef CONFIG_SCSI_EATA_LINKED_COMMANDS
#define CONFIG_SCSI_EATA_MAX_TAGS 16
#define CONFIG_SCSI_FUTURE_DOMAIN_MODULE 1
#define CONFIG_SCSI_GDTH_MODULE 1
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INITIO_MODULE 1
#define CONFIG_SCSI_INIA100_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_2_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#define CONFIG_SCSI_SYM53C8XX_MMIO 1
#define CONFIG_SCSI_IPR_MODULE 1
#define CONFIG_SCSI_IPR_TRACE 1
#undef CONFIG_SCSI_IPR_DUMP
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#undef CONFIG_SCSI_QLA_FC
#define CONFIG_SCSI_LPFC_MODULE 1
#define CONFIG_SCSI_DC395x_MODULE 1
#define CONFIG_SCSI_DC390T_MODULE 1
#define CONFIG_SCSI_NSP32_MODULE 1
#define CONFIG_SCSI_DEBUG_MODULE 1

/*
 * PCMCIA SCSI adapter support
 */
#undef CONFIG_PCMCIA_AHA152X
#undef CONFIG_PCMCIA_FDOMAIN
#undef CONFIG_PCMCIA_NINJA_SCSI
#undef CONFIG_PCMCIA_QLOGIC
#undef CONFIG_PCMCIA_SYM53C500

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD_MODULE 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID10_MODULE 1
#define CONFIG_MD_RAID5_MODULE 1
#undef CONFIG_MD_RAID5_RESHAPE
#define CONFIG_MD_RAID6_MODULE 1
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM_MODULE 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT_MODULE 1
#define CONFIG_DM_MIRROR_MODULE 1
#define CONFIG_DM_ZERO_MODULE 1
#define CONFIG_DM_MULTIPATH_MODULE 1
#define CONFIG_DM_MULTIPATH_EMC_MODULE 1

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION
#undef CONFIG_FUSION_SPI
#undef CONFIG_FUSION_FC
#undef CONFIG_FUSION_SAS

/*
 * IEEE 1394 (FireWire) support
 */
#define CONFIG_IEEE1394_MODULE 1

/*
 * Subsystem Options
 */
#undef CONFIG_IEEE1394_VERBOSEDEBUG
#define CONFIG_IEEE1394_OUI_DB 1
#define CONFIG_IEEE1394_EXTRA_CONFIG_ROMS 1
#define CONFIG_IEEE1394_CONFIG_ROM_IP1394 1
#define CONFIG_IEEE1394_EXPORT_FULL_API 1

/*
 * Device Drivers
 */
#define CONFIG_IEEE1394_PCILYNX_MODULE 1
#define CONFIG_IEEE1394_OHCI1394_MODULE 1

/*
 * Protocol Drivers
 */
#define CONFIG_IEEE1394_VIDEO1394_MODULE 1
#define CONFIG_IEEE1394_SBP2_MODULE 1
#undef CONFIG_IEEE1394_SBP2_PHYS_DMA
#define CONFIG_IEEE1394_ETH1394_MODULE 1
#define CONFIG_IEEE1394_DV1394_MODULE 1
#define CONFIG_IEEE1394_RAWIO_MODULE 1

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#undef CONFIG_DUMMY
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#define CONFIG_IMQ 1
#undef CONFIG_IMQ_BEHAVIOR_AA
#undef CONFIG_IMQ_BEHAVIOR_AB
#define CONFIG_IMQ_BEHAVIOR_BA 1
#undef CONFIG_IMQ_BEHAVIOR_BB
#define CONFIG_IMQ_NUM_DEVS 2
#define CONFIG_TUN 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * PHY device support
 */
#define CONFIG_PHYLIB_MODULE 1

/*
 * MII PHY device drivers
 */
#define CONFIG_MARVELL_PHY_MODULE 1
#define CONFIG_DAVICOM_PHY_MODULE 1
#define CONFIG_QSEMI_PHY_MODULE 1
#define CONFIG_LXT_PHY_MODULE 1
#define CONFIG_CICADA_PHY_MODULE 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#define CONFIG_HAPPYMEAL_MODULE 1
#define CONFIG_SUNGEM_MODULE 1
#define CONFIG_CASSINI_MODULE 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_VORTEX_MODULE 1
#define CONFIG_TYPHOON_MODULE 1

/*
 * Tulip family network device support
 */
#undef CONFIG_NET_TULIP
#define CONFIG_HP100_MODULE 1
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32_MODULE 1
#define CONFIG_AMD8111_ETH_MODULE 1
#define CONFIG_AMD8111E_NAPI 1
#define CONFIG_ADAPTEC_STARFIRE_MODULE 1
#define CONFIG_ADAPTEC_STARFIRE_NAPI 1
#define CONFIG_B44_MODULE 1
#define CONFIG_FORCEDETH_MODULE 1
#define CONFIG_DGRS_MODULE 1
#define CONFIG_EEPRO100_MODULE 1
#define CONFIG_E100_MODULE 1
#define CONFIG_FEALNX_MODULE 1
#define CONFIG_NATSEMI_MODULE 1
#define CONFIG_NE2K_PCI_MODULE 1
#define CONFIG_8139CP_MODULE 1
#define CONFIG_8139TOO_MODULE 1
#define CONFIG_8139TOO_PIO 1
#undef CONFIG_8139TOO_TUNE_TWISTER
#undef CONFIG_8139TOO_8129
#undef CONFIG_8139_OLD_RX_RESET
#define CONFIG_SIS900_MODULE 1
#define CONFIG_EPIC100_MODULE 1
#define CONFIG_SUNDANCE_MODULE 1
#undef CONFIG_SUNDANCE_MMIO
#define CONFIG_TLAN_MODULE 1
#undef CONFIG_RHINEFET
#undef CONFIG_VIA_RHINE

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#define CONFIG_E1000_NAPI 1
#undef CONFIG_E1000_DISABLE_PACKET_SPLIT
#define CONFIG_NS83820_MODULE 1
#define CONFIG_HAMACHI_MODULE 1
#define CONFIG_YELLOWFIN_MODULE 1
#define CONFIG_R8169_MODULE 1
#define CONFIG_R8169_NAPI 1
#define CONFIG_R8169_VLAN 1
#define CONFIG_SIS190_MODULE 1
#define CONFIG_SKGE_MODULE 1
#define CONFIG_SKY2_MODULE 1
#define CONFIG_SK98LIN_MODULE 1
#define CONFIG_VIA_VELOCITY_MODULE 1
#define CONFIG_TIGON3_MODULE 1
#define CONFIG_BNX2_MODULE 1

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_CHELSIO_T1_MODULE 1
#define CONFIG_IXGB_MODULE 1
#define CONFIG_IXGB_NAPI 1
#define CONFIG_S2IO_MODULE 1
#define CONFIG_S2IO_NAPI 1

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1
#undef CONFIG_NET_WIRELESS_RTNETLINK

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_PCMCIA_WAVELAN
#undef CONFIG_PCMCIA_NETWAVE

/*
 * Wireless 802.11 Frequency Hopping cards support
 */
#undef CONFIG_PCMCIA_RAYCS

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#undef CONFIG_IPW2100
#undef CONFIG_IPW2200
#undef CONFIG_AIRO
#undef CONFIG_HERMES
#undef CONFIG_ATMEL

/*
 * Wireless 802.11b Pcmcia/Cardbus cards support
 */
#undef CONFIG_AIRO_CS
#undef CONFIG_PCMCIA_WL3501

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#undef CONFIG_PRISM54
#undef CONFIG_HOSTAP
#define CONFIG_NET_WIRELESS 1

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#define CONFIG_PCMCIA_3C589_MODULE 1
#define CONFIG_PCMCIA_3C574_MODULE 1
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#define CONFIG_PCMCIA_PCNET_MODULE 1
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#define CONFIG_PCMCIA_AXNET_MODULE 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_FDDI
#undef CONFIG_HIPPI
#define CONFIG_PPP 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC 1
#define CONFIG_PPP_SYNC_TTY 1
#define CONFIG_PPP_DEFLATE 1
#define CONFIG_PPP_BSDCOMP 1
#define CONFIG_PPP_MPPE 1
#define CONFIG_PPPOE 1
#undef CONFIG_SLIP
#undef CONFIG_NET_FC
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#undef CONFIG_INPUT_MOUSEDEV
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#undef CONFIG_INPUT_EVDEV
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#undef CONFIG_INPUT_MOUSE
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT 1
#undef CONFIG_SERIO_CT82C710
#define CONFIG_SERIO_PCIPS2 1
#define CONFIG_SERIO_LIBPS2 1
#undef CONFIG_SERIO_RAW
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#undef CONFIG_COMPUTONE
#undef CONFIG_ROCKETPORT
#undef CONFIG_MOXA
#undef CONFIG_CYCLADES
#undef CONFIG_DIGIEPCA
#undef CONFIG_MOXA_INTELLIO
#undef CONFIG_MOXA_SMARTIO
#undef CONFIG_ISI
#undef CONFIG_SYNCLINK
#undef CONFIG_SYNCLINKMP
#undef CONFIG_SYNCLINK_GT
#undef CONFIG_N_HDLC
#undef CONFIG_RISCOM8
#undef CONFIG_SPECIALIX
#undef CONFIG_SX
#undef CONFIG_RIO
#undef CONFIG_STALDRV

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#undef CONFIG_SERIAL_8250_PCI
#undef CONFIG_SERIAL_8250_CS
#define CONFIG_SERIAL_8250_NR_UARTS 2
#define CONFIG_SERIAL_8250_RUNTIME_UARTS 2
#define CONFIG_SERIAL_8250_EXTENDED 1
#undef CONFIG_SERIAL_8250_MANY_PORTS
#undef CONFIG_SERIAL_8250_SHARE_IRQ
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#undef CONFIG_SERIAL_8250_RSA

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#undef CONFIG_SERIAL_JSM
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG 1
#define CONFIG_ACQUIRE_WDT 1
#define CONFIG_ADVANTECH_WDT 1
#define CONFIG_ALIM1535_WDT 1
#define CONFIG_ALIM7101_WDT 1
#define CONFIG_SC520_WDT 1
#define CONFIG_EUROTECH_WDT 1
#define CONFIG_IB700_WDT 1
#define CONFIG_IBMASR 1
#define CONFIG_WAFER_WDT 1
#define CONFIG_I6300ESB_WDT 1
#define CONFIG_I8XX_TCO 1
#define CONFIG_SC1200_WDT 1
#define CONFIG_SCx200_WDT 1
#define CONFIG_60XX_WDT 1
#define CONFIG_SBC8360_WDT 1
#define CONFIG_CPU5_WDT 1
#define CONFIG_W83627HF_WDT 1
#define CONFIG_W83877F_WDT 1
#define CONFIG_W83977F_WDT 1
#define CONFIG_MACHZ_WDT 1
#define CONFIG_SBC_EPX_C3_WATCHDOG 1

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG 1
#define CONFIG_WDTPCI 1
#undef CONFIG_WDT_501_PCI

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG 1
#define CONFIG_HW_RANDOM 1
#undef CONFIG_NVRAM
#define CONFIG_RTC 1
#undef CONFIG_DTLK
#undef CONFIG_R3964
#undef CONFIG_APPLICOM
#undef CONFIG_SONYPI

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_FTAPE
#define CONFIG_AGP 1
#define CONFIG_AGP_ALI_MODULE 1
#define CONFIG_AGP_ATI_MODULE 1
#define CONFIG_AGP_AMD_MODULE 1
#define CONFIG_AGP_AMD64_MODULE 1
#define CONFIG_AGP_INTEL 1
#define CONFIG_AGP_NVIDIA_MODULE 1
#define CONFIG_AGP_SIS_MODULE 1
#define CONFIG_AGP_SWORKS_MODULE 1
#define CONFIG_AGP_VIA_MODULE 1
#define CONFIG_AGP_EFFICEON_MODULE 1
#undef CONFIG_DRM

/*
 * PCMCIA character devices
 */
#undef CONFIG_SYNCLINK_CS
#undef CONFIG_CARDMAN_4000
#undef CONFIG_CARDMAN_4040
#undef CONFIG_MWAVE
#define CONFIG_SCx200_GPIO_MODULE 1
#define CONFIG_CS5535_GPIO_MODULE 1
#undef CONFIG_RAW_DRIVER
#undef CONFIG_HPET
#undef CONFIG_HANGCHECK_TIMER

/*
 * TPM devices
 */
#undef CONFIG_TCG_TPM
#undef CONFIG_TELCLOCK

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT 1
#define CONFIG_I2C_ALGOPCF 1
#define CONFIG_I2C_ALGOPCA 1

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ALI1535
#undef CONFIG_I2C_ALI1563
#undef CONFIG_I2C_ALI15X3
#undef CONFIG_I2C_AMD756
#undef CONFIG_I2C_AMD8111
#undef CONFIG_I2C_I801
#undef CONFIG_I2C_I810
#undef CONFIG_I2C_PIIX4
#define CONFIG_I2C_ISA_MODULE 1
#undef CONFIG_I2C_NFORCE2
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_PROSAVAGE
#undef CONFIG_I2C_SAVAGE4
#define CONFIG_SCx200_I2C_MODULE 1
#define CONFIG_SCx200_I2C_SCL 12
#define CONFIG_SCx200_I2C_SDA 13
#undef CONFIG_SCx200_ACB
#undef CONFIG_I2C_SIS5595
#undef CONFIG_I2C_SIS630
#undef CONFIG_I2C_SIS96X
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_VIA
#undef CONFIG_I2C_VIAPRO
#undef CONFIG_I2C_VOODOO3
#undef CONFIG_I2C_PCA_ISA

/*
 * Miscellaneous I2C Chip support
 */
#define CONFIG_SENSORS_DS1337 1
#define CONFIG_SENSORS_DS1374 1
#define CONFIG_SENSORS_EEPROM 1
#define CONFIG_SENSORS_PCF8574 1
#define CONFIG_SENSORS_PCA9539 1
#define CONFIG_SENSORS_PCF8591 1
#define CONFIG_SENSORS_MAX6875 1
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * SPI support
 */
#undef CONFIG_SPI

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Hardware Monitoring support
 */
#define CONFIG_HWMON 1
#define CONFIG_HWMON_VID_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ADM1025_MODULE 1
#define CONFIG_SENSORS_ADM1026_MODULE 1
#define CONFIG_SENSORS_ADM1031_MODULE 1
#define CONFIG_SENSORS_ADM9240_MODULE 1
#define CONFIG_SENSORS_AD7418_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_ATXP1_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#define CONFIG_SENSORS_F71805F_MODULE 1
#define CONFIG_SENSORS_FSCHER_MODULE 1
#define CONFIG_SENSORS_FSCPOS_MODULE 1
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_GL520SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM63_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM77_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM87_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#define CONFIG_SENSORS_LM92_MODULE 1
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_PC87360_MODULE 1
#define CONFIG_SENSORS_SIS5595_MODULE 1
#define CONFIG_SENSORS_SMSC47M1_MODULE 1
#define CONFIG_SENSORS_SMSC47B397_MODULE 1
#define CONFIG_SENSORS_VIA686A_MODULE 1
#define CONFIG_SENSORS_VT8231_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83792D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1
#define CONFIG_SENSORS_W83627EHF_MODULE 1
#define CONFIG_SENSORS_AD741X_MODULE 1
#define CONFIG_SENSORS_HDAPS_MODULE 1
#undef CONFIG_HWMON_DEBUG_CHIP

/*
 * Misc devices
 */
#define CONFIG_IBM_ASM 1

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV
#define CONFIG_VIDEO_V4L2 1

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB
#undef CONFIG_USB_DABUSB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT 1
#define CONFIG_FB_CFB_COPYAREA 1
#define CONFIG_FB_CFB_IMAGEBLIT 1
#undef CONFIG_FB_MACMODES
#undef CONFIG_FB_FIRMWARE_EDID
#define CONFIG_FB_MODE_HELPERS 1
#undef CONFIG_FB_TILEBLITTING
#undef CONFIG_FB_CIRRUS
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#undef CONFIG_FB_ARC
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#define CONFIG_FB_VGA16 1
#define CONFIG_FB_VESA 1
#define CONFIG_VIDEO_SELECT 1
#undef CONFIG_FB_HGA
#undef CONFIG_FB_S1D13XXX
#undef CONFIG_FB_NVIDIA
#undef CONFIG_FB_RIVA
#define CONFIG_FB_I810 1
#undef CONFIG_FB_I810_GTF
#undef CONFIG_FB_INTEL
#undef CONFIG_FB_MATROX
#undef CONFIG_FB_RADEON
#define CONFIG_FB_ATY128 1
#undef CONFIG_FB_ATY
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_CYBLA
#undef CONFIG_FB_TRIDENT
#undef CONFIG_FB_GEODE
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_VGACON_SOFT_SCROLLBACK 1
#define CONFIG_VGACON_SOFT_SCROLLBACK_SIZE 64
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FRAMEBUFFER_CONSOLE_ROTATION
#define CONFIG_FONTS 1
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1
#define CONFIG_FONT_6x11 1
#define CONFIG_FONT_7x14 1
#define CONFIG_FONT_PEARL_8x8 1
#define CONFIG_FONT_ACORN_8x8 1
#define CONFIG_FONT_MINI_4x6 1
#define CONFIG_FONT_SUN8x16 1
#define CONFIG_FONT_SUN12x22 1
#define CONFIG_FONT_10x18 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#define CONFIG_LOGO_LINUX_MONO 1
#define CONFIG_LOGO_LINUX_VGA16 1
#define CONFIG_LOGO_LINUX_CLUT224 1
#undef CONFIG_BACKLIGHT_LCD_SUPPORT

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1
#define CONFIG_USB_ARCH_HAS_EHCI 1
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#define CONFIG_USB_BANDWIDTH 1
#define CONFIG_USB_DYNAMIC_MINORS 1
#define CONFIG_USB_SUSPEND 1
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD 1
#define CONFIG_USB_EHCI_SPLIT_ISO 1
#define CONFIG_USB_EHCI_ROOT_HUB_TT 1
#define CONFIG_USB_ISP116X_HCD 1
#define CONFIG_USB_OHCI_HCD 1
#undef CONFIG_USB_OHCI_BIG_ENDIAN
#define CONFIG_USB_OHCI_LITTLE_ENDIAN 1
#define CONFIG_USB_UHCI_HCD 1
#define CONFIG_USB_SL811_HCD 1
#define CONFIG_USB_SL811_CS 1

/*
 * USB Device Class drivers
 */
#define CONFIG_USB_ACM 1
#define CONFIG_USB_PRINTER 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support'
 */

/*
 * may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE 1
#undef CONFIG_USB_STORAGE_DEBUG
#define CONFIG_USB_STORAGE_DATAFAB 1
#define CONFIG_USB_STORAGE_FREECOM 1
#define CONFIG_USB_STORAGE_ISD200 1
#define CONFIG_USB_STORAGE_DPCM 1
#define CONFIG_USB_STORAGE_USBAT 1
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#define CONFIG_USB_STORAGE_JUMPSHOT 1
#define CONFIG_USB_STORAGE_ALAUDA 1
#define CONFIG_USB_LIBUSUAL 1

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_USB_HIDINPUT_POWERBOOK
#undef CONFIG_HID_FF
#undef CONFIG_USB_HIDDEV
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_ACECAD
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_TOUCHSCREEN
#undef CONFIG_USB_YEALINK
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE
#undef CONFIG_USB_ATI_REMOTE2
#undef CONFIG_USB_KEYSPAN_REMOTE
#undef CONFIG_USB_APPLETOUCH

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#undef CONFIG_USB_MICROTEK

/*
 * USB Network Adapters
 */
#define CONFIG_USB_CATC_MODULE 1
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_RTL8150_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1
#define CONFIG_USB_NET_AX8817X_MODULE 1
#define CONFIG_USB_NET_CDCETHER_MODULE 1
#define CONFIG_USB_NET_GL620A_MODULE 1
#define CONFIG_USB_NET_NET1080_MODULE 1
#define CONFIG_USB_NET_PLUSB_MODULE 1
#define CONFIG_USB_NET_RNDIS_HOST_MODULE 1
#define CONFIG_USB_NET_CDC_SUBSET_MODULE 1
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_NET_ZAURUS_MODULE 1
#undef CONFIG_USB_ZD1201
#undef CONFIG_USB_MON

/*
 * USB port drivers
 */

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL 1
#define CONFIG_USB_SERIAL_CONSOLE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#undef CONFIG_USB_SERIAL_AIRPRIME
#undef CONFIG_USB_SERIAL_ANYDATA
#undef CONFIG_USB_SERIAL_ARK3116
#undef CONFIG_USB_SERIAL_BELKIN
#undef CONFIG_USB_SERIAL_WHITEHEAT
#undef CONFIG_USB_SERIAL_DIGI_ACCELEPORT
#undef CONFIG_USB_SERIAL_CP2101
#undef CONFIG_USB_SERIAL_CYPRESS_M8
#undef CONFIG_USB_SERIAL_EMPEG
#undef CONFIG_USB_SERIAL_FTDI_SIO
#undef CONFIG_USB_SERIAL_FUNSOFT
#undef CONFIG_USB_SERIAL_VISOR
#undef CONFIG_USB_SERIAL_IPAQ
#undef CONFIG_USB_SERIAL_IR
#undef CONFIG_USB_SERIAL_EDGEPORT
#undef CONFIG_USB_SERIAL_EDGEPORT_TI
#undef CONFIG_USB_SERIAL_GARMIN
#undef CONFIG_USB_SERIAL_IPW
#undef CONFIG_USB_SERIAL_KEYSPAN_PDA
#undef CONFIG_USB_SERIAL_KEYSPAN
#undef CONFIG_USB_SERIAL_KLSI
#undef CONFIG_USB_SERIAL_KOBIL_SCT
#undef CONFIG_USB_SERIAL_MCT_U232
#undef CONFIG_USB_SERIAL_NAVMAN
#define CONFIG_USB_SERIAL_PL2303 1
#undef CONFIG_USB_SERIAL_HP4X
#undef CONFIG_USB_SERIAL_SAFE
#undef CONFIG_USB_SERIAL_TI
#undef CONFIG_USB_SERIAL_CYBERJACK
#define CONFIG_USB_SERIAL_XIRCOM 1
#undef CONFIG_USB_SERIAL_OPTION
#undef CONFIG_USB_SERIAL_OMNINET
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#undef CONFIG_USB_EMI62
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#undef CONFIG_USB_LCD
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#undef CONFIG_USB_IDMOUSE
#undef CONFIG_USB_SISUSBVGA
#undef CONFIG_USB_LD
#undef CONFIG_USB_TEST

/*
 * USB DSL modem support
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * LED devices
 */
#undef CONFIG_NEW_LEDS

/*
 * LED drivers
 */
#undef CONFIG_RBGPIO

/*
 * LED Triggers
 */

/*
 * InfiniBand support
 */
#undef CONFIG_INFINIBAND

/*
 * EDAC - error detection and reporting (RAS) (EXPERIMENTAL)
 */
#undef CONFIG_EDAC

/*
 * Real Time Clock
 */
#define CONFIG_RTC_LIB 1
#define CONFIG_RTC_CLASS 1
#define CONFIG_RTC_HCTOSYS 1
#define CONFIG_RTC_HCTOSYS_DEVICE "rtc0"

/*
 * RTC interfaces
 */
#define CONFIG_RTC_INTF_SYSFS 1
#define CONFIG_RTC_INTF_PROC 1
#define CONFIG_RTC_INTF_DEV 1

/*
 * RTC drivers
 */
#define CONFIG_RTC_DRV_X1205 1
#define CONFIG_RTC_DRV_DS1672 1
#define CONFIG_RTC_DRV_PCF8563 1
#define CONFIG_RTC_DRV_RS5C372 1
#define CONFIG_RTC_DRV_M48T86 1
#undef CONFIG_RTC_DRV_TEST

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#undef CONFIG_EXT2_FS_POSIX_ACL
#undef CONFIG_EXT2_FS_SECURITY
#define CONFIG_EXT2_FS_XIP 1
#define CONFIG_FS_XIP 1
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#undef CONFIG_EXT3_FS_POSIX_ACL
#undef CONFIG_EXT3_FS_SECURITY
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS 1
#undef CONFIG_REISERFS_CHECK
#define CONFIG_REISERFS_PROC_INFO 1
#define CONFIG_REISERFS_FS_XATTR 1
#undef CONFIG_REISERFS_FS_POSIX_ACL
#undef CONFIG_REISERFS_FS_SECURITY
#undef CONFIG_JFS_FS
#undef CONFIG_FS_POSIX_ACL
#define CONFIG_XFS_FS 1
#undef CONFIG_XFS_QUOTA
#undef CONFIG_XFS_SECURITY
#undef CONFIG_XFS_POSIX_ACL
#undef CONFIG_XFS_RT
#undef CONFIG_OCFS2_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#define CONFIG_SQUASHFS 1
#undef CONFIG_SQUASHFS_EMBEDDED
#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3
#undef CONFIG_SQUASHFS_VMALLOC
#undef CONFIG_INOTIFY
#undef CONFIG_QUOTA
#undef CONFIG_DNOTIFY
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS
#undef CONFIG_FUSE_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS 1
#define CONFIG_UDF_FS 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#define CONFIG_MSDOS_FS 1
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_NTFS_FS 1
#undef CONFIG_NTFS_DEBUG
#define CONFIG_NTFS_RW 1

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#undef CONFIG_PROC_KCORE
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#undef CONFIG_DEVFS_DEBUG
#define CONFIG_SYSFS 1
#define CONFIG_TMPFS 1
#undef CONFIG_HUGETLBFS
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1
#undef CONFIG_CONFIGFS_FS

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_YAFFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_WRITEBUFFER 1
#undef CONFIG_JFFS2_SUMMARY
#define CONFIG_JFFS2_COMPRESSION_OPTIONS 1
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_JFFS2_CMODE_NONE
#undef CONFIG_JFFS2_CMODE_PRIORITY
#define CONFIG_JFFS2_CMODE_SIZE 1
#undef CONFIG_CRAMFS
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef CONFIG_NFS_V3_ACL
#define CONFIG_NFS_V4 1
#define CONFIG_NFS_DIRECTIO 1
#undef CONFIG_NFSD
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_NFS_COMMON 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#undef CONFIG_RPCSEC_GSS_SPKM3
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#undef CONFIG_CIFS
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS
#undef CONFIG_9P_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_OPENWRT_PARTITION
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#undef CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#define CONFIG_LDM_PARTITION 1
#undef CONFIG_LDM_DEBUG
#undef CONFIG_SGI_PARTITION
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_KARMA_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef CONFIG_NLS_CODEPAGE_437
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#undef CONFIG_NLS_CODEPAGE_850
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#undef CONFIG_NLS_CODEPAGE_936
#undef CONFIG_NLS_CODEPAGE_950
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#undef CONFIG_NLS_ISO8859_1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#undef CONFIG_NLS_ISO8859_15
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#undef CONFIG_NLS_UTF8

/*
 * Instrumentation Support
 */
#undef CONFIG_PROFILING
#undef CONFIG_KPROBES

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#undef CONFIG_MAGIC_SYSRQ
#undef CONFIG_DEBUG_KERNEL
#define CONFIG_LOG_BUF_SHIFT 14
#undef CONFIG_DEBUG_BUGVERBOSE
#undef CONFIG_DEBUG_FS
#undef CONFIG_UNWIND_INFO
#define CONFIG_EARLY_PRINTK 1
#define CONFIG_STACK_BACKTRACE_COLS 2
#define CONFIG_X86_FIND_SMP_CONFIG 1
#define CONFIG_X86_MPPARSE 1
#define CONFIG_DOUBLEFAULT 1

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#undef CONFIG_CRYPTO_NULL
#undef CONFIG_CRYPTO_MD4
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#undef CONFIG_CRYPTO_SHA256
#undef CONFIG_CRYPTO_SHA512
#undef CONFIG_CRYPTO_WP512
#undef CONFIG_CRYPTO_TGR192
#define CONFIG_CRYPTO_DES 1
#undef CONFIG_CRYPTO_BLOWFISH
#undef CONFIG_CRYPTO_TWOFISH
#undef CONFIG_CRYPTO_SERPENT
#define CONFIG_CRYPTO_AES 1
#undef CONFIG_CRYPTO_AES_586
#undef CONFIG_CRYPTO_CAST5
#undef CONFIG_CRYPTO_CAST6
#undef CONFIG_CRYPTO_TEA
#define CONFIG_CRYPTO_ARC4 1
#undef CONFIG_CRYPTO_KHAZAD
#undef CONFIG_CRYPTO_ANUBIS
#define CONFIG_CRYPTO_DEFLATE 1
#define CONFIG_CRYPTO_MICHAEL_MIC 1
#define CONFIG_CRYPTO_CRC32C 1
#undef CONFIG_CRYPTO_TEST

/*
 * OCF Configuration
 */
#undef CONFIG_OCF_OCF

/*
 * Hardware crypto devices
 */
#define CONFIG_CRYPTO_DEV_PADLOCK 1
#define CONFIG_CRYPTO_DEV_PADLOCK_AES 1

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#define CONFIG_CRC16 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
#define CONFIG_TEXTSEARCH 1
#define CONFIG_TEXTSEARCH_KMP 1
#define CONFIG_TEXTSEARCH_BM 1
#define CONFIG_TEXTSEARCH_FSM 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_X86_BIOS_REBOOT 1
#define CONFIG_KTIME_SCALAR 1
