'\" t
.\"     Title: libblkid
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2022-08-04
.\"    Manual: Programmer's Manual
.\"    Source: util-linux 2.38.1
.\"  Language: English
.\"
.TH "LIBBLKID" "3" "2022-08-04" "util\-linux 2.38.1" "Programmer\(aqs Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
libblkid \- block device identification library
.SH "SYNOPSIS"
.sp
\fB#include <blkid.h>\fP
.sp
\fBcc\fP \fIfile.c\fP \fB\-lblkid\fP
.SH "DESCRIPTION"
.sp
The \fBlibblkid\fP library is used to identify block devices (disks) as to their content (e.g., filesystem type) as well as extracting additional information such as filesystem labels/volume names, unique identifiers/serial numbers. A common use is to allow use of \fBLABEL=\fP and \fBUUID=\fP tags instead of hard\-coding specific block device names into configuration files.
.sp
The low\-level part of the library also allows the extraction of information about partitions and block device topology.
.sp
The high\-level part of the library keeps information about block devices in a cache file and is verified to still be valid before being returned to the user (if the user has read permission on the raw block device, otherwise not). The cache file also allows unprivileged users (normally anyone other than root, or those not in the "disk" group) to locate devices by label/id. The standard location of the cache file can be overridden by the environment variable \fBBLKID_FILE\fP.
.sp
In situations where one is getting information about a single known device, it does not impact performance whether the cache is used or not (unless you are not able to read the block device directly).
.sp
The high\-level part of the library supports two methods to determine \fBLABEL/UUID\fP. It reads information directly from a block device or read information from /dev/disk/by\-* udev symlinks. The udev is preferred method by default.
.sp
If you are dealing with multiple devices, use of the cache is highly recommended (even if empty) as devices will be scanned at most one time and the on\-disk cache will be updated if possible.
.sp
In some cases (modular kernels), block devices are not even visible until after they are accessed the first time, so it is critical that there is some way to locate these devices without enumerating only visible devices, so the use of the cache file is \fBrequired\fP in this situation.
.SH "CONFIGURATION FILE"
.sp
The standard location of the \fI/etc/blkid.conf\fP config file can be overridden by the environment variable \fBBLKID_CONF\fP. For more details about the config file see \fBblkid\fP(8) man page.
.SH "AUTHORS"
.sp
\fBlibblkid\fP was written by Andreas Dilger for the ext2 filesystem utilities, with input from Ted Ts\(cqo. The library was subsequently heavily modified by Ted Ts\(cqo.
.sp
The low\-level probing code was rewritten by Karel Zak.
.SH "COPYING"
.sp
\fBlibblkid\fP is available under the terms of the GNU Library General Public License (LGPL), version 2 (or at your discretion any later version).
.SH "SEE ALSO"
.sp
\fBblkid\fP(8),
\fBfindfs\fP(8)
.SH "REPORTING BUGS"
.sp
For bug reports, use the issue tracker at \c
.URL "https://github.com/util\-linux/util\-linux/issues" "" "."
.SH "AVAILABILITY"
.sp
The \fBlibblkid\fP library is part of the util\-linux package since version 2.15. It can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."