config_require(agent/nsTransactionTable)
config_require(agent/nsModuleTable)
config_require(agent/nsDebug)
config_require(agent/nsCache)
config_require(agent/nsLogging)
config_require(agent/nsVacmAccessTable)
config_add_mib(NET-SNMP-AGENT-MIB)
