#!/bin/sh

insmod bridge
brctl addbr br0
brctl addbr br1
brctl addbr br2
brctl addif br0 tap0
brctl addif br0 tap1
brctl addif br0 tap2
brctl addif br1 tap3
brctl addif br1 tap4
brctl addif br1 tap5
brctl addif br2 tap6
brctl addif br2 tap7
brctl addif br2 tap8
ifconfig br0 up
ifconfig br1 up
ifconfig br2 up
