svn add Doc/README.rst
svn add Doc/README.txt
svn add Doc/c-api/coro.rst
svn add Doc/howto/instrumentation.rst
svn add Doc/howto/webservers.rst
svn add Doc/includes/email-alternative-new-api.py
svn add Doc/includes/email-read-alternative-new-api.py
svn add Doc/includes/email-read-alternative.py
svn add Doc/library/asyncio-queue.rst
svn add Doc/library/email-examples.rst
svn add Doc/library/email.compat32-message.rst
svn add Doc/library/email.examples.rst
svn add Doc/library/hashlib-blake2-tree.png
svn add Doc/library/secrets.rst
svn add Doc/library/superseded.rst
svn add Doc/library/typing.rst
svn add Doc/library/zipapp.rst
svn add Doc/tools/extensions
svn add Doc/tools/pydoctheme
svn add Doc/tools/roman.py
svn add Doc/tools/sphinxext
svn add Doc/tools/sphinxext/c_annotations.py
svn add Doc/tools/sphinxext/download.html
svn add Doc/tools/sphinxext/indexcontent.html
svn add Doc/tools/sphinxext/indexsidebar.html
svn add Doc/tools/sphinxext/layout.html
svn add Doc/tools/sphinxext/opensearch.xml
svn add Doc/tools/sphinxext/patchlevel.py
svn add Doc/tools/sphinxext/pydoctheme
svn add Doc/tools/sphinxext/pydoctheme/static
svn add Doc/tools/sphinxext/pydoctheme/static/pydoctheme.css
svn add Doc/tools/sphinxext/pydoctheme/theme.conf
svn add Doc/tools/sphinxext/pyspecific.py
svn add Doc/tools/sphinxext/static
svn add Doc/tools/sphinxext/static/basic.css
svn add Doc/tools/sphinxext/static/copybutton.js
svn add Doc/tools/sphinxext/static/py.png
svn add Doc/tools/sphinxext/static/sidebar.js
svn add Doc/tools/sphinxext/static/version_switch.js
svn add Doc/tools/sphinxext/susp-ignored.csv
svn add Doc/tools/sphinxext/suspicious.py
svn add Doc/tools/static
svn add Doc/tools/susp-ignored.csv
svn add Doc/tools/templates
svn add Doc/tutorial/venv.rst
svn add Doc/using/scripts.rst
svn add Doc/using/win_installer.png
svn add Doc/whatsnew/3.5.rst
svn add Doc/whatsnew/3.6.rst
svn add Include/odictobject.h
svn add Include/osmodule.h
svn add Include/pydtrace.d
svn add Include/pydtrace.h
svn add Include/pylifecycle.h
svn add Include/pystrhex.h
svn add Lib/_compression.py
svn add Lib/_pydecimal.py
svn add Lib/asyncio/base_futures.py
svn add Lib/asyncio/base_tasks.py
svn add Lib/asyncio/compat.py
svn add Lib/asyncio/sslproto.py
svn add Lib/collections/__main__.py
svn add Lib/distutils/_msvccompiler.py
svn add Lib/distutils/command/wininst-14.0-amd64.exe
svn add Lib/distutils/command/wininst-14.0.exe
svn add Lib/distutils/tests/test_msvccompiler.py
svn add Lib/encodings/koi8_t.py
svn add Lib/encodings/kz1048.py
svn add Lib/encodings/oem.py
svn add Lib/ensurepip/_bundled/pip-1.5.6-py2.py3-none-any.whl
svn add Lib/ensurepip/_bundled/pip-9.0.1-py2.py3-none-any.whl
svn add Lib/ensurepip/_bundled/setuptools-2.1-py2.py3-none-any.whl
svn add Lib/ensurepip/_bundled/setuptools-28.8.0-py2.py3-none-any.whl
svn add Lib/idlelib/AutoComplete.py
svn add Lib/idlelib/AutoCompleteWindow.py
svn add Lib/idlelib/AutoExpand.py
svn add Lib/idlelib/Bindings.py
svn add Lib/idlelib/CallTipWindow.py
svn add Lib/idlelib/CallTips.py
svn add Lib/idlelib/ClassBrowser.py
svn add Lib/idlelib/CodeContext.py
svn add Lib/idlelib/ColorDelegator.py
svn add Lib/idlelib/Debugger.py
svn add Lib/idlelib/Delegator.py
svn add Lib/idlelib/EditorWindow.py
svn add Lib/idlelib/FileList.py
svn add Lib/idlelib/FormatParagraph.py
svn add Lib/idlelib/GrepDialog.py
svn add Lib/idlelib/HyperParser.py
svn add Lib/idlelib/IOBinding.py
svn add Lib/idlelib/IdleHistory.py
svn add Lib/idlelib/MultiCall.py
svn add Lib/idlelib/MultiStatusBar.py
svn add Lib/idlelib/NEWS2x.txt
svn add Lib/idlelib/ObjectBrowser.py
svn add Lib/idlelib/OutputWindow.py
svn add Lib/idlelib/ParenMatch.py
svn add Lib/idlelib/PathBrowser.py
svn add Lib/idlelib/Percolator.py
svn add Lib/idlelib/PyParse.py
svn add Lib/idlelib/PyShell.py
svn add Lib/idlelib/RemoteDebugger.py
svn add Lib/idlelib/RemoteObjectBrowser.py
svn add Lib/idlelib/ReplaceDialog.py
svn add Lib/idlelib/RstripExtension.py
svn add Lib/idlelib/ScriptBinding.py
svn add Lib/idlelib/ScrolledList.py
svn add Lib/idlelib/SearchDialog.py
svn add Lib/idlelib/SearchDialogBase.py
svn add Lib/idlelib/SearchEngine.py
svn add Lib/idlelib/StackViewer.py
svn add Lib/idlelib/ToolTip.py
svn add Lib/idlelib/TreeWidget.py
svn add Lib/idlelib/UndoDelegator.py
svn add Lib/idlelib/WidgetRedirector.py
svn add Lib/idlelib/WindowList.py
svn add Lib/idlelib/ZoomHeight.py
svn add Lib/idlelib/aboutDialog.py
svn add Lib/idlelib/autocomplete.py
svn add Lib/idlelib/autocomplete_w.py
svn add Lib/idlelib/autoexpand.py
svn add Lib/idlelib/browser.py
svn add Lib/idlelib/calltip_w.py
svn add Lib/idlelib/calltips.py
svn add Lib/idlelib/codecontext.py
svn add Lib/idlelib/colorizer.py
svn add Lib/idlelib/config.py
svn add Lib/idlelib/configDialog.py
svn add Lib/idlelib/configHandler.py
svn add Lib/idlelib/configHelpSourceEdit.py
svn add Lib/idlelib/configSectionNameDialog.py
svn add Lib/idlelib/config_key.py
svn add Lib/idlelib/configdialog.py
svn add Lib/idlelib/debugger.py
svn add Lib/idlelib/debugger_r.py
svn add Lib/idlelib/debugobj.py
svn add Lib/idlelib/debugobj_r.py
svn add Lib/idlelib/delegator.py
svn add Lib/idlelib/dynOptionMenuWidget.py
svn add Lib/idlelib/dynoption.py
svn add Lib/idlelib/editor.py
svn add Lib/idlelib/filelist.py
svn add Lib/idlelib/grep.py
svn add Lib/idlelib/help.html
svn add Lib/idlelib/help.py
svn add Lib/idlelib/help.txt
svn add Lib/idlelib/help_about.py
svn add Lib/idlelib/history.py
svn add Lib/idlelib/hyperparser.py
svn add Lib/idlelib/idle_test/test_colorizer.py
svn add Lib/idlelib/idle_test/test_config.py
svn add Lib/idlelib/idle_test/test_config_key.py
svn add Lib/idlelib/idle_test/test_config_name.py
svn add Lib/idlelib/idle_test/test_debugger.py
svn add Lib/idlelib/idle_test/test_editmenu.py
svn add Lib/idlelib/idle_test/test_editor.py
svn add Lib/idlelib/idle_test/test_formatparagraph.py
svn add Lib/idlelib/idle_test/test_help.py
svn add Lib/idlelib/idle_test/test_help_about.py
svn add Lib/idlelib/idle_test/test_history.py
svn add Lib/idlelib/idle_test/test_idlehistory.py
svn add Lib/idlelib/idle_test/test_iomenu.py
svn add Lib/idlelib/idle_test/test_macosx.py
svn add Lib/idlelib/idle_test/test_outwin.py
svn add Lib/idlelib/idle_test/test_paragraph.py
svn add Lib/idlelib/idle_test/test_percolator.py
svn add Lib/idlelib/idle_test/test_query.py
svn add Lib/idlelib/idle_test/test_redirector.py
svn add Lib/idlelib/idle_test/test_replace.py
svn add Lib/idlelib/idle_test/test_scrolledlist.py
svn add Lib/idlelib/idle_test/test_search.py
svn add Lib/idlelib/idle_test/test_searchbase.py
svn add Lib/idlelib/idle_test/test_searchdialogbase.py
svn add Lib/idlelib/idle_test/test_tree.py
svn add Lib/idlelib/idle_test/test_undo.py
svn add Lib/idlelib/idle_test/test_widgetredir.py
svn add Lib/idlelib/idlever.py
svn add Lib/idlelib/iomenu.py
svn add Lib/idlelib/keybindingDialog.py
svn add Lib/idlelib/macosx.py
svn add Lib/idlelib/macosxSupport.py
svn add Lib/idlelib/mainmenu.py
svn add Lib/idlelib/multicall.py
svn add Lib/idlelib/outwin.py
svn add Lib/idlelib/paragraph.py
svn add Lib/idlelib/parenmatch.py
svn add Lib/idlelib/pathbrowser.py
svn add Lib/idlelib/percolator.py
svn add Lib/idlelib/pyparse.py
svn add Lib/idlelib/pyshell.py
svn add Lib/idlelib/query.py
svn add Lib/idlelib/redirector.py
svn add Lib/idlelib/replace.py
svn add Lib/idlelib/rstrip.py
svn add Lib/idlelib/runscript.py
svn add Lib/idlelib/scrolledlist.py
svn add Lib/idlelib/search.py
svn add Lib/idlelib/searchbase.py
svn add Lib/idlelib/searchengine.py
svn add Lib/idlelib/stackviewer.py
svn add Lib/idlelib/statusbar.py
svn add Lib/idlelib/testcode.py
svn add Lib/idlelib/textView.py
svn add Lib/idlelib/textview.py
svn add Lib/idlelib/tooltip.py
svn add Lib/idlelib/tree.py
svn add Lib/idlelib/undo.py
svn add Lib/idlelib/windows.py
svn add Lib/idlelib/zoomheight.py
svn add Lib/idlelib/zzdummy.py
svn add Lib/imp.py.orig
svn add Lib/importlib/_bootstrap_external.py
svn add Lib/lib2to3/fixes/fix_callable.py
svn add Lib/lib2to3/tests/__main__.py
svn add Lib/plat-aix4
svn add Lib/plat-aix4/IN.py
svn add Lib/plat-aix4/regen
svn add Lib/plat-darwin
svn add Lib/plat-darwin/IN.py
svn add Lib/plat-darwin/regen
svn add Lib/plat-freebsd4
svn add Lib/plat-freebsd4/IN.py
svn add Lib/plat-freebsd4/regen
svn add Lib/plat-freebsd5
svn add Lib/plat-freebsd5/IN.py
svn add Lib/plat-freebsd5/regen
svn add Lib/plat-freebsd6
svn add Lib/plat-freebsd6/IN.py
svn add Lib/plat-freebsd6/regen
svn add Lib/plat-freebsd7
svn add Lib/plat-freebsd7/IN.py
svn add Lib/plat-freebsd7/regen
svn add Lib/plat-freebsd8
svn add Lib/plat-freebsd8/IN.py
svn add Lib/plat-freebsd8/regen
svn add Lib/plat-generic
svn add Lib/plat-generic/regen
svn add Lib/plat-linux
svn add Lib/plat-linux/CDROM.py
svn add Lib/plat-linux/DLFCN.py
svn add Lib/plat-linux/IN.py
svn add Lib/plat-linux/TYPES.py
svn add Lib/plat-linux/regen
svn add Lib/plat-netbsd1
svn add Lib/plat-netbsd1/IN.py
svn add Lib/plat-netbsd1/regen
svn add Lib/plat-next3
svn add Lib/plat-next3/regen
svn add Lib/plat-sunos5
svn add Lib/plat-sunos5/CDIO.py
svn add Lib/plat-sunos5/DLFCN.py
svn add Lib/plat-sunos5/IN.py
svn add Lib/plat-sunos5/STROPTS.py
svn add Lib/plat-sunos5/TYPES.py
svn add Lib/plat-sunos5/regen
svn add Lib/plat-unixware7
svn add Lib/plat-unixware7/IN.py
svn add Lib/plat-unixware7/STROPTS.py
svn add Lib/plat-unixware7/regen
svn add Lib/secrets.py
svn add Lib/signal.py
svn add Lib/site-packages/README
svn add Lib/site-packages/README.txt
svn add Lib/test/185test.db
svn add Lib/test/allsans.pem
svn add Lib/test/ann_module.py
svn add Lib/test/ann_module2.py
svn add Lib/test/ann_module3.py
svn add Lib/test/bisect.py
svn add Lib/test/buffer_tests.py
svn add Lib/test/capath/b1930218.0
svn add Lib/test/capath/ceff1710.0
svn add Lib/test/check_soundcard.vbs
svn add Lib/test/dh1024.pem
svn add Lib/test/dh512.pem
svn add Lib/test/dtracedata
svn add Lib/test/eintrdata
svn add Lib/test/https_svn_python_org_root.pem
svn add Lib/test/imghdrdata/python.exr
svn add Lib/test/imghdrdata/python.webp
svn add Lib/test/imp_dummy.py
svn add Lib/test/libregrtest
svn add Lib/test/mod_generics_cache.py
svn add Lib/test/mp_preload.py
svn add Lib/test/pythoninfo.py
svn add Lib/test/script_helper.py
svn add Lib/test/selfsigned_pythontestdotnet.pem
svn add Lib/test/sha256.pem
svn add Lib/test/signalinterproctester.py
svn add Lib/test/support/script_helper.py
svn add Lib/test/test_asdl_parser.py
svn add Lib/test/test_asyncgen.py
svn add Lib/test/test_asyncio/test_pep492.py
svn add Lib/test/test_asyncio/test_sslproto.py
svn add Lib/test/test_baseexception.py
svn add Lib/test/test_coroutines.py
svn add Lib/test/test_dict_version.py
svn add Lib/test/test_dtrace.py
svn add Lib/test/test_eintr.py
svn add Lib/test/test_exception_hierarchy.py
svn add Lib/test/test_fstring.py
svn add Lib/test/test_generator_stop.py
svn add Lib/test/test_import
svn add Lib/test/test_import.py
svn add Lib/test/test_importlib/builtin/util.py
svn add Lib/test/test_importlib/extension/util.py
svn add Lib/test/test_importlib/import_/util.py
svn add Lib/test/test_importlib/regrtest.py
svn add Lib/test/test_importlib/source/util.py
svn add Lib/test/test_importlib/test_lazy.py
svn add Lib/test/test_ordered_dict.py
svn add Lib/test/test_pep247.py
svn add Lib/test/test_pep277.py
svn add Lib/test/test_pep292.py
svn add Lib/test/test_pep3120.py
svn add Lib/test/test_pep3131.py
svn add Lib/test/test_pep3151.py
svn add Lib/test/test_pep352.py
svn add Lib/test/test_pep380.py
svn add Lib/test/test_script_helper.py
svn add Lib/test/test_secrets.py
svn add Lib/test/test_string_literals.py
svn add Lib/test/test_strlit.py
svn add Lib/test/test_subclassinit.py
svn add Lib/test/test_symbol.py
svn add Lib/test/test_tix.py
svn add Lib/test/test_tools/test_fixcid.py
svn add Lib/test/test_tools/test_i18n.py
svn add Lib/test/test_turtle.py
svn add Lib/test/test_typing.py
svn add Lib/test/test_unicode_file_functions.py
svn add Lib/test/test_unicode_identifiers.py
svn add Lib/test/test_utf8source.py
svn add Lib/test/test_warnings
svn add Lib/test/test_warnings.py
svn add Lib/test/test_winconsoleio.py
svn add Lib/test/test_yield_from.py
svn add Lib/test/test_zipapp.py
svn add Lib/test/warning_tests.py
svn add Lib/test/wrongcert.pem
svn add Lib/tkinter/_fix.py
svn add Lib/turtledemo/sorting_animate.py
svn add Lib/typing.py
svn add Lib/venv/scripts/common
svn add Lib/venv/scripts/posix/activate
svn add Lib/zipapp.py
svn add Mac/BuildScript/openssl_sdk_makedepend.patch
svn add Mac/BuildScript/resources/License.rtf
svn add Mac/BuildScript/resources/ReadMe.rtf
svn add Mac/BuildScript/resources/ReadMe.txt
svn add Mac/BuildScript/resources/install_certificates.command
svn add Mac/BuildScript/resources/readme.rtf
svn add Mac/Tools/bundlebuilder.py
svn add Misc/RPM
svn add Misc/RPM/README
svn add Misc/RPM/python-3.4.spec
svn add Modules/README
svn add Modules/Setup.dist.orig
svn add Modules/_asynciomodule.c
svn add Modules/_blake2
svn add Modules/_ctypes/libffi_arm_wince
svn add Modules/_ctypes/libffi_arm_wince/debug.c
svn add Modules/_ctypes/libffi_arm_wince/ffi.c
svn add Modules/_ctypes/libffi_arm_wince/ffi.h
svn add Modules/_ctypes/libffi_arm_wince/ffi_common.h
svn add Modules/_ctypes/libffi_arm_wince/fficonfig.h
svn add Modules/_ctypes/libffi_arm_wince/ffitarget.h
svn add Modules/_ctypes/libffi_arm_wince/prep_cif.c
svn add Modules/_ctypes/libffi_arm_wince/sysv.asm
svn add Modules/_decimal/libmpdec/memory.h
svn add Modules/_decimal/libmpdec/mpalloc.h
svn add Modules/_freeze_importlib.c
svn add Modules/_io/clinic
svn add Modules/_io/winconsoleio.c
svn add Modules/_sha3
svn add Modules/_testembed.c
svn add Modules/_testmultiphase.c
svn add Modules/cjkcodecs/clinic
svn add Modules/clinic/_asynciomodule.c.h
svn add Modules/clinic/_codecsmodule.c.h
svn add Modules/clinic/_cryptmodule.c.h
svn add Modules/clinic/_cursesmodule.c.h
svn add Modules/clinic/_datetimemodule.c.h
svn add Modules/clinic/_dbmmodule.c.h
svn add Modules/clinic/_elementtree.c.h
svn add Modules/clinic/_gdbmmodule.c.h
svn add Modules/clinic/_hashopenssl.c.h
svn add Modules/clinic/_opcode.c.h
svn add Modules/clinic/_sre.c.h
svn add Modules/clinic/_ssl.c.h
svn add Modules/clinic/_tkinter.c.h
svn add Modules/clinic/_weakref.c.h
svn add Modules/clinic/_winapi.c.h
svn add Modules/clinic/arraymodule.c.h
svn add Modules/clinic/cmathmodule.c.h
svn add Modules/clinic/fcntlmodule.c.h
svn add Modules/clinic/grpmodule.c.h
svn add Modules/clinic/md5module.c.h
svn add Modules/clinic/posixmodule.c.h
svn add Modules/clinic/pwdmodule.c.h
svn add Modules/clinic/pyexpat.c.h
svn add Modules/clinic/sha1module.c.h
svn add Modules/clinic/sha256module.c.h
svn add Modules/clinic/sha512module.c.h
svn add Modules/clinic/signalmodule.c.h
svn add Modules/clinic/spwdmodule.c.h
svn add Modules/clinic/unicodedata.c.h
svn add Modules/expat/amigaconfig.h
svn add Modules/expat/loadlibrary.c
svn add Modules/expat/macconfig.h
svn add Modules/expat/siphash.h
svn add Modules/expat/watcomconfig.h
svn add Modules/python.c
svn add Modules/winreparse.h
svn add Objects/README
svn add Objects/clinic
svn add Objects/dict-common.h
svn add Objects/odictobject.c
svn add PC/VS9.0
svn add PC/VS9.0/_bz2.vcproj
svn add PC/VS9.0/_ctypes.vcproj
svn add PC/VS9.0/_ctypes_test.vcproj
svn add PC/VS9.0/_decimal.vcproj
svn add PC/VS9.0/_elementtree.vcproj
svn add PC/VS9.0/_hashlib.vcproj
svn add PC/VS9.0/_lzma.vcproj
svn add PC/VS9.0/_msi.vcproj
svn add PC/VS9.0/_multiprocessing.vcproj
svn add PC/VS9.0/_socket.vcproj
svn add PC/VS9.0/_sqlite3.vcproj
svn add PC/VS9.0/_ssl.vcproj
svn add PC/VS9.0/_testbuffer.vcproj
svn add PC/VS9.0/_testcapi.vcproj
svn add PC/VS9.0/_testimportmultiple.vcproj
svn add PC/VS9.0/_tkinter.vcproj
svn add PC/VS9.0/bdist_wininst.vcproj
svn add PC/VS9.0/debug.vsprops
svn add PC/VS9.0/kill_python.c
svn add PC/VS9.0/kill_python.vcproj
svn add PC/VS9.0/make_buildinfo.c
svn add PC/VS9.0/make_buildinfo.vcproj
svn add PC/VS9.0/make_versioninfo.vcproj
svn add PC/VS9.0/pcbuild.sln
svn add PC/VS9.0/pginstrument.vsprops
svn add PC/VS9.0/pgupdate.vsprops
svn add PC/VS9.0/pyd.vsprops
svn add PC/VS9.0/pyd_d.vsprops
svn add PC/VS9.0/pyexpat.vcproj
svn add PC/VS9.0/pyproject.vsprops
svn add PC/VS9.0/python.vcproj
svn add PC/VS9.0/python3dll.vcproj
svn add PC/VS9.0/pythoncore.vcproj
svn add PC/VS9.0/pythonw.vcproj
svn add PC/VS9.0/release.vsprops
svn add PC/VS9.0/select.vcproj
svn add PC/VS9.0/sqlite3.vcproj
svn add PC/VS9.0/sqlite3.vsprops
svn add PC/VS9.0/ssl.vcproj
svn add PC/VS9.0/unicodedata.vcproj
svn add PC/VS9.0/winsound.vcproj
svn add PC/VS9.0/x64.vsprops
svn add PC/VS9.0/xxlimited.vcproj
svn add PC/_findvs.cpp
svn add PC/_testconsole.c
svn add PC/bdist_wininst/bdist_wininst.vcxproj
svn add PC/bdist_wininst/bdist_wininst.vcxproj.filters
svn add PC/bdist_wininst/build.bat
svn add PC/bdist_wininst/wininst-7.1.sln
svn add PC/bdist_wininst/wininst-7.1.vcproj
svn add PC/bdist_wininst/wininst-8.sln
svn add PC/bdist_wininst/wininst-8.vcproj
svn add PC/bdist_wininst/wininst.dsp
svn add PC/bdist_wininst/wininst.dsw
svn add PC/clinic
svn add PC/example_nt
svn add PC/example_nt/example.c
svn add PC/example_nt/example.sln
svn add PC/example_nt/example.vcproj
svn add PC/example_nt/readme.txt
svn add PC/example_nt/setup.py
svn add PC/external
svn add PC/icons/baselogo.svg
svn add PC/icons/launcher.icns
svn add PC/icons/launcher.ico
svn add PC/icons/launcher.svg
svn add PC/icons/py.icns
svn add PC/icons/py.ico
svn add PC/icons/py.svg
svn add PC/icons/pyc.icns
svn add PC/icons/pyc.ico
svn add PC/icons/pyc.svg
svn add PC/icons/pyd.icns
svn add PC/icons/pyd.ico
svn add PC/icons/pyd.svg
svn add PC/icons/python.icns
svn add PC/icons/python.ico
svn add PC/icons/python.svg
svn add PC/icons/pythonw.icns
svn add PC/icons/pythonw.ico
svn add PC/icons/pythonw.svg
svn add PC/icons/setup.icns
svn add PC/icons/setup.ico
svn add PC/icons/setup.svg
svn add PC/icons/source.xar
svn add PC/icons.mak
svn add PC/icons.rc
svn add PC/invalid_parameter_handler.c
svn add PC/launcher.ico
svn add PC/make_versioninfo.c
svn add PC/py.ico
svn add PC/pyc.ico
svn add PC/pycon.ico
svn add PC/pyshellext.cpp
svn add PC/pyshellext.def
svn add PC/pyshellext.idl
svn add PC/pyshellext.rc
svn add PC/pyshellext_d.def
svn add PC/python.manifest
svn add PC/python3.mak
svn add PC/python34gen.py
svn add PC/python34stub.def
svn add PC/python_ver_rc.h
svn add PC/pythonw_exe.rc
svn add PC/sqlite3.rc
svn add PC/validate_ucrtbase.py
svn add PCbuild/_asyncio.vcxproj
svn add PCbuild/_asyncio.vcxproj.filters
svn add PCbuild/_testconsole.vcxproj
svn add PCbuild/_testconsole.vcxproj.filters
svn add PCbuild/_testmultiphase.vcxproj
svn add PCbuild/_testmultiphase.vcxproj.filters
svn add PCbuild/bdist_wininst.vcxproj
svn add PCbuild/bdist_wininst.vcxproj.filters
svn add PCbuild/build_pgo.bat
svn add PCbuild/build_ssl.bat
svn add PCbuild/build_ssl.py
svn add PCbuild/build_tkinter.py
svn add PCbuild/clean.bat
svn add PCbuild/debug.props
svn add PCbuild/find_msbuild.bat
svn add PCbuild/find_python.bat
svn add PCbuild/get_external.py
svn add PCbuild/get_externals.bat
svn add PCbuild/installer.bmp
svn add PCbuild/kill_python.c
svn add PCbuild/kill_python.vcxproj
svn add PCbuild/kill_python.vcxproj.filters
svn add PCbuild/libeay.vcxproj
svn add PCbuild/liblzma.vcxproj
svn add PCbuild/make_buildinfo.c
svn add PCbuild/make_buildinfo.vcxproj
svn add PCbuild/make_buildinfo.vcxproj.filters
svn add PCbuild/make_versioninfo.vcxproj
svn add PCbuild/make_versioninfo.vcxproj.filters
svn add PCbuild/openssl.props
svn add PCbuild/pcbuild.proj
svn add PCbuild/pginstrument.props
svn add PCbuild/pgupdate.props
svn add PCbuild/prepare_ssl.bat
svn add PCbuild/prepare_ssl.py
svn add PCbuild/pyd.props
svn add PCbuild/pyd_d.props
svn add PCbuild/pyshellext.vcxproj
svn add PCbuild/pyshellext.vcxproj.filters
svn add PCbuild/python.props
svn add PCbuild/release.props
svn add PCbuild/sqlite3.props
svn add PCbuild/ssl.vcxproj
svn add PCbuild/ssleay.vcxproj
svn add PCbuild/tcl.vcxproj
svn add PCbuild/tcltk.props
svn add PCbuild/tix.vcxproj
svn add PCbuild/tk.vcxproj
svn add PCbuild/urlretrieve.py
svn add PCbuild/vs9to10.py
svn add PCbuild/vs9to8.py
svn add PCbuild/x64.props
svn add Parser/spark.py
svn add Programs
svn add Python/README
svn add Python/clinic
svn add Python/importlib_external.h
svn add Python/pylifecycle.c
svn add Python/pystrhex.c
svn add Python/wordcode_helpers.h
svn add README
svn add README.rst
svn add Tools/buildbot/README.tcltk-AMD64
svn add Tools/buildbot/build-amd64.bat
svn add Tools/buildbot/clean-amd64.bat
svn add Tools/buildbot/external-amd64.bat
svn add Tools/buildbot/external-common.bat
svn add Tools/buildbot/external.bat
svn add Tools/buildbot/test-amd64.bat
svn add Tools/hg
svn add Tools/hg/hgtouch.py
svn add Tools/msi/build.bat
svn add Tools/msi/buildrelease.bat
svn add Tools/msi/bundle
svn add Tools/msi/common.wxs
svn add Tools/msi/common_en-US.wxl_template
svn add Tools/msi/core
svn add Tools/msi/crtlicense.txt
svn add Tools/msi/csv_to_wxs.py
svn add Tools/msi/dev
svn add Tools/msi/distutils.command.bdist_wininst.py
svn add Tools/msi/doc
svn add Tools/msi/exe
svn add Tools/msi/generate_md5.py
svn add Tools/msi/get_externals.bat
svn add Tools/msi/launcher
svn add Tools/msi/lib
svn add Tools/msi/make_zip.proj
svn add Tools/msi/make_zip.py
svn add Tools/msi/msi.props
svn add Tools/msi/msi.py
svn add Tools/msi/msi.targets
svn add Tools/msi/msilib.py
svn add Tools/msi/msisupport.c
svn add Tools/msi/msisupport.mak
svn add Tools/msi/path
svn add Tools/msi/pip
svn add Tools/msi/purge.py
svn add Tools/msi/schema.py
svn add Tools/msi/sequence.py
svn add Tools/msi/tcltk
svn add Tools/msi/test
svn add Tools/msi/testrelease.bat
svn add Tools/msi/tools
svn add Tools/msi/uisample.py
svn add Tools/msi/uploadrelease.bat
svn add Tools/msi/uploadrelease.proj
svn add Tools/msi/wix.props
svn add Tools/nuget
svn add Tools/scripts/ftpmirror.py
svn add Tools/scripts/generate_opcode_h.py
svn add Tools/ssl/multissltests.py
svn add Tools/ssl/sslspeed.vcxproj
svn add Tools/ssl/test_multiple_versions.py
svn add Tools/tz
svn add aclocal.m4
svn add add.sh
svn add setup.py.orig
svn add site
svn add site/config.site
