'\" t
.\"     Title: lsirq
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2022-05-11
.\"    Manual: User Commands
.\"    Source: util-linux 2.38.1
.\"  Language: English
.\"
.TH "LSIRQ" "1" "2022-05-11" "util\-linux 2.38.1" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
lsirq \- utility to display kernel interrupt information
.SH "SYNOPSIS"
.sp
\fBlsirq\fP [options]
.SH "DESCRIPTION"
.sp
Display kernel interrupt counter information.
.sp
The default output is subject to change. So whenever possible, you should avoid using default outputs in your scripts. Always explicitly define expected columns by using \fB\-\-output\fP.
.SH "OPTIONS"
.sp
\fB\-n\fP, \fB\-\-noheadings\fP
.RS 4
Don\(cqt print headings.
.RE
.sp
\fB\-o\fP, \fB\-\-output\fP \fIlist\fP
.RS 4
Specify which output columns to print. Use \fB\-\-help\fP to get a list of all supported columns. The default list of columns may be extended if list is specified in the format \fI+list\fP.
.RE
.sp
\fB\-s\fP, \fB\-\-sort\fP \fIcolumn\fP
.RS 4
Specify sort criteria by column name. See \fB\-\-help\fP output to get column names.
.RE
.sp
\fB\-J\fP, \fB\-\-json\fP
.RS 4
Use JSON output format.
.RE
.sp
\fB\-P\fP, \fB\-\-pairs\fP
.RS 4
Produce output in the form of key="value" pairs. All potentially unsafe characters are hex\-escaped (\(rsx<code>).
.RE
.sp
\fB\-S\fP, \fB\-\-softirq\fP
.RS 4
Show softirqs information.
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display help text and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version and exit.
.RE
.SH "AUTHORS"
.sp
.MTO "pizhenwei\(atbytedance.com" "Zhenwei Pi" ","
.MTO "kerolasa\(atiki.fi" "Sami Kerola" ","
.MTO "kzak\(atredhat.com" "Karel Zak" ""
.SH "REPORTING BUGS"
.sp
For bug reports, use the issue tracker at \c
.URL "https://github.com/util\-linux/util\-linux/issues" "" "."
.SH "AVAILABILITY"
.sp
The \fBlsirq\fP command is part of the util\-linux package which can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."