'\" t
.\"     Title: mountpoint
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-10-23
.\"    Manual: User Commands
.\"    Source: util-linux 2.39.3
.\"  Language: English
.\"
.TH "MOUNTPOINT" "1" "2023-10-23" "util\-linux 2.39.3" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mountpoint \- see if a directory or file is a mountpoint
.SH "SYNOPSIS"
.sp
\fBmountpoint\fP [\fB\-d\fP|\fB\-q\fP] \fIdirectory\fP|\fIfile\fP
.sp
\fBmountpoint\fP \fB\-x\fP \fIdevice\fP
.SH "DESCRIPTION"
.sp
\fBmountpoint\fP checks whether the given \fIdirectory\fP or \fIfile\fP is mentioned in the \fI/proc/self/mountinfo\fP file.
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-\-fs\-devno\fP
.RS 4
Show the major/minor numbers of the device that is mounted on the given directory.
.RE
.sp
\fB\-q\fP, \fB\-\-quiet\fP
.RS 4
Be quiet \- don\(cqt print anything.
.RE
.sp
\fB\-\-nofollow\fP
.RS 4
Do not follow symbolic link if it the last element of the \fIdirectory\fP path.
.RE
.sp
\fB\-x\fP, \fB\-\-devno\fP
.RS 4
Show the major/minor numbers of the given blockdevice on standard output.
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display help text and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version and exit.
.RE
.SH "EXIT STATUS"
.sp
\fBmountpoint\fP has the following exit status values:
.sp
\fB0\fP
.RS 4
success; the directory is a mountpoint, or device is block device on \fB\-\-devno\fP
.RE
.sp
\fB1\fP
.RS 4
failure; incorrect invocation, permissions or system error
.RE
.sp
\fB32\fP
.RS 4
failure; the directory is not a mountpoint, or device is not a block device on \fB\-\-devno\fP
.RE
.SH "ENVIRONMENT"
.sp
\fBLIBMOUNT_DEBUG\fP=all
.RS 4
enables libmount debug output.
.RE
.SH "NOTES"
.sp
The util\-linux \fBmountpoint\fP implementation was written from scratch for libmount. The original version for sysvinit suite was written by Miquel van Smoorenburg.
.SH "AUTHORS"
.sp
.MTO "kzak\(atredhat.com" "Karel Zak" ""
.SH "SEE ALSO"
.sp
\fBmount\fP(8)
.SH "REPORTING BUGS"
.sp
For bug reports, use the issue tracker at \c
.URL "https://github.com/util\-linux/util\-linux/issues" "" "."
.SH "AVAILABILITY"
.sp
The \fBmountpoint\fP command is part of the util\-linux package which can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."