# $Id: Makefile,v 1.1.1.1 2005/06/13 16:47:47 bogdan_iancu Exp $
#
# Various URI checks
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uri.so
LIBS=

include ../../Makefile.modules

