#!/bin/sh

. ../eval_tools.sh

HEADER snmptrapd discards of unauthorized notification types 

#
# Begin test
#

CONFIGTRAPD createUser testuser
CONFIGTRAPD authuser log testuser noAuthNoPriv .1.3.6.1.6.3.1.1.5.2
CONFIGTRAPD agentxsocket /dev/null

STARTTRAPD

CAPTURE "snmptrap -Ci -t $SNMP_SLEEP -d -v 3 -u testuser -l nanp $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 system.sysContact.0 s blah"

STOPTRAPD

CHECKTRAPD "coldStart"
EXPECTRESULT 0
if [ "$snmp_last_test_result" != 0 ] ; then
    return_value=1
    FINISHED
fi

FINISHED
