ifeq ($(CONFIG_NDTRADE),y)
DD_CFLAGS += -DHAVE_NDTRADE
endif
ifeq ($(CONFIG_JJAP005),y)
DD_CFLAGS += -DHAVE_JJAP005 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_JJAP501),y)
DD_CFLAGS += -DHAVE_JJAP501 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_JA76PF2),y)
DD_CFLAGS += -DHAVE_JA76PF2
endif
ifeq ($(CONFIG_AC722),y)
DD_CFLAGS += -DHAVE_AC722 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_AC622),y)
DD_CFLAGS += -DHAVE_AC622 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_CHILLISPOT),y)
DD_CFLAGS += -DHAVE_COOVA_CHILLI
endif
ifeq ($(CONFIG_SANSFIL),y)
DD_CFLAGS += -DHAVE_SANSFIL
endif
ifeq ($(CONFIG_ONNET_BLANK),y)
DD_CFLAGS += -DHAVE_ONNET_BLANK
endif
ifeq ($(CONFIG_KORENRON),y)
DD_CFLAGS += -DHAVE_KORENRON
endif
ifeq ($(CONFIG_TESTEM),y)
DD_CFLAGS += -DHAVE_TESTEM
endif
ifeq ($(CONFIG_HOBBIT),y)
DD_CFLAGS += -DHAVE_HOBBIT
endif
ifeq ($(CONFIG_ANTAIRA),y)
DD_CFLAGS += -DHAVE_ANTAIRA
endif
ifeq ($(CONFIG_PERU),y)
DD_CFLAGS += -DHAVE_PERU
endif
ifeq ($(CONFIG_FMS2111),y)
DD_CFLAGS += -DHAVE_FMS2111
endif
ifeq ($(CONFIG_ANTAIRA_MINI),y)
DD_CFLAGS += -DHAVE_ANTAIRA_MINI
endif
ifeq ($(CONFIG_WIRCOM),y)
DD_CFLAGS += -DHAVE_WIRCOM
endif
ifeq ($(CONFIG_SRS),y)
DD_CFLAGS += -DHAVE_SRS
endif
ifeq ($(CONFIG_CARAMBOLA),y)
DD_CFLAGS += -DHAVE_CARAMBOLA
endif

ifeq ($(CONFIG_UDPXY),y)
DD_CFLAGS += -DHAVE_UDPXY  
endif
ifeq ($(CONFIG_ATH5K),y)
CFLAGS += -DHAVE_ATH5K
endif
ifeq ($(CONFIG_E200),y)
CFLAGS += -DHAVE_E200
endif
ifeq ($(CONFIG_SPEEDCHECKER),y)
CFLAGS += -DHAVE_SPEEDCHECKER
CFLAGS += -DHAVE_SHOWNF
endif
ifeq ($(CONFIG_LIBMBIM),y)
CFLAGS += -DHAVE_LIBMBIM
endif
ifeq ($(CONFIG_NLD),y)
CFLAGS += -DHAVE_NLD
endif

