ifeq ($(CONFIG_JJAP005),y)
DD_CFLAGS += -DHAVE_JJAP005 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_JJAP501),y)
DD_CFLAGS += -DHAVE_JJAP501 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_AC722),y)
DD_CFLAGS += -DHAVE_AC722 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_AC622),y)
DD_CFLAGS += -DHAVE_AC622 -DDDMACOFFSET=$(CONFIG_MACOFFSET)
endif
ifeq ($(CONFIG_CHILLISPOT),y)
DD_CFLAGS += -DHAVE_COOVA_CHILLI
endif
