.TH "leaf_handlers" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leaf_handlers \- Process individual leaf objects A group of handlers to implement individual leaf objects and instances (both scalar objects, and individual objects and instances within a table).  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBinstance\fP"
.br
.RI "\fIProcess individual MIB instances easily. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBscalar\fP"
.br
.RI "\fIProcess scalars easily. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBscalar_group\fP"
.br
.RI "\fIProcess groups of scalars. \fP"
.PP
.in +1c

.ti -1c
.RI "\fBwatcher\fP"
.br
.RI "\fIWatch a specified variable and process it as an instance or scalar object. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
Process individual leaf objects A group of handlers to implement individual leaf objects and instances (both scalar objects, and individual objects and instances within a table). 
.PP
These handlers will typically allow control to be passed down to a lower level, user-provided handler, but this is (usually) optional. 
