.TH "The Net-SNMP agent" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The Net-SNMP agent \- The snmp agent responds to SNMP queries from management stations.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBNet-SNMP Agent handler and extensibility API\fP"
.br
.RI "\fIThe basic theory goes something like this: In the past, with the original mib module api (which derived from the original CMU SNMP code) the underlying mib modules were passed very little information (only the truly most basic information about a request). \fP"
.PP
.in +1c

.ti -1c
.RI "\fBMaintain a registry of MIB subtrees, together with related information regarding mibmodule, sessions, etc\fP"
.br
.ti -1c
.RI "\fBTrap generation routines for mib modules to use\fP"
.br
.ti -1c
.RI "\fBnet-snmp agent related processing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The snmp agent responds to SNMP queries from management stations. 
.PP

