faketime set 100
client_show
remove_old_client_entries 50

faketime show
client bssid=00:11:22:33:44:55 client=ff:ee:dd:cc:bb:aa

faketime add 25
faketime show
client bssid=01:11:22:33:44:55 client=ff:ee:dd:cc:bb:aa

faketime add 25
faketime show
client bssid=02:11:22:33:44:55 client=ff:ee:dd:cc:bb:aa

faketime add 25
faketime show
client bssid=03:11:22:33:44:55 client=ff:ee:dd:cc:bb:aa

faketime add 25
faketime show
client bssid=04:11:22:33:44:55 client=ff:ee:dd:cc:bb:aa

client_show

remove_old_client_entries 50
client_show

faketime add 25
remove_old_client_entries 0
client_show
