generic logging for net-snmp
NAME
generic logging for net-snmp -
Defines
#define LOGLENGTH 1024
#define va_copy(dest, src) memcpy (&dest, &src, sizeof (va_list))
#define LOG_CONS 0
#define LOG_PID 0
#define LOG_LOCAL0 0
#define LOG_LOCAL1 0
#define LOG_LOCAL2 0
#define LOG_LOCAL3 0
#define LOG_LOCAL4 0
#define LOG_LOCAL5 0
#define LOG_LOCAL6 0
#define LOG_LOCAL7 0
#define LOG_DAEMON 0
#define LOG_USER 0
Functions
void netsnmp_enable_filelog (netsnmp_log_handler *logh, int dont_zero_log)
int vsnprintf (char *str, size_t count, const char *fmt, va_list arg)
void init_snmp_logging (void)
void shutdown_snmp_logging (void)
int decode_priority (char *optarg, int *pri_max)
int decode_facility (char *optarg)
int snmp_log_options (char *optarg, int argc, char *const *argv)
char * snmp_log_syslogname (const char *pstr)
void snmp_log_options_usage (const char *lead, FILE *outf)
int snmp_get_do_logging (void)
Is logging done?
void snmp_disable_syslog_entry (netsnmp_log_handler *logh)
void snmp_disable_syslog (void)
void snmp_disable_filelog_entry (netsnmp_log_handler *logh)
void snmp_disable_filelog (void)
int snmp_stderrlog_status (void)
void snmp_disable_stderrlog (void)
void snmp_disable_calllog (void)
void snmp_disable_log (void)
void netsnmp_logging_restart (void)
void snmp_enable_syslog (void)
void snmp_enable_syslog_ident (const char *ident, const int facility)
void snmp_enable_filelog (const char *logfilename, int dont_zero_log)
void snmp_enable_stderrlog (void)
void snmp_enable_calllog (void)
netsnmp_log_handler * netsnmp_find_loghandler (const char *token)
int netsnmp_add_loghandler (netsnmp_log_handler *logh)
netsnmp_log_handler * netsnmp_register_loghandler (int type, int priority)
int netsnmp_enable_loghandler (const char *token)
int netsnmp_disable_loghandler (const char *token)
int netsnmp_remove_loghandler (netsnmp_log_handler *logh)
int log_handler_stdouterr (netsnmp_log_handler *logh, int pri, const char *str)
int log_handler_syslog (netsnmp_log_handler *logh, int pri, const char *str)
int log_handler_file (netsnmp_log_handler *logh, int pri, const char *str)
int log_handler_callback (netsnmp_log_handler *logh, int pri, const char *str)
int log_handler_null (netsnmp_log_handler *logh, int pri, const char *str)
void snmp_log_string (int priority, const char *str)
int snmp_vlog (int priority, const char *format, va_list ap)
This snmp logging function allows variable argument list given the specified priority, format and a populated va_list structure.
int snmp_log (int priority, const char *format,...)
This snmp logging function allows variable argument list given the specified format and priority.
void snmp_log_perror (const char *s)
netsnmp_log_handler * get_logh_head (void)
Variables
netsnmp_log_handler * logh_head = NULL
netsnmp_log_handler * logh_priorities [LOG_DEBUG+1]
Function Documentation
void netsnmp_logging_restart (void)
hmm, don't zero status isn't saved.. i think it's safer not to overwrite, in case a hup is just to re-read config files...
Definition at line 613 of file snmp_logging.c.
References netsnmp_log_handler_s::enabled, logh_head, netsnmp_log_handler_s::next, snmp_disable_syslog_entry(), snmp_enable_syslog_ident(), and netsnmp_log_handler_s::type.
int snmp_get_do_logging (void)
Is logging done?
Returns:
Returns 0 if logging is off, 1 when it is done.
Definition at line 470 of file snmp_logging.c.
References netsnmp_log_handler_s::enabled, logh_head, and netsnmp_log_handler_s::next.
Referenced by netsnmp_agent_check_parse().
int snmp_log (int priority, const char * format, ...)
This snmp logging function allows variable argument list given the specified format and priority.
Calls the snmp_vlog function. The default logfile this function writes to is /var/log/snmpd.log.
See also:
snmp_vlog
Examples:
delayed_instance.c.
Definition at line 1252 of file snmp_logging.c.
References snmp_vlog().
Referenced by _callback_lock(), _request_set_error(), _sess_read(), agent_check_and_process(), config_perror(), config_pwarn(), convert_v1pdu_to_v2(), convert_v2pdu_to_v1(), copy_word(), create_trap_session(), init_agent(), init_master_agent(), netsnmp_agent_check_packet(), netsnmp_agent_check_parse(), netsnmp_baby_steps_handler_get(), netsnmp_cache_create(), netsnmp_cache_helper_handler(), netsnmp_cache_timer_start(), netsnmp_cache_timer_stop(), netsnmp_call_handler(), netsnmp_call_handlers(), netsnmp_call_next_handler(), netsnmp_call_next_handler_one_request(), netsnmp_config_parse_add_row(), netsnmp_config_parse_table_set(), netsnmp_container_get_null(), netsnmp_container_iterator_get(), netsnmp_container_table_handler_get(), netsnmp_container_table_register(), netsnmp_data_list_add_data(), netsnmp_data_list_add_node(), netsnmp_ds_handle_config(), netsnmp_get_multiplexer_handler(), netsnmp_get_table_data_handler(), netsnmp_get_table_data_set_handler(), netsnmp_get_table_handler(), netsnmp_get_tdata_handler(), netsnmp_inject_handler_before(), netsnmp_instance_counter32_handler(), netsnmp_mark_row_column_writable(), netsnmp_multiplexer_helper_handler(), netsnmp_read_data_callback(), netsnmp_register_handler(), netsnmp_register_handler_nocallback(), netsnmp_register_mib(), netsnmp_register_num_file_instance(), netsnmp_register_save_list(), netsnmp_request_set_error_all(), netsnmp_row_merge_status_get(), netsnmp_save_all_data_callback(), netsnmp_send_traps(), netsnmp_sess_log_error(), netsnmp_set_row_column(), netsnmp_table_container_register(), netsnmp_table_data_add_row(), netsnmp_table_data_set_helper_handler(), netsnmp_table_iterator_helper_handler(), netsnmp_table_row_handler_get(), netsnmp_table_row_register(), netsnmp_table_set_add_default_row(), netsnmp_tdata_add_row(), netsnmp_wrap_up_request(), read_config_print_usage(), read_config_read_octet_string(), read_config_store(), register_signal(), snmp_build(), snmp_clean_persistent(), snmp_log_perror(), snmp_pdu_parse(), snmp_perror(), snmp_save_persistent(), snmp_set_var_value(), snmpd_parse_config_authtrap(), snmpv3_make_report(), snmpv3_packet_build(), snmpv3_parse(), and table_helper_handler().
int snmp_vlog (int priority, const char * format, va_list ap)
This snmp logging function allows variable argument list given the specified priority, format and a populated va_list structure.
The default logfile this function writes to is /var/log/snmpd.log.
Parameters:
priority is an integer representing the type of message to be written to the snmp log file. The types are errors, warning, and information.
The error types are:
LOG_EMERG system is unusable
LOG_ALERT action must be taken immediately
LOG_CRIT critical conditions
LOG_ERR error conditions
The warning type is:
LOG_WARNING warning conditions
The information types are:
LOG_NOTICE normal but significant condition
LOG_INFO informational
LOG_DEBUG debug-level messages
format is a pointer to a char representing the variable argument list format used.
ap is a va_list type used to traverse the list of arguments.
Returns:
Returns 0 on success, -1 when the code could not format the log- string, -2 when dynamic memory could not be allocated if the length of the log buffer is greater then 1024 bytes. For each of these errors a LOG_ERR messgae is written to the logfile.
See also:
snmp_log
Definition at line 1191 of file snmp_logging.c.
References LOGLENGTH, NULL, snmp_log_string(), va_copy, and vsnprintf().
Referenced by snmp_log().