.TH "netsnmp_column_info_t" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_column_info_t \- column info struct.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <table.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBisRange\fP"
.br
.ti -1c
.RI "char \fBlist_count\fP"
.br
.RI "\fIonly useful if isRange == 0 \fP"
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   unsigned int \fBrange\fP [2]"
.br
.ti -1c
.RI "   unsigned int * \fBlist\fP"
.br
.ti -1c
.RI "} \fBdetails\fP"
.br
.ti -1c
.RI "\fBnetsnmp_column_info_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
column info struct. 

OVERLAPPING RANGES ARE NOT SUPPORTED. 
.PP
Definition at line 52 of file table.h.
.SH "Field Documentation"
.PP 
.SS "char \fBnetsnmp_column_info_t::list_count\fP"
.PP
only useful if isRange == 0 
.PP
Definition at line 55 of file table.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
