.TH "baby_steps" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baby_steps \- Calls your handler in baby_steps for set processing.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBbaby_steps_access_multiplexer: calls individual access methods based on baby_step mode.\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBnetsnmp_mib_handler\fP * \fBnetsnmp_baby_steps_handler_get\fP (u_long modes)"
.br
.RI "\fIreturns a baby_steps handler that can be injected into a given handler chain. \fP"
.ti -1c
.RI "void \fBnetsnmp_baby_steps_handler_init\fP (void)"
.br
.RI "\fIinitializes the baby_steps helper which then registers a baby_steps handler as a run-time injectable handler for configuration file use. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Calls your handler in baby_steps for set processing. 
.PP
.SH "Function Documentation"
.PP 
.SS "\fBnetsnmp_mib_handler\fP* netsnmp_baby_steps_handler_get (u_long modes)"
.PP
returns a baby_steps handler that can be injected into a given handler chain. 
.PP
Definition at line 58 of file baby_steps.c.
.PP
References netsnmp_mib_handler_s::myvoid, netsnmp_create_handler(), netsnmp_handler_free(), NULL, netsnmp_baby_steps_modes_s::registered, snmp_log(), and SNMP_MALLOC_TYPEDEF.
.PP
Referenced by netsnmp_baby_steps_handler_init().
.SS "void netsnmp_baby_steps_handler_init (void)"
.PP
initializes the baby_steps helper which then registers a baby_steps handler as a run-time injectable handler for configuration file use. 
.PP
Definition at line 319 of file baby_steps.c.
.PP
References netsnmp_baby_steps_handler_get(), and netsnmp_register_handler_by_name().
