.TH "table_iterator.h" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table_iterator.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBnetsnmp_iterator_info_s\fP"
.br
.RI "\fIHolds iterator information containing functions which should be called by the iterator_handler to loop over your data set and sort it in a SNMP specific manner. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNETSNMP_ITERATOR_FLAG_SORTED\fP   0x01"
.br
.ti -1c
.RI "#define \fBTABLE_ITERATOR_NAME\fP   'table_iterator'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBnetsnmp_variable_list\fP *() \fBNetsnmp_First_Data_Point\fP (void **loop_context, void **data_context, \fBnetsnmp_variable_list\fP *, struct \fBnetsnmp_iterator_info_s\fP *)"
.br
.ti -1c
.RI "typedef \fBnetsnmp_variable_list\fP *() \fBNetsnmp_Next_Data_Point\fP (void **loop_context, void **data_context, \fBnetsnmp_variable_list\fP *, struct \fBnetsnmp_iterator_info_s\fP *)"
.br
.ti -1c
.RI "typedef void *() \fBNetsnmp_Make_Data_Context\fP (void *loop_context, struct \fBnetsnmp_iterator_info_s\fP *)"
.br
.ti -1c
.RI "typedef void() \fBNetsnmp_Free_Loop_Context\fP (void *, struct \fBnetsnmp_iterator_info_s\fP *)"
.br
.ti -1c
.RI "typedef void() \fBNetsnmp_Free_Data_Context\fP (void *, struct \fBnetsnmp_iterator_info_s\fP *)"
.br
.ti -1c
.RI "typedef \fBnetsnmp_iterator_info_s\fP \fBnetsnmp_iterator_info\fP"
.br
.RI "\fITypedefs the \fBnetsnmp_iterator_info_s\fP struct into netsnmp_iterator_info. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBnetsnmp_mib_handler\fP * \fBnetsnmp_get_table_iterator_handler\fP (\fBnetsnmp_iterator_info\fP *iinfo)"
.br
.RI "\fIreturns a netsnmp_mib_handler object for the table_iterator helper \fP"
.ti -1c
.RI "int \fBnetsnmp_register_table_iterator\fP (\fBnetsnmp_handler_registration\fP *reginfo, \fBnetsnmp_iterator_info\fP *iinfo)"
.br
.RI "\fICreates and registers a table iterator helper handler calling netsnmp_create_handler with a handler name set to TABLE_ITERATOR_NAME and access method, netsnmp_table_iterator_helper_handler. \fP"
.ti -1c
.RI "void \fBnetsnmp_iterator_delete_table\fP (\fBnetsnmp_iterator_info\fP *iinfo)"
.br
.ti -1c
.RI "NETSNMP_INLINE void * \fBnetsnmp_extract_iterator_context\fP (\fBnetsnmp_request_info\fP *request)"
.br
.RI "\fIextracts the table_iterator specific data from a request. \fP"
.ti -1c
.RI "NETSNMP_INLINE void \fBnetsnmp_insert_iterator_context\fP (\fBnetsnmp_request_info\fP *request, void *data)"
.br
.RI "\fIinserts table_iterator specific data for a newly created row into a request \fP"
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_first\fP (\fBnetsnmp_iterator_info\fP *iinfo)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_get\fP (\fBnetsnmp_iterator_info\fP *iinfo, void *row)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_next\fP (\fBnetsnmp_iterator_info\fP *iinfo, void *row)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_get_byidx\fP (\fBnetsnmp_iterator_info\fP *iinfo, \fBnetsnmp_variable_list\fP *indexes)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_next_byidx\fP (\fBnetsnmp_iterator_info\fP *iinfo, \fBnetsnmp_variable_list\fP *indexes)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_get_byoid\fP (\fBnetsnmp_iterator_info\fP *iinfo, oid *instance, size_t len)"
.br
.ti -1c
.RI "void * \fBnetsnmp_iterator_row_next_byoid\fP (\fBnetsnmp_iterator_info\fP *iinfo, oid *instance, size_t len)"
.br
.ti -1c
.RI "int \fBnetsnmp_iterator_row_count\fP (\fBnetsnmp_iterator_info\fP *iinfo)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBNetsnmp_Node_Handler\fP \fBnetsnmp_table_iterator_helper_handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBtable_iterator.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
