storage space for defaults
NAME
storage space for defaults - The purpose of the default storage is three-fold:.
Data Structures
struct netsnmp_ds_read_config_s
Typedefs
typedef netsnmp_ds_read_config_s netsnmp_ds_read_config
Functions
void netsnmp_ds_handle_config (const char *token, char *line)
int netsnmp_ds_set_boolean (int storeid, int which, int value)
Stores 'true' or 'false' given an int value for value into netsnmp_ds_booleans[store][which] slot.
int netsnmp_ds_toggle_boolean (int storeid, int which)
int netsnmp_ds_get_boolean (int storeid, int which)
int netsnmp_ds_set_int (int storeid, int which, int value)
int netsnmp_ds_get_int (int storeid, int which)
int netsnmp_ds_set_string (int storeid, int which, const char *value)
char * netsnmp_ds_get_string (int storeid, int which)
int netsnmp_ds_set_void (int storeid, int which, void *value)
void * netsnmp_ds_get_void (int storeid, int which)
int netsnmp_ds_parse_boolean (char *line)
int netsnmp_ds_register_config (u_char type, const char *ftype, const char *token, int storeid, int which)
int netsnmp_ds_register_premib (u_char type, const char *ftype, const char *token, int storeid, int which)
void netsnmp_ds_shutdown ()
Detailed Description
The purpose of the default storage is three-fold:.
1) To create a global storage space without creating a whole bunch of globally accessible variables or a whole bunch of access functions to work with more privately restricted variables.
2) To provide a single location where the thread lock- ing needs to be implemented. At the time of this writing, however, thread locking is not yet in place.
3) To reduce the number of cross dependencies between code pieces that may or may not be linked together in the long run. This provides for a single loca- tion in which configuration data, for example, can be stored for a separate section of code that may not be linked in to the application in question.
The functions defined here implement these goals.
Currently, three data types are supported: booleans, inte- gers, and strings. Each of these data types have separate storage spaces. In addition, the storage space for each data type is divided further by the application level. Currently, there are two storage spaces. The first is reserved for the SNMP library itself. The second is intended for use in applications and is not modified or checked by the library, and, therefore, this is the space usable by you.
These definitions correspond with the 'storid' argument to the API
#define NETSNMP_DS_LIBRARY_ID 0
#define NETSNMP_DS_APPLICATION_ID 1
#define NETSNMP_DS_TOKEN_ID 2
These definitions correspond with the 'which' argument to the API, when the storeid argument is NETSNMP_DS_LIBRARY_ID
library booleans
#define NETSNMP_DS_LIB_MIB_ERRORS 0
#define NETSNMP_DS_LIB_SAVE_MIB_DESCRS 1
#define NETSNMP_DS_LIB_MIB_COMMENT_TERM 2
#define NETSNMP_DS_LIB_MIB_PARSE_LABEL 3
#define NETSNMP_DS_LIB_DUMP_PACKET 4
#define NETSNMP_DS_LIB_LOG_TIMESTAMP 5
#define NETSNMP_DS_LIB_DONT_READ_CONFIGS 6
#define NETSNMP_DS_LIB_MIB_REPLACE 7 replace objects from latest module
#define NETSNMP_DS_LIB_PRINT_NUMERIC_ENUM 8 print only numeric enum values
#define NETSNMP_DS_LIB_PRINT_NUMERIC_OIDS 9 print only numeric enum values
#define NETSNMP_DS_LIB_DONT_BREAKDOWN_OIDS 10 dont print oid indexes specially
#define NETSNMP_DS_LIB_ALARM_DONT_USE_SIG 11 don't use the alarm() signal
#define NETSNMP_DS_LIB_PRINT_FULL_OID 12 print fully qualified oids
#define NETSNMP_DS_LIB_QUICK_PRINT 13 print very brief output for parsing
#define NETSNMP_DS_LIB_RANDOM_ACCESS 14 random access to oid labels
#define NETSNMP_DS_LIB_REGEX_ACCESS 15 regex matching to oid labels
#define NETSNMP_DS_LIB_DONT_CHECK_RANGE 16 don't check values for ranges on send
#define NETSNMP_DS_LIB_NO_TOKEN_WARNINGS 17 no warn about unknown config tokens
#define NETSNMP_DS_LIB_NUMERIC_TIMETICKS 18 print timeticks as a number
#define NETSNMP_DS_LIB_ESCAPE_QUOTES 19 shell escape quote marks in oids
#define NETSNMP_DS_LIB_REVERSE_ENCODE 20 encode packets from back to front
#define NETSNMP_DS_LIB_PRINT_BARE_VALUE 21 just print value (not OID = value)
#define NETSNMP_DS_LIB_EXTENDED_INDEX 22 print extended index format [x1][x2]
#define NETSNMP_DS_LIB_PRINT_HEX_TEXT 23 print ASCII text along with hex strings
#define NETSNMP_DS_LIB_PRINT_UCD_STYLE_OID 24 print OID's using the UCD-style prefix suppression
#define NETSNMP_DS_LIB_READ_UCD_STYLE_OID 25 require top-level OIDs to be prefixed with a dot
#define NETSNMP_DS_LIB_HAVE_READ_PREMIB_CONFIG 26 have the pre-mib parsing config tokens been processed
#define NETSNMP_DS_LIB_HAVE_READ_CONFIG 27 have the config tokens been processed
#define NETSNMP_DS_LIB_QUICKE_PRINT 28
#define NETSNMP_DS_LIB_DONT_PRINT_UNITS 29 don't print UNITS suffix
#define NETSNMP_DS_LIB_NO_DISPLAY_HINT 30 don't apply DISPLAY-HINTs
#define NETSNMP_DS_LIB_16BIT_IDS 31 restrict requestIDs, etc to 16-bit values
#define NETSNMP_DS_LIB_DONT_PERSIST_STATE 32 don't save/load any persistant state
#define NETSNMP_DS_LIB_2DIGIT_HEX_OUTPUT 33 print a leading 0 on hex values <= 'f'
library integers
#define NETSNMP_DS_LIB_MIB_WARNINGS 0
#define NETSNMP_DS_LIB_SECLEVEL 1
#define NETSNMP_DS_LIB_SNMPVERSION 2
#define NETSNMP_DS_LIB_DEFAULT_PORT 3
#define NETSNMP_DS_LIB_OID_OUTPUT_FORMAT 4
#define NETSNMP_DS_LIB_STRING_OUTPUT_FORMAT 5
library strings
#define NETSNMP_DS_LIB_SECNAME 0
#define NETSNMP_DS_LIB_CONTEXT 1
#define NETSNMP_DS_LIB_PASSPHRASE 2
#define NETSNMP_DS_LIB_AUTHPASSPHRASE 3
#define NETSNMP_DS_LIB_PRIVPASSPHRASE 4
#define NETSNMP_DS_LIB_OPTIONALCONFIG 5
#define NETSNMP_DS_LIB_APPTYPE 6
#define NETSNMP_DS_LIB_COMMUNITY 7
#define NETSNMP_DS_LIB_PERSISTENT_DIR 8
#define NETSNMP_DS_LIB_CONFIGURATION_DIR 9
#define NETSNMP_DS_LIB_SECMODEL 10
#define NETSNMP_DS_LIB_MIBDIRS 11
#define NETSNMP_DS_LIB_OIDSUFFIX 12
#define NETSNMP_DS_LIB_OIDPREFIX 13
#define NETSNMP_DS_LIB_CLIENT_ADDR 14
#define NETSNMP_DS_LIB_TEMP_FILE_PATTERN 15
#define NETSNMP_DS_LIB_AUTHMASTERKEY 16
#define NETSNMP_DS_LIB_PRIVMASTERKEY 17
#define NETSNMP_DS_LIB_AUTHLOCALIZEDKEY 18
#define NETSNMP_DS_LIB_PRIVLOCALIZEDKEY 19
Function Documentation
int netsnmp_ds_set_boolean (int storeid, int which, int value)
Stores 'true' or 'false' given an int value for value into netsnmp_ds_booleans[store][which] slot.
Parameters:
storeid an index to the boolean storage container's first index(store)
which an index to the boolean storage container's second index(which)
value if > 0, 'true' is set into the slot otherwise 'false'
Returns:
Returns SNMPPERR_GENERR if the storeid and which parameters do not correspond to a valid slot, or SNMPERR_SUCCESS otherwise.
Definition at line 197 of file default_store.c.
Referenced by init_agent(), netsnmp_ds_handle_config(), read_configs(), read_premib_configs(), setup_tree(), and snmp_out_toggle_options().