set_data: helps storing and retriving of data during set transactions
NAME
set_data: helps storing and retriving of data during set transactions - The set_data helper.
Data Structures
struct netsnmp_set_data_master_s
struct netsnmp_set_data_store_s
Functions
void netsnmp_set_data_cache (netsnmp_request_info *request, unsigned int magic_num, void *new_data, size_t new_data_len, void *old_data, size_t old_data_len)
stores new and old information based on the magic number.
netsnmp_set_data_ netsnmp_mib_handler * netsnmp_get_multiplexer_handler (netsnmp_mib_handler_methods *req)
returns a multiplixer handler given a netsnmp_mib_handler_methods structure of subhandlers.
int netsnmp_multiplexer_helper_handler (netsnmp_mib_handler *handler, netsnmp_handler_registration *reginfo, netsnmp_agent_request_info *reqinfo, netsnmp_request_info *requests)
implements the multiplexer helper
DETAILED DESCRIPTION
The set_data helper.
FUNCTION DOCUMENTATION
netsnmp_set_data_ netsnmp_mib_handler* netsnmp_get_multiplexer_handler (netsnmp_mib_handler_methods * req)
returns a multiplixer handler given a netsnmp_mib_handler_methods structure of subhandlers.
Definition at line 84 of file set_data.c.
References netsnmp_create_handler(), and netsnmp_multiplexer_helper_handler().
int netsnmp_multiplexer_helper_handler (netsnmp_mib_handler * handler, netsnmp_handler_registration * reginfo, netsnmp_agent_request_info * reqinfo, netsnmp_request_info * requests)
implements the multiplexer helper
Definition at line 105 of file set_data.c.
References netsnmp_call_handler(), and netsnmp_extract_iterator_context().
Referenced by netsnmp_get_multiplexer_handler().
void netsnmp_set_data_cache (netsnmp_request_info * request, unsigned int magic_num, void * new_data, size_t new_data_len, void * old_data, size_t old_data_len)
stores new and old information based on the magic number.
Definition at line 45 of file set_data.c.
References netsnmp_create_data_list(), netsnmp_extract_table_info(), netsnmp_request_add_list_data(), and SNMP_MIN.