.TH "netsnmp_table_request_info_s" 3 "24 Nov 2006" "Version 5.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_table_request_info_s \- The table request info structure.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <table.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBcolnum\fP"
.br
.RI "\fI0 if OID not long enough \fP"
.ti -1c
.RI "unsigned int \fBnumber_indexes\fP"
.br
.RI "\fI0 if failure to parse any \fP"
.ti -1c
.RI "\fBnetsnmp_variable_list\fP * \fBindexes\fP"
.br
.RI "\fIcontents freed by helper upon exit \fP"
.ti -1c
.RI "oid \fBindex_oid\fP [MAX_OID_LEN]"
.br
.ti -1c
.RI "size_t \fBindex_oid_len\fP"
.br
.ti -1c
.RI "\fBnetsnmp_table_registration_info\fP * \fBreg_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The table request info structure. 
.PP
Definition at line 102 of file table.h.
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBnetsnmp_table_request_info_s::colnum\fP"
.PP
0 if OID not long enough 
.PP
Definition at line 104 of file table.h.
.PP
Referenced by netsnmp_table_build_oid(), netsnmp_table_build_oid_from_index(), netsnmp_table_data_set_helper_handler(), netsnmp_table_iterator_helper_handler(), and table_helper_handler().
.SS "\fBnetsnmp_variable_list\fP* \fBnetsnmp_table_request_info_s::indexes\fP"
.PP
contents freed by helper upon exit 
.PP
Definition at line 108 of file table.h.
.PP
Referenced by netsnmp_container_table_row_insert(), netsnmp_insert_iterator_context(), netsnmp_insert_table_row(), netsnmp_table_build_oid(), netsnmp_table_data_set_create_newrowstash(), netsnmp_update_indexes_from_variable_list(), netsnmp_update_variable_list_from_index(), and table_helper_handler().
.SS "unsigned int \fBnetsnmp_table_request_info_s::number_indexes\fP"
.PP
0 if failure to parse any 
.PP
Definition at line 106 of file table.h.
.PP
Referenced by table_helper_handler().

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
