debug: print out debugging information about the handler chain being called.
NAME
debug: print out debugging information about the handler chain being called. - This is a useful module for run-time debugging of requests as the pass this handler in a calling chain.
handler
void netsnmp_init_debug_helper (void)
initializes the debug helper which then registers a debug handler as a run-time injectable handler for configuration file use.
void netsnmp_init_serialize (void)
initializes the serialize helper which then registers a serialize handler as a run-time injectable handler for configuration file use.
void netsnmp_init_read_only_helper (void)
initializes the read_only helper which then registers a read_only handler as a run-time injectable handler for configuration file use.
void netsnmp_init_bulk_to_next_helper (void)
initializes the bulk_to_next helper which then registers a bulk_to_next handler as a run-time injectable handler for configuration file use.
void netsnmp_init_helpers (void)
call the initialization sequence for all handlers with init_ routines.
Functions
netsnmp_mib_handler * netsnmp_get_debug_handler (void)
returns a debug handler that can be injected into a given handler chain.
DETAILED DESCRIPTION
This is a useful module for run-time debugging of requests as the pass this handler in a calling chain.
All debugging output is done via the standard debugging routines with a token name of 'helper:debug', so use the -Dhelper:debug command line flag to see the output when running the snmpd demon. It's not recommended you compile this into a handler chain during compile time, but instead use the 'injectHandler' token in the snmpd.conf file (or similar) to add it to the chain later:
injectHandler debug my_module_name
to see an example output, try:
injectHandler debug mibII/system
and then run snmpwalk on the 'system' group.
FUNCTION DOCUMENTATION
netsnmp_mib_handler* netsnmp_get_debug_handler (void)
returns a debug handler that can be injected into a given handler chain.
Definition at line 44 of file debug_handler.c.
References netsnmp_create_handler().
Referenced by netsnmp_init_debug_helper().
void netsnmp_init_bulk_to_next_helper (void)
initializes the bulk_to_next helper which then registers a bulk_to_next handler as a run-time injectable handler for configuration file use.
Definition at line 95 of file bulk_to_next.c.
References netsnmp_get_bulk_to_next_handler(), and netsnmp_register_handler_by_name().
Referenced by netsnmp_init_helpers().
void netsnmp_init_debug_helper (void)
initializes the debug helper which then registers a debug handler as a run-time injectable handler for configuration file use.
Definition at line 147 of file debug_handler.c.
References netsnmp_get_debug_handler(), and netsnmp_register_handler_by_name().
Referenced by netsnmp_init_helpers().
void netsnmp_init_helpers (void)
call the initialization sequence for all handlers with init_ routines.
Definition at line 31 of file all_helpers.c.
References netsnmp_init_bulk_to_next_helper(), netsnmp_init_debug_helper(), netsnmp_init_read_only_helper(), and netsnmp_init_serialize().
void netsnmp_init_read_only_helper (void)
initializes the read_only helper which then registers a read_only handler as a run-time injectable handler for configuration file use.
Definition at line 71 of file read_only.c.
References netsnmp_get_read_only_handler(), and netsnmp_register_handler_by_name().
Referenced by netsnmp_init_helpers().
void netsnmp_init_serialize (void)
initializes the serialize helper which then registers a serialize handler as a run-time injectable handler for configuration file use.
Definition at line 96 of file serialize.c.
References netsnmp_get_serialize_handler(), and netsnmp_register_handler_by_name().
Referenced by netsnmp_init_helpers().