svn add COPYRIGHT
svn add SPONSORS
svn add acinclude/ax_cxx_compile_stdcxx_0x.m4
svn add acinclude/ax_cxx_compile_stdcxx_11.m4
svn add acinclude/ax_with_prog.m4
svn add autom4te.cache
svn add autom4te.cache/output.0
svn add autom4te.cache/output.1
svn add autom4te.cache/requests
svn add autom4te.cache/traces.0
svn add autom4te.cache/traces.1
svn add cfgaux/test-driver
svn add check.sh
svn add compat/getaddrinfo.c
svn add compat/getnameinfo.c
svn add compat/inet_ntop.c
svn add compat/inet_pton.c
svn add compat/mswin.cc
svn add compat/os/mswin.h
svn add compat/os/windows.h
svn add compat/strsep.c
svn add compat/strsep.h
svn add compat/unsafe.h
svn add configure.orig
svn add contrib/squid.rc
svn add doc/release-notes
svn add errors/ka
svn add errors/zh-cn
svn add errors/zh-cn/ERR_ACCESS_DENIED
svn add errors/zh-cn/ERR_ACL_TIME_QUOTA_EXCEEDED
svn add errors/zh-cn/ERR_AGENT_CONFIGURE
svn add errors/zh-cn/ERR_AGENT_WPAD
svn add errors/zh-cn/ERR_CACHE_ACCESS_DENIED
svn add errors/zh-cn/ERR_CACHE_MGR_ACCESS_DENIED
svn add errors/zh-cn/ERR_CANNOT_FORWARD
svn add errors/zh-cn/ERR_CONFLICT_HOST
svn add errors/zh-cn/ERR_CONNECT_FAIL
svn add errors/zh-cn/ERR_DIR_LISTING
svn add errors/zh-cn/ERR_DNS_FAIL
svn add errors/zh-cn/ERR_ESI
svn add errors/zh-cn/ERR_FORWARDING_DENIED
svn add errors/zh-cn/ERR_FTP_DISABLED
svn add errors/zh-cn/ERR_FTP_FAILURE
svn add errors/zh-cn/ERR_FTP_FORBIDDEN
svn add errors/zh-cn/ERR_FTP_NOT_FOUND
svn add errors/zh-cn/ERR_FTP_PUT_CREATED
svn add errors/zh-cn/ERR_FTP_PUT_ERROR
svn add errors/zh-cn/ERR_FTP_PUT_MODIFIED
svn add errors/zh-cn/ERR_FTP_UNAVAILABLE
svn add errors/zh-cn/ERR_GATEWAY_FAILURE
svn add errors/zh-cn/ERR_ICAP_FAILURE
svn add errors/zh-cn/ERR_INVALID_REQ
svn add errors/zh-cn/ERR_INVALID_RESP
svn add errors/zh-cn/ERR_INVALID_URL
svn add errors/zh-cn/ERR_LIFETIME_EXP
svn add errors/zh-cn/ERR_NO_RELAY
svn add errors/zh-cn/ERR_ONLY_IF_CACHED_MISS
svn add errors/zh-cn/ERR_PRECONDITION_FAILED
svn add errors/zh-cn/ERR_READ_ERROR
svn add errors/zh-cn/ERR_READ_TIMEOUT
svn add errors/zh-cn/ERR_SECURE_CONNECT_FAIL
svn add errors/zh-cn/ERR_SHUTTING_DOWN
svn add errors/zh-cn/ERR_SOCKET_FAILURE
svn add errors/zh-cn/ERR_TOO_BIG
svn add errors/zh-cn/ERR_UNSUP_HTTPVERSION
svn add errors/zh-cn/ERR_UNSUP_REQ
svn add errors/zh-cn/ERR_URN_RESOLVE
svn add errors/zh-cn/ERR_WRITE_ERROR
svn add errors/zh-cn/ERR_ZERO_SIZE_OBJECT
svn add errors/zh-cn/error-details.txt
svn add errors/zh-hans
svn add errors/zh-hant
svn add errors/zh-tw
svn add errors/zh-tw/ERR_ACCESS_DENIED
svn add errors/zh-tw/ERR_ACL_TIME_QUOTA_EXCEEDED
svn add errors/zh-tw/ERR_AGENT_CONFIGURE
svn add errors/zh-tw/ERR_AGENT_WPAD
svn add errors/zh-tw/ERR_CACHE_ACCESS_DENIED
svn add errors/zh-tw/ERR_CACHE_MGR_ACCESS_DENIED
svn add errors/zh-tw/ERR_CANNOT_FORWARD
svn add errors/zh-tw/ERR_CONFLICT_HOST
svn add errors/zh-tw/ERR_CONNECT_FAIL
svn add errors/zh-tw/ERR_DIR_LISTING
svn add errors/zh-tw/ERR_DNS_FAIL
svn add errors/zh-tw/ERR_ESI
svn add errors/zh-tw/ERR_FORWARDING_DENIED
svn add errors/zh-tw/ERR_FTP_DISABLED
svn add errors/zh-tw/ERR_FTP_FAILURE
svn add errors/zh-tw/ERR_FTP_FORBIDDEN
svn add errors/zh-tw/ERR_FTP_NOT_FOUND
svn add errors/zh-tw/ERR_FTP_PUT_CREATED
svn add errors/zh-tw/ERR_FTP_PUT_ERROR
svn add errors/zh-tw/ERR_FTP_PUT_MODIFIED
svn add errors/zh-tw/ERR_FTP_UNAVAILABLE
svn add errors/zh-tw/ERR_GATEWAY_FAILURE
svn add errors/zh-tw/ERR_ICAP_FAILURE
svn add errors/zh-tw/ERR_INVALID_REQ
svn add errors/zh-tw/ERR_INVALID_RESP
svn add errors/zh-tw/ERR_INVALID_URL
svn add errors/zh-tw/ERR_LIFETIME_EXP
svn add errors/zh-tw/ERR_NO_RELAY
svn add errors/zh-tw/ERR_ONLY_IF_CACHED_MISS
svn add errors/zh-tw/ERR_PRECONDITION_FAILED
svn add errors/zh-tw/ERR_READ_ERROR
svn add errors/zh-tw/ERR_READ_TIMEOUT
svn add errors/zh-tw/ERR_SECURE_CONNECT_FAIL
svn add errors/zh-tw/ERR_SHUTTING_DOWN
svn add errors/zh-tw/ERR_SOCKET_FAILURE
svn add errors/zh-tw/ERR_TOO_BIG
svn add errors/zh-tw/ERR_UNSUP_HTTPVERSION
svn add errors/zh-tw/ERR_UNSUP_REQ
svn add errors/zh-tw/ERR_URN_RESOLVE
svn add errors/zh-tw/ERR_WRITE_ERROR
svn add errors/zh-tw/ERR_ZERO_SIZE_OBJECT
svn add errors/zh-tw/error-details.txt
svn add helpers/basic_auth/DB/basic_db_auth.8
svn add helpers/basic_auth/DB/config.test
svn add helpers/basic_auth/DB/required.m4
svn add helpers/basic_auth/LDAP/README
svn add helpers/basic_auth/LDAP/config.test
svn add helpers/basic_auth/LDAP/required.m4
svn add helpers/basic_auth/MSNT
svn add helpers/basic_auth/MSNT/Makefile.am
svn add helpers/basic_auth/MSNT/Makefile.in
svn add helpers/basic_auth/MSNT/README.html
svn add helpers/basic_auth/MSNT/allowusers.cc
svn add helpers/basic_auth/MSNT/config.test
svn add helpers/basic_auth/MSNT/confload.cc
svn add helpers/basic_auth/MSNT/denyusers.cc
svn add helpers/basic_auth/MSNT/msntauth-v2.0.lsm
svn add helpers/basic_auth/MSNT/msntauth.cc
svn add helpers/basic_auth/MSNT/msntauth.conf.default
svn add helpers/basic_auth/MSNT/msntauth.h
svn add helpers/basic_auth/MSNT/usersfile.cc
svn add helpers/basic_auth/MSNT/usersfile.h
svn add helpers/basic_auth/MSNT/valid.cc
svn add helpers/basic_auth/MSNT/valid.h
svn add helpers/basic_auth/MSNT-multi-domain/README.txt
svn add helpers/basic_auth/MSNT-multi-domain/config.test
svn add helpers/basic_auth/MSNT-multi-domain/required.m4
svn add helpers/basic_auth/NCSA/config.test
svn add helpers/basic_auth/NCSA/required.m4
svn add helpers/basic_auth/NIS/config.test
svn add helpers/basic_auth/NIS/required.m4
svn add helpers/basic_auth/PAM/config.test
svn add helpers/basic_auth/PAM/required.m4
svn add helpers/basic_auth/POP3/config.test
svn add helpers/basic_auth/POP3/required.m4
svn add helpers/basic_auth/RADIUS/config.test
svn add helpers/basic_auth/RADIUS/required.m4
svn add helpers/basic_auth/SASL/config.test
svn add helpers/basic_auth/SASL/required.m4
svn add helpers/basic_auth/SMB/COPYING-2.0
svn add helpers/basic_auth/SMB/config.test
svn add helpers/basic_auth/SMB/required.m4
svn add helpers/basic_auth/SMB_LM
svn add helpers/basic_auth/SSPI/config.test
svn add helpers/basic_auth/SSPI/required.m4
svn add helpers/basic_auth/fake/config.test
svn add helpers/basic_auth/fake/required.m4
svn add helpers/basic_auth/getpwnam/config.test
svn add helpers/basic_auth/getpwnam/required.m4
svn add helpers/basic_auth/modules.m4
svn add helpers/digest_auth/LDAP/config.test
svn add helpers/digest_auth/LDAP/required.m4
svn add helpers/digest_auth/eDirectory/config.test
svn add helpers/digest_auth/eDirectory/required.m4
svn add helpers/digest_auth/file/config.test
svn add helpers/digest_auth/file/required.m4
svn add helpers/digest_auth/modules.m4
svn add helpers/external_acl/AD_group/config.test
svn add helpers/external_acl/AD_group/required.m4
svn add helpers/external_acl/LDAP_group/config.test
svn add helpers/external_acl/LDAP_group/required.m4
svn add helpers/external_acl/LM_group/config.test
svn add helpers/external_acl/LM_group/required.m4
svn add helpers/external_acl/SQL_session/config.test
svn add helpers/external_acl/SQL_session/ext_sql_session_acl.8
svn add helpers/external_acl/SQL_session/required.m4
svn add helpers/external_acl/delayer
svn add helpers/external_acl/eDirectory_userip/config.test
svn add helpers/external_acl/eDirectory_userip/required.m4
svn add helpers/external_acl/file_userip/config.test
svn add helpers/external_acl/file_userip/required.m4
svn add helpers/external_acl/kerberos_ldap_group/config.test
svn add helpers/external_acl/kerberos_ldap_group/required.m4
svn add helpers/external_acl/modules.m4
svn add helpers/external_acl/session/config.test
svn add helpers/external_acl/session/required.m4
svn add helpers/external_acl/time_quota/config.test
svn add helpers/external_acl/time_quota/required.m4
svn add helpers/external_acl/unix_group/config.test
svn add helpers/external_acl/unix_group/required.m4
svn add helpers/external_acl/wbinfo_group/config.test
svn add helpers/external_acl/wbinfo_group/ext_wbinfo_group_acl.8
svn add helpers/external_acl/wbinfo_group/required.m4
svn add helpers/log_daemon/DB/config.test
svn add helpers/log_daemon/DB/log_db_daemon.8
svn add helpers/log_daemon/DB/required.m4
svn add helpers/log_daemon/file/config.test
svn add helpers/log_daemon/file/required.m4
svn add helpers/log_daemon/modules.m4
svn add helpers/negotiate_auth/SSPI/config.test
svn add helpers/negotiate_auth/SSPI/required.m4
svn add helpers/negotiate_auth/kerberos/COPYING
svn add helpers/negotiate_auth/kerberos/config.test
svn add helpers/negotiate_auth/kerberos/negotiate_kerberos.h
svn add helpers/negotiate_auth/kerberos/negotiate_kerberos_pac.cc
svn add helpers/negotiate_auth/kerberos/required.m4
svn add helpers/negotiate_auth/modules.m4
svn add helpers/negotiate_auth/wrapper/config.test
svn add helpers/negotiate_auth/wrapper/required.m4
svn add helpers/ntlm_auth/SSPI/config.test
svn add helpers/ntlm_auth/SSPI/required.m4
svn add helpers/ntlm_auth/fake/config.test
svn add helpers/ntlm_auth/fake/required.m4
svn add helpers/ntlm_auth/modules.m4
svn add helpers/ntlm_auth/smb_lm/config.test
svn add helpers/ntlm_auth/smb_lm/required.m4
svn add helpers/ssl
svn add helpers/storeid_rewrite
svn add helpers/url_rewrite/fake/config.test
svn add helpers/url_rewrite/fake/required.m4
svn add helpers/url_rewrite/modules.m4
svn add icons/icon.list
svn add icons/list
svn add include/Array.h
svn add include/RefCount.h
svn add include/Stack.h
svn add include/squid_endian.h
svn add include/squid_windows.h
svn add include/unitTestMain.h
svn add lib/libTrie/AUTHORS
svn add lib/libTrie/COPYING
svn add lib/libTrie/ChangeLog
svn add lib/libTrie/INSTALL
svn add lib/libTrie/NEWS
svn add lib/libTrie/README
svn add lib/libTrie/Trie.cc
svn add lib/libTrie/Trie.h
svn add lib/libTrie/TrieCharTransform.h
svn add lib/libTrie/TrieNode.cc
svn add lib/libTrie/TrieNode.h
svn add lib/libTrie/acinclude.m4
svn add lib/libTrie/aclocal.m4
svn add lib/libTrie/autom4te.cache
svn add lib/libTrie/autom4te.cache/output.0
svn add lib/libTrie/autom4te.cache/output.1
svn add lib/libTrie/autom4te.cache/requests
svn add lib/libTrie/autom4te.cache/traces.0
svn add lib/libTrie/autom4te.cache/traces.1
svn add lib/libTrie/cfgaux
svn add lib/libTrie/cfgaux/config.guess
svn add lib/libTrie/cfgaux/config.sub
svn add lib/libTrie/cfgaux/depcomp
svn add lib/libTrie/cfgaux/install-sh
svn add lib/libTrie/cfgaux/ltmain.sh
svn add lib/libTrie/cfgaux/missing
svn add lib/libTrie/config.h.in
svn add lib/libTrie/configure
svn add lib/libTrie/configure.ac
svn add lib/libTrie/include
svn add lib/libTrie/include/Makefile.am
svn add lib/libTrie/include/Makefile.in
svn add lib/libTrie/include/Trie.cci
svn add lib/libTrie/include/Trie.h
svn add lib/libTrie/include/TrieCharTransform.h
svn add lib/libTrie/include/TrieNode.cci
svn add lib/libTrie/include/TrieNode.h
svn add lib/libTrie/libltdl
svn add lib/libTrie/libltdl/Makefile.am
svn add lib/libTrie/libltdl/Makefile.in
svn add lib/libTrie/libltdl/README
svn add lib/libTrie/libltdl/aclocal.m4
svn add lib/libTrie/libltdl/argz.c
svn add lib/libTrie/libltdl/argz_.h
svn add lib/libTrie/libltdl/config
svn add lib/libTrie/libltdl/config/compile
svn add lib/libTrie/libltdl/config/config.guess
svn add lib/libTrie/libltdl/config/config.sub
svn add lib/libTrie/libltdl/config/depcomp
svn add lib/libTrie/libltdl/config/install-sh
svn add lib/libTrie/libltdl/config/ltmain.sh
svn add lib/libTrie/libltdl/config/missing
svn add lib/libTrie/libltdl/config-h.in
svn add lib/libTrie/libltdl/configure
svn add lib/libTrie/libltdl/configure.ac
svn add lib/libTrie/libltdl/libltdl
svn add lib/libTrie/libltdl/libltdl/lt__alloc.h
svn add lib/libTrie/libltdl/libltdl/lt__dirent.h
svn add lib/libTrie/libltdl/libltdl/lt__glibc.h
svn add lib/libTrie/libltdl/libltdl/lt__private.h
svn add lib/libTrie/libltdl/libltdl/lt__strl.h
svn add lib/libTrie/libltdl/libltdl/lt_dlloader.h
svn add lib/libTrie/libltdl/libltdl/lt_error.h
svn add lib/libTrie/libltdl/libltdl/lt_system.h
svn add lib/libTrie/libltdl/libltdl/slist.h
svn add lib/libTrie/libltdl/loaders
svn add lib/libTrie/libltdl/loaders/dld_link.c
svn add lib/libTrie/libltdl/loaders/dlopen.c
svn add lib/libTrie/libltdl/loaders/dyld.c
svn add lib/libTrie/libltdl/loaders/load_add_on.c
svn add lib/libTrie/libltdl/loaders/loadlibrary.c
svn add lib/libTrie/libltdl/loaders/preopen.c
svn add lib/libTrie/libltdl/loaders/shl_load.c
svn add lib/libTrie/libltdl/lt__alloc.c
svn add lib/libTrie/libltdl/lt__dirent.c
svn add lib/libTrie/libltdl/lt__strl.c
svn add lib/libTrie/libltdl/lt_dlloader.c
svn add lib/libTrie/libltdl/lt_error.c
svn add lib/libTrie/libltdl/ltdl.c
svn add lib/libTrie/libltdl/ltdl.h
svn add lib/libTrie/libltdl/m4
svn add lib/libTrie/libltdl/m4/argz.m4
svn add lib/libTrie/libltdl/m4/libtool.m4
svn add lib/libTrie/libltdl/m4/ltdl.m4
svn add lib/libTrie/libltdl/m4/ltoptions.m4
svn add lib/libTrie/libltdl/m4/ltsugar.m4
svn add lib/libTrie/libltdl/m4/ltversion.m4
svn add lib/libTrie/libltdl/m4/lt~obsolete.m4
svn add lib/libTrie/libltdl/slist.c
svn add lib/libTrie/src
svn add lib/libTrie/src/Makefile.am
svn add lib/libTrie/src/Makefile.in
svn add lib/libTrie/src/Trie.cc
svn add lib/libTrie/src/TrieNode.cc
svn add lib/malloc_trace.cc
svn add lib/ntlmauth/support_endian.h
svn add lib/snmplib
svn add lib/sspwin32.c
svn add lib/sspwin32.cc
svn add lib/tests/testArray.cc
svn add lib/tests/testArray.h
svn add lib/tests/testMain.cc
svn add plugins
svn add plugins/squid_radius_auth
svn add plugins/squid_radius_auth/COPYRIGHT
svn add plugins/squid_radius_auth/Changelog
svn add plugins/squid_radius_auth/Make.inc
svn add plugins/squid_radius_auth/Makefile
svn add plugins/squid_radius_auth/Makefile.default
svn add plugins/squid_radius_auth/Makefile.solaris
svn add plugins/squid_radius_auth/README
svn add plugins/squid_radius_auth/etc
svn add plugins/squid_radius_auth/etc/squid_radius_auth.conf
svn add plugins/squid_radius_auth/md5.c
svn add plugins/squid_radius_auth/md5.h
svn add plugins/squid_radius_auth/radius.h
svn add plugins/squid_radius_auth/squid_rad_auth.c
svn add plugins/squid_radius_auth/squid_radius_auth.8
svn add plugins/squid_radius_auth/util.c
svn add plugins/squid_radius_auth/util.h
svn add snmplib
svn add snmplib/Makefile.am
svn add snmplib/Makefile.in
svn add snmplib/asn1.c
svn add snmplib/coexistance.c
svn add snmplib/mib.c
svn add snmplib/parse.c
svn add snmplib/snmp_api.c
svn add snmplib/snmp_api_error.c
svn add snmplib/snmp_error.c
svn add snmplib/snmp_msg.c
svn add snmplib/snmp_pdu.c
svn add snmplib/snmp_vars.c
svn add snmplib/snmplib_debug.c
svn add src/CollapsedForwarding.cc
svn add src/CollapsedForwarding.h
svn add src/FwdState.cc
svn add src/FwdState.h
svn add src/HelperChildConfig.cc
svn add src/HelperChildConfig.h
svn add src/HttpStatusCode.h
svn add src/HttpStatusLine.cc
svn add src/HttpStatusLine.h
svn add src/HttpVersion.h
svn add src/LogTags.h
svn add src/Makefile.in.orig
svn add src/MasterXaction.cc
svn add src/MasterXaction.h
svn add src/MessageSizes.h
svn add src/Notes.cc
svn add src/Notes.h
svn add src/OutOfBoundsException.h
svn add src/PeerPoolMgr.cc
svn add src/PeerPoolMgr.h
svn add src/SBuf.cc
svn add src/SBufAlgos.h
svn add src/SBufDetailedStats.h
svn add src/SBufExceptions.cc
svn add src/SBufList.cc
svn add src/SBufList.h
svn add src/SBufStatsAction.cc
svn add src/SBufStatsAction.h
svn add src/SBufStream.h
svn add src/Server.cc
svn add src/Server.h
svn add src/Store.cci
svn add src/Transients.h
svn add src/URLScheme.cc
svn add src/URLScheme.h
svn add src/acl/AdaptationService.cc
svn add src/acl/AdaptationService.h
svn add src/acl/AdaptationServiceData.cc
svn add src/acl/AdaptationServiceData.h
svn add src/acl/AllOf.cc
svn add src/acl/AllOf.h
svn add src/acl/AnyOf.cc
svn add src/acl/AnyOf.h
svn add src/acl/AtStep.cc
svn add src/acl/AtStep.h
svn add src/acl/AtStepData.cc
svn add src/acl/AtStepData.h
svn add src/acl/BoolOps.cc
svn add src/acl/BoolOps.h
svn add src/acl/InnerNode.cc
svn add src/acl/InnerNode.h
svn add src/acl/Note.cc
svn add src/acl/Note.h
svn add src/acl/NoteData.cc
svn add src/acl/NoteData.h
svn add src/acl/ServerCertificate.cc
svn add src/acl/ServerCertificate.h
svn add src/acl/ServerName.cc
svn add src/acl/ServerName.h
svn add src/acl/Tree.cc
svn add src/acl/Tree.h
svn add src/acl/forward.h
svn add src/anyp/TrafficMode.h
svn add src/anyp/UriScheme.cc
svn add src/anyp/UriScheme.h
svn add src/anyp/forward.h
svn add src/auth/QueueNode.h
svn add src/auth/User.cci
svn add src/auth/basic/Config.cc
svn add src/auth/basic/Config.h
svn add src/auth/basic/auth_basic.cc
svn add src/auth/basic/auth_basic.h
svn add src/auth/digest/Config.cc
svn add src/auth/digest/Config.h
svn add src/auth/digest/auth_digest.cc
svn add src/auth/digest/auth_digest.h
svn add src/auth/negotiate/Config.cc
svn add src/auth/negotiate/Config.h
svn add src/auth/negotiate/auth_negotiate.cc
svn add src/auth/negotiate/auth_negotiate.h
svn add src/auth/ntlm/Config.cc
svn add src/auth/ntlm/Config.h
svn add src/auth/ntlm/auth_ntlm.cc
svn add src/auth/ntlm/auth_ntlm.h
svn add src/base/CharacterSet.cc
svn add src/base/CharacterSet.h
svn add src/base/Lock.h
svn add src/base/LruMap.h
svn add src/base/RefCount.h
svn add src/base/StringArea.h
svn add src/clientStreamForward.h
svn add src/clients
svn add src/comm/Flag.h
svn add src/comm/Read.cc
svn add src/comm/Read.h
