svn del COPYRIGHT
svn del acinclude/ax_cxx_compile_stdcxx_0x.m4
svn del autom4te.cache
svn del autom4te.cache/output.0
svn del autom4te.cache/output.1
svn del autom4te.cache/requests
svn del autom4te.cache/traces.0
svn del autom4te.cache/traces.1
svn del check.sh
svn del compat/getaddrinfo.c
svn del compat/getnameinfo.c
svn del compat/inet_ntop.c
svn del compat/inet_pton.c
svn del compat/mswin.cc
svn del compat/os/mswin.h
svn del compat/os/windows.h
svn del compat/strsep.c
svn del compat/strsep.h
svn del compat/unsafe.h
svn del contrib/squid.rc
svn del errors/zh-cn
svn del errors/zh-cn/ERR_ACCESS_DENIED
svn del errors/zh-cn/ERR_ACL_TIME_QUOTA_EXCEEDED
svn del errors/zh-cn/ERR_AGENT_CONFIGURE
svn del errors/zh-cn/ERR_AGENT_WPAD
svn del errors/zh-cn/ERR_CACHE_ACCESS_DENIED
svn del errors/zh-cn/ERR_CACHE_MGR_ACCESS_DENIED
svn del errors/zh-cn/ERR_CANNOT_FORWARD
svn del errors/zh-cn/ERR_CONFLICT_HOST
svn del errors/zh-cn/ERR_CONNECT_FAIL
svn del errors/zh-cn/ERR_DIR_LISTING
svn del errors/zh-cn/ERR_DNS_FAIL
svn del errors/zh-cn/ERR_ESI
svn del errors/zh-cn/ERR_FORWARDING_DENIED
svn del errors/zh-cn/ERR_FTP_DISABLED
svn del errors/zh-cn/ERR_FTP_FAILURE
svn del errors/zh-cn/ERR_FTP_FORBIDDEN
svn del errors/zh-cn/ERR_FTP_NOT_FOUND
svn del errors/zh-cn/ERR_FTP_PUT_CREATED
svn del errors/zh-cn/ERR_FTP_PUT_ERROR
svn del errors/zh-cn/ERR_FTP_PUT_MODIFIED
svn del errors/zh-cn/ERR_FTP_UNAVAILABLE
svn del errors/zh-cn/ERR_GATEWAY_FAILURE
svn del errors/zh-cn/ERR_ICAP_FAILURE
svn del errors/zh-cn/ERR_INVALID_REQ
svn del errors/zh-cn/ERR_INVALID_RESP
svn del errors/zh-cn/ERR_INVALID_URL
svn del errors/zh-cn/ERR_LIFETIME_EXP
svn del errors/zh-cn/ERR_NO_RELAY
svn del errors/zh-cn/ERR_ONLY_IF_CACHED_MISS
svn del errors/zh-cn/ERR_PRECONDITION_FAILED
svn del errors/zh-cn/ERR_READ_ERROR
svn del errors/zh-cn/ERR_READ_TIMEOUT
svn del errors/zh-cn/ERR_SECURE_CONNECT_FAIL
svn del errors/zh-cn/ERR_SHUTTING_DOWN
svn del errors/zh-cn/ERR_SOCKET_FAILURE
svn del errors/zh-cn/ERR_TOO_BIG
svn del errors/zh-cn/ERR_UNSUP_HTTPVERSION
svn del errors/zh-cn/ERR_UNSUP_REQ
svn del errors/zh-cn/ERR_URN_RESOLVE
svn del errors/zh-cn/ERR_WRITE_ERROR
svn del errors/zh-cn/ERR_ZERO_SIZE_OBJECT
svn del errors/zh-cn/error-details.txt
svn del errors/zh-tw
svn del errors/zh-tw/ERR_ACCESS_DENIED
svn del errors/zh-tw/ERR_ACL_TIME_QUOTA_EXCEEDED
svn del errors/zh-tw/ERR_AGENT_CONFIGURE
svn del errors/zh-tw/ERR_AGENT_WPAD
svn del errors/zh-tw/ERR_CACHE_ACCESS_DENIED
svn del errors/zh-tw/ERR_CACHE_MGR_ACCESS_DENIED
svn del errors/zh-tw/ERR_CANNOT_FORWARD
svn del errors/zh-tw/ERR_CONFLICT_HOST
svn del errors/zh-tw/ERR_CONNECT_FAIL
svn del errors/zh-tw/ERR_DIR_LISTING
svn del errors/zh-tw/ERR_DNS_FAIL
svn del errors/zh-tw/ERR_ESI
svn del errors/zh-tw/ERR_FORWARDING_DENIED
svn del errors/zh-tw/ERR_FTP_DISABLED
svn del errors/zh-tw/ERR_FTP_FAILURE
svn del errors/zh-tw/ERR_FTP_FORBIDDEN
svn del errors/zh-tw/ERR_FTP_NOT_FOUND
svn del errors/zh-tw/ERR_FTP_PUT_CREATED
svn del errors/zh-tw/ERR_FTP_PUT_ERROR
svn del errors/zh-tw/ERR_FTP_PUT_MODIFIED
svn del errors/zh-tw/ERR_FTP_UNAVAILABLE
svn del errors/zh-tw/ERR_GATEWAY_FAILURE
svn del errors/zh-tw/ERR_ICAP_FAILURE
svn del errors/zh-tw/ERR_INVALID_REQ
svn del errors/zh-tw/ERR_INVALID_RESP
svn del errors/zh-tw/ERR_INVALID_URL
svn del errors/zh-tw/ERR_LIFETIME_EXP
svn del errors/zh-tw/ERR_NO_RELAY
svn del errors/zh-tw/ERR_ONLY_IF_CACHED_MISS
svn del errors/zh-tw/ERR_PRECONDITION_FAILED
svn del errors/zh-tw/ERR_READ_ERROR
svn del errors/zh-tw/ERR_READ_TIMEOUT
svn del errors/zh-tw/ERR_SECURE_CONNECT_FAIL
svn del errors/zh-tw/ERR_SHUTTING_DOWN
svn del errors/zh-tw/ERR_SOCKET_FAILURE
svn del errors/zh-tw/ERR_TOO_BIG
svn del errors/zh-tw/ERR_UNSUP_HTTPVERSION
svn del errors/zh-tw/ERR_UNSUP_REQ
svn del errors/zh-tw/ERR_URN_RESOLVE
svn del errors/zh-tw/ERR_WRITE_ERROR
svn del errors/zh-tw/ERR_ZERO_SIZE_OBJECT
svn del errors/zh-tw/error-details.txt
svn del helpers/basic_auth/DB/basic_db_auth.8
svn del helpers/basic_auth/DB/config.test
svn del helpers/basic_auth/LDAP/README
svn del helpers/basic_auth/LDAP/config.test
svn del helpers/basic_auth/MSNT
svn del helpers/basic_auth/MSNT/Makefile.am
svn del helpers/basic_auth/MSNT/Makefile.in
svn del helpers/basic_auth/MSNT/README.html
svn del helpers/basic_auth/MSNT/allowusers.cc
svn del helpers/basic_auth/MSNT/config.test
svn del helpers/basic_auth/MSNT/confload.cc
svn del helpers/basic_auth/MSNT/denyusers.cc
svn del helpers/basic_auth/MSNT/msntauth-v2.0.lsm
svn del helpers/basic_auth/MSNT/msntauth.cc
svn del helpers/basic_auth/MSNT/msntauth.conf.default
svn del helpers/basic_auth/MSNT/msntauth.h
svn del helpers/basic_auth/MSNT/usersfile.cc
svn del helpers/basic_auth/MSNT/usersfile.h
svn del helpers/basic_auth/MSNT/valid.cc
svn del helpers/basic_auth/MSNT/valid.h
svn del helpers/basic_auth/MSNT-multi-domain/README.txt
svn del helpers/basic_auth/MSNT-multi-domain/config.test
svn del helpers/basic_auth/NCSA/config.test
svn del helpers/basic_auth/NIS/config.test
svn del helpers/basic_auth/PAM/config.test
svn del helpers/basic_auth/POP3/config.test
svn del helpers/basic_auth/RADIUS/config.test
svn del helpers/basic_auth/SASL/config.test
svn del helpers/basic_auth/SMB/COPYING-2.0
svn del helpers/basic_auth/SMB/config.test
svn del helpers/basic_auth/SSPI/config.test
svn del helpers/basic_auth/fake/config.test
svn del helpers/basic_auth/getpwnam/config.test
svn del helpers/digest_auth/LDAP/config.test
svn del helpers/digest_auth/eDirectory/config.test
svn del helpers/digest_auth/file/config.test
svn del helpers/external_acl/AD_group/config.test
svn del helpers/external_acl/LDAP_group/config.test
svn del helpers/external_acl/LM_group/config.test
svn del helpers/external_acl/SQL_session/config.test
svn del helpers/external_acl/SQL_session/ext_sql_session_acl.8
svn del helpers/external_acl/eDirectory_userip/config.test
svn del helpers/external_acl/file_userip/config.test
svn del helpers/external_acl/kerberos_ldap_group/config.test
svn del helpers/external_acl/session/config.test
svn del helpers/external_acl/time_quota/config.test
svn del helpers/external_acl/unix_group/config.test
svn del helpers/external_acl/wbinfo_group/config.test
svn del helpers/external_acl/wbinfo_group/ext_wbinfo_group_acl.8
svn del helpers/log_daemon/DB/config.test
svn del helpers/log_daemon/DB/log_db_daemon.8
svn del helpers/log_daemon/file/config.test
svn del helpers/negotiate_auth/SSPI/config.test
svn del helpers/negotiate_auth/kerberos/COPYING
svn del helpers/negotiate_auth/kerberos/config.test
svn del helpers/negotiate_auth/wrapper/config.test
svn del helpers/ntlm_auth/SSPI/config.test
svn del helpers/ntlm_auth/fake/config.test
svn del helpers/ntlm_auth/smb_lm/config.test
svn del helpers/url_rewrite/fake/config.test
svn del icons/list
svn del include/Array.h
svn del include/RefCount.h
svn del include/Stack.h
svn del include/squid_endian.h
svn del include/squid_windows.h
svn del lib/libTrie/AUTHORS
svn del lib/libTrie/COPYING
svn del lib/libTrie/ChangeLog
svn del lib/libTrie/INSTALL
svn del lib/libTrie/NEWS
svn del lib/libTrie/README
svn del lib/libTrie/acinclude.m4
svn del lib/libTrie/aclocal.m4
svn del lib/libTrie/autom4te.cache
svn del lib/libTrie/autom4te.cache/output.0
svn del lib/libTrie/autom4te.cache/output.1
svn del lib/libTrie/autom4te.cache/requests
svn del lib/libTrie/autom4te.cache/traces.0
svn del lib/libTrie/autom4te.cache/traces.1
svn del lib/libTrie/cfgaux
svn del lib/libTrie/cfgaux/config.guess
svn del lib/libTrie/cfgaux/config.sub
svn del lib/libTrie/cfgaux/depcomp
svn del lib/libTrie/cfgaux/install-sh
svn del lib/libTrie/cfgaux/ltmain.sh
svn del lib/libTrie/cfgaux/missing
svn del lib/libTrie/config.h.in
svn del lib/libTrie/configure
svn del lib/libTrie/configure.ac
svn del lib/libTrie/include
svn del lib/libTrie/include/Makefile.am
svn del lib/libTrie/include/Makefile.in
svn del lib/libTrie/include/Trie.cci
svn del lib/libTrie/include/Trie.h
svn del lib/libTrie/include/TrieCharTransform.h
svn del lib/libTrie/include/TrieNode.cci
svn del lib/libTrie/include/TrieNode.h
svn del lib/libTrie/libltdl
svn del lib/libTrie/libltdl/Makefile.am
svn del lib/libTrie/libltdl/Makefile.in
svn del lib/libTrie/libltdl/README
svn del lib/libTrie/libltdl/aclocal.m4
svn del lib/libTrie/libltdl/argz.c
svn del lib/libTrie/libltdl/argz_.h
svn del lib/libTrie/libltdl/config
svn del lib/libTrie/libltdl/config/compile
svn del lib/libTrie/libltdl/config/config.guess
svn del lib/libTrie/libltdl/config/config.sub
svn del lib/libTrie/libltdl/config/depcomp
svn del lib/libTrie/libltdl/config/install-sh
svn del lib/libTrie/libltdl/config/ltmain.sh
svn del lib/libTrie/libltdl/config/missing
svn del lib/libTrie/libltdl/config-h.in
svn del lib/libTrie/libltdl/configure
svn del lib/libTrie/libltdl/configure.ac
svn del lib/libTrie/libltdl/libltdl
svn del lib/libTrie/libltdl/libltdl/lt__alloc.h
svn del lib/libTrie/libltdl/libltdl/lt__dirent.h
svn del lib/libTrie/libltdl/libltdl/lt__glibc.h
svn del lib/libTrie/libltdl/libltdl/lt__private.h
svn del lib/libTrie/libltdl/libltdl/lt__strl.h
svn del lib/libTrie/libltdl/libltdl/lt_dlloader.h
svn del lib/libTrie/libltdl/libltdl/lt_error.h
svn del lib/libTrie/libltdl/libltdl/lt_system.h
svn del lib/libTrie/libltdl/libltdl/slist.h
svn del lib/libTrie/libltdl/loaders
svn del lib/libTrie/libltdl/loaders/dld_link.c
svn del lib/libTrie/libltdl/loaders/dlopen.c
svn del lib/libTrie/libltdl/loaders/dyld.c
svn del lib/libTrie/libltdl/loaders/load_add_on.c
svn del lib/libTrie/libltdl/loaders/loadlibrary.c
svn del lib/libTrie/libltdl/loaders/preopen.c
svn del lib/libTrie/libltdl/loaders/shl_load.c
svn del lib/libTrie/libltdl/lt__alloc.c
svn del lib/libTrie/libltdl/lt__dirent.c
svn del lib/libTrie/libltdl/lt__strl.c
svn del lib/libTrie/libltdl/lt_dlloader.c
svn del lib/libTrie/libltdl/lt_error.c
svn del lib/libTrie/libltdl/ltdl.c
svn del lib/libTrie/libltdl/ltdl.h
svn del lib/libTrie/libltdl/m4
svn del lib/libTrie/libltdl/m4/argz.m4
svn del lib/libTrie/libltdl/m4/libtool.m4
svn del lib/libTrie/libltdl/m4/ltdl.m4
svn del lib/libTrie/libltdl/m4/ltoptions.m4
svn del lib/libTrie/libltdl/m4/ltsugar.m4
svn del lib/libTrie/libltdl/m4/ltversion.m4
svn del lib/libTrie/libltdl/m4/lt~obsolete.m4
svn del lib/libTrie/libltdl/slist.c
svn del lib/libTrie/src
svn del lib/libTrie/src/Makefile.am
svn del lib/libTrie/src/Makefile.in
svn del lib/libTrie/src/Trie.cc
svn del lib/libTrie/src/TrieNode.cc
svn del lib/malloc_trace.cc
svn del lib/sspwin32.c
svn del lib/tests/testArray.cc
svn del lib/tests/testArray.h
svn del lib/tests/testMain.cc
svn del plugins
svn del plugins/squid_radius_auth
svn del plugins/squid_radius_auth/COPYRIGHT
svn del plugins/squid_radius_auth/Changelog
svn del plugins/squid_radius_auth/Make.inc
svn del plugins/squid_radius_auth/Makefile
svn del plugins/squid_radius_auth/Makefile.default
svn del plugins/squid_radius_auth/Makefile.solaris
svn del plugins/squid_radius_auth/README
svn del plugins/squid_radius_auth/etc
svn del plugins/squid_radius_auth/etc/squid_radius_auth.conf
svn del plugins/squid_radius_auth/md5.c
svn del plugins/squid_radius_auth/md5.h
svn del plugins/squid_radius_auth/radius.h
svn del plugins/squid_radius_auth/squid_rad_auth.c
svn del plugins/squid_radius_auth/squid_radius_auth.8
svn del plugins/squid_radius_auth/util.c
svn del plugins/squid_radius_auth/util.h
svn del snmplib
svn del snmplib/Makefile.am
svn del snmplib/Makefile.in
svn del snmplib/asn1.c
svn del snmplib/coexistance.c
svn del snmplib/mib.c
svn del snmplib/parse.c
svn del snmplib/snmp_api.c
svn del snmplib/snmp_api_error.c
svn del snmplib/snmp_error.c
svn del snmplib/snmp_msg.c
svn del snmplib/snmp_pdu.c
svn del snmplib/snmp_vars.c
svn del snmplib/snmplib_debug.c
svn del src/HelperChildConfig.cc
svn del src/HelperChildConfig.h
svn del src/HttpStatusCode.h
svn del src/HttpStatusLine.cc
svn del src/HttpStatusLine.h
svn del src/HttpVersion.h
svn del src/Server.cc
svn del src/Server.h
svn del src/Store.cci
svn del src/URLScheme.cc
svn del src/URLScheme.h
svn del src/auth/User.cci
svn del src/auth/basic/auth_basic.cc
svn del src/auth/basic/auth_basic.h
svn del src/auth/digest/auth_digest.cc
svn del src/auth/digest/auth_digest.h
svn del src/auth/negotiate/auth_negotiate.cc
svn del src/auth/negotiate/auth_negotiate.h
svn del src/auth/ntlm/auth_ntlm.cc
svn del src/auth/ntlm/auth_ntlm.h
svn del src/base/StringArea.h
