Document: rtpproxy
Title: Debian rtpproxy Manual
Author: <insert document author here>
Abstract: This manual describes what rtpproxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpproxy/rtpproxy.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpproxy/rtpproxy.ps.gz

Format: text
Files: /usr/share/doc/rtpproxy/rtpproxy.text.gz

Format: HTML
Index: /usr/share/doc/rtpproxy/html/index.html
Files: /usr/share/doc/rtpproxy/html/*.html

  
