#!/bin/sh

mkdir -p /tmp/wireguard

wg genkey > /tmp/wireguard/oet$1_peer$2_private
wg pubkey < /tmp/wireguard/oet$1_peer$2_private > /tmp/wireguard/oet$1_peer$2_public
nvram set oet$1_peerkey$2=$(cat /tmp/wireguard/oet$1_peer$2_public)
if [ "$(nvram get wan_proto)" = "disabled" ]
then
	EP=$(nvram get lan_ipaddr)
else
	EP=$(get_wanip)
fi
if [ "$(nvram get oet$1_endpoint$2)" = "1" ]
then
	LISTENPORT=$(nvram get oet$1_peerport$2)
else
	LISTENPORT="51820"
fi

echo "[Interface]" > /tmp/wireguard/oet$1_peer$2_conf
echo "Address = $(nvram get oet$1_ipaddr)" >> /tmp/wireguard/oet$1_peer$2_conf
echo "PrivateKey = $(cat /tmp/wireguard/oet$1_peer$2_private)" >> /tmp/wireguard/oet$1_peer$2_conf
echo "ListenPort = $LISTENPORT" >> /tmp/wireguard/oet$1_peer$2_conf
echo "[Peer]" >> /tmp/wireguard/oet$1_peer$2_conf
echo "PublicKey = $(nvram get oet$1_public)" >> /tmp/wireguard/oet$1_peer$2_conf
echo "Endpoint = $EP:$(nvram get oet$1_port)" >> /tmp/wireguard/oet$1_peer$2_conf
#echo "AllowedIPs = $EP" >> /tmp/wireguard/oet$1_peer$2_conf
echo "AllowedIPs = 0.0.0.0/0, ::/0" >> /tmp/wireguard/oet$1_peer$2_conf
if [ $(nvram get oet$1_usepsk$2) = "1" ]
then
echo "PresharedKey = $(nvram get oet$1_psk$2)" >> /tmp/wireguard/oet$1_peer$2_conf
fi
echo "PersistentKeepalive = $(nvram get oet$1_ka$2)" >> /tmp/wireguard/oet$1_peer$2_conf
qrencode -t svg --rle -r /tmp/wireguard/oet$1_peer$2_conf -o /tmp/wireguard/oet$1_peer$2_svg