.TH int6kstat 1 "November 2013" "open-plc-utils-0.0.3" "Qualcomm Atheros Open Powerline Toolkit"

.SH NAME
int6kstat - Qualcomm Atheros INT6x00 Link Statistics

.SH SYNOPSIS
.BR int6kstat
.RI [ options ] 
.RI [ device ] 
.RI [ device ] 
[...]

.SH DESCRIPTION
The Atheros Device Statistics Utility polls a device and prints network and link statistics in various formats suitable for use by other programs.
This is a work in progress so usr feedback is encouraged.

.P
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBplc\fR man page for an overview and installation instructions.

.SH OPTIONS

.TP
.RB -C
Clear device link statistics using VS_LNK_STATS.
Statistics are read and cleared then displayed.
The statistics that are read and displayed depend on options \fB-d\fR, \fB-p\fR and \fB-s\fR but all link statistics are cleared.

.TP
-\fBd \fIdirection\fR
Return statistics for the specified direction using VS_LNK_STATS.
Direction can be \fB0\fR=tx, \fB1\fR=rx, \fB2\fR=both or "\fBrx\fR", "\fBtx\fR" or "\fBboth\fR".

.TP
.RB - e
Redirects stderr messages to stdout.
By convention status and error messages are printed on stderr while primary program output is printed on stdout.
This option prints all output on stdout in cases where this is desired.

.TP
.RB - i
Select the host Ethernet interface.
All requests are sent via this host interface and only reponses received via this host interface are recognized.
The default interface is \fBeth1\fR because most people use \fBeth0\fR as their principle network connection; however, if environment string "PLC" is defined then it takes precedence over the default interface.
This option then takes precedence over either default.

.TP
-\fBl \fIcount\fR
Define the number of times that the command will be repeated for each device specified.
Normally, you will repeat operations on one device only.

.TP
.RB - m
Displays network membership information, as seen by one device, using VS_NW_INFO.
Use option \fB-t\fR for complete network topology seen by the local host.

.TP
-\fBp \fIpeernode\fR
Ethernet hardware address of the peer node for VS_LNK_STATS.
This option is required for all Link ID values except \fB0xFC\fR.
The default is \fB00:00:00:00:00:00\fR.

.TP
.RB - q
Enter quiet mode.
Progress messages are suppressed.

.TP
-\fBs \fIlinkid\fR
The Link ID for VS_LNK_STATS.
Link ID values range from \fB0\fR through \fB255\fR but not all values are accepted by the device firmware.
Values may be expressed in decimal, binary prefixed with "\fB0b\fR" or hexadecimal prefixed by "\fB0x\fR".
Many valid values can be expressed by name.
Valid values are listed and explained under \fBLINKID\fR.
The default Link ID is \fB0xFC\fR.

.TP
.RB - t
Display network topology using VS_SW_VER and VS_NW_INFO messages.
This option is similar to option \fB-m\fR but provides complete network topology plus device hardware and firmware version.
Topology is always relative to the local host, or local hosts if present.
Powerline devices that appear on the command line are not used for this operation.
PHY rates displaye by this option may saturate at 255 mbps.

.TP
.RB - v 
Enter verbose mode.
All Etherenet frames sent or received by the program are displayed on stdout.

.TP
-\fBw \fIseconds\fR
Defines the number of \fIseconds\fR to wait before repeating command line options.
This option has no effect unless option -\fBl\fR is also specified with a non-zero value.

.TP
-\fB?\fR, --\fBhelp\fR
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
-\fB!\fR, --\fBversion\fR
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH ARGUMENTS

.TP
.BR device
The MAC address of some powerline device.
More than one address may be specified.
If more than one address is specified then operations are performed on each device in turn.
The default address is \fBlocal\fR.
See \fBDEVICES\fR for information about symbolic device addresses.

.SH LINKID

.TP 
.BR 0x00 , CSMA-CAP0
Display CSMA statistics for CAP0 traffic using a single peer node.
The peer node MAC address must be specified using option \fB-p\fR.

.TP
.BR 0x01 , CSMA-CAP1
Display CSMA statistics for CAP1 traffic using a single peer node.
The peer node MAC address must be specified using option \fB-p\fR.

.TP
.BR 0x02 , CSMA-CAP2
Display CSMA statistics for CAP2 traffic using a single peer node.
The peer node MAC address must be specified using option \fB-p\fR.

.TP
.BR 0x03 , CSMA-CAP3
Display CSMA statistics for CAP3 traffic using a single peer node.
The peer node MAC address must be specified using option \fB-p\fR.

.TP
.BR 0xF8 , CSMA-PEER
Display CSMA statistics for all traffic using a single  peer node.
The peer node MAC address must be specified using option \fB-p\fR.

.TP
.BR 0xFC , CSMA-ALL
Display CSMA statistics for all traffic with all peer nodes.
A peer node MAC address is not needed and will be ignored if provided.
This value is the default for option \fB-s\fR.

.SH DEVICES
Powerline devices use Ethernet Media Access Control (MAC) addresses.
A MAC address is a 48-bit value entered as 12 hexadecimal digits in upper, lower or mixed character case.
Octets may be separated with colons for clarity.
For example, "00b052000001", "00:b0:52:00:00:01" and "00b052:000001" are valid and equivalent.

.PP
The following MAC addresses are special and may be entered by name instead of number.

.TP
.BR all
Same as "broadcast".

.TP
.BR broadcast
A synonym for the Ethernet broadcast address, \fBFF:FF:FF:FF:FF:FF\fR.
All devices, whether local, remote or foreign recognize messages sent to this address.
A remote device is any device at the far end of a powerline connection.
A foreign device is any device not manufactured by Atheros.

.TP
.BR local
A synonym for the Qualcomm Atheros vendor specific Local Management Address (LMA), \fB00:B0:52:00:00:01\fR.
All local Atheros devices recognize this address but remote and foreign devices do not.
A remote device is any device at the far end of a powerline connection.
A foreign device is any device not manufactured by Atheros.

.SH REFERENCES
See the Qualcomm Atheros HomePlug AV Firmware Technical Reference Manual for more information.

.SH DISCLAIMER
Atheros HomePlug AV Vendor Specific Management Message Entry structure and content is proprietary to Qualcomm Atheros, Ocala FL USA.
Consequently, public information may not be available.
Qualcomm Atheros reserves the right to modify message structure and content in future firmware releases without any obligation to notify or compensate users of this program.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR plc ( 1 ),
.BR int6krate ( 1 ),
.BR int6krule ( 1 ),
.BR int6ktone ( 1 )

.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>

