:INPUT,FORWARD,OUTPUT
-p tcp -m tcp --sport 1;=;OK
-p tcp -m tcp --sport 65535;=;OK
-p tcp -m tcp --dport 1;=;OK
-p tcp -m tcp --dport 65535;=;OK
-p tcp -m tcp --sport 1:1023;=;OK
-p tcp -m tcp --sport 1024:65535;=;OK
-p tcp -m tcp --sport 1024:;-p tcp -m tcp --sport 1024:65535;OK
-p tcp -m tcp --sport :;-p tcp -m tcp;OK
-p tcp -m tcp ! --sport :;-p tcp -m tcp ! --sport 0:65535;OK
-p tcp -m tcp --sport :4;-p tcp -m tcp --sport 0:4;OK
-p tcp -m tcp --sport 4:;-p tcp -m tcp --sport 4:65535;OK
-p tcp -m tcp --sport 4:4;-p tcp -m tcp --sport 4;OK
-p tcp -m tcp --sport 4:3;;FAIL
-p tcp -m tcp --dport :;-p tcp -m tcp;OK
-p tcp -m tcp ! --dport :;-p tcp -m tcp ! --dport 0:65535;OK
-p tcp -m tcp --dport :4;-p tcp -m tcp --dport 0:4;OK
-p tcp -m tcp --dport 4:;-p tcp -m tcp --dport 4:65535;OK
-p tcp -m tcp --dport 4:4;-p tcp -m tcp --dport 4;OK
-p tcp -m tcp --dport 4:3;;FAIL
-p tcp -m tcp ! --sport 1;=;OK
-p tcp -m tcp ! --sport 65535;=;OK
-p tcp -m tcp ! --dport 1;=;OK
-p tcp -m tcp ! --dport 65535;=;OK
-p tcp -m tcp --sport 1 --dport 65535;=;OK
-p tcp -m tcp --sport 65535 --dport 1;=;OK
-p tcp -m tcp ! --sport 1 --dport 65535;=;OK
-p tcp -m tcp ! --sport 65535 --dport 1;=;OK
-p tcp -m tcp --sport 65536;;FAIL
-p tcp -m tcp --sport -1;;FAIL
-p tcp -m tcp --dport -1;;FAIL
-p tcp -m tcp --syn;-p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN;OK
-p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN;=;OK
-p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG SYN;=;OK
-p tcp -m tcp ! --tcp-flags FIN,SYN,RST,PSH,ACK,URG SYN;=;OK
-p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG RST;=;OK
-m tcp --dport 1;;FAIL
-m tcp --dport 1 -p tcp;-p tcp -m tcp --dport 1;OK
-m tcp --dport 1 -p 6;-p tcp -m tcp --dport 1;OK
# should we accept this below?
-p tcp -m tcp;=;OK
