#!/bin/bash

. ./test.common

test_start "large time offset"

min_sync_time=1300
max_sync_time=1400

for time_offset in -1e2 1e2; do
	run_test || test_fail
	check_chronyd_exit || test_fail
	check_source_selection || test_fail
	check_packet_interval || test_fail
	check_sync || test_fail
done

test_pass
