#!/usr/bin/env bash

. ./test.common

test_start "name resolving"

dns=1

run_test || test_fail
check_chronyd_exit || test_fail
check_source_selection || test_fail
check_packet_interval || test_fail
check_sync || test_fail

test_pass
