#!/bin/bash

. ./test.common
test_start "minpoll/maxpoll options"

wander=0.0
jitter=1e-6

time_max_limit=1e-5
freq_max_limit=1e-5
time_rms_limit=5e-6
freq_rms_limit=5e-6
client_conf="makestep 1e-2 1"

for poll in $(seq 1 14); do
	client_server_options="minpoll $poll maxpoll $poll"
	limit=$[2**$poll * 10]
	min_sync_time=$[2**$poll * 2]
	max_sync_time=$[2**$poll * 21 / 10 + 1]
	client_max_min_out_interval=$(awk "BEGIN {print 2^$poll * 1.1}")
	client_min_mean_out_interval=$(awk "BEGIN {print 2^$poll * 0.99}")

	run_test || test_fail
	check_chronyd_exit || test_fail
	check_source_selection || test_fail
	check_packet_interval || test_fail
	check_sync || test_fail
done

test_pass
