#!/bin/bash

. ./test.common
test_start "iburst option"

freq_offset=1e-4

client_conf="makestep 1e-2 1
driftfile tmp/drift"
client_server_options="iburst"

min_sync_time=4
max_sync_time=6

echo "100 1.0" > tmp/drift

run_test || test_fail
check_chronyd_exit || test_fail
check_source_selection || test_fail
check_packet_interval || test_fail
check_sync || test_fail

test_pass
