#!/bin/bash

. ./test.common
test_start "initstepslew directive"

freq_offset=0.0
wander=0.0
time_rms_limit=1e-3
limit=100

client_conf="initstepslew 5 192.168.123.1"

min_sync_time=6
max_sync_time=35

for time_offset in -2.0 -0.2 0.2 2.0; do
	run_test || test_fail
	check_chronyd_exit || test_fail
	check_packet_interval || test_fail
	check_sync || test_fail
done

min_sync_time=5
max_sync_time=5

for time_offset in -1e8 -1e2 1e2 1e8; do
	run_test || test_fail
	check_packet_interval || test_fail
	check_sync || test_fail
done

test_pass
