#!/bin/bash

. ./test.common

test_start "packet loss"

# Drop 33% of packets by default and 100% on the 3->1 path
base_delay=$(cat <<-EOF | tr -d '\n'
  (+ 1e-4
     (* -1 (equal 0.33 (uniform) 1.0))
     (* -1 (equal 0.1 from 3) (equal 0.1 to 1)))
EOF
)
clients=2
peers=2
jitter=1e-5
limit=20000
max_sync_time=10000

for options in "maxpoll 8" "maxpoll 8 xleave"; do
	client_server_options=$options
	client_peer_options=$options

	run_test || test_fail
	check_chronyd_exit || test_fail
	check_sync || test_fail
done

test_pass
