#!/bin/bash

. ./test.common

test_start "logchange directive"

time_offset=2
min_sync_time=600
max_sync_time=700
client_server_options="maxsamples 6"
client_conf="logchange 0.1"
client_step="(* $step (equal 0.1 (sum 1.0) 300))"

run_test || test_fail
check_chronyd_exit || test_fail
check_source_selection || test_fail
check_packet_interval || test_fail
check_sync || test_fail
check_log_messages "clock wrong by" 4 8 || test_fail

test_pass
