#!/bin/sh

touch ecos-ref.sgml
touch makefile
chmod +w ecos-ref.sgml 
chmod +w makefile

sgmldir="`dirname $0`"
doclist="${sgmldir}/doclist"
toplvl="${sgmldir}/../.."

cat > makefile <<EOF
#=============================================================================
#
#    makefile
#
#    For building the eCos docs
#
#=============================================================================
#####ECOSGPLCOPYRIGHTBEGIN####
# -------------------------------------------
# This file is part of eCos, the Embedded Configurable Operating System.
# Copyright (C) 1998, 1999, 2000, 2001, 2002 Red Hat, Inc.
# Copyright (C) 2003 Jonathan Larmour
#
# eCos is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 or (at your option) any later version.
#
# eCos is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with eCos; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#
# As a special exception, if other files instantiate templates or use macros
# or inline functions from this file, or you compile this file and link it
# with other works to produce a work based on this file, this file does not
# by itself cause the resulting work to be covered by the GNU General Public
# License. However the source code for this file must still be made available
# in accordance with section (3) of the GNU General Public License.
#
# This exception does not invalidate any other reasons why a work based on
# this file might be covered by the GNU General Public License.
# -------------------------------------------
#####ECOSGPLCOPYRIGHTEND####
#=============================================================================
#####DESCRIPTIONBEGIN####
#
# Author(s):     jlarmour
# Date:          2002-02-05
#####DESCRIPTIONEND####
#=============================================================================

TOPLEVEL   := ${toplvl}/packages
EOF
/bin/echo MAIN_SGML   := ecos-ref.sgml >> makefile
/bin/echo -n OTHER_SGML   :=  >> makefile

cat >ecos-ref.sgml <<EOF
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook V3.1//EN" [

<!-- Begin Document Specific Declarations -->
<!ENTITY ui "&micro;ITRON">
<!ENTITY versiondir CDATA "v2_0">
<!ENTITY version CDATA "2.0">
<!ENTITY lt SDATA "[lt    ]">
EOF

PACKAGEVER=${1:-'current'}

for i in `cat ${doclist}`; do
  line="`echo $i | sed 's/#.*//;'`"
  if (test ! -z $line); then
   /bin/echo -n " ${toplvl}/packages/$i" | sed "s@/current/@/${PACKAGEVER}/@g" >> makefile
   entityi="`echo $i | sed 's@\+@x@g; s@/@-@g; s@\.@-@g; s@_@-@g; s@-current-doc@@g; s@-current@@g'`"
   echo "<!ENTITY $entityi SYSTEM \"${toplvl}/packages/$i\">" | sed "s@/current/@/${PACKAGEVER}/@g" >> ecos-ref.sgml
  fi
done

# Go through again but find GIFs and PNGs to copy
for i in `for j in \`cat ${doclist}\` ; do dirname $j ; done | sort | uniq` ; do
  diri=`echo ${toplvl}/packages/$i | sed "s@/current/@/${PACKAGEVER}/@g"`
  dirigifs=`ls $diri/*.gif $diri/*.png 2>/dev/null | tr '\n' ' '`
  if [ x"$dirigifs" != x ]; then
        copyfiles="$copyfiles $dirigifs"
  fi
done

cat >> makefile <<EOF

MAIN_HTML  := ecos-ref.html
MAIN_PDF   := ecos-ref.pdf
PICTURES   :=
COPYFILES  := $copyfiles

include \$(TOPLEVEL)/pkgconf/rules.doc
EOF

cat >> ecos-ref.sgml <<EOF
<!-- End Document Specific Declarations -->
]>

<BOOK ID="ECOS-REF">
  <bookinfo>
    <TITLE>eCos Reference Manual</TITLE>

    <copyright>
      <year>1998</year>
      <year>1999</year>
      <year>2000</year>
      <year>2001</year>
      <year>2002</year>
      <year>2003</year>
      <holder>Red Hat, Inc.</holder>
      <holder>Nick Garnett (eCosCentric)</holder>
      <holder>Jonathan Larmour (eCosCentric)</holder>
      <holder>Andrew Lunn (Ascom)</holder>
      <holder>Gary Thomas (MLB Associates)</holder>
      <holder>Bart Veer (eCosCentric)</holder>
    </copyright>

    <legalnotice>
	<title>Documentation licensing terms</title>
<para>This material may be distributed only subject to the terms
and conditions set forth in the Open Publication License, v1.0
or later (the latest version is presently available at
<ulink url="http://www.opencontent.org/openpub/">http://www.opencontent.org/openpub/</ulink>).
</para>
<para>
Distribution of substantively modified versions of this
document is prohibited without the explicit permission of the
copyright holder.</para>
<para>
Distribution of the work or derivative of the work in any
standard (paper) book form is prohibited unless prior
permission is obtained from the copyright holder.
</para>
    </legalnotice>
    <legalnotice>
      <title>Trademarks</title>
<para>Altera&reg; and Excalibur&trade; are trademarks of Altera Corporation.</para>
<para>AMD&reg; is a registered trademark of Advanced Micro Devices, Inc.</para>
<para>ARM&reg;, StrongARM&reg;, Thumb&reg;, ARM7&trade;, ARM9&trade;  is a registered trademark of Advanced RISC Machines, Ltd.</para>
<para>Cirrus Logic&reg; and Maverick&trade; are registered trademarks of Cirrus Logic, Inc.</para>
<para>Cogent&trade; is a trademark of Cogent Computer Systems, Inc.</para>
<para>Compaq&reg; is a registered trademark of the Compaq Computer Corporation.</para>
<para>Fujitsu&reg; is a registered trademark of Fujitsu Limited.</para>
<para>IBM&reg;, and PowerPC&trade; are trademarks of International Business Machines Corporation.</para>
<para>IDT&reg; is a registered trademark of Integrated Device Technology Inc.</para>
<para>Intel&reg;, i386&trade;, Pentium&reg;, StrataFlash&reg; and XScale&trade; are trademarks of Intel Corporation.</para>
<para>Intrinsyc&reg; and Cerf&trade; are trademarks of Intrinsyc Software, Inc.</para>
<para>Linux&reg; is a registered trademark of Linus Torvalds. </para>
<para>Matsushita&trade; and Panasonic&reg; are trademarks of the Matsushita Electric Industrial Corporation.</para>
<para>Microsoft&reg;, Windows&reg;, Windows NT&reg; and Windows XP&reg; are registered trademarks of Microsoft Corporation, Inc. </para>
<para>MIPS&reg;, MIPS32&trade; MIPS64&trade;, 4K&trade, 5K&trade; Atlas&trade; and Malta&trade; are trademarks of MIPS Technologies, Inc.</para>
<para>Motorola&reg;, ColdFire&reg; is a trademark of Motorola, Inc.</para>
<para>NEC&reg; V800&trade;, V850&trade;, V850/SA1&trade;, V850/SB1&trade;, VR4300&trade;, and VRC4375&trade; are trademarks of NEC Corporation.</para>
<para>PMC-Sierra&reg; RM7000&trade; and Ocelot&trade; are trademarks of PMC-Sierra Incorporated. </para>
<para>Red Hat, eCos&trade;, RedBoot&trade;, GNUPro&reg;, and Insight&trade; are trademarks of Red Hat, Inc. </para>
<para>Samsung&reg; and CalmRISC&trade; are trademarks or registered trademarks of Samsung, Inc. </para>
<para>Sharp&reg; is a registered trademark of Sharp Electronics Corp.</para>
<para>SPARC&reg; is a registered trademark of SPARC International, Inc., and is used under license by Sun Microsystems, Inc. </para>
<para>Sun Microsystems&reg; and Solaris&reg; are registered trademarks of Sun Microsystems, Inc. </para>
<para>SuperH&trade; and Renesas&trade; are trademarks owned by Renesas Technology Corp.</para>
<para>Texas Instruments&reg;, OMAP&trade; and Innovator&trade; are trademarks of Texas Instruments Incorporated.</para>
<para>Toshiba&reg; is a registered trademark of the Toshiba Corporation.</para>
<para>UNIX&reg; is a registered trademark of The Open Group. </para>
<para>All other brand and product names, trademarks, and copyrights are the
property of their respective owners. </para>
      </legalnotice>
      <legalnotice>
<title>Warranty</title>
<para>eCos and RedBoot are open source software, covered by a
modified version of the <ulink url="http://www.gnu.org/copyleft/gpl.html">GNU
General Public Licence</ulink>,
and you are welcome to change it and/or distribute copies of it under certain
conditions. See <ulink
url="http://ecos.sourceware.org/license-overview.html">http://ecos.sourceware.org/license-overview.html
</ulink> for more information about the license.</para>
<para>eCos and RedBoot software have NO WARRANTY. </para>
<para>Because this software is licensed free of charge, there are no warranties
for it, to the extent permitted by applicable law. Except when otherwise stated
in writing, the copyright holders and/or other parties provide the software
&ldquo;as is&rdquo; without warranty of any kind, either expressed or implied,
including, but not limited to, the implied warranties of merchantability and
fitness for a particular purpose. The entire risk as to the quality and performance
of the software is with you. Should the software prove defective, you assume
the cost of all necessary servicing, repair or correction.</para>
<para> In no event, unless required by applicable law or agreed to in writing,
will any copyright holder, or any other party who may modify and/or redistribute
the program as permitted above, be liable to you for damages, including any
general, special, incidental or consequential damages arising out of the use
or inability to use the program (including but not limited to loss of data
or data being rendered inaccurate or losses sustained by you or third parties
or a failure of the program to operate with any other programs), even if such
holder or other party has been advised of the possibility of such damages.
</para>
      </legalnotice>
  </bookinfo>
<toc id="ecos-toc"></toc>
EOF

for i in `cat ${doclist}`; do
  line="`echo $i | sed 's/#.*//;'`"
  if (test ! -z $line); then
   entityi="`echo $i | sed 's@\+@x@g; s@/@-@g; s@\.@-@g; s@_@-@g; s@-current-doc@@g; s@-current@@g'`"
   # special kludge
   if [ "`basename $i`" != "tcpip-manpages.sgml" -a \
	"`basename $i`" != "snmp-manpages.sgml" -a \
	"`basename $i`" != "libipsec.sgml" -a \
	"`basename $i`" != "libipsec-manpages.sgml" -a \
	"`basename $i`" != "openbsd-manpages-bridge.sgml" -a \
	"`basename $i`" != "openbsd-manpages-netintro.sgml" -a \
	"`basename $i`" != "openbsd-manpages-stp.sgml" -a \
	"`basename $i`" != "porting.sgml" ]; then
     echo "&$entityi;" >> ecos-ref.sgml
   fi
  fi
done

echo '</book>' >> ecos-ref.sgml
