# $Id: Makefile,v 1.5 2003/05/23 15:43:44 andrei Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=textops.so
LIBS=

include ../../Makefile.modules

