.\"                              hey, Emacs:   -*- nroff -*-
.\" frottle is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH FROTTLE 1 "July 25, 2003"
.\" Please update the above date whenever this man page is modified.
.SH NAME
frottle \- Packet collision avoidance and bandwidth shaping for
wireless networks
.SH SYNOPSIS
.B frottle
.RI [ options ]
.SH DESCRIPTION
\fBfrottle\fP was developed to combat the issue of hidden node (packet 
collisions) in large area 802.11b wireless networks. It utilises the 
ipq library in iptables which allows a userspace application to accept 
or drop packets asyncronously. At one location frottle is run in master 
mode. This master polls the other locations which run frottle in client 
mode. As each client is polled it is allowed to send a limited ammount 
of data. The polling algorithm is fairly complex and based on many 
variables. It has been developed and refinded in a real world wireless 
environment.
.SH OPTIONS
\fBfrottle\fP accepts the following options:
.TP
.B \-c, \-\-conf
Alternate location for frottle.conf (default /etc/frottle.conf).
.TP
.B \-V, \-\-verbose
Send additional messages to the terminal (as well as the syslog).
.TP
.B \-d, \-\-daemon
Daemonise (detach from terminal) upon execution.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.SH frottle.conf
\fBfrottle.conf\fP can have the following settings: 
.TP
.B mastermode
When set to '1' frottle will act as a master. Default '0'. Frottle 
can act as a master and client at the same time. 
.TP
.B clientmode
When set to '1' frottle will act as a client. Default '0'. Frottle 
can act as a master and client at the same time. 
.TP
.B daemon
When set to '1' frottle will daemonise (detach from the terminal) 
upon execution. Default '0'. (Use 'killall -TERM frottle' to quit 
frottle if you use this option.) 
.TP
.B verbose
When set to '1' additional messages will be sent to the terminal 
(as well as the syslog). Default '0'. 
.TP
.B masterport
The UDP port used for master - client communications. Must be set 
the same for both master and clients. Default '999'. 
.TP
.B masterip (client only) 
The IP of the master to connect to, i.e. '10.60.0.2'. No default. 
.TP
.B queuesize (client and self-client only) 
The maximum number of packets that can be held in each queue at 
any one time. Default '10'. 
.TP
.B hiports (client only) 
High priority ports. Up to 10 can be specified. Default '22, 53'. 
Matching is performed on both source and destination port. 
.TP
.B winterface (client only) 
If a wireless connection is present and wireless-tools is 
installed, the wireless interface can be specified. Default 'eth1'. 
This interface will be polled for information to feed to the 
master for display and use in the polling algorithm. 
.TP
.B statsfile (client only)
Optional path and filename for output of stats information in html 
format, i.e. '\\var\\www\\html\\frottle.html'. Default none. 
.TP
.B selfclient (master only)
When set to '1' a selfclient has a higher priority and more 
bandwidth than a master with 'clientmode' specified. Use this 
when the master is acting as a hub for all client data. 
Default '0'.
.TP
.B timeout (master only)
The time to wait for a client to respond that it has completed
it's poll sequence, in mS. Default '100'.
.TP
.B pollparams (master only)
Polling paramteres used to control the bandwidth use. 
Default '60000,10,6000,7,5000,5,4000'. The format of this parameter 
is 'm,p1,b1,p2,b2,p3,b3' where 'm' is the maximum number of bytes 
that can be sent by a self client in one poll loop. 'p1,b1' is the 
maximum number of packets & bytes that can be sent by clients 
reporting a data rate of 5 Mb/s or greater. 'p2,b2' is the maximum 
number of packets & bytes that can be sent by client reporting a 
data rate of 2-5 Mb/s. 'p3,b3' is the maximum number of packets & 
bytes that can be sent by client reporting a data rate of less than 
2 Mb/s.
.TP
.B infofile (master only) 
Path and filename for output of master information in html format. 
Default '\\tmp\\frottle.html'.
.br
.SH iptables requirement 
Each client must add the following lines to their iptables 
configuration (firewall script):
.br
.br
    modprobe iptable_filter 
.br
    modprobe ip_queue 
.br
    iptables -A OUTPUT -p UDP --dport 999 -j ACCEPT 
.br
    iptables -A INPUT -p UDP --sport 999 -j ACCEPT 
.br
    iptables -A OUTPUT -p ALL -o eth1 -j QUEUE 
.br
    iptables -A FORWARD -p ALL -o eth1 -j QUEUE
.br
.br
The first two lines load the required modules. The second two lines 
allow control packets between the master and client to go straight 
through. The last two lines send all packets going out the wireless 
interface (eth1 in this example) to the QUEUE where frottle will 
handle them.
.br
.br
The master must have the following lines:
.br
.br
    modprobe iptable_filter 
.br
    modprobe ip_queue 
.br
    iptables -A INPUT -p UDP --dport 999 -j ACCEPT 
.br
    iptables -A OUTPUT -p UDP --sport 999 -j ACCEPT 
.br
.br
The first two lines load the required modules. The second two lines 
allow control packets between the master and client to go straight 
through. If the master is also acting as a client or self client it
will also need the following:
.br
.br
    iptables -A OUTPUT -p ALL -o eth1 -j QUEUE
.br
    iptables -A FORWARD -p ALL -o eth1 -j QUEUE
.br
.SH Signals
\fBfrottle\fP reacts to the following signals:
.TP
.B HUP
Frottle will re-read some parameters from the .conf file upon receiving
a HUP signal.
.TP
.B TERM, QUIT, INT
Frottle will close gracefully when it receives one of these signals.
.SH "SEE ALSO"
.BR iptables (8),
.BR libipq (3), 
http://www.wafreenet.org/?page=frottle
.SH AUTHOR
Chris King <frottle@wafreenet.org>.
