.\" Copyright (c) 2015 Jaegeuk Kim <jaegeuk@kernel.org>
.\"
.TH RESIZE.F2FS 8
.SH NAME
resize.f2fs \- resize filesystem size
.SH SYNOPSIS
.B resize.f2fs
[
.B \-t
.I target sectors
]
[
.B \-d
.I debugging-level
]
.I device
.SH DESCRIPTION
.B resize.f2fs
is used to resize an f2fs file system (usually in a disk partition).
\fIdevice\fP is the special file corresponding to the device (e.g.
\fI/dev/sdXX\fP).

Current version only supports expanding the prebuilt filesystem.

.PP
The exit code returned by
.B resize.f2fs
is 0 on success and -1 on failure.
.SH OPTIONS
.TP
.BI \-t " target sectors"
Specify the size in sectors.
.TP
.BI \-d " debug-level"
Specify the level of debugging options.
The default number is 0, which shows basic debugging messages.
.TP
.SH AUTHOR
This version of
.B resize.f2fs
has been written by Jaegeuk Kim <jaegeuk@kernel.org>.
.SH AVAILABILITY
.B resize.f2fs
is available from git://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git.
.SH SEE ALSO
.BR mkfs.f2fs(8),
.BR fsck.f2fs(8),
.BR dump.f2fs(8),
.BR defrag.f2fs(8),
.BR sload.f2fs(8).
