/*
 * Broadcom UPnP module, xml_x_wancommoninterfaceconfig.c
 *
 * Copyright (C) 2008, Broadcom Corporation
 * All Rights Reserved.
 * 
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom Corporation.
 *
 * $Id: xml_x_wancommoninterfaceconfig.c,v 1.5 2007/11/23 09:51:55 Exp $
 */
#include <upnp.h>

char xml_x_wancommoninterfaceconfig[] = "<?xml version=\"1.0\"?>\n"
					"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
					"<specVersion>\n"
					"<major>1</major>\n"
					"<minor>0</minor>\n"
					"</specVersion>\n"
					"<actionList>\n"
					"<action>\n"
					"<name>SetEnabledForInternet</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewEnabledForInternet</name>\n"
					"<direction>in</direction>\n"
					"<relatedStateVariable>EnabledForInternet</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetEnabledForInternet</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewEnabledForInternet</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>EnabledForInternet</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetCommonLinkProperties</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewWANAccessType</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>WANAccessType</relatedStateVariable>\n"
					"</argument>\n"
					"<argument>\n"
					"<name>NewLayer1UpstreamMaxBitRate</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>Layer1UpstreamMaxBitRate</relatedStateVariable>\n"
					"</argument>\n"
					"<argument>\n"
					"<name>NewLayer1DownstreamMaxBitRate</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>Layer1DownstreamMaxBitRate</relatedStateVariable>\n"
					"</argument>\n"
					"<argument>\n"
					"<name>NewPhysicalLinkStatus</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>PhysicalLinkStatus</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetMaximumActiveConnections</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewMaximumActiveConnections</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>MaximumActiveConnections</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetTotalBytesSent</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewTotalBytesSent</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>TotalBytesSent</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetTotalPacketsSent</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewTotalPacketsSent</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>TotalPacketsSent</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetTotalBytesReceived</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewTotalBytesReceived</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>TotalBytesReceived</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetTotalPacketsReceived</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewTotalPacketsReceived</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>TotalPacketsReceived</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"<action>\n"
					"<name>GetActiveConnections</name>\n"
					"<argumentList>\n"
					"<argument>\n"
					"<name>NewActiveConnectionIndex</name>\n"
					"<direction>in</direction>\n"
					"<relatedStateVariable>NumberOfActiveConnections</relatedStateVariable>\n"
					"</argument>\n"
					"<argument>\n"
					"<name>NewActiveConnDeviceContainer</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>ActiveConnectionDeviceContainer</relatedStateVariable>\n"
					"</argument>\n"
					"<argument>\n"
					"<name>NewActiveConnectionServiceID</name>\n"
					"<direction>out</direction>\n"
					"<relatedStateVariable>ActiveConnectionServiceID</relatedStateVariable>\n"
					"</argument>\n"
					"</argumentList>\n"
					"</action>\n"
					"</actionList>\n"
					"<serviceStateTable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>WANAccessType</name>\n"
					"<dataType>string</dataType>\n"
					"<allowedValueList>\n"
					"<allowedValue>DSL</allowedValue>\n"
					"<allowedValue>POTS</allowedValue>\n"
					"<allowedValue>Cable</allowedValue>\n"
					"<allowedValue>Ethernet</allowedValue>\n"
					"<allowedValue>Other</allowedValue>\n"
					"</allowedValueList>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>Layer1UpstreamMaxBitRate</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>Layer1DownstreamMaxBitRate</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"yes\">\n"
					"<name>PhysicalLinkStatus</name>\n"
					"<dataType>string</dataType>\n"
					"<allowedValueList>\n"
					"<allowedValue>Up</allowedValue>\n"
					"<allowedValue>Down</allowedValue>\n"
					"<allowedValue>Initializing</allowedValue>\n"
					"<allowedValue>Unavailable</allowedValue>\n"
					"</allowedValueList>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"yes\">\n"
					"<name>EnabledForInternet</name>\n"
					"<dataType>boolean</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>MaximumActiveConnections</name>\n"
					"<dataType>ui2</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>NumberOfActiveConnections</name>\n"
					"<dataType>ui2</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>TotalBytesSent</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>TotalBytesReceived</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>TotalPacketsSent</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>TotalPacketsReceived</name>\n"
					"<dataType>ui4</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>ActiveConnectionDeviceContainer</name>\n"
					"<dataType>string</dataType>\n"
					"</stateVariable>\n"
					"<stateVariable sendEvents=\"no\">\n"
					"<name>ActiveConnectionServiceID</name>\n"
					"<dataType>string</dataType>\n"
					"</stateVariable>\n"
					"</serviceStateTable>\n"
					"</scpd>\n"
					"\n";
